# Makefile.in generated by automake 1.11.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/RJMCMC
pkgincludedir = $(includedir)/RJMCMC
pkglibdir = $(libdir)/RJMCMC
pkglibexecdir = $(libexecdir)/RJMCMC
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/rjmcmc.pc.in \
	$(top_srcdir)/configure \
	$(top_srcdir)/include/rjmcmc/rjmcmc_config.h.in AUTHORS \
	COPYING ChangeLog INSTALL NEWS compile config.guess config.sub \
	depcomp install-sh ltmain.sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/libtool.m4 \
	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
	$(top_srcdir)/m4/ltversion.m4 $(top_srcdir)/m4/lt~obsolete.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/include/rjmcmc/rjmcmc_config.h
CONFIG_CLEAN_FILES = rjmcmc.pc
CONFIG_CLEAN_VPATH_FILES =
SOURCES =
DIST_SOURCES =
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-dvi-recursive install-exec-recursive \
	install-html-recursive install-info-recursive \
	install-pdf-recursive install-ps-recursive install-recursive \
	installcheck-recursive installdirs-recursive pdf-recursive \
	ps-recursive uninstall-recursive
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__installdirs = "$(DESTDIR)$(pkgconfigdir)"
DATA = $(pkgconfig_DATA)
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
AM_RECURSIVE_TARGETS = $(RECURSIVE_TARGETS:-recursive=) \
	$(RECURSIVE_CLEAN_TARGETS:-recursive=) tags TAGS ctags CTAGS \
	distdir dist dist-all distcheck
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /short/r17/rcb547/code/repos/iearth/RJMCMC-1.0.11/missing --run aclocal-1.11
AMTAR = ${SHELL} /short/r17/rcb547/code/repos/iearth/RJMCMC-1.0.11/missing --run tar
AR = ar
AUTOCONF = ${SHELL} /short/r17/rcb547/code/repos/iearth/RJMCMC-1.0.11/missing --run autoconf
AUTOHEADER = ${SHELL} /short/r17/rcb547/code/repos/iearth/RJMCMC-1.0.11/missing --run autoheader
AUTOMAKE = ${SHELL} /short/r17/rcb547/code/repos/iearth/RJMCMC-1.0.11/missing --run automake-1.11
AWK = gawk
CC = icc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = icc -E
CPPFLAGS =  -I/usr/include/openmpi
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
F77 = gfortran
FC = gfortran
FCFLAGS = -g -O2
FFLAGS = -g -O2
FGREP = /bin/grep -F
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /opt/bin/ld -m elf_x86_64
LDFLAGS =  -L/usr/lib/openmpi
LIBMPI = -lmpi
LIBOBJS = 
LIBS = -lm 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /short/r17/rcb547/code/repos/iearth/RJMCMC-1.0.11/missing --run makeinfo
MANIFEST_TOOL = :
MKDIR_P = /bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OPENMPI_CPPFLAGS = -I/usr/include/openmpi
OPENMPI_LDFLAGS = -L/usr/lib/openmpi
OTOOL = 
OTOOL64 = 
PACKAGE = RJMCMC
PACKAGE_BUGREPORT = http://www.iearth.org.au/codes/RJMCMC
PACKAGE_NAME = rjmcmc
PACKAGE_STRING = rjmcmc 1.0.11
PACKAGE_TARNAME = RJMCMC
PACKAGE_VERSION = 1.0.11
PATH_SEPARATOR = :
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 1.0.11
abs_builddir = /short/r17/rcb547/code/repos/iearth/RJMCMC-1.0.11
abs_srcdir = /short/r17/rcb547/code/repos/iearth/RJMCMC-1.0.11
abs_top_builddir = /short/r17/rcb547/code/repos/iearth/RJMCMC-1.0.11
abs_top_srcdir = /short/r17/rcb547/code/repos/iearth/RJMCMC-1.0.11
ac_ct_AR = ar
ac_ct_CC = icc
ac_ct_DUMPBIN = 
ac_ct_F77 = gfortran
ac_ct_FC = gfortran
am__include = include
am__leading_dot = .
am__quote = 
am__tar = tar --format=ustar -chf - "$$tardir"
am__untar = tar -xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /short/r17/rcb547/code/repos/iearth/RJMCMC-1.0.11/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /short/public/rcb547/apps/iearth/LIBRJMCMC-1.0.11/intel-cc-14.1.106
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
ACLOCAL_AMFLAGS = -I m4
SUBDIRS = src \
	include

pkgconfigdir = $(libdir)/pkgconfig
pkgconfig_DATA = rjmcmc.pc
DIST_SUBDIRS = src \
	include \
	tests \
	examples/1d/partitioned/fm/functionfit \
	examples/1d/partitioned/fm/functionfitf \
	examples/1d/partitioned/fm/gaussian \
	examples/1d/partitioned/fm/natural \
	examples/1d/partitioned/fm/regression \
	examples/1d/partitioned/fm/step \
	examples/1d/partitioned/fm/synthdata \
	examples/1d/partitioned/fm/velocityf \
	examples/1d/partitioned/regression/multiquad \
	examples/1d/partitioned/regression/multistep \
	examples/1d/partitioned/regression/sawtooth \
	examples/1d/partitioned/regression/zeromultistep \
	examples/1d/single/regression/cubic \
	examples/1d/single/fm/gaussian \
	examples/1d/single/fm/simplef \
	examples/1d/single/fm/simpleimage \
	examples/1d/single/fm/spherefit \
	examples/2d/partitioned/fm/mpi_regression \
	examples/2d/partitioned/fm/regression \
	examples/2d/partitioned/fm/gaussian \
	examples/2d/partitioned/regression/ausmoho \
	examples/2d/partitioned/regression/callbackex \
	examples/2d/partitioned/regression/disc \
	examples/2d/partitioned/regression/gaussian \
	examples/2d/partitioned/regression/square \
	tests/regression/1d/partitioned/fm/MPI_part1d_forwardmodel_c \
	tests/regression/1d/partitioned/fm/MPI_part1d_forwardmodel_hierarchical_c \
	tests/regression/1d/partitioned/fm/MPI_part1d_forwardmodel_natural_c \
	tests/regression/1d/partitioned/fm/MPI_part1d_forwardmodel_natural_hierarchical_c \
	tests/regression/1d/partitioned/fm/part1d_forwardmodel_c \
	tests/regression/1d/partitioned/fm/part1d_forwardmodel_hierarchical_c \
	tests/regression/1d/partitioned/fm/part1d_forwardmodel_natural_c \
	tests/regression/1d/partitioned/fm/part1d_forwardmodel_natural_hierarchical_c \
	tests/regression/1d/partitioned/fm/part1d_forwardmodel_zero_cubic_c \
	tests/regression/1d/single/fm/MPI_single_forwardmodel_c \
	tests/regression/1d/single/fm/MPI_single_forwardmodel_hierarchical_c \
	tests/regression/1d/single/fm/single_forwardmodel_c \
	tests/regression/1d/single/fm/single_forwardmodel_hierarchical_c \
	tests/regression/2d/partitioned/fm/MPI_part2d_forwardmodel_c \
	tests/regression/2d/partitioned/fm/MPI_part2d_forwardmodel_hierarchical_c \
	tests/regression/2d/partitioned/fm/part2d_forwardmodel_c \
	tests/regression/2d/partitioned/fm/part2d_forwardmodel_hierarchical_c

EXTRA_DIST = \
	macosx/builduniversal.sh \
	macosx/installuniversal.sh \
	macosx/buildforpython.sh \
	doc/rjmcmc.dox \
	doc/images/main_tree.py \
	doc/images/Makefile \
	python/swig/rjmcmc.i \
	python/swig/rjmcmc_helper.c \
	python/swig/rjmcmc_helper.h \
	python/swig/setup.py \
	python/tutorial/fm/ch0-createdata.py \
	python/tutorial/fm/ch1-loading.py \
	python/tutorial/fm/ch2-analyse.py \
	python/tutorial/fm/ch3-regression.py \
	python/tutorial/single/data.txt \
	python/tutorial/single/ch0-createdata.py \
	python/tutorial/single/ch1-loading.py \
	python/tutorial/single/ch2-analyse.py \
	python/tutorial/single/ch3-orderanalysis.py \
	python/tutorial/single/ch4-confidence.py \
	python/tutorial/single/ch5-hierarchical.py \
	python/tutorial/single/doc/tufte-book.cls \
	python/tutorial/single/doc/tufte-common.def \
	python/tutorial/single/doc/tufte-handout.cls \
	python/tutorial/single/doc/tutorial_single.tex \
	python/tutorial/multi/data.txt \
	python/tutorial/multi/ch0-createdata.py \
	python/tutorial/multi/ch1-loading.py \
	python/tutorial/multi/ch2-analyse.py \
	python/tutorial/multi/ch3-orderanalysis.py \
	python/tutorial/multi/ch4-confidence.py \
	python/tutorial/multi/ch5-hierarchical.py \
	python/tutorial/multi/doc/tufte-book.cls \
	python/tutorial/multi/doc/tufte-common.def \
	python/tutorial/multi/doc/tufte-handout.cls \
	python/tutorial/multi/doc/tutorial_multi.tex \
	doc/images/main_tree.pdf \
	doc/images/main_tree.png \
	template/part1d/Makefile \
	template/part1d/part1dtemplate.c \
	template/part1d/data.txt \
	template/part1d_fortran/Makefile \
	template/part1d_fortran/part1d_fortran.f90 \
	template/part1d_fortran/data.txt \
	template/part1d_hierarchical_fortran/create_data.py \
	template/part1d_hierarchical_fortran/data.txt \
	template/part1d_hierarchical_fortran/Makefile \
	template/part1d_hierarchical_fortran/part1d_hierarchical_fortran.f90 \
	template/part1d_hierarchical_fortran/realdata.txt \
	template/part1d_hierarchical_fortran/svdbacksub.f90 \
	template/part1d_hierarchical_fortran/svdtest.f90 \
	template/part1d_hierarchical_fortran/svdtest.m \
	template/part1d_hierarchical_fortran/blas/caxpy.f     \
	template/part1d_hierarchical_fortran/blas/ccopy.f	 \
	template/part1d_hierarchical_fortran/blas/cdotc.f	 \
	template/part1d_hierarchical_fortran/blas/cdotu.f	 \
	template/part1d_hierarchical_fortran/blas/cgbmv.f	 \
	template/part1d_hierarchical_fortran/blas/cgemm.f	 \
	template/part1d_hierarchical_fortran/blas/cgemv.f	 \
	template/part1d_hierarchical_fortran/blas/cgerc.f	 \
	template/part1d_hierarchical_fortran/blas/cgeru.f	 \
	template/part1d_hierarchical_fortran/blas/chbmv.f	 \
	template/part1d_hierarchical_fortran/blas/chemm.f	 \
	template/part1d_hierarchical_fortran/blas/chemv.f	 \
	template/part1d_hierarchical_fortran/blas/cher2.f	 \
	template/part1d_hierarchical_fortran/blas/cher2k.f	 \
	template/part1d_hierarchical_fortran/blas/cher.f	 \
	template/part1d_hierarchical_fortran/blas/cherk.f	 \
	template/part1d_hierarchical_fortran/blas/chpmv.f	 \
	template/part1d_hierarchical_fortran/blas/chpr2.f	 \
	template/part1d_hierarchical_fortran/blas/chpr.f	 \
	template/part1d_hierarchical_fortran/blas/crotg.f	 \
	template/part1d_hierarchical_fortran/blas/cscal.f	 \
	template/part1d_hierarchical_fortran/blas/csrot.f	 \
	template/part1d_hierarchical_fortran/blas/csscal.f	 \
	template/part1d_hierarchical_fortran/blas/cswap.f	 \
	template/part1d_hierarchical_fortran/blas/csymm.f	 \
	template/part1d_hierarchical_fortran/blas/csyr2k.f	 \
	template/part1d_hierarchical_fortran/blas/csyrk.f	 \
	template/part1d_hierarchical_fortran/blas/ctbmv.f	 \
	template/part1d_hierarchical_fortran/blas/ctbsv.f	 \
	template/part1d_hierarchical_fortran/blas/ctpmv.f	 \
	template/part1d_hierarchical_fortran/blas/ctpsv.f	 \
	template/part1d_hierarchical_fortran/blas/ctrmm.f	 \
	template/part1d_hierarchical_fortran/blas/ctrmv.f	 \
	template/part1d_hierarchical_fortran/blas/ctrsm.f	 \
	template/part1d_hierarchical_fortran/blas/ctrsv.f	 \
	template/part1d_hierarchical_fortran/blas/dasum.f	 \
	template/part1d_hierarchical_fortran/blas/daxpy.f	 \
	template/part1d_hierarchical_fortran/blas/dcabs1.f	 \
	template/part1d_hierarchical_fortran/blas/dcopy.f	 \
	template/part1d_hierarchical_fortran/blas/ddot.f	 \
	template/part1d_hierarchical_fortran/blas/dgbmv.f	 \
	template/part1d_hierarchical_fortran/blas/dgemm.f	 \
	template/part1d_hierarchical_fortran/blas/dgemv.f	 \
	template/part1d_hierarchical_fortran/blas/dger.f	 \
	template/part1d_hierarchical_fortran/blas/dnrm2.f	 \
	template/part1d_hierarchical_fortran/blas/drot.f	 \
	template/part1d_hierarchical_fortran/blas/drotg.f	 \
	template/part1d_hierarchical_fortran/blas/drotm.f	 \
	template/part1d_hierarchical_fortran/blas/drotmg.f	 \
	template/part1d_hierarchical_fortran/blas/dsbmv.f	 \
	template/part1d_hierarchical_fortran/blas/dscal.f	 \
	template/part1d_hierarchical_fortran/blas/dsdot.f	 \
	template/part1d_hierarchical_fortran/blas/dspmv.f	 \
	template/part1d_hierarchical_fortran/blas/dspr2.f	 \
	template/part1d_hierarchical_fortran/blas/dspr.f	 \
	template/part1d_hierarchical_fortran/blas/dswap.f	 \
	template/part1d_hierarchical_fortran/blas/dsymm.f	 \
	template/part1d_hierarchical_fortran/blas/dsymv.f	 \
	template/part1d_hierarchical_fortran/blas/dsyr2.f	 \
	template/part1d_hierarchical_fortran/blas/dsyr2k.f	 \
	template/part1d_hierarchical_fortran/blas/dsyr.f	 \
	template/part1d_hierarchical_fortran/blas/dsyrk.f	 \
	template/part1d_hierarchical_fortran/blas/dtbmv.f	 \
	template/part1d_hierarchical_fortran/blas/dtbsv.f	 \
	template/part1d_hierarchical_fortran/blas/dtpmv.f	 \
	template/part1d_hierarchical_fortran/blas/dtpsv.f	 \
	template/part1d_hierarchical_fortran/blas/dtrmm.f	 \
	template/part1d_hierarchical_fortran/blas/dtrmv.f	 \
	template/part1d_hierarchical_fortran/blas/dtrsm.f	 \
	template/part1d_hierarchical_fortran/blas/dtrsv.f	 \
	template/part1d_hierarchical_fortran/blas/dzasum.f	 \
	template/part1d_hierarchical_fortran/blas/dznrm2.f	 \
	template/part1d_hierarchical_fortran/blas/icamax.f	 \
	template/part1d_hierarchical_fortran/blas/idamax.f	 \
	template/part1d_hierarchical_fortran/blas/isamax.f	 \
	template/part1d_hierarchical_fortran/blas/izamax.f	 \
	template/part1d_hierarchical_fortran/blas/lsame.f	 \
	template/part1d_hierarchical_fortran/blas/Makefile	 \
	template/part1d_hierarchical_fortran/blas/sasum.f	 \
	template/part1d_hierarchical_fortran/blas/saxpy.f	 \
	template/part1d_hierarchical_fortran/blas/scabs1.f	 \
	template/part1d_hierarchical_fortran/blas/scasum.f	 \
	template/part1d_hierarchical_fortran/blas/scnrm2.f	 \
	template/part1d_hierarchical_fortran/blas/scopy.f	 \
	template/part1d_hierarchical_fortran/blas/sdot.f	 \
	template/part1d_hierarchical_fortran/blas/sdsdot.f	 \
	template/part1d_hierarchical_fortran/blas/sgbmv.f	 \
	template/part1d_hierarchical_fortran/blas/sgemm.f	 \
	template/part1d_hierarchical_fortran/blas/sgemv.f	 \
	template/part1d_hierarchical_fortran/blas/sger.f	 \
	template/part1d_hierarchical_fortran/blas/snrm2.f	 \
	template/part1d_hierarchical_fortran/blas/srot.f	 \
	template/part1d_hierarchical_fortran/blas/srotg.f	 \
	template/part1d_hierarchical_fortran/blas/srotm.f	 \
	template/part1d_hierarchical_fortran/blas/srotmg.f	 \
	template/part1d_hierarchical_fortran/blas/ssbmv.f	 \
	template/part1d_hierarchical_fortran/blas/sscal.f	 \
	template/part1d_hierarchical_fortran/blas/sspmv.f	 \
	template/part1d_hierarchical_fortran/blas/sspr2.f	 \
	template/part1d_hierarchical_fortran/blas/sspr.f	 \
	template/part1d_hierarchical_fortran/blas/sswap.f	 \
	template/part1d_hierarchical_fortran/blas/ssymm.f	 \
	template/part1d_hierarchical_fortran/blas/ssymv.f	 \
	template/part1d_hierarchical_fortran/blas/ssyr2.f	 \
	template/part1d_hierarchical_fortran/blas/ssyr2k.f	 \
	template/part1d_hierarchical_fortran/blas/ssyr.f	 \
	template/part1d_hierarchical_fortran/blas/ssyrk.f	 \
	template/part1d_hierarchical_fortran/blas/stbmv.f	 \
	template/part1d_hierarchical_fortran/blas/stbsv.f	 \
	template/part1d_hierarchical_fortran/blas/stpmv.f	 \
	template/part1d_hierarchical_fortran/blas/stpsv.f	 \
	template/part1d_hierarchical_fortran/blas/strmm.f	 \
	template/part1d_hierarchical_fortran/blas/strmv.f	 \
	template/part1d_hierarchical_fortran/blas/strsm.f	 \
	template/part1d_hierarchical_fortran/blas/strsv.f	 \
	template/part1d_hierarchical_fortran/blas/xerbla_array.f \
	template/part1d_hierarchical_fortran/blas/xerbla.f	 \
	template/part1d_hierarchical_fortran/blas/zaxpy.f	 \
	template/part1d_hierarchical_fortran/blas/zcopy.f	 \
	template/part1d_hierarchical_fortran/blas/zdotc.f	 \
	template/part1d_hierarchical_fortran/blas/zdotu.f	 \
	template/part1d_hierarchical_fortran/blas/zdrot.f	 \
	template/part1d_hierarchical_fortran/blas/zdscal.f	 \
	template/part1d_hierarchical_fortran/blas/zgbmv.f	 \
	template/part1d_hierarchical_fortran/blas/zgemm.f	 \
	template/part1d_hierarchical_fortran/blas/zgemv.f	 \
	template/part1d_hierarchical_fortran/blas/zgerc.f	 \
	template/part1d_hierarchical_fortran/blas/zgeru.f	 \
	template/part1d_hierarchical_fortran/blas/zhbmv.f	 \
	template/part1d_hierarchical_fortran/blas/zhemm.f	 \
	template/part1d_hierarchical_fortran/blas/zhemv.f	 \
	template/part1d_hierarchical_fortran/blas/zher2.f	 \
	template/part1d_hierarchical_fortran/blas/zher2k.f	 \
	template/part1d_hierarchical_fortran/blas/zher.f	 \
	template/part1d_hierarchical_fortran/blas/zherk.f	 \
	template/part1d_hierarchical_fortran/blas/zhpmv.f	 \
	template/part1d_hierarchical_fortran/blas/zhpr2.f	 \
	template/part1d_hierarchical_fortran/blas/zhpr.f	 \
	template/part1d_hierarchical_fortran/blas/zrotg.f	 \
	template/part1d_hierarchical_fortran/blas/zscal.f	 \
	template/part1d_hierarchical_fortran/blas/zswap.f	 \
	template/part1d_hierarchical_fortran/blas/zsymm.f	 \
	template/part1d_hierarchical_fortran/blas/zsyr2k.f	 \
	template/part1d_hierarchical_fortran/blas/zsyrk.f	 \
	template/part1d_hierarchical_fortran/blas/ztbmv.f	 \
	template/part1d_hierarchical_fortran/blas/ztbsv.f	 \
	template/part1d_hierarchical_fortran/blas/ztpmv.f	 \
	template/part1d_hierarchical_fortran/blas/ztpsv.f	 \
	template/part1d_hierarchical_fortran/blas/ztrmm.f	 \
	template/part1d_hierarchical_fortran/blas/ztrmv.f	 \
	template/part1d_hierarchical_fortran/blas/ztrsm.f	 \
	template/part1d_hierarchical_fortran/blas/ztrsv.f     \
	template/part1d_hierarchical_fortran/lapack/dbdsdc.f   \
	template/part1d_hierarchical_fortran/lapack/dbdsqr.f   \
	template/part1d_hierarchical_fortran/lapack/dgebd2.f   \
	template/part1d_hierarchical_fortran/lapack/dgebrd.f   \
	template/part1d_hierarchical_fortran/lapack/dgelq2.f   \
	template/part1d_hierarchical_fortran/lapack/dgelqf.f   \
	template/part1d_hierarchical_fortran/lapack/dgeqr2.f   \
	template/part1d_hierarchical_fortran/lapack/dgeqrf.f   \
	template/part1d_hierarchical_fortran/lapack/dgesdd.f   \
	template/part1d_hierarchical_fortran/lapack/disnan.f   \
	template/part1d_hierarchical_fortran/lapack/dlabrd.f   \
	template/part1d_hierarchical_fortran/lapack/dlacpy.f   \
	template/part1d_hierarchical_fortran/lapack/dlaed6.f   \
	template/part1d_hierarchical_fortran/lapack/dlaisnan.f \
	template/part1d_hierarchical_fortran/lapack/dlamch.f   \
	template/part1d_hierarchical_fortran/lapack/dlamrg.f   \
	template/part1d_hierarchical_fortran/lapack/dlange.f   \
	template/part1d_hierarchical_fortran/lapack/dlanst.f   \
	template/part1d_hierarchical_fortran/lapack/dlapy2.f   \
	template/part1d_hierarchical_fortran/lapack/dlarfb.f   \
	template/part1d_hierarchical_fortran/lapack/dlarf.f    \
	template/part1d_hierarchical_fortran/lapack/dlarfg.f   \
	template/part1d_hierarchical_fortran/lapack/dlarft.f   \
	template/part1d_hierarchical_fortran/lapack/dlartg.f   \
	template/part1d_hierarchical_fortran/lapack/dlas2.f    \
	template/part1d_hierarchical_fortran/lapack/dlascl.f   \
	template/part1d_hierarchical_fortran/lapack/dlasd0.f   \
	template/part1d_hierarchical_fortran/lapack/dlasd1.f   \
	template/part1d_hierarchical_fortran/lapack/dlasd2.f   \
	template/part1d_hierarchical_fortran/lapack/dlasd3.f   \
	template/part1d_hierarchical_fortran/lapack/dlasd4.f   \
	template/part1d_hierarchical_fortran/lapack/dlasd5.f   \
	template/part1d_hierarchical_fortran/lapack/dlasd6.f   \
	template/part1d_hierarchical_fortran/lapack/dlasd7.f   \
	template/part1d_hierarchical_fortran/lapack/dlasd8.f   \
	template/part1d_hierarchical_fortran/lapack/dlasda.f   \
	template/part1d_hierarchical_fortran/lapack/dlasdq.f   \
	template/part1d_hierarchical_fortran/lapack/dlasdt.f   \
	template/part1d_hierarchical_fortran/lapack/dlaset.f   \
	template/part1d_hierarchical_fortran/lapack/dlasq1.f   \
	template/part1d_hierarchical_fortran/lapack/dlasq2.f   \
	template/part1d_hierarchical_fortran/lapack/dlasq3.f   \
	template/part1d_hierarchical_fortran/lapack/dlasq4.f   \
	template/part1d_hierarchical_fortran/lapack/dlasq5.f   \
	template/part1d_hierarchical_fortran/lapack/dlasq6.f   \
	template/part1d_hierarchical_fortran/lapack/dlasr.f    \
	template/part1d_hierarchical_fortran/lapack/dlasrt.f   \
	template/part1d_hierarchical_fortran/lapack/dlassq.f   \
	template/part1d_hierarchical_fortran/lapack/dlasv2.f   \
	template/part1d_hierarchical_fortran/lapack/dorg2r.f   \
	template/part1d_hierarchical_fortran/lapack/dorgbr.f   \
	template/part1d_hierarchical_fortran/lapack/dorgl2.f   \
	template/part1d_hierarchical_fortran/lapack/dorglq.f   \
	template/part1d_hierarchical_fortran/lapack/dorgqr.f   \
	template/part1d_hierarchical_fortran/lapack/dorm2r.f   \
	template/part1d_hierarchical_fortran/lapack/dormbr.f   \
	template/part1d_hierarchical_fortran/lapack/dorml2.f   \
	template/part1d_hierarchical_fortran/lapack/dormlq.f   \
	template/part1d_hierarchical_fortran/lapack/dormqr.f   \
	template/part1d_hierarchical_fortran/lapack/ieeeck.f   \
	template/part1d_hierarchical_fortran/lapack/iladlc.f   \
	template/part1d_hierarchical_fortran/lapack/iladlr.f   \
	template/part1d_hierarchical_fortran/lapack/ilaenv.f   \
	template/part1d_hierarchical_fortran/lapack/iparmq.f   \
	template/part1d_hierarchical_fortran/lapack/lsame.f    \
	template/part1d_hierarchical_fortran/lapack/Makefile   \
	template/part1d_hierarchical_fortran/lapack/xerbla.f 

all: all-recursive

.SUFFIXES:
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

include/rjmcmc/rjmcmc_config.h: include/rjmcmc/stamp-h1
	@if test ! -f $@; then \
	  rm -f include/rjmcmc/stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) include/rjmcmc/stamp-h1; \
	else :; fi

include/rjmcmc/stamp-h1: $(top_srcdir)/include/rjmcmc/rjmcmc_config.h.in $(top_builddir)/config.status
	@rm -f include/rjmcmc/stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status include/rjmcmc/rjmcmc_config.h
$(top_srcdir)/include/rjmcmc/rjmcmc_config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f include/rjmcmc/stamp-h1
	touch $@

distclean-hdr:
	-rm -f include/rjmcmc/rjmcmc_config.h include/rjmcmc/stamp-h1
rjmcmc.pc: $(top_builddir)/config.status $(srcdir)/rjmcmc.pc.in
	cd $(top_builddir) && $(SHELL) ./config.status $@

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt
install-pkgconfigDATA: $(pkgconfig_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(pkgconfigdir)" || $(MKDIR_P) "$(DESTDIR)$(pkgconfigdir)"
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(pkgconfigdir)" || exit $$?; \
	done

uninstall-pkgconfigDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	test -n "$$files" || exit 0; \
	echo " ( cd '$(DESTDIR)$(pkgconfigdir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(pkgconfigdir)" && rm -f $$files

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@fail= failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

$(RECURSIVE_CLEAN_TARGETS):
	@fail= failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS: tags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d "$(distdir)/$$subdir" \
	    || $(MKDIR_P) "$(distdir)/$$subdir" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod u+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@$(am__cd) '$(distuninstallcheck_dir)' \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(DATA)
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(pkgconfigdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-generic clean-libtool mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -f Makefile
distclean-am: clean-am distclean-generic distclean-hdr \
	distclean-libtool distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am: install-pkgconfigDATA

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am:

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-generic mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-pkgconfigDATA

.MAKE: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) ctags-recursive \
	install-am install-strip tags-recursive

.PHONY: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) CTAGS GTAGS \
	all all-am am--refresh check check-am clean clean-generic \
	clean-libtool ctags ctags-recursive dist dist-all dist-bzip2 \
	dist-gzip dist-lzma dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-generic distclean-hdr \
	distclean-libtool distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-pdf install-pdf-am install-pkgconfigDATA install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs installdirs-am maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-generic \
	mostlyclean-libtool pdf pdf-am ps ps-am tags tags-recursive \
	uninstall uninstall-am uninstall-pkgconfigDATA


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
