bbox2d.h File Reference
2D Bounding Box routines
Data Structures
struct bbox2d
Typedefs
typedef struct bbox2d bbox2d_t
Functions
void bbox2d_set (bbox2d_t *bound, double xmin, double xmax, double ymin, double ymax)
Set a bounding box.
void bbox2d_initialize (bbox2d_t *bound, double x, double y)
Initialise a bounding box to an initial point (creating an infinitesimal bound).
void bbox2d_expand (bbox2d_t *bound, double x, double y)
Expand a bounding box to include a point.
void bbox2d_bound_expand (bbox2d_t *bound, const bbox2d_t *exp_bound)
Expand a bounding box to include another bounding box.
Detailed Description
2D Bounding Box routines
2D bounding boxes are used in the constrained delaunay code as well as for 2D forward model codes.
Typedef Documentation
typedef struct bbox2d bbox2d_t
Function Documentation
void bbox2d_bound_expand (bbox2d_t * bound, const bbox2d_t * exp_bound)
Expand a bounding box to include another bounding box.
Increases an existing bounding box to include the specified bounding box. If the existing bound completely contains the specified bound, the existing bound is unchanged.
References bbox2d::xmax, bbox2d::xmin, bbox2d::ymax, and bbox2d::ymin.
Referenced by position_map2d_delaunay_move(), and position_map2d_quadtree_move().
void bbox2d_expand (bbox2d_t * bound, double x, double y)
Expand a bounding box to include a point.
Increases an existing bounding box to include the specified point. If the point x, y is already in the bound, the bounding box will not be changed.
References x, bbox2d::xmax, bbox2d::xmin, y, bbox2d::ymax, and bbox2d::ymin.
Referenced by delaunay2d_add(), and delaunay2d_save_cc_geo().
void bbox2d_initialize (bbox2d_t * bound, double x, double y)
Initialise a bounding box to an initial point (creating an infinitesimal bound).
Sets the bound to an infinitesimal point, ie xmin = xmax = x and ymin = ymax = y.
References x, bbox2d::xmax, bbox2d::xmin, y, bbox2d::ymax, and bbox2d::ymin.
Referenced by delaunay2d_add(), and delaunay2d_save_cc_geo().
void bbox2d_set (bbox2d_t * bound, double xmin, double xmax, double ymin, double ymax)
Set a bounding box.
Sets a bounding box to given values. No validity checking is performed (ie xmin < xmax).
References bbox2d::xmax, bbox2d::xmin, bbox2d::ymax, and bbox2d::ymin.
Referenced by position_map2d_linear_delete(), position_map2d_linear_insert(), and position_map2d_linear_move().