curvefit.h File Reference
1D Curve Fitting routines
#include `rjmcmc/dataset1d.h`
*
#include `rjmcmc/rjmcmc_random.h`
*
Typedefs
typedef struct _curvefit_result curvefit_result_t
Functions
curvefit_result_t * curvefit_create (int maxorder)
Create a new curvefit_result_t.
void curvefit_destroy (curvefit_result_t *cf)
Free memory allocated for curvefit_result_t obecjt.
int curvefit_compute (const dataset1d_t *d, int di, int dj, int order, curvefit_result_t *cf)
Computing polynomial fitting parameters.
int curvefit_compute_lambda (const dataset1d_t *d, double lambda, int di, int dj, int order, curvefit_result_t *cf)
Compute polynomial fitting parameters with an error scale.
int curvefit_sample (curvefit_result_t *cf, rjmcmc_normal_rand_t normal, double *coeff, int coeff_len, double *prob)
Generate a random polynomial.
int curvefit_sample_mean (curvefit_result_t *cf, double *coeff, int coeff_len)
Retrieve the mean (best fit) polynomial.
int curvefit_sample_sigma (curvefit_result_t *cf, double *sigma, int sigma_len)
Retrieve the sigma diagonals.
int curvefit_sample_detCm (curvefit_result_t *cf, double *detCm, int order)
Compute the determinant of the Covariance matrix.
int curvefit_evaluate_pk (curvefit_result_t *cf, const dataset1d_t *data, int di, int dj, int max_order, const double *fixed_prior, double auto_z, double *mean_misfit, double *detCm, double *prior, double **S, double *pk, double *kcdf, double **mean, double **sigma)
Compute the complete fit over all orders.
double ** cf_L (curvefit_result_t *cf)
double ** cf_Z (curvefit_result_t *cf)
double ** cf_S (curvefit_result_t *cf)
double * cf_mu (curvefit_result_t *cf)
Detailed Description
1D Curve Fitting routines
The curvefit_result_t type is used for computing best fit and randomly perturbed polynomials for a given dataset1d_t .
Typedef Documentation
typedef struct _curvefit_result curvefit_result_t
Function Documentation
double** cf_L (curvefit_result_t * cf)
References _curvefit_result::L.
double* cf_mu (curvefit_result_t * cf)
References _curvefit_result::mu.
double** cf_S (curvefit_result_t * cf)
References _curvefit_result::S.
double** cf_Z (curvefit_result_t * cf)
References _curvefit_result::Z.
int curvefit_compute (const dataset1d_t * d, int di, int dj, int order, curvefit_result_t * cf)
Computing polynomial fitting parameters.
Computes the various fitting parameters for a given dataset or subset thereof.
Parameters
d The dataset
di First index into dataset
dj Last index into dataset
order The order of the polynomial to fit
cf The curvefit_result_t to store the data (must have been allocated previously using curvefit_create
References _curvefit_result::alpha, _curvefit_result::b, _curvefit_result::beta, _curvefit_result::L, _curvefit_result::maxorder, _curvefit_result::mu, _dataset1d::points, rjmcmc_error(), _curvefit_result::S, _curvefit_result::Si, _curvefit_result::x, and _curvefit_result::Z.
Referenced by part1d_regression_rj_propose_move(), and single1d_regression_propose_lambda().
int curvefit_compute_lambda (const dataset1d_t * d, double lambda, int di, int dj, int order, curvefit_result_t * cf)
Compute polynomial fitting parameters with an error scale.
This function is equivalent to curvefit_compute with the addition of an error scaling term lambda.
Parameters
d The dataset
lambda The error scaling term, must be greater than 0.
di First index into dataset
dj Last index into dataset
order The order of the polynomial to fit
cf The curvefit_result_t to store the data (must have been allocated previously using curvefit_create
References _curvefit_result::alpha, _curvefit_result::b, _curvefit_result::beta, _curvefit_result::L, _curvefit_result::maxorder, _curvefit_result::mu, _dataset1d::points, rjmcmc_error(), _curvefit_result::S, _curvefit_result::x, and _curvefit_result::Z.
Referenced by curvefit_compute_mean_misfit().
curvefit_result_t* curvefit_create (int maxorder)
Create a new curvefit_result_t.
Parameters
maxorder Allow 0 .. maxorder to fit a dataset.
References _curvefit_result::alpha, _curvefit_result::b, _curvefit_result::beta, _curvefit_result::L, _curvefit_result::maxorder, _curvefit_result::mu, rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), _curvefit_result::S, _curvefit_result::Si, _curvefit_result::x, and _curvefit_result::Z.
Referenced by part1d_regression_rj_create(), single1d_direct_regression(), and single1d_regression_create().
void curvefit_destroy (curvefit_result_t * cf)
Free memory allocated for curvefit_result_t obecjt.
References _curvefit_result::alpha, _curvefit_result::b, _curvefit_result::beta, _curvefit_result::L, _curvefit_result::maxorder, _curvefit_result::mu, rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), _curvefit_result::S, _curvefit_result::Si, _curvefit_result::x, and _curvefit_result::Z.
Referenced by part1d_regression_rj_destroy(), and single1d_regression_destroy().
[curvefit_evaluate_pk(curvefit_result_t *cf, const dataset1d_t *data, int di, int dj, int max_order, const double *fixed_prior, double auto_z, double *mean_misfit, double *detCm, double *prior, double **S, double *pk, double *kcdf, double **mean, double **sigma)]int curvefit_evaluate_pk (curvefit_result_t * cf, const dataset1d_t * data, int di, int dj, int max_order, const double * fixed_prior, double auto_z, double * mean_misfit, double * detCm, double * prior, double ** S, double * pk, double * kcdf, double ** mean, double ** sigma)
Compute the complete fit over all orders.
Computes the fit of polynomials of varying order to a given dataset. Used to determine the relative likelihood of support for polynomials of different order to a given dataset.
Parameters
cf The curvefit_result_t object
data The dataset
di First index into dataset
dj Last index into dataset
max_order The maximum order polynomial to fit (cannot be greater than that of th the curvefit object).
fixed_prior Use a fixed prior for the different orders (set to NULL to use the automatic prior).
auto_z Z score for automatic prior, ie 3 = 3 standard deviations prior.
mean_misfit Output array of the misfit of the mean curve to the data for each order.
detCm Output array of determinant of the Covariance matrix for each order.
S Covariance Matrix output
pk Output array of probability of each order.
kcdf Cummulative probability of each order.
mean Output Mean curves for each order.
sigma Output Standard deviation for each order.
References curvefit_compute_mean_misfit(), and M_PI.
Referenced by part1d_regression_rj_propose_move(), single1d_direct_regression(), and single1d_evaluate_pk().
int curvefit_sample (curvefit_result_t * cf, rjmcmc_normal_rand_t normal, double * coeff, int coeff_len, double * prob)
Generate a random polynomial.
From a previous computed curvefit_result_t object, generate a random polynomial.
Parameters
cf The :curvefit_result_t object.
normal A function pointer to the Gaussian random number generator.
coeff Output array for polynomial coefficients.
coeff_len Size of the coeff array
prob A single double output value representing the probability of this curve.
References _curvefit_result::b, M_PI, _curvefit_result::mu, normal, rjmcmc_error(), _curvefit_result::Si, _curvefit_result::x, and _curvefit_result::Z.
Referenced by part1d_regression_rj_propose_move(), and single1d_regression_propose_lambda().
int curvefit_sample_detCm (curvefit_result_t * cf, double * detCm, int order)
Compute the determinant of the Covariance matrix.
Computes the determinant of the covariance matrix using the Cholesky decomposition.
Parameters
cf The :curvefit_result_t object.
detCm Output double for determinant
order Order of the previous computation.
References _curvefit_result::alpha, _curvefit_result::b, _curvefit_result::beta, _curvefit_result::L, _point1d::n, _point1d::x, _curvefit_result::x, _point1d::y, y, and _curvefit_result::Z.
Referenced by curvefit_compute_mean_misfit().
int curvefit_sample_mean (curvefit_result_t * cf, double * coeff, int coeff_len)
Retrieve the mean (best fit) polynomial.
From a previous computed curvefit_result_t object, retrieve the mean or best fit polynomial to the data.
Parameters
cf The :curvefit_result_t object.
coeff Output array for polynomial coefficients.
coeff_len Size of the coeff array
References _curvefit_result::mu.
Referenced by curvefit_compute_mean_misfit().
int curvefit_sample_sigma (curvefit_result_t * cf, double * sigma, int sigma_len)
Retrieve the sigma diagonals.
Retrieves the square root of the diagonals of the covariance matrix, ie standard deviation.
Parameters
cf The :curvefit_result_t object.
sigma Output array for diagonal elements.
sigma_len sigma array length.
References _curvefit_result::S.
Referenced by curvefit_compute_mean_misfit().