dataset1d.c File Reference
#include <stdlib.h>
*
#include <stdio.h>
*
#include <float.h>
*
#include `rjmcmc/dataset1d.h`
*
#include `rjmcmc/rjmcmc_debug.h`
*
Functions
dataset1d_t * dataset1d_create (int size)
Create a new empty dataset.
void dataset1d_destroy (dataset1d_t *d)
Destroy a dataset.
dataset1d_t * dataset1d_load_fixed (const char *filename, double n)
Load a dataset with a fixed noise parameter.
dataset1d_t * dataset1d_create_from_array (const double *x, const double *y, const double *n, int size)
Create a dataset from arrays.
dataset1d_t * dataset1d_load_known (const char *filename)
Load a dataset with known noise.
void dataset1d_sort (dataset1d_t *d)
Reorder dataset by x coordinate.
int dataset1d_range (const dataset1d_t *data, double xl, double xr, int *_xi, int *_xj)
Subset of a dataset.
int dataset1d_mean_variance (const dataset1d_t *data, int xi, int xj, double *_mean, double *_variance)
Compute the mean and variance.
Function Documentation
dataset1d_t* dataset1d_create (int size)
Create a new empty dataset.
Allocate a new dataset1d_t object of a given size.
Parameters
The maximum number of points.
References _dataset1d::lambdamax, _dataset1d::lambdamin, _dataset1d::lambdastd, _dataset1d::npoints, _dataset1d::points, rjmcmc_fatal(), _dataset1d::xmax, _dataset1d::xmin, _dataset1d::ymax, and _dataset1d::ymin.
Referenced by dataset1d_create_from_array(), dataset1d_load_fixed(), and dataset1d_load_known().
dataset1d_t* dataset1d_create_from_array (const double * x, const double * y, const double * n, int size)
Create a dataset from arrays.
Creates a dataset1d_t object from existing arrays of coordinates and noise. The arrays are copied into the dataset1d_t object.
Parameters
x X coordinates
y Y coordinates
n Noise values per point size The number of (X, Y, N) tuples.
References dataset1d_create(), _point1d::n, _dataset1d::points, _point1d::x, _dataset1d::xmax, _dataset1d::xmin, _point1d::y, _dataset1d::ymax, and _dataset1d::ymin.
void dataset1d_destroy (dataset1d_t * d)
Destroy a dataset.
Deallocate an existing dataset1d_t object.
Parameters
d The dataset to destroy.
Examples:
1d/partitioned/regression/zeromultistep/zeromultistep.c, and 1d/single/regression/cubic/cubic.c.
References _dataset1d::points.
dataset1d_t* dataset1d_load_fixed (const char * filename, double n)
Load a dataset with a fixed noise parameter.
Loads a file containing x, y coordinates and applies a fixed noise level to each data point. The expected format is a text file containing space separated x and y coordinates on each line.
Parameters
filename The file to load.
n The fixed noise level.
Examples:
1d/partitioned/regression/sawtooth/sawtooth.c.
References dataset1d_create(), _point1d::n, _dataset1d::points, rjmcmc_error(), _point1d::x, x, _dataset1d::xmax, _dataset1d::xmin, _point1d::y, y, _dataset1d::ymax, and _dataset1d::ymin.
dataset1d_t* dataset1d_load_known (const char * filename)
Load a dataset with known noise.
Loads a file containing x, y coordinates and noise. The expected format is a text file containing space separated x and y coordinates and noise on each line.
Parameters
filename The file to load.
Examples:
1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, and 1d/single/regression/cubic/cubic.c.
References _curvefit_result::b, dataset1d_create(), _point1d::n, _dataset1d::points, rjmcmc_error(), _point1d::x, x, _dataset1d::xmax, _dataset1d::xmin, _point1d::y, y, _dataset1d::ymax, and _dataset1d::ymin.
int dataset1d_mean_variance (const dataset1d_t * d, int xi, int xj, double * mean, double * variance)
Compute the mean and variance.
Computes the mean and variance of a set of data points in a given range of indices.
Parameters
d The dataset1d_t object
xi The first point to include in the mean/variance
xj The last point to include in the mean/variance
mean The mean output
variance The variance output.
Returns
The number of points in the range or -1 on error.
References _dataset1d::npoints, _dataset1d::points, rjmcmc_error(), and _point1d::y.
Referenced by part1d_zero_propose_birth(), part1d_zero_propose_death(), and part1d_zero_propose_move().
int dataset1d_range (const dataset1d_t * data, double xl, double xr, int * xi, int * xj)
Subset of a dataset.
Outputs the indices of the subset of a dataset that is within a given range of x coordinates.
Parameters
data The dataset1d_t object
xl The left x-coordinate of the range.
xr The right x-coordinate of the range.
xi The index of the first data point in the x-coordinate range.
xj The index of the last data point in the x-coordinate range.
Returns
The number of data points in the x-coordinate range or -1 on error.
References _dataset1d::npoints, _dataset1d::points, and _point1d::x.
Referenced by part1d_regression_rj_initialize(), part1d_regression_rj_propose_birth(), part1d_regression_rj_propose_death(), part1d_regression_rj_propose_move(), part1d_regression_rj_propose_value(), part1d_zero_propose_birth(), part1d_zero_propose_death(), and part1d_zero_propose_move().
void dataset1d_sort (dataset1d_t * d)
Reorder dataset by x coordinate.
Sorts the points within the dataset to ascending in x-coordinate.
Parameters
d The dataset1d_t object to sort.
References _dataset1d::npoints, _dataset1d::points, and rjmcmc_error().