dataset2d.c File Reference
#include <stdlib.h>
*
#include <stdio.h>
*
#include <float.h>
*
#include <rjmcmc/dataset2d.h>
*
#include <rjmcmc/rjmcmc_util.h>
*
Functions
dataset2d_t * dataset2d_allocate (int npoints)
Create a new empty dataset.
void dataset2d_destroy (dataset2d_t *d)
Destroy a dataset.
dataset2d_t * dataset2d_load_fixed (const char *filename, double sigma)
Load a dataset with a fixed noise parameter.
dataset2d_t * dataset2d_load_known (const char *filename)
Load a dataset with known noise.
Function Documentation
dataset2d_t* dataset2d_allocate (int npoints)
Create a new empty dataset.
Allocate a new dataset2d_t object of a given size.
Parameters
The maximum number of points.
References _dataset2d::lambdamax, _dataset2d::lambdamin, _dataset2d::lambdastd, _point2d::n, _dataset1d::npoints, _dataset2d::npoints, _dataset2d::points, _point2d::x, _dataset2d::xmax, _dataset2d::xmin, _point2d::y, _dataset2d::ymax, _dataset2d::ymin, _point2d::z, _dataset2d::zmax, and _dataset2d::zmin.
Referenced by dataset2d_load_fixed(), and dataset2d_load_known().
void dataset2d_destroy (dataset2d_t * d)
Destroy a dataset.
Deallocate an existing dataset2d_t object.
Parameters
d The dataset to destroy.
Examples:
2d/partitioned/fm/regression/regression.c, 2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References _dataset2d::points.
dataset2d_t* dataset2d_load_fixed (const char * filename, double sigma)
Load a dataset with a fixed noise parameter.
Loads a file containing x, y, z coordinates and applies a fixed noise level to each data point. The expected format is a text file containing space separated x, y and z coordinates on each line.
Parameters
filename The file to load.
sigma The fixed noise level.
Examples:
2d/partitioned/fm/regression/regression.c, 2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References dataset2d_allocate(), _point2d::n, _dataset2d::points, rjmcmc_error(), _point2d::x, x, _dataset2d::xmax, _dataset1d::xmin, _dataset2d::xmin, _point2d::y, y, _dataset2d::ymax, _dataset1d::ymin, _dataset2d::ymin, _point2d::z, z, _dataset2d::zmax, and _dataset2d::zmin.
dataset2d_t* dataset2d_load_known (const char * filename)
Load a dataset with known noise.
Loads a file containing x, y, z coordinates and noise. The expected format is a text file containing space separated x, y and z coordinates and noise on each line.
Parameters
filename The file to load.
References dataset2d_allocate(), _point2d::n, _dataset2d::points, rjmcmc_error(), _point2d::x, x, _dataset2d::xmax, _dataset1d::xmin, _dataset2d::xmin, _point2d::y, y, _dataset2d::ymax, _dataset1d::ymin, _dataset2d::ymin, _point2d::z, z, _dataset2d::zmax, and _dataset2d::zmin.