delaunay2d.c File Reference
#include <stdlib.h>
*
#include <stdio.h>
*
#include <math.h>
*
#include <string.h>
*
#include <rjmcmc/delaunay2d.h>
*
#include <rjmcmc/rjmcmc_defines.h>
*
Data Structures
struct _point
struct _triangle
struct _edgelist
struct _delaunay2d
Macros
#define TRIANGLE_INCR 1024
#define DLIST_INCR 16
#define MAXEDGES 32
Typedefs
typedef struct _point point_t
typedef struct _triangle triangle_t
typedef struct _edgelist edgelist_t
Functions
int delaunay2d_all_visible (const delaunay2d_t *d, int *vlist, int nvertices)
delaunay2d_t * delaunay2d_create (int maxpoints, double xmin, double xmax, double ymin, double ymax)
Create an initial Delaunay tesselation.
void delaunay2d_destroy (delaunay2d_t *d)
delaunay2d_t * delaunay2d_load (const char *filename)
int delaunay2d_save (const delaunay2d_t *d, const char *filename)
int delaunay2d_clone (const delaunay2d_t *src, delaunay2d_t *dst)
int delaunay2d_add (delaunay2d_t *d, double x, double y, bbox2d_t *bound)
int delaunay2d_delete (delaunay2d_t *d, int pi, bbox2d_t *bound)
int delaunay2d_shift_replace (delaunay2d_t *d, int pi)
int delaunay2d_find_enclosing_triangle (const delaunay2d_t *d, int t0, double px, double py, int *pa, int *pb, int *pc, double *ba, double *bb, double *bc)
int delaunay2d_nearest (delaunay2d_t *d, int include_corners, double px, double py)
int delaunay2d_nearest_from (delaunay2d_t *d, int p0, int include_corners, double px, double py)
int delaunay2d_point_of_index (const delaunay2d_t *d, int i, double *px, double *py)
int delaunay2d_index_of_point (const delaunay2d_t *d, double x, double y)
int delaunay2d_npoints (const delaunay2d_t *d)
int delaunay2d_polygon_bound (const delaunay2d_t *d, int pi, bbox2d_t *bound)
int delaunay2d_ct_update (delaunay2d_t *d, const double *point_z, int n)
int delaunay2d_ct_value_at (delaunay2d_t *d, int t0, double px, double py, double *z)
int barycentre (double px, double py, double x1, double y1, double x2, double y2, double x3, double y3, double *ba, double *bb, double *bc)
int point_in_triangle (double px, double py, double x1, double y1, double x2, double y2, double x3, double y3)
int delaunay2d_validate_circumcircles (const delaunay2d_t *d)
int delaunay2d_validate_edges (const delaunay2d_t *d)
int delaunay2d_validate_delaunay (const delaunay2d_t *d)
int delaunay2d_validate_neighbours (const delaunay2d_t *d)
int delaunay2d_validate_nonintersecting (const delaunay2d_t *d)
void delaunay2d_print_points (const delaunay2d_t *d)
void delaunay2d_print_edges (const delaunay2d_t *d)
void delaunay2d_print_triangles (const delaunay2d_t *d)
int triangle_circumcircle (double x1, double y1, double x2, double y2, double x3, double y3, double *cx, double *cy, double *r2)
int delaunay2d_save_geo (const delaunay2d_t *d, const char *filename)
int delaunay2d_save_cc_geo (const delaunay2d_t *d, const char *filename)
Macro Definition Documentation
#define DLIST_INCR 16
Referenced by delaunay2d_create(), and delaunay2d_save_cc_geo().
#define MAXEDGES 32
Referenced by delaunay2d_shift_replace().
#define TRIANGLE_INCR 1024
Referenced by delaunay2d_create(), and delaunay2d_ct_value_at().
Typedef Documentation
typedef struct _edgelist edgelist_t
typedef struct _point point_t
typedef struct _triangle triangle_t
Function Documentation
int barycentre (double px, double py, double x1, double y1, double x2, double y2, double x3, double y3, double * ba, double * bb, double * bc)
Referenced by point_in_triangle().
int delaunay2d_add (delaunay2d_t * d, double x, double y, bbox2d_t * bound)
References bbox2d_expand(), bbox2d_initialize(), c, delaunay2d_find_enclosing_triangle(), _triangle::n, _delaunay2d::np, _delaunay2d::nt, _delaunay2d::p, RJMCMC_CONDITIONCHECKINT, _delaunay2d::t, _triangle::v, _point::x, and _point::y.
Referenced by position_map2d_delaunay_insert(), and position_map2d_delaunay_move().
int delaunay2d_all_visible (const delaunay2d_t * d, int * vlist, int nvertices)
References _delaunay2d::p, _point::x, and _point::y.
int delaunay2d_clone (const delaunay2d_t * src, delaunay2d_t * dst)
References _triangle::cr2, _triangle::cx, _triangle::cy, _triangle::detT, _delaunay2d::e, _edgelist::edge, _delaunay2d::maxpoints, _triangle::n, _edgelist::n, _delaunay2d::np, _delaunay2d::nt, _delaunay2d::p, RJMCMC_CONDITIONCHECKINT, _delaunay2d::st, _delaunay2d::t, _triangle::v, _point::x, and _point::y.
Referenced by position_map2d_delaunay_clone().
delaunay2d_t* delaunay2d_create (int maxpoints, double xmin, double xmax, double ymin, double ymax)
Create an initial Delaunay tesselation.
Creates an initial delaunay2d_t object with four points representing the bounding box and 2 triangles tesselating the region.
Parameters
maxpoints The maximum number of points allowed to managed.
xmin Min x-coordinate
xmax Max x-coordinate
ymin Min y-coordinate
ymax Max y-coordinate
References _delaunay2d::ci, _delaunay2d::d2max, DLIST_INCR, _delaunay2d::e, _delaunay2d::felist, _delaunay2d::ftlist, _delaunay2d::listsize, _delaunay2d::maxpoints, _delaunay2d::nf, _delaunay2d::nlist, _delaunay2d::np, _delaunay2d::nt, _delaunay2d::p, RJMCMC_CONDITIONCHECKPTR, RJMCMC_INTCHECKPTR, RJMCMC_NULLCHECKPTR, _delaunay2d::sf, _delaunay2d::st, _delaunay2d::t, _delaunay2d::tlist, TRIANGLE_INCR, _delaunay2d::vlist, _delaunay2d::xmax, _delaunay2d::xmin, _delaunay2d::ymax, and _delaunay2d::ymin.
Referenced by delaunay2d_load(), and position_map2d_delaunay_create().
int delaunay2d_ct_update (delaunay2d_t * d, const double * point_z, int n)
References _triangle::ct, _point::dx, _point::dy, _delaunay2d::e, _edgelist::n, _delaunay2d::np, _delaunay2d::nt, _delaunay2d::p, _delaunay2d::t, _triangle::v, _point::x, _point::y, and _point::z.
int delaunay2d_ct_value_at (delaunay2d_t * d, int t0, double px, double py, double * z)
References c, _triangle::cr2, _triangle::ct, _triangle::cx, _triangle::cy, delaunay2d_find_enclosing_triangle(), _triangle::detT, _point::dx, _point::dy, _delaunay2d::e, _edgelist::edge, _delaunay2d::maxpoints, _triangle::n, _edgelist::n, _delaunay2d::np, _delaunay2d::nt, _delaunay2d::p, RJMCMC_CONDITIONCHECKINT, rjmcmc_error(), RJMCMC_NULLCHECKINT, _delaunay2d::st, _delaunay2d::t, TRIANGLE_INCR, _triangle::v, _point::x, and _point::y.
int delaunay2d_delete (delaunay2d_t * d, int pi, bbox2d_t * bound)
References _delaunay2d::felist, _delaunay2d::ftlist, _delaunay2d::nf, _delaunay2d::np, _delaunay2d::nt, RJMCMC_CONDITIONCHECKINT, _delaunay2d::t, _delaunay2d::tlist, _triangle::v, and _delaunay2d::vlist.
Referenced by position_map2d_delaunay_delete(), and position_map2d_delaunay_move().
void delaunay2d_destroy (delaunay2d_t * d)
References _delaunay2d::e, _delaunay2d::felist, _delaunay2d::ftlist, _delaunay2d::nlist, _delaunay2d::p, _delaunay2d::t, _delaunay2d::tlist, and _delaunay2d::vlist.
Referenced by position_map2d_delaunay_destroy().
int delaunay2d_find_enclosing_triangle (const delaunay2d_t * d, int t0, double px, double py, int * pa, int * pb, int * pc, double * ba, double * bb, double * bc)
References delaunay2d_print_points(), delaunay2d_print_triangles(), delaunay2d_validate_circumcircles(), delaunay2d_validate_neighbours(), delaunay2d_validate_nonintersecting(), _triangle::n, _delaunay2d::t, _triangle::v, _delaunay2d::xmax, _delaunay2d::xmin, _delaunay2d::ymax, and _delaunay2d::ymin.
Referenced by delaunay2d_add(), delaunay2d_ct_value_at(), and position_map2d_delaunay_enclosing_triangle().
int delaunay2d_index_of_point (const delaunay2d_t * d, double x, double y)
References _delaunay2d::np, _delaunay2d::p, RJMCMC_CONDITIONCHECKINT, _point::x, and _point::y.
delaunay2d_t* delaunay2d_load (const char * filename)
References c, delaunay2d_create(), _triangle::n, _delaunay2d::np, _delaunay2d::nt, _delaunay2d::p, _delaunay2d::t, _triangle::v, _point::x, and _point::y.
int delaunay2d_nearest (delaunay2d_t * d, int include_corners, double px, double py)
References delaunay2d_nearest_from().
int delaunay2d_nearest_from (delaunay2d_t * d, int p0, int include_corners, double px, double py)
References _delaunay2d::ci, _delaunay2d::d2max, delaunay2d_validate_delaunay(), delaunay2d_validate_edges(), _delaunay2d::e, _edgelist::edge, and _edgelist::n.
Referenced by delaunay2d_nearest(), and position_map2d_delaunay_nearest().
int delaunay2d_npoints (const delaunay2d_t * d)
References _delaunay2d::np, and RJMCMC_CONDITIONCHECKINT.
int delaunay2d_point_of_index (const delaunay2d_t * d, int i, double * px, double * py)
References _delaunay2d::np, _delaunay2d::p, RJMCMC_CONDITIONCHECKINT, _point::x, and _point::y.
Referenced by position_map2d_delaunay_nearest(), and position_map2d_delaunay_position_of_index().
int delaunay2d_polygon_bound (const delaunay2d_t * d, int pi, bbox2d_t * bound)
References _delaunay2d::nt, RJMCMC_CONDITIONCHECKINT, _delaunay2d::t, and _triangle::v.
Referenced by position_map2d_delaunay_polygon_bound().
void delaunay2d_print_edges (const delaunay2d_t * d)
References _delaunay2d::e, _edgelist::edge, _edgelist::n, and _delaunay2d::np.
void delaunay2d_print_points (const delaunay2d_t * d)
References _delaunay2d::np, _delaunay2d::p, _point::x, and _point::y.
Referenced by delaunay2d_find_enclosing_triangle(), delaunay2d_validate_circumcircles(), delaunay2d_validate_neighbours(), and position_map2d_delaunay_move().
void delaunay2d_print_triangles (const delaunay2d_t * d)
References _triangle::cr2, _triangle::cx, _triangle::cy, _triangle::detT, _point::dx, _point::dy, _delaunay2d::e, _edgelist::edge, _triangle::n, _edgelist::n, _delaunay2d::np, _delaunay2d::nt, _delaunay2d::p, RJMCMC_CONDITIONCHECKINT, RJMCMC_NULLCHECKPTR, _delaunay2d::t, triangle_circumcircle(), _triangle::v, _point::x, and _point::y.
Referenced by delaunay2d_find_enclosing_triangle(), delaunay2d_validate_circumcircles(), delaunay2d_validate_neighbours(), and position_map2d_delaunay_move().
int delaunay2d_save (const delaunay2d_t * d, const char * filename)
References _delaunay2d::maxpoints, _triangle::n, _delaunay2d::np, _delaunay2d::nt, _delaunay2d::p, _delaunay2d::st, _delaunay2d::t, _triangle::v, _point::x, _delaunay2d::xmax, _delaunay2d::xmin, _point::y, _delaunay2d::ymax, and _delaunay2d::ymin.
Referenced by position_map2d_delaunay_save().
int delaunay2d_save_cc_geo (const delaunay2d_t * d, const char * filename)
References bbox2d_expand(), bbox2d_initialize(), _point::ci, _delaunay2d::ci, _triangle::cr2, _triangle::cx, _triangle::cy, DLIST_INCR, _point::dx, _point::dy, _delaunay2d::felist, _delaunay2d::ftlist, _delaunay2d::listsize, _triangle::n, _delaunay2d::nf, _delaunay2d::nlist, _delaunay2d::nt, _delaunay2d::p, _point::pd2, point_in_triangle(), RJMCMC_CONDITIONCHECKINT, RJMCMC_NULLCHECKINT, _delaunay2d::sf, _delaunay2d::t, _delaunay2d::tlist, _triangle::v, _delaunay2d::vlist, _point::x, and _point::y.
int delaunay2d_save_geo (const delaunay2d_t * d, const char * filename)
References _delaunay2d::np, _delaunay2d::nt, _delaunay2d::p, _delaunay2d::t, _triangle::v, _point::x, and _point::y.
int delaunay2d_shift_replace (delaunay2d_t * d, int pi)
References _delaunay2d::e, _edgelist::edge, MAXEDGES, _edgelist::n, _delaunay2d::np, _delaunay2d::nt, _delaunay2d::p, RJMCMC_CONDITIONCHECKINT, _delaunay2d::t, _triangle::v, _point::x, and _point::y.
Referenced by position_map2d_delaunay_move().
int delaunay2d_validate_circumcircles (const delaunay2d_t * d)
References _triangle::cr2, _triangle::cx, _triangle::cy, delaunay2d_print_points(), delaunay2d_print_triangles(), _point::dx, _point::dy, _delaunay2d::nt, _delaunay2d::p, RJMCMC_CONDITIONCHECKINT, _delaunay2d::t, _triangle::v, _point::x, and _point::y.
Referenced by delaunay2d_find_enclosing_triangle(), and position_map2d_delaunay_validate().
int delaunay2d_validate_delaunay (const delaunay2d_t * d)
References _triangle::cr2, _triangle::cx, _triangle::cy, _point::dx, _point::dy, _delaunay2d::np, _delaunay2d::nt, _delaunay2d::p, _delaunay2d::t, _triangle::v, _point::x, and _point::y.
Referenced by delaunay2d_nearest_from(), and position_map2d_delaunay_validate().
int delaunay2d_validate_edges (const delaunay2d_t * d)
References _delaunay2d::e, _edgelist::edge, _edgelist::n, _delaunay2d::np, _delaunay2d::nt, _delaunay2d::t, and _triangle::v.
Referenced by delaunay2d_nearest_from(), and position_map2d_delaunay_validate().
int delaunay2d_validate_neighbours (const delaunay2d_t * d)
References delaunay2d_print_points(), delaunay2d_print_triangles(), _triangle::n, _delaunay2d::nt, _delaunay2d::t, and _triangle::v.
Referenced by delaunay2d_find_enclosing_triangle(), and position_map2d_delaunay_validate().
int delaunay2d_validate_nonintersecting (const delaunay2d_t * d)
References _delaunay2d::np, _delaunay2d::nt, _delaunay2d::p, _delaunay2d::t, _triangle::v, _point::x, and _point::y.
Referenced by delaunay2d_find_enclosing_triangle().
int point_in_triangle (double px, double py, double x1, double y1, double x2, double y2, double x3, double y3)
References barycentre(), _triangle::n, _delaunay2d::p, RJMCMC_CONDITIONCHECKINT, _delaunay2d::t, triangle_circumcircle(), _triangle::v, _point::x, and _point::y.
Referenced by delaunay2d_save_cc_geo().
int triangle_circumcircle (double x1, double y1, double x2, double y2, double x3, double y3, double * cx, double * cy, double * r2)
References _point::dx, and _point::dy.
Referenced by delaunay2d_print_triangles(), and point_in_triangle().