engine.h File Reference
#include <rjmcmc/rjmcmc.h>
*
Data Structures
struct _rjmcmc_engine_cb
Typedefs
typedef struct _rjmcmc_engine_cb rjmcmc_engine_cb_t
Functions
int rjmcmc_engine_run (rjmcmc_engine_cb_t *cb, int burn_iterations, int total_iterations, int sample_rate)
int rjmcmc_engine_init (rjmcmc_engine_cb_t *cb, int burn_iterations, int total_iterations, int sample_rate)
int rjmcmc_engine_restart (rjmcmc_engine_cb_t *cb, int burn_iterations, int total_iterations, int sample_rate, int iteration, double likelihood)
int rjmcmc_engine_step (rjmcmc_engine_cb_t *cb)
int rjmcmc_engine_finish (rjmcmc_engine_cb_t *cb)
Typedef Documentation
typedef struct _rjmcmc_engine_cb rjmcmc_engine_cb_t
Function Documentation
int rjmcmc_engine_finish (rjmcmc_engine_cb_t * cb)
int rjmcmc_engine_init (rjmcmc_engine_cb_t * cb, int burn_iterations, int total_iterations, int sample_rate)
References _rjmcmc_engine_cb::arg, _rjmcmc_engine_cb::burnin, _rjmcmc_engine_cb::current_like, _rjmcmc_engine_cb::i, _rjmcmc_engine_cb::initialize_state, rjmcmc_error(), _rjmcmc_engine_cb::sample_rate, and _rjmcmc_engine_cb::total.
Referenced by part1d_forwardmodel_natural_hierarchical_init(), part1d_forwardmodel_natural_init(), and rjmcmc_engine_run().
int rjmcmc_engine_restart (rjmcmc_engine_cb_t * cb, int burn_iterations, int total_iterations, int sample_rate, int iteration, double likelihood)
References _rjmcmc_engine_cb::burnin, _rjmcmc_engine_cb::current_like, _rjmcmc_engine_cb::i, likelihood, _delaunay2d::p, rjmcmc_engine_step(), rjmcmc_error(), _rjmcmc_engine_cb::sample_rate, and _rjmcmc_engine_cb::total.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart().
int rjmcmc_engine_run (rjmcmc_engine_cb_t * cb, int burn_iterations, int total_iterations, int sample_rate)
References _delaunay2d::p, rjmcmc_engine_init(), and rjmcmc_engine_step().
Referenced by MPI_part1d_forwardmodel(), MPI_part1d_forwardmodel_hierarchical(), MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), MPI_part2d_forwardmodel(), MPI_part2d_forwardmodel_checkpoint(), MPI_part2d_forwardmodel_hierarchical(), MPI_part2d_forwardmodel_hierarchical_restartable(), MPI_single_forwardmodel(), MPI_single_forwardmodel_hierarchical(), part1d_forwardmodel(), part1d_forwardmodel_hierarchical(), part1d_forwardmodel_natural(), part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel_zero_cubic(), part1d_natural_regression(), part1d_regression(), part1d_zero_regression(), part2d_forwardmodel(), part2d_forwardmodel_hierarchical(), part2d_forwardmodel_restartable(), part2d_regression(), single_forwardmodel(), and single_forwardmodel_hierarchical().
int rjmcmc_engine_step (rjmcmc_engine_cb_t * cb)
References _rjmcmc_engine_cb::accept, _rjmcmc_engine_cb::arg, _rjmcmc_engine_cb::compute_misfit, _rjmcmc_engine_cb::current_like, _rjmcmc_engine_cb::i, _delaunay2d::p, _rjmcmc_engine_cb::perturb_process, rjmcmc_error(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, and _rjmcmc_engine_cb::total.
Referenced by part1d_forwardmodel_natural_hierarchical_step(), part1d_forwardmodel_natural_step(), rjmcmc_engine_restart(), and rjmcmc_engine_run().