forwardmodel_part1d_hierarchical.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <math.h>
*
#include <float.h>
*
#include <string.h>
*
#include <rjmcmc/forwardmodel.h>
*
#include <rjmcmc/engine.h>
*
#include <rjmcmc/forwardmodel_mpi.h>
*
#include <rjmcmc/part1d_forwardmodel.h>
*
#include <rjmcmc/rjmcmc_util.h>
*
#include <rjmcmc/rjmcmc_debug.h>
*
Data Structures
struct part1dfm
struct _part1d_fm_hierarchical_likelihood_state
Enumerations
enum {
*
BIRTH = 0,
DEATH,
MOVE,
LOCALVALUE,
*
HIERARCHICALVALUE,
GLOBALVALUE,
NPROCESSES,
NPROCESSES_NOGLOBAL = GLOBALVALUE
 }
Functions
resultset1dfm_t * part1d_forwardmodel_hierarchical (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results)
Partitioned 1d forwardmodel with hierarchical parameters.
resultset1dfm_t * part1d_forwardmodel_natural_hierarchical (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results)
Natural partitioned forward model with hierarchical parameters.
void * part1d_forwardmodel_natural_hierarchical_init (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results)
int part1d_forwardmodel_natural_hierarchical_step (void *_s)
resultset1dfm_t * part1d_forwardmodel_natural_hierarchical_finish (void *_s)
resultset1dfm_t * MPI_part1d_forwardmodel_hierarchical (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
resultset1dfm_t * MPI_part1d_forwardmodel_natural_hierarchical (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
Enumeration Type Documentation
anonymous enum
Enumerator
BIRTH
DEATH
MOVE
LOCALVALUE
HIERARCHICALVALUE
GLOBALVALUE
NPROCESSES
NPROCESSES_NOGLOBAL
Function Documentation
[MPI_part1d_forwardmodel_hierarchical(int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)]resultset1dfm_t* MPI_part1d_forwardmodel_hierarchical (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void * user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
References _rjmcmc_engine_cb::accept, _rjmcmc_engine_cb::arg, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, part1dfm::hierarchical_parameters, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, MPI_resultset1dfm_assemble_results(), part1dfm::nglobalparameters, part1dfm::nhierarchicalparameters, part1dfm::nlocalparameters, part1dfm::normal, NPROCESSES, part1dfm::nprocesses, NPROCESSES_NOGLOBAL, PART1D_FM_ZERO, part1d_forwardmodel_create(), part1d_forwardmodel_destroy(), _rjmcmc_engine_cb::perturb_process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::random, part1dfm::results, resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
Referenced by mpi_part1d_forwardmodel_hierarchical_f().
[MPI_part1d_forwardmodel_natural_hierarchical(int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)]resultset1dfm_t* MPI_part1d_forwardmodel_natural_hierarchical (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void * user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
References _rjmcmc_engine_cb::accept, part1dfm::accepted, _rjmcmc_engine_cb::arg, BIRTH, part1dfm::birth_prob, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, part1dfm::current_like, part1dfm::current_logdetce, DEATH, part1dfm::death_prob, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, GLOBALVALUE, _part1d_fm_hierarchical_likelihood_state::gradients, part1dfm::hierarchical_parameters, part1dfm::hierarchical_prob, HIERARCHICALVALUE, part1dfm::index, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, LOCALVALUE, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, _part1d_fm_hierarchical_likelihood_state::model, MOVE, part1dfm::move_prob, MPI_resultset1dfm_assemble_results(), part1dfm::nglobalparameters, part1dfm::nhierarchicalparameters, part1dfm::nlocalparameters, _part1d_fm_hierarchical_likelihood_state::nlocalparameters, part1dfm::normal, NPROCESSES, part1dfm::nprocesses, NPROCESSES_NOGLOBAL, part1dfm::out, PART1D_FM_NATURAL, part1d_forwardmodel_clone(), part1d_forwardmodel_create(), part1d_forwardmodel_destroy(), part1d_forwardmodel_evaluate_local_parameters(), part1d_forwardmodel_global_parameters(), part1d_forwardmodel_hierarchical_parameters(), part1d_forwardmodel_initialize(), part1d_forwardmodel_partition_fill_list(), part1d_forwardmodel_partition_position(), part1d_forwardmodel_partitions(), part1d_forwardmodel_propose_birth(), part1d_forwardmodel_propose_death(), part1d_forwardmodel_propose_global_value(), part1d_forwardmodel_propose_hierarchical(), part1d_forwardmodel_propose_local_value(), part1d_forwardmodel_propose_move(), _rjmcmc_engine_cb::perturb_process, part1dfm::process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::proposed_like, part1dfm::proposed_logdetce, part1dfm::random, part1dfm::results, resultset1dfm_accept(), resultset1dfm_accept_local_value(), resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), resultset1dfm_propose(), resultset1dfm_sample_global_parameter(), resultset1dfm_sample_hierarchical(), resultset1dfm_sample_local_parameter(), resultset1dfm_sample_misfit(), resultset1dfm_sample_npartitions(), resultset1dfm_sample_partition_x(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), rjmcmc_random_choose_int(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::value_prob, _part1d_fm_hierarchical_likelihood_state::values, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
Referenced by mpi_part1d_forwardmodel_natural_hierarchical_f().
[part1d_forwardmodel_hierarchical(int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results)]resultset1dfm_t* part1d_forwardmodel_hierarchical (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void * user_arg, int results)
Partitioned 1d forwardmodel with hierarchical parameters.
This method is the same as the part1d_forwardmodel except it also solves for hierarchical parameters that are used to construct the covariance matrix. See [bodin2012A] for an example application of hierarchical solving.
Parameters
burnin The number of burn in iterations.
total The total number of iterations (must be greater than burnin).
minpart The minimum number of partitions, this should be 2.
maxpart The maximum number of partitions.
minx The lower bound value of the x coordinate
maxx The upper bound value of the x coordinate.
xsamples When producing mean curves etc, the number of discretization steps used for constructing the curve. A value of 100 suits most cases.
ysamples Results such as median, mode, credible intervals are computed using a histogram of values, this parameter sets the number of bins for this histogram. A value of 100 suits most cases.
credible_interval The credible interval expressed as a percentage between 0 and 1.
pd The standard deviation of the perturb partition boundary (move) step.
random User supplied uniform random number generator.
normal User supplied normal random number generator.
nglobalparameters The number of global parameters.
global_parameters An array of global parameters (their min, max and perturbation standard deviations).
nlocalparameters The number of local parameters.
local_parameters An array of local parameters (their min, max and perturbation standard deviations).
nhierarchicalparameters The number of hierarchical parameters.
hierarchical_parameters An array of hierarchical parameters (their min, max and perturbation standard deviations).
lp The hierarchical likelihood function.
user_arg A pointer to user data that will be supplied to the likelihood function.
results The results desired as a bitwise or'ing of resultset1dfm_result_t values.
For an example of using this function, see the example 1d/single/fm/partitioned/regression/regression.c
Examples:
1d/partitioned/fm/regression/regression.c.
References _rjmcmc_engine_cb::accept, _rjmcmc_engine_cb::arg, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, part1dfm::current_like, part1dfm::current_logdetce, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, part1dfm::hierarchical_parameters, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, part1dfm::nglobalparameters, part1dfm::nhierarchicalparameters, part1dfm::nlocalparameters, part1dfm::normal, NPROCESSES, part1dfm::nprocesses, NPROCESSES_NOGLOBAL, PART1D_FM_ZERO, part1d_forwardmodel_create(), part1d_forwardmodel_destroy(), _rjmcmc_engine_cb::perturb_process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::proposed_like, part1dfm::proposed_logdetce, part1dfm::random, part1dfm::results, resultset1dfm_assemble_results(), resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
Referenced by part1d_forwardmodel_hierarchical_f().
[part1d_forwardmodel_natural_hierarchical(int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results)]resultset1dfm_t* part1d_forwardmodel_natural_hierarchical (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void * user_arg, int results)
Natural partitioned forward model with hierarchical parameters.
This method is the same as the part1d_forwardmodel_hierarchical except it uses joined line segments between partition boundaries rather than zero order fits within each partition to fit the data.
Parameters
burnin The number of burn in iterations.
total The total number of iterations (must be greater than burnin).
minpart The minimum number of partitions, this should be 2.
maxpart The maximum number of partitions.
minx The lower bound value of the x coordinate
maxx The upper bound value of the x coordinate.
xsamples When producing mean curves etc, the number of discretization steps used for constructing the curve. A value of 100 suits most cases.
ysamples Results such as median, mode, credible intervals are computed using a histogram of values, this parameter sets the number of bins for this histogram. A value of 100 suits most cases.
credible_interval The credible interval expressed as a percentage between 0 and 1.
pd The standard deviation of the perturb partition boundary (move) step.
random User supplied uniform random number generator.
normal User supplied normal random number generator.
nglobalparameters The number of global parameters.
global_parameters An array of global parameters (their min, max and perturbation standard deviations).
nlocalparameters The number of local parameters.
local_parameters An array of local parameters (their min, max and perturbation standard deviations).
nhierarchicalparameters The number of hierarchical parameters.
hierarchical_parameters An array of hierarchical parameters (their min, max and perturbation standard deviations).
lp The hierarchical likelihood function.
user_arg A pointer to user data that will be supplied to the likelihood function.
results The results desired as a bitwise or'ing of resultset1dfm_result_t values.
References _rjmcmc_engine_cb::accept, _rjmcmc_engine_cb::arg, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, part1dfm::hierarchical_parameters, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, part1dfm::nglobalparameters, part1dfm::nhierarchicalparameters, part1dfm::nlocalparameters, part1dfm::normal, NPROCESSES, part1dfm::nprocesses, NPROCESSES_NOGLOBAL, PART1D_FM_NATURAL, part1d_forwardmodel_create(), part1d_forwardmodel_destroy(), _rjmcmc_engine_cb::perturb_process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::random, part1dfm::results, resultset1dfm_assemble_results(), resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
Referenced by part1d_forwardmodel_natural_hierarchical_f().
resultset1dfm_t* part1d_forwardmodel_natural_hierarchical_finish (void * _s)
References part1dfm::current, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::nlocalparameters, part1d_forwardmodel_destroy(), part1dfm::proposed, part1dfm::results, resultset1dfm_assemble_results(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), part1dfm::x, and part1dfm::y.
Referenced by part1d_forwardmodel_natural_hierarchical_finish_f().
[part1d_forwardmodel_natural_hierarchical_init(int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results)]void* part1d_forwardmodel_natural_hierarchical_init (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void * user_arg, int results)
References _rjmcmc_engine_cb::accept, _rjmcmc_engine_cb::arg, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, part1dfm::hierarchical_parameters, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, part1dfm::nglobalparameters, part1dfm::nhierarchicalparameters, part1dfm::nlocalparameters, part1dfm::normal, NPROCESSES, part1dfm::nprocesses, NPROCESSES_NOGLOBAL, PART1D_FM_NATURAL, part1d_forwardmodel_create(), _rjmcmc_engine_cb::perturb_process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::random, part1dfm::results, resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_engine_init(), rjmcmc_error(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
Referenced by part1d_forwardmodel_natural_hierarchical_init_f().
int part1d_forwardmodel_natural_hierarchical_step (void * _s)
References part1dfm::cb, and rjmcmc_engine_step().
Referenced by part1d_forwardmodel_natural_hierarchical_step_f().