forwardmodel_f.c File Reference
#include <stdlib.h>
*
#include <rjmcmc/rjmcmc.h>
*
#include <rjmcmc/forwardmodel.h>
*
#include <rjmcmc/forwardmodel_f.h>
*
#include <rjmcmc/forwardmodel_mpi.h>
*
Data Structures
struct part1d_fm_value_at_wrap
struct part1d_forwardmodel_wrap
struct part1d_hierarchical_forwardmodel_wrap
struct part2d_fm_value_at_wrap
struct part2d_forwardmodel_wrap
struct part2d_forwardmodel_hierarchical_wrap
Functions
resultsetfm_t * single_forwardmodel_f (int burnin, int total, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nparameters, const forwardmodelparameter_t *parameters, single_fm_likelihood_t *lp, void **user_arg, int samples, double credible_interval, int results)
resultsetfm_t * single_forwardmodel_hierarchical_f (int burnin, int total, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nparameters, const forwardmodelparameter_t *parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchicalparameters, single_fm_likelihood_hierarchical_t *lp, void **user_arg, int samples, double credible_interval, int results)
resultset1dfm_t * part1d_forwardmodel_f (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_f_t *lp, void *user_arg, int results)
resultset1dfm_t * part1d_forwardmodel_hierarchical_f (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_f_t *lp, void *user_arg, int results)
resultset1dfm_t * part1d_forwardmodel_natural_f (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_f_t *lp, void *user_arg, int results)
resultset1dfm_t * part1d_forwardmodel_natural_hierarchical_f (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_f_t *lp, void *user_arg, int results)
void * part1d_forwardmodel_natural_hierarchical_init_f (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_f_t *lp, void *user_arg, int results)
int part1d_forwardmodel_natural_hierarchical_step_f (void *state)
resultset1dfm_t * part1d_forwardmodel_natural_hierarchical_finish_f (void *state)
resultset2dfm_t * part2d_forwardmodel_f (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_f_t *lp, void *user_arg, int results)
resultset2dfm_t * part2d_forwardmodel_hierarchical_f (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part2d_fm_hierarchical_likelihood_f_t *lp, void *user_arg, int results)
resultsetfm_t * mpi_single_forwardmodel_f (int burnin, int total, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nparameters, const forwardmodelparameter_t *parameters, single_fm_likelihood_t *lp, void *user_arg, int samples, double credible_interval, int results, int mpisize, int mpirank, int root, int comm)
resultsetfm_t * mpi_single_forwardmodel_hierarchical_f (int burnin, int total, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nparameters, const forwardmodelparameter_t *parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchicalparameters, single_fm_likelihood_hierarchical_t *lp, void *user_arg, int samples, double credible_interval, int results, int mpisize, int mpirank, int root, int comm)
resultset1dfm_t * mpi_part1d_forwardmodel_f (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_f_t *lp, void *user_arg, int results, int mpisize, int mpirank, int root, int comm)
resultset1dfm_t * mpi_part1d_forwardmodel_natural_f (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_f_t *lp, void *user_arg, int results, int mpisize, int mpirank, int root, int comm)
resultset1dfm_t * mpi_part1d_forwardmodel_hierarchical_f (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_f_t *lp, void *user_arg, int results, int mpisize, int mpirank, int root, int comm)
resultset1dfm_t * mpi_part1d_forwardmodel_natural_hierarchical_f (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_f_t *lp, void *user_arg, int results, int mpisize, int mpirank, int root, int comm)
resultset2dfm_t * mpi_part2d_forwardmodel_f (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_f_t *lp, void *user_arg, int results, int mpisize, int mpirank, int root, int comm)
resultset2dfm_t * mpi_part2d_forwardmodel_hierarchical_f (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part2d_fm_hierarchical_likelihood_f_t *lp, void *user_arg, int results, int mpisize, int mpirank, int root, int comm)
resultset2dfm_t * mpi_part2d_forwardmodel_hierarchical_restartable_f (const char *infile_template, const char *outfile_template, int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part2d_fm_hierarchical_likelihood_f_t *lp, void *user_arg, int results, int mpisize, int mpirank, int root, int comm)
Function Documentation
[mpi_part1d_forwardmodel_f(int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_f_t *lp, void *user_arg, int results, int mpisize, int mpirank, int root, int comm)]resultset1dfm_t* mpi_part1d_forwardmodel_f (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t * random, rjmcmc_normal_rand_t * normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part1d_fm_likelihood_f_t * lp, void * user_arg, int results, int mpisize, int mpirank, int root, int comm)
References part1d_forwardmodel_wrap::lp, MPI_part1d_forwardmodel(), user_arg, and part1d_forwardmodel_wrap::user_arg.
[mpi_part1d_forwardmodel_hierarchical_f(int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_f_t *lp, void *user_arg, int results, int mpisize, int mpirank, int root, int comm)]resultset1dfm_t* mpi_part1d_forwardmodel_hierarchical_f (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t * random, rjmcmc_normal_rand_t * normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part1d_fm_hierarchical_likelihood_f_t * lp, void * user_arg, int results, int mpisize, int mpirank, int root, int comm)
References part1d_hierarchical_forwardmodel_wrap::lp, MPI_part1d_forwardmodel_hierarchical(), user_arg, and part1d_hierarchical_forwardmodel_wrap::user_arg.
[mpi_part1d_forwardmodel_natural_f(int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_f_t *lp, void *user_arg, int results, int mpisize, int mpirank, int root, int comm)]resultset1dfm_t* mpi_part1d_forwardmodel_natural_f (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t * random, rjmcmc_normal_rand_t * normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part1d_fm_likelihood_f_t * lp, void * user_arg, int results, int mpisize, int mpirank, int root, int comm)
References part1d_forwardmodel_wrap::lp, MPI_part1d_forwardmodel_natural(), user_arg, and part1d_forwardmodel_wrap::user_arg.
[mpi_part1d_forwardmodel_natural_hierarchical_f(int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_f_t *lp, void *user_arg, int results, int mpisize, int mpirank, int root, int comm)]resultset1dfm_t* mpi_part1d_forwardmodel_natural_hierarchical_f (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t * random, rjmcmc_normal_rand_t * normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part1d_fm_hierarchical_likelihood_f_t * lp, void * user_arg, int results, int mpisize, int mpirank, int root, int comm)
References part1d_hierarchical_forwardmodel_wrap::lp, MPI_part1d_forwardmodel_natural_hierarchical(), user_arg, and part1d_hierarchical_forwardmodel_wrap::user_arg.
[mpi_part2d_forwardmodel_f(int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_f_t *lp, void *user_arg, int results, int mpisize, int mpirank, int root, int comm)]resultset2dfm_t* mpi_part2d_forwardmodel_f (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t * random, rjmcmc_normal_rand_t * normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part2d_fm_likelihood_f_t * lp, void * user_arg, int results, int mpisize, int mpirank, int root, int comm)
References part2d_forwardmodel_wrap::lp, MPI_part2d_forwardmodel(), user_arg, and part2d_forwardmodel_wrap::user_arg.
[mpi_part2d_forwardmodel_hierarchical_f(int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part2d_fm_hierarchical_likelihood_f_t *lp, void *user_arg, int results, int mpisize, int mpirank, int root, int comm)]resultset2dfm_t* mpi_part2d_forwardmodel_hierarchical_f (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t * random, rjmcmc_normal_rand_t * normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part2d_fm_hierarchical_likelihood_f_t * lp, void * user_arg, int results, int mpisize, int mpirank, int root, int comm)
References part2d_forwardmodel_hierarchical_wrap::lp, MPI_part2d_forwardmodel_hierarchical(), user_arg, and part2d_forwardmodel_hierarchical_wrap::user_arg.
[mpi_part2d_forwardmodel_hierarchical_restartable_f(const char *infile_template, const char *outfile_template, int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part2d_fm_hierarchical_likelihood_f_t *lp, void *user_arg, int results, int mpisize, int mpirank, int root, int comm)]resultset2dfm_t* mpi_part2d_forwardmodel_hierarchical_restartable_f (const char * infile_template, const char * outfile_template, int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t * random, rjmcmc_normal_rand_t * normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part2d_fm_hierarchical_likelihood_f_t * lp, void * user_arg, int results, int mpisize, int mpirank, int root, int comm)
References part2d_forwardmodel_hierarchical_wrap::lp, MPI_part2d_forwardmodel_hierarchical_restartable(), user_arg, and part2d_forwardmodel_hierarchical_wrap::user_arg.
[mpi_single_forwardmodel_f(int burnin, int total, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nparameters, const forwardmodelparameter_t *parameters, single_fm_likelihood_t *lp, void *user_arg, int samples, double credible_interval, int results, int mpisize, int mpirank, int root, int comm)]resultsetfm_t* mpi_single_forwardmodel_f (int burnin, int total, rjmcmc_uniform_rand_t * random, rjmcmc_normal_rand_t * normal, int nparameters, const forwardmodelparameter_t * parameters, single_fm_likelihood_t * lp, void * user_arg, int samples, double credible_interval, int results, int mpisize, int mpirank, int root, int comm)
References MPI_single_forwardmodel().
[mpi_single_forwardmodel_hierarchical_f(int burnin, int total, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nparameters, const forwardmodelparameter_t *parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchicalparameters, single_fm_likelihood_hierarchical_t *lp, void *user_arg, int samples, double credible_interval, int results, int mpisize, int mpirank, int root, int comm)]resultsetfm_t* mpi_single_forwardmodel_hierarchical_f (int burnin, int total, rjmcmc_uniform_rand_t * random, rjmcmc_normal_rand_t * normal, int nparameters, const forwardmodelparameter_t * parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchicalparameters, single_fm_likelihood_hierarchical_t * lp, void * user_arg, int samples, double credible_interval, int results, int mpisize, int mpirank, int root, int comm)
References MPI_single_forwardmodel_hierarchical().
[part1d_forwardmodel_f(int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_f_t *lp, void *user_arg, int results)]resultset1dfm_t* part1d_forwardmodel_f (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t * random, rjmcmc_normal_rand_t * normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part1d_fm_likelihood_f_t * lp, void * user_arg, int results)
References part1d_forwardmodel_wrap::lp, part1d_forwardmodel(), user_arg, and part1d_forwardmodel_wrap::user_arg.
[part1d_forwardmodel_hierarchical_f(int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_f_t *lp, void *user_arg, int results)]resultset1dfm_t* part1d_forwardmodel_hierarchical_f (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t * random, rjmcmc_normal_rand_t * normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part1d_fm_hierarchical_likelihood_f_t * lp, void * user_arg, int results)
References part1d_hierarchical_forwardmodel_wrap::lp, part1d_forwardmodel_hierarchical(), user_arg, and part1d_hierarchical_forwardmodel_wrap::user_arg.
[part1d_forwardmodel_natural_f(int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_f_t *lp, void *user_arg, int results)]resultset1dfm_t* part1d_forwardmodel_natural_f (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t * random, rjmcmc_normal_rand_t * normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part1d_fm_likelihood_f_t * lp, void * user_arg, int results)
References part1d_forwardmodel_wrap::lp, part1d_forwardmodel_natural(), user_arg, and part1d_forwardmodel_wrap::user_arg.
[part1d_forwardmodel_natural_hierarchical_f(int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_f_t *lp, void *user_arg, int results)]resultset1dfm_t* part1d_forwardmodel_natural_hierarchical_f (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t * random, rjmcmc_normal_rand_t * normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part1d_fm_hierarchical_likelihood_f_t * lp, void * user_arg, int results)
References part1d_hierarchical_forwardmodel_wrap::lp, part1d_forwardmodel_natural_hierarchical(), user_arg, and part1d_hierarchical_forwardmodel_wrap::user_arg.
resultset1dfm_t* part1d_forwardmodel_natural_hierarchical_finish_f (void * state)
References part1d_forwardmodel_natural_hierarchical_finish(), and part1d_hierarchical_forwardmodel_wrap::step_state.
[part1d_forwardmodel_natural_hierarchical_init_f(int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_f_t *lp, void *user_arg, int results)]void* part1d_forwardmodel_natural_hierarchical_init_f (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t * random, rjmcmc_normal_rand_t * normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part1d_fm_hierarchical_likelihood_f_t * lp, void * user_arg, int results)
References part1d_hierarchical_forwardmodel_wrap::lp, part1d_forwardmodel_natural_hierarchical_init(), part1d_hierarchical_forwardmodel_wrap::step_state, user_arg, and part1d_hierarchical_forwardmodel_wrap::user_arg.
int part1d_forwardmodel_natural_hierarchical_step_f (void * state)
References part1d_forwardmodel_natural_hierarchical_step(), and part1d_hierarchical_forwardmodel_wrap::step_state.
[part2d_forwardmodel_f(int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_f_t *lp, void *user_arg, int results)]resultset2dfm_t* part2d_forwardmodel_f (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t * random, rjmcmc_normal_rand_t * normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part2d_fm_likelihood_f_t * lp, void * user_arg, int results)
References part2d_forwardmodel_wrap::lp, part2d_forwardmodel(), user_arg, and part2d_forwardmodel_wrap::user_arg.
[part2d_forwardmodel_hierarchical_f(int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part2d_fm_hierarchical_likelihood_f_t *lp, void *user_arg, int results)]resultset2dfm_t* part2d_forwardmodel_hierarchical_f (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t * random, rjmcmc_normal_rand_t * normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part2d_fm_hierarchical_likelihood_f_t * lp, void * user_arg, int results)
References part2d_forwardmodel_hierarchical_wrap::lp, part2d_forwardmodel_hierarchical(), user_arg, and part2d_forwardmodel_hierarchical_wrap::user_arg.
[single_forwardmodel_f(int burnin, int total, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nparameters, const forwardmodelparameter_t *parameters, single_fm_likelihood_t *lp, void **user_arg, int samples, double credible_interval, int results)]resultsetfm_t* single_forwardmodel_f (int burnin, int total, rjmcmc_uniform_rand_t * random, rjmcmc_normal_rand_t * normal, int nparameters, const forwardmodelparameter_t * parameters, single_fm_likelihood_t * lp, void ** user_arg, int samples, double credible_interval, int results)
References single_forwardmodel().
[single_forwardmodel_hierarchical_f(int burnin, int total, rjmcmc_uniform_rand_t *random, rjmcmc_normal_rand_t *normal, int nparameters, const forwardmodelparameter_t *parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchicalparameters, single_fm_likelihood_hierarchical_t *lp, void **user_arg, int samples, double credible_interval, int results)]resultsetfm_t* single_forwardmodel_hierarchical_f (int burnin, int total, rjmcmc_uniform_rand_t * random, rjmcmc_normal_rand_t * normal, int nparameters, const forwardmodelparameter_t * parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchicalparameters, single_fm_likelihood_hierarchical_t * lp, void ** user_arg, int samples, double credible_interval, int results)
References single_forwardmodel_hierarchical().