forwardmodel_single.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <math.h>
*
#include <float.h>
*
#include <rjmcmc/forwardmodel.h>
*
#include <rjmcmc/engine.h>
*
#include <rjmcmc/rjmcmc_util.h>
*
#include <rjmcmc/rjmcmc_debug.h>
*
#include <rjmcmc/rjmcmc_random.h>
*
Data Structures
struct fmsingle
Functions
resultsetfm_t * single_forwardmodel (int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t *parameters, single_fm_likelihood_t lp, void *user_arg, int samples, double credible_interval, int results)
Single Partition Forward Model.
resultsetfm_t * single_forwardmodel_hierarchical (int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t *parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchicalparameters, single_fm_likelihood_hierarchical_t lp, void *user_arg, int samples, double credible_interval, int results)
Single Partition Forward Model with Hierarchical Noise.
resultsetfm_t * MPI_single_forwardmodel (int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t *parameters, single_fm_likelihood_t lp, void *user_arg, int samples, double credible_interval, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
resultsetfm_t * MPI_single_forwardmodel_hierarchical (int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t *parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchicalparameters, single_fm_likelihood_hierarchical_t lp, void *user_arg, int samples, double credible_interval, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
Function Documentation
[MPI_single_forwardmodel(int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t *parameters, single_fm_likelihood_t lp, void *user_arg, int samples, double credible_interval, int results, int mpisize, int mpirank, int root, MPI_Comm comm)]resultsetfm_t* MPI_single_forwardmodel (int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t * parameters, single_fm_likelihood_t lp, void * user_arg, int samples, double credible_interval, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
References fmsingle::current, fmsingle::current_hierarchical, fmsingle::current_like, fmsingle::current_logdetce, fmsingle::hierarchicalparameters, fmsingle::lp, fmsingle::lp_hierarchical, MPI_resultsetfm_assemble_results(), fmsingle::nhierarchicalparameters, fmsingle::normal, fmsingle::nparameters, fmsingle::nsamples, fmsingle::out, fmsingle::parameters, fmsingle::process, fmsingle::proposed, fmsingle::proposed_hierarchical, fmsingle::proposed_like, fmsingle::proposed_logdetce, fmsingle::random, fmsingle::results, resultsetfm_create(), rjmcmc_create_array_1d(), rjmcmc_destroy_array_1d(), rjmcmc_engine_run(), rjmcmc_error(), samples, and fmsingle::user_arg.
Referenced by mpi_single_forwardmodel_f().
[MPI_single_forwardmodel_hierarchical(int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t *parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchicalparameters, single_fm_likelihood_hierarchical_t lp, void *user_arg, int samples, double credible_interval, int results, int mpisize, int mpirank, int root, MPI_Comm comm)]resultsetfm_t* MPI_single_forwardmodel_hierarchical (int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t * parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchicalparameters, single_fm_likelihood_hierarchical_t lp, void * user_arg, int samples, double credible_interval, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
References fmsingle::current, fmsingle::current_hierarchical, fmsingle::current_like, fmsingle::current_logdetce, fmsingle::hierarchicalparameters, fmsingle::lp, fmsingle::lp_hierarchical, MPI_resultsetfm_assemble_results(), fmsingle::nhierarchicalparameters, fmsingle::normal, fmsingle::nparameters, fmsingle::nsamples, fmsingle::out, fmsingle::parameters, fmsingle::process, fmsingle::proposed, fmsingle::proposed_hierarchical, fmsingle::random, fmsingle::results, resultsetfm_create(), rjmcmc_create_array_1d(), rjmcmc_destroy_array_1d(), rjmcmc_engine_run(), rjmcmc_error(), samples, and fmsingle::user_arg.
Referenced by mpi_single_forwardmodel_hierarchical_f().
[single_forwardmodel(int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t *parameters, single_fm_likelihood_t lp, void *user_arg, int samples, double credible_interval, int results)]resultsetfm_t* single_forwardmodel (int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t * parameters, single_fm_likelihood_t lp, void * user_arg, int samples, double credible_interval, int results)
Single Partition Forward Model.
A single partition 1D forward model is essentially attempting to solve for a number of parameters. A range of these parameters is supplied via the parameters parameter.
The user supplied callback function, lp, will be passed at each iteration a set of parameters in an array. The callback should calculate negative log likelihood of the model (note that multiplicative and additive constants can be left out as these will cancel) . For an uncorrelated gaussian, this simplifies to (and removing the additive constant):
 \log({\mathrm{likelihood}}) = \sum_{i = 1}^n \frac{\left(g\left(m\right)_i - d_i\right)^2}{2 \sigma_i^2} 
From the actual likelihood:
 \Pr(d|m) = \frac{1}{\prod_{i=1}^n \sqrt{2 \pi \cdot \sigma_i^2}} \exp{\left( \sum_{i = 1}^n \frac{-\left(g\left(m\right)_i - d_i\right)^2}{2\sigma_i^2}\right)} 
Where $g(m)_i$ is the data/model generated from the parameters passed to the function, $d_i$ is the data/model to compare, and . $\sigma_i$ is the variance of the noise or uncertainty in the data. If the variance is not known and set to unity, the simulation will tend to overfit the data (unless the variance is actually near 1). In this case it is recommended that the single_forwardmodel_hierarchical function be used instead as it will also perturb an estimate of $\sigma$. Note that we don't need to calculate the scaling constant for the gaussian probability in this case since it is cancelled out in the MCMC step. This is not the case for the hierarchical version single_forwardmodel_hierarchical.
Parameters
burnin The number of burn in iterations.
total The total number of iterations (must be greater than burnin).
random User supplied uniform random number generator.
normal User supplied normal random number generator.
nparameters The number of parameters in the forward model.
parameters The array of parameter information.
lp The hierarchical likelihood function.
user_arg A pointer to user data that will be supplied to the likelihood function.
samples Results such as median, mode, credible intervals are computed using a histogram of values, this parameter sets the number of bins for this histogram. A value of 100 suits most cases.
credible_interval The credible interval expressed as a percentage between 0 and 1.
results The results desired as a bitwise or'ing of resultsetfm_result_t values.
For an example of using this function, see the example 1d/single/fm/simpleimage/simpleimage.c
Examples:
1d/single/fm/simpleimage/simpleimage.c, and 1d/single/fm/spherefit/spherefit.c.
References fmsingle::current, fmsingle::current_hierarchical, fmsingle::current_like, fmsingle::current_logdetce, fmsingle::hierarchicalparameters, fmsingle::lp, fmsingle::lp_hierarchical, fmsingle::nhierarchicalparameters, fmsingle::normal, fmsingle::nparameters, fmsingle::nsamples, fmsingle::out, fmsingle::parameters, fmsingle::process, fmsingle::proposed, fmsingle::proposed_hierarchical, fmsingle::proposed_like, fmsingle::proposed_logdetce, fmsingle::random, fmsingle::results, resultsetfm_assemble_results(), resultsetfm_create(), rjmcmc_create_array_1d(), rjmcmc_destroy_array_1d(), rjmcmc_engine_run(), rjmcmc_error(), samples, and fmsingle::user_arg.
Referenced by single_forwardmodel_f().
[single_forwardmodel_hierarchical(int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t *parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchicalparameters, single_fm_likelihood_hierarchical_t lp, void *user_arg, int samples, double credible_interval, int results)]resultsetfm_t* single_forwardmodel_hierarchical (int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t * parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchicalparameters, single_fm_likelihood_hierarchical_t lp, void * user_arg, int nsamples, double credible_interval, int results)
Single Partition Forward Model with Hierarchical Noise.
This forward model adds a custom number of hierarchical parameters that affect the scaling constant of the likelihood and therefore the log(likelihood) that needs to be returned from the likelihood function.
The general gaussian probability is:
 \Pr() = \frac{1}{(2 \pi)^{n/2} |C_e|} \exp{-\frac{1}{2}(g(m) - d)^T C_e^{-1} (g(m) - d)} 
Where $ C_e $ is the covariance matrix that is generated from the hierarchical parameters. In the simplest case you would have 1 hierarchical parameter with the diagonal of the covariance matrix set to this value.
The callback function now needs to calculate the entire likelihood value but only when the hierarchical parameters are perturbed. To facilitate this and to allow some efficiency gains in not having to continuously evaluate the determinant of the covariance matrix, the callback function only needs to return the positive value of the exponential term above, ie $\frac{1}{2}(g(m) - d)^T C_e^{-1} (g(m) - d)$, and the determinant of the covariance when needed. This is indicated with the hierarchical parameter to the callback function. In psuedo code, the callback function should follow the following pattern:
loglikelihood = calculate_log_likelihood();
if (hierarchical == 1) {
     logdetce = calculate_log_detCe();
} 

return loglikelihood;
Parameters
burnin The number of burn in iterations.
total The total number of iterations (must be greater than burnin).
random User supplied uniform random number generator.
normal User supplied normal random number generator.
nparameters The number of parameters in the forward model.
parameters The array of parameter information.
nhierarchicalparameters The number of hierarchical parameters to sample
hierarchicalparameters
lp The hierarchical likelihood function. Note that this has a different signature than the single_forwardmodel function parameter of the same name.
user_arg A pointer to user data that will be supplied to the likelihood function.
nsamples The number of data points used in calculating the likelihood.
credible_interval The credible interval expressed as a percentage between 0 and 1.
results The results desired as a bitwise or'ing of resultsetfm_result_t values.
For an example of using this function, see the example 1d/single/fm/simpleimage/simpleimage.c
Examples:
1d/single/fm/simpleimage/simpleimage.c.
References fmsingle::current, fmsingle::current_hierarchical, fmsingle::current_like, fmsingle::current_logdetce, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _forwardmodelparameter::fstd_value, fmsingle::hierarchicalparameters, fmsingle::lp, fmsingle::lp_hierarchical, fmsingle::nhierarchicalparameters, fmsingle::normal, fmsingle::nparameters, fmsingle::nsamples, fmsingle::out, fmsingle::parameters, fmsingle::process, fmsingle::proposed, fmsingle::proposed_hierarchical, fmsingle::proposed_like, fmsingle::proposed_logdetce, fmsingle::random, fmsingle::results, resultsetfm_accept(), resultsetfm_assemble_results(), resultsetfm_create(), resultsetfm_propose(), resultsetfm_sample(), resultsetfm_sample_hierarchical(), resultsetfm_sample_misfit(), rjmcmc_create_array_1d(), rjmcmc_destroy_array_1d(), rjmcmc_engine_run(), rjmcmc_error(), rjmcmc_random_choose_double(), rjmcmc_random_choose_int(), samples, and fmsingle::user_arg.
Referenced by single_forwardmodel_hierarchical_f().