forwardmodel_part2d_hierarchical.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <math.h>
*
#include <float.h>
*
#include <rjmcmc/engine.h>
*
#include <rjmcmc/forwardmodel.h>
*
#include <rjmcmc/part2d_forwardmodel.h>
*
#include <rjmcmc/rjmcmc_util.h>
*
#include <rjmcmc/rjmcmc_debug.h>
*
Data Structures
struct part2dfm
struct _part2d_fm_likelihood_state
Enumerations
enum {
*
BIRTH = 0,
DEATH,
MOVE,
LOCALVALUE,
*
HIERARCHICALVALUE,
GLOBALVALUE,
NPROCESSES,
NPROCESSES_NOGLOBAL = GLOBALVALUE
 }
Functions
resultset2dfm_t * part2d_forwardmodel_hierarchical (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part2d_fm_hierarchical_likelihood_t lp, void *user_arg, int results)
A partitioned 2d forward model with hierarchical parameters.
resultset2dfm_t * MPI_part2d_forwardmodel_hierarchical (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part2d_fm_hierarchical_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
resultset2dfm_t * MPI_part2d_forwardmodel_hierarchical_restartable (const char *model_file_in_template, const char *model_file_out_template, int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part2d_fm_hierarchical_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
Enumeration Type Documentation
anonymous enum
Enumerator
BIRTH
DEATH
MOVE
LOCALVALUE
HIERARCHICALVALUE
GLOBALVALUE
NPROCESSES
NPROCESSES_NOGLOBAL
Function Documentation
[MPI_part2d_forwardmodel_hierarchical(int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part2d_fm_hierarchical_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)]resultset2dfm_t* MPI_part2d_forwardmodel_hierarchical (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part2d_fm_hierarchical_likelihood_t lp, void * user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
References part2dfm::bound, part2dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part2dfm::global_parameters, part2dfm::hierarchical_parameters, part2dfm::initpart, part2dfm::local_parameters, part2dfm::lp, part2dfm::maxpart, part2dfm::mf_gradients, part2dfm::mf_values, part2dfm::minpart, MPI_resultset2dfm_assemble_results(), part2dfm::nglobalparameters, part2dfm::nhierarchicalparameters, part2dfm::nlocalparameters, part2dfm::normal, NPROCESSES, part2dfm::nprocesses, NPROCESSES_NOGLOBAL, PART2D_FM_ZERO, part2d_forwardmodel_create(), part2d_forwardmodel_destroy(), part2dfm::proddelta_l, part2dfm::proposed, part2dfm::random, part2dfm::results, resultset2dfm_create(), resultset2dfm_fill_xcoord_vector(), resultset2dfm_fill_ycoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_3d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_3d(), rjmcmc_engine_run(), rjmcmc_error(), part2dfm::user_arg, part2dfm::x, bbox2d::xmax, bbox2d::xmin, part2dfm::xsamples, part2dfm::y, bbox2d::ymax, bbox2d::ymin, part2dfm::ysamples, and part2dfm::z.
Referenced by mpi_part2d_forwardmodel_hierarchical_f().
[MPI_part2d_forwardmodel_hierarchical_restartable(const char *model_file_in_template, const char *model_file_out_template, int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part2d_fm_hierarchical_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)]resultset2dfm_t* MPI_part2d_forwardmodel_hierarchical_restartable (const char * model_file_in_template, const char * model_file_out_template, int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part2d_fm_hierarchical_likelihood_t lp, void * user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
References part2dfm::accepted, BIRTH, part2dfm::birth_prob, part2dfm::bound, part2dfm::current, part2dfm::current_like, part2dfm::current_logdetce, DEATH, part2dfm::death_prob, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part2dfm::global_parameters, GLOBALVALUE, _part2d_fm_likelihood_state::gradients, part2dfm::hierarchical_parameters, part2dfm::hierarchical_prob, HIERARCHICALVALUE, part2dfm::initpart, part2dfm::local_parameters, LOCALVALUE, part2dfm::lp, part2dfm::maxpart, part2dfm::mf_gradients, part2dfm::mf_values, part2dfm::minpart, _part2d_fm_likelihood_state::model, MOVE, part2dfm::move_prob, MPI_resultset2dfm_assemble_results(), part2dfm::nglobalparameters, part2dfm::nhierarchicalparameters, part2dfm::nlocalparameters, _part2d_fm_likelihood_state::nlocalparameters, part2dfm::normal, NPROCESSES, part2dfm::nprocesses, NPROCESSES_NOGLOBAL, part2dfm::out, PART2D_FM_ZERO, part2d_forwardmodel_clone(), part2d_forwardmodel_create(), part2d_forwardmodel_destroy(), part2d_forwardmodel_evaluate_local_parameters(), part2d_forwardmodel_global_parameters(), part2d_forwardmodel_hierarchical_parameters(), part2d_forwardmodel_initialize(), part2d_forwardmodel_load(), part2d_forwardmodel_partition_centre(), part2d_forwardmodel_partitions(), part2d_forwardmodel_propose_birth(), part2d_forwardmodel_propose_death(), part2d_forwardmodel_propose_global_value(), part2d_forwardmodel_propose_hierarchical(), part2d_forwardmodel_propose_local_value(), part2d_forwardmodel_propose_move(), part2d_forwardmodel_save(), part2dfm::pbound, part2dfm::process, part2dfm::proddelta_l, part2dfm::proposed, part2dfm::proposed_like, part2dfm::proposed_logdetce, part2dfm::random, part2dfm::results, resultset2dfm_accept(), resultset2dfm_create(), resultset2dfm_fill_xcoord_vector(), resultset2dfm_fill_ycoord_vector(), resultset2dfm_propose(), resultset2dfm_sample_centre(), resultset2dfm_sample_global_parameter(), resultset2dfm_sample_hierarchical_parameter(), resultset2dfm_sample_local_parameter(), resultset2dfm_sample_misfit(), resultset2dfm_sample_npartitions(), rjmcmc_create_array_1d(), rjmcmc_create_array_3d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_3d(), rjmcmc_engine_run(), rjmcmc_error(), rjmcmc_random_choose_int(), part2dfm::user_arg, part2dfm::value_prob, _part2d_fm_likelihood_state::values, part2dfm::x, bbox2d::xmax, bbox2d::xmin, part2dfm::xsamples, part2dfm::y, bbox2d::ymax, bbox2d::ymin, part2dfm::ysamples, and part2dfm::z.
Referenced by mpi_part2d_forwardmodel_hierarchical_restartable_f().
[part2d_forwardmodel_hierarchical(int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part2d_fm_hierarchical_likelihood_t lp, void *user_arg, int results)]resultset2dfm_t* part2d_forwardmodel_hierarchical (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part2d_fm_hierarchical_likelihood_t lp, void * user_arg, int results)
A partitioned 2d forward model with hierarchical parameters.
This method is the same as the part2d_forwardmodel method except it also solves for hierarchical parameters that are used to construct the covariance matrix.
Parameters
burnin The number of burn in iterations.
total The total number of iterations (must be greater than burnin).
thin The number of samples to skip when averaging (0 means none).
minpart The minimum number of partitions, this should be 2.
maxpart The maximum number of partitions.
initpart The initial number of partitions.
minx The lower bound value of the x coordinate
maxx The upper bound value of the x coordinate.
miny The lower bound value of the y coordinate
maxy The upper bound value of the y coordinate.
xsamples When producing mean curves etc, the number of discretization steps used for constructing the curve. A value of 100 suits most cases.
ysamples When producing mean curves etc, the number of discretization steps used for constructing the curve. A value of 100 suits most cases.
zsamples Results such as median, mode, credible intervals are computed using a histogram of values, this parameter sets the number of bins for this histogram. A value of 100 suits most cases.
credible_interval The credible interval expressed as a percentage between 0 and 1.
pdx The standard deviation of the perturb partition boundary (move) step in the x direction.
pdy The standard deviation of the perturb partition boundary (move) step in the y direction.
random User supplied uniform random number generator.
normal User supplied normal random number generator.
nglobalparameters The number of global parameters.
global_parameters An array of global parameters (their min, max and perturbation standard deviations).
nlocalparameters The number of local parameters.
local_parameters An array of local parameters (their min, max and perturbation standard deviations).
nhierarchicalparameters The number of hierarchical parameters.
hierarchical_parameters An array of hierarchical parameters (their min, max and perturbation standard deviations).
lp The likelihood function.
user_arg A pointer to user data that will be supplied to the likelihood function.
results The results desired as a bitwise or'ing of resultset1dfm_result_t values.
For an example of using this function, see the example 2d/partitioned/fm/regression/regression.h
References part2dfm::bound, part2dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part2dfm::global_parameters, part2dfm::hierarchical_parameters, part2dfm::initpart, part2dfm::local_parameters, part2dfm::lp, part2dfm::maxpart, part2dfm::mf_gradients, part2dfm::mf_values, part2dfm::minpart, part2dfm::nglobalparameters, part2dfm::nhierarchicalparameters, part2dfm::nlocalparameters, part2dfm::normal, NPROCESSES, part2dfm::nprocesses, NPROCESSES_NOGLOBAL, PART2D_FM_ZERO, part2d_forwardmodel_create(), part2d_forwardmodel_destroy(), part2dfm::proddelta_l, part2dfm::proposed, part2dfm::random, part2dfm::results, resultset2dfm_assemble_results(), resultset2dfm_create(), resultset2dfm_fill_xcoord_vector(), resultset2dfm_fill_ycoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_3d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_3d(), rjmcmc_engine_run(), rjmcmc_error(), part2dfm::user_arg, part2dfm::x, bbox2d::xmax, bbox2d::xmin, part2dfm::xsamples, part2dfm::y, bbox2d::ymax, bbox2d::ymin, part2dfm::ysamples, and part2dfm::z.
Referenced by part2d_forwardmodel_hierarchical_f().