forwardmodel_mpi.h File Reference
#include <rjmcmc/rjmcmc_config.h>
*
#include <rjmcmc/forwardmodel.h>
*
Functions
resultsetfm_t * MPI_single_forwardmodel (int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t *parameters, single_fm_likelihood_t lp, void *user_arg, int samples, double credible_interval, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
resultsetfm_t * MPI_single_forwardmodel_hierarchical (int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t *parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchicalparameters, single_fm_likelihood_hierarchical_t lp, void *user_arg, int samples, double credible_interval, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
resultset1dfm_t * MPI_part1d_forwardmodel (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
resultset1dfm_t * MPI_part1d_forwardmodel_natural (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
resultset1dfm_t * MPI_part1d_forwardmodel_hierarchical (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
resultset1dfm_t * MPI_part1d_forwardmodel_natural_hierarchical (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
resultset2dfm_t * MPI_part2d_forwardmodel (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
resultset2dfm_t * MPI_part2d_forwardmodel_checkpoint (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_t lp, void *user_arg, int results, int checkpoint_interval, const char *checkpoint_prefix, int mpisize, int mpirank, int root, MPI_Comm comm)
resultset2dfm_t * MPI_part2d_forwardmodel_checkpoint_restart (rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, part2d_fm_likelihood_t lp, void *user_arg, int checkpoint, int checkpoint_interval, const char *checkpoint_prefix, int mpisize, int mpirank, int root, MPI_Comm comm, int *requested_results, int *burnin, int *total, int *thin, int *xsamples, int *ysamples, int *zsamples, int *nprocesses, int *maxpartitions, double *xmin, double *xmax, double *ymin, double *ymax, double *credibleinterval, int *nhierarchical, int *nglobal, int *nlocal, forwardmodelparameter_t **local_parameters, forwardmodelparameter_t **global_parameters)
resultset2dfm_t * MPI_part2d_forwardmodel_hierarchical (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part2d_fm_hierarchical_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
resultset2dfm_t * MPI_part2d_forwardmodel_hierarchical_restartable (const char *model_file_in_template, const char *nodel_file_out_template, int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part2d_fm_hierarchical_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
Function Documentation
[MPI_part1d_forwardmodel(int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)]resultset1dfm_t* MPI_part1d_forwardmodel (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part1d_fm_likelihood_t lp, void * user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
References _rjmcmc_engine_cb::accept, _rjmcmc_engine_cb::arg, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, MPI_resultset1dfm_assemble_results(), part1dfm::nglobalparameters, part1dfm::nlocalparameters, part1dfm::normal, part1dfm::nprocesses, PART1D_FM_ZERO, part1d_forwardmodel_create(), part1d_forwardmodel_destroy(), _rjmcmc_engine_cb::perturb_process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::random, part1dfm::results, resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
Referenced by mpi_part1d_forwardmodel_f().
[MPI_part1d_forwardmodel_hierarchical(int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)]resultset1dfm_t* MPI_part1d_forwardmodel_hierarchical (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void * user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
References _rjmcmc_engine_cb::accept, _rjmcmc_engine_cb::arg, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, part1dfm::hierarchical_parameters, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, MPI_resultset1dfm_assemble_results(), part1dfm::nglobalparameters, part1dfm::nhierarchicalparameters, part1dfm::nlocalparameters, part1dfm::normal, NPROCESSES, part1dfm::nprocesses, NPROCESSES_NOGLOBAL, PART1D_FM_ZERO, part1d_forwardmodel_create(), part1d_forwardmodel_destroy(), _rjmcmc_engine_cb::perturb_process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::random, part1dfm::results, resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
Referenced by mpi_part1d_forwardmodel_hierarchical_f().
[MPI_part1d_forwardmodel_natural(int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)]resultset1dfm_t* MPI_part1d_forwardmodel_natural (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part1d_fm_likelihood_t lp, void * user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
References _rjmcmc_engine_cb::accept, part1dfm::accepted, _rjmcmc_engine_cb::arg, part1dfm::birth_prob, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, part1dfm::current_like, part1dfm::death_prob, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, _part1d_fm_likelihood_state::gradients, part1dfm::index, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, _part1d_fm_likelihood_state::model, part1dfm::move_prob, MPI_resultset1dfm_assemble_results(), part1dfm::nglobalparameters, part1dfm::nlocalparameters, _part1d_fm_likelihood_state::nlocalparameters, part1dfm::normal, part1dfm::nprocesses, part1dfm::out, PART1D_FM_NATURAL, part1d_forwardmodel_clone(), part1d_forwardmodel_create(), part1d_forwardmodel_destroy(), part1d_forwardmodel_evaluate_local_parameters(), part1d_forwardmodel_global_parameters(), part1d_forwardmodel_initialize(), part1d_forwardmodel_partition_fill_list(), part1d_forwardmodel_partition_position(), part1d_forwardmodel_partitions(), part1d_forwardmodel_propose_birth(), part1d_forwardmodel_propose_death(), part1d_forwardmodel_propose_global_value(), part1d_forwardmodel_propose_local_value(), part1d_forwardmodel_propose_move(), _rjmcmc_engine_cb::perturb_process, part1dfm::process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::proposed_like, part1dfm::random, part1dfm::results, resultset1dfm_accept(), resultset1dfm_accept_local_value(), resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), resultset1dfm_propose(), resultset1dfm_propose_local_value(), resultset1dfm_sample_global_parameter(), resultset1dfm_sample_local_parameter(), resultset1dfm_sample_misfit(), resultset1dfm_sample_npartitions(), resultset1dfm_sample_partition_x(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), rjmcmc_random_choose_int(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::value_prob, _part1d_fm_likelihood_state::values, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
Referenced by mpi_part1d_forwardmodel_natural_f().
[MPI_part1d_forwardmodel_natural_hierarchical(int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)]resultset1dfm_t* MPI_part1d_forwardmodel_natural_hierarchical (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void * user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
References _rjmcmc_engine_cb::accept, part1dfm::accepted, _rjmcmc_engine_cb::arg, BIRTH, part1dfm::birth_prob, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, part1dfm::current_like, part1dfm::current_logdetce, DEATH, part1dfm::death_prob, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, GLOBALVALUE, _part1d_fm_hierarchical_likelihood_state::gradients, part1dfm::hierarchical_parameters, part1dfm::hierarchical_prob, HIERARCHICALVALUE, part1dfm::index, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, LOCALVALUE, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, _part1d_fm_hierarchical_likelihood_state::model, MOVE, part1dfm::move_prob, MPI_resultset1dfm_assemble_results(), part1dfm::nglobalparameters, part1dfm::nhierarchicalparameters, part1dfm::nlocalparameters, _part1d_fm_hierarchical_likelihood_state::nlocalparameters, part1dfm::normal, NPROCESSES, part1dfm::nprocesses, NPROCESSES_NOGLOBAL, part1dfm::out, PART1D_FM_NATURAL, part1d_forwardmodel_clone(), part1d_forwardmodel_create(), part1d_forwardmodel_destroy(), part1d_forwardmodel_evaluate_local_parameters(), part1d_forwardmodel_global_parameters(), part1d_forwardmodel_hierarchical_parameters(), part1d_forwardmodel_initialize(), part1d_forwardmodel_partition_fill_list(), part1d_forwardmodel_partition_position(), part1d_forwardmodel_partitions(), part1d_forwardmodel_propose_birth(), part1d_forwardmodel_propose_death(), part1d_forwardmodel_propose_global_value(), part1d_forwardmodel_propose_hierarchical(), part1d_forwardmodel_propose_local_value(), part1d_forwardmodel_propose_move(), _rjmcmc_engine_cb::perturb_process, part1dfm::process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::proposed_like, part1dfm::proposed_logdetce, part1dfm::random, part1dfm::results, resultset1dfm_accept(), resultset1dfm_accept_local_value(), resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), resultset1dfm_propose(), resultset1dfm_sample_global_parameter(), resultset1dfm_sample_hierarchical(), resultset1dfm_sample_local_parameter(), resultset1dfm_sample_misfit(), resultset1dfm_sample_npartitions(), resultset1dfm_sample_partition_x(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), rjmcmc_random_choose_int(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::value_prob, _part1d_fm_hierarchical_likelihood_state::values, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
Referenced by mpi_part1d_forwardmodel_natural_hierarchical_f().
[MPI_part2d_forwardmodel(int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)]resultset2dfm_t* MPI_part2d_forwardmodel (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part2d_fm_likelihood_t lp, void * user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
References MPI_resultset2dfm_assemble_results(), part2dfm::mpirank, NPROCESSES, part2dfm::nprocesses, NPROCESSES_NOGLOBAL, part2dfm::results, rjmcmc_engine_run(), and rjmcmc_error().
Referenced by mpi_part2d_forwardmodel_f().
[MPI_part2d_forwardmodel_checkpoint(int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_t lp, void *user_arg, int results, int checkpoint_interval, const char *checkpoint_prefix, int mpisize, int mpirank, int root, MPI_Comm comm)]resultset2dfm_t* MPI_part2d_forwardmodel_checkpoint (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part2d_fm_likelihood_t lp, void * user_arg, int results, int checkpoint_interval, const char * checkpoint_prefix, int mpisize, int mpirank, int root, MPI_Comm comm)
References part2dfm::checkpoint_interval, part2dfm::checkpoint_prefix, MPI_resultset2dfm_assemble_results(), part2dfm::mpirank, NPROCESSES, part2dfm::nprocesses, NPROCESSES_NOGLOBAL, part2dfm::results, rjmcmc_engine_run(), and rjmcmc_error().
[MPI_part2d_forwardmodel_checkpoint_restart(rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, part2d_fm_likelihood_t lp, void *user_arg, int checkpoint, int checkpoint_interval, const char *checkpoint_prefix, int mpisize, int mpirank, int root, MPI_Comm comm, int *requested_results, int *burnin, int *total, int *thin, int *xsamples, int *ysamples, int *zsamples, int *nprocesses, int *maxpartitions, double *xmin, double *xmax, double *ymin, double *ymax, double *credibleinterval, int *nhierarchical, int *nglobal, int *nlocal, forwardmodelparameter_t **local_parameters, forwardmodelparameter_t **global_parameters)]resultset2dfm_t* MPI_part2d_forwardmodel_checkpoint_restart (rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, part2d_fm_likelihood_t lp, void * user_arg, int checkpoint, int checkpoint_interval, const char * checkpoint_prefix, int mpisize, int mpirank, int root, MPI_Comm comm, int * requested_results, int * burnin, int * total, int * thin, int * xsamples, int * ysamples, int * zsamples, int * nprocesses, int * maxpartitions, double * xmin, double * xmax, double * ymin, double * ymax, double * credibleinterval, int * nhierarchical, int * nglobal, int * nlocal, forwardmodelparameter_t ** local_parameters, forwardmodelparameter_t ** global_parameters)
References part2dfm::accepted, BIRTH, part2dfm::birth_prob, part2dfm::bound, part2dfm::checkpoint_interval, part2dfm::checkpoint_prefix, credible_interval, part2dfm::current, part2dfm::current_like, DEATH, part2dfm::death_prob, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part2dfm::global_parameters, part2dfm::global_value_prob, GLOBALVALUE, _part2d_fm_likelihood_state::gradients, part2dfm::initpart, part2dfm::local_parameters, LOCALVALUE, part2dfm::lp, part2dfm::maxpart, part2dfm::mf_global_parameters, part2dfm::mf_gradients, part2dfm::mf_values, part2dfm::minpart, _part2d_fm_likelihood_state::model, MODEL_CHECKPOINT_TEMPLATE, MOVE, part2dfm::move_prob, MPI_resultset2dfm_assemble_results(), part2dfm::mpirank, part2dfm::nglobalparameters, part2dfm::nlocalparameters, _part2d_fm_likelihood_state::nlocalparameters, part2dfm::normal, part2dfm::nprocesses, part2dfm::out, PART2D_FM_ZERO, part2d_forwardmodel_clone(), part2d_forwardmodel_create(), part2d_forwardmodel_destroy(), part2d_forwardmodel_evaluate_local_parameters(), part2d_forwardmodel_global_parameters(), part2d_forwardmodel_initialize(), part2d_forwardmodel_load(), part2d_forwardmodel_min_partitions(), part2d_forwardmodel_partition_centre(), part2d_forwardmodel_partitions(), part2d_forwardmodel_pdx(), part2d_forwardmodel_pdy(), part2d_forwardmodel_propose_birth(), part2d_forwardmodel_propose_death(), part2d_forwardmodel_propose_global_value(), part2d_forwardmodel_propose_local_value(), part2d_forwardmodel_propose_move(), part2d_forwardmodel_save(), part2dfm::pbound, part2dfm::process, part2dfm::proddelta_l, part2dfm::proposed, part2dfm::proposed_like, part2dfm::random, requested_results, part2dfm::results, resultset2dfm_accept(), RESULTSET2DFM_BINARY, resultset2dfm_create(), resultset2dfm_fill_xcoord_vector(), resultset2dfm_fill_ycoord_vector(), resultset2dfm_get_misfit(), resultset2dfm_load(), resultset2dfm_propose(), resultset2dfm_sample_centre(), resultset2dfm_sample_global_parameter(), resultset2dfm_sample_local_parameter(), resultset2dfm_sample_misfit(), resultset2dfm_sample_npartitions(), resultset2dfm_save(), RESULTSET_CHECKPOINT_TEMPLATE, rjmcmc_create_array_1d(), rjmcmc_create_array_3d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_3d(), rjmcmc_engine_restart(), rjmcmc_error(), RJMCMC_NULLCHECKINT, rjmcmc_random_choose_int(), total, part2dfm::user_arg, part2dfm::value_prob, _part2d_fm_likelihood_state::values, part2dfm::x, bbox2d::xmax, bbox2d::xmin, part2dfm::xsamples, part2dfm::y, bbox2d::ymax, bbox2d::ymin, part2dfm::ysamples, and part2dfm::z.
[MPI_part2d_forwardmodel_hierarchical(int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part2d_fm_hierarchical_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)]resultset2dfm_t* MPI_part2d_forwardmodel_hierarchical (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part2d_fm_hierarchical_likelihood_t lp, void * user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
References part2dfm::bound, part2dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part2dfm::global_parameters, part2dfm::hierarchical_parameters, part2dfm::initpart, part2dfm::local_parameters, part2dfm::lp, part2dfm::maxpart, part2dfm::mf_gradients, part2dfm::mf_values, part2dfm::minpart, MPI_resultset2dfm_assemble_results(), part2dfm::nglobalparameters, part2dfm::nhierarchicalparameters, part2dfm::nlocalparameters, part2dfm::normal, NPROCESSES, part2dfm::nprocesses, NPROCESSES_NOGLOBAL, PART2D_FM_ZERO, part2d_forwardmodel_create(), part2d_forwardmodel_destroy(), part2dfm::proddelta_l, part2dfm::proposed, part2dfm::random, part2dfm::results, resultset2dfm_create(), resultset2dfm_fill_xcoord_vector(), resultset2dfm_fill_ycoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_3d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_3d(), rjmcmc_engine_run(), rjmcmc_error(), part2dfm::user_arg, part2dfm::x, bbox2d::xmax, bbox2d::xmin, part2dfm::xsamples, part2dfm::y, bbox2d::ymax, bbox2d::ymin, part2dfm::ysamples, and part2dfm::z.
Referenced by mpi_part2d_forwardmodel_hierarchical_f().
[MPI_part2d_forwardmodel_hierarchical_restartable(const char *model_file_in_template, const char *nodel_file_out_template, int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part2d_fm_hierarchical_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)]resultset2dfm_t* MPI_part2d_forwardmodel_hierarchical_restartable (const char * model_file_in_template, const char * nodel_file_out_template, int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part2d_fm_hierarchical_likelihood_t lp, void * user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
References part2dfm::accepted, BIRTH, part2dfm::birth_prob, part2dfm::bound, part2dfm::current, part2dfm::current_like, part2dfm::current_logdetce, DEATH, part2dfm::death_prob, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part2dfm::global_parameters, GLOBALVALUE, _part2d_fm_likelihood_state::gradients, part2dfm::hierarchical_parameters, part2dfm::hierarchical_prob, HIERARCHICALVALUE, part2dfm::initpart, part2dfm::local_parameters, LOCALVALUE, part2dfm::lp, part2dfm::maxpart, part2dfm::mf_gradients, part2dfm::mf_values, part2dfm::minpart, _part2d_fm_likelihood_state::model, MOVE, part2dfm::move_prob, MPI_resultset2dfm_assemble_results(), part2dfm::nglobalparameters, part2dfm::nhierarchicalparameters, part2dfm::nlocalparameters, _part2d_fm_likelihood_state::nlocalparameters, part2dfm::normal, NPROCESSES, part2dfm::nprocesses, NPROCESSES_NOGLOBAL, part2dfm::out, PART2D_FM_ZERO, part2d_forwardmodel_clone(), part2d_forwardmodel_create(), part2d_forwardmodel_destroy(), part2d_forwardmodel_evaluate_local_parameters(), part2d_forwardmodel_global_parameters(), part2d_forwardmodel_hierarchical_parameters(), part2d_forwardmodel_initialize(), part2d_forwardmodel_load(), part2d_forwardmodel_partition_centre(), part2d_forwardmodel_partitions(), part2d_forwardmodel_propose_birth(), part2d_forwardmodel_propose_death(), part2d_forwardmodel_propose_global_value(), part2d_forwardmodel_propose_hierarchical(), part2d_forwardmodel_propose_local_value(), part2d_forwardmodel_propose_move(), part2d_forwardmodel_save(), part2dfm::pbound, part2dfm::process, part2dfm::proddelta_l, part2dfm::proposed, part2dfm::proposed_like, part2dfm::proposed_logdetce, part2dfm::random, part2dfm::results, resultset2dfm_accept(), resultset2dfm_create(), resultset2dfm_fill_xcoord_vector(), resultset2dfm_fill_ycoord_vector(), resultset2dfm_propose(), resultset2dfm_sample_centre(), resultset2dfm_sample_global_parameter(), resultset2dfm_sample_hierarchical_parameter(), resultset2dfm_sample_local_parameter(), resultset2dfm_sample_misfit(), resultset2dfm_sample_npartitions(), rjmcmc_create_array_1d(), rjmcmc_create_array_3d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_3d(), rjmcmc_engine_run(), rjmcmc_error(), rjmcmc_random_choose_int(), part2dfm::user_arg, part2dfm::value_prob, _part2d_fm_likelihood_state::values, part2dfm::x, bbox2d::xmax, bbox2d::xmin, part2dfm::xsamples, part2dfm::y, bbox2d::ymax, bbox2d::ymin, part2dfm::ysamples, and part2dfm::z.
Referenced by mpi_part2d_forwardmodel_hierarchical_restartable_f().
[MPI_single_forwardmodel(int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t *parameters, single_fm_likelihood_t lp, void *user_arg, int samples, double credible_interval, int results, int mpisize, int mpirank, int root, MPI_Comm comm)]resultsetfm_t* MPI_single_forwardmodel (int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t * parameters, single_fm_likelihood_t lp, void * user_arg, int samples, double credible_interval, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
References fmsingle::current, fmsingle::current_hierarchical, fmsingle::current_like, fmsingle::current_logdetce, fmsingle::hierarchicalparameters, fmsingle::lp, fmsingle::lp_hierarchical, MPI_resultsetfm_assemble_results(), fmsingle::nhierarchicalparameters, fmsingle::normal, fmsingle::nparameters, fmsingle::nsamples, fmsingle::out, fmsingle::parameters, fmsingle::process, fmsingle::proposed, fmsingle::proposed_hierarchical, fmsingle::proposed_like, fmsingle::proposed_logdetce, fmsingle::random, fmsingle::results, resultsetfm_create(), rjmcmc_create_array_1d(), rjmcmc_destroy_array_1d(), rjmcmc_engine_run(), rjmcmc_error(), samples, and fmsingle::user_arg.
Referenced by mpi_single_forwardmodel_f().
[MPI_single_forwardmodel_hierarchical(int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t *parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchicalparameters, single_fm_likelihood_hierarchical_t lp, void *user_arg, int samples, double credible_interval, int results, int mpisize, int mpirank, int root, MPI_Comm comm)]resultsetfm_t* MPI_single_forwardmodel_hierarchical (int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t * parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchicalparameters, single_fm_likelihood_hierarchical_t lp, void * user_arg, int samples, double credible_interval, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
References fmsingle::current, fmsingle::current_hierarchical, fmsingle::current_like, fmsingle::current_logdetce, fmsingle::hierarchicalparameters, fmsingle::lp, fmsingle::lp_hierarchical, MPI_resultsetfm_assemble_results(), fmsingle::nhierarchicalparameters, fmsingle::normal, fmsingle::nparameters, fmsingle::nsamples, fmsingle::out, fmsingle::parameters, fmsingle::process, fmsingle::proposed, fmsingle::proposed_hierarchical, fmsingle::random, fmsingle::results, resultsetfm_create(), rjmcmc_create_array_1d(), rjmcmc_destroy_array_1d(), rjmcmc_engine_run(), rjmcmc_error(), samples, and fmsingle::user_arg.
Referenced by mpi_single_forwardmodel_hierarchical_f().