forwardmodel_part1d.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <math.h>
*
#include <float.h>
*
#include <rjmcmc/engine.h>
*
#include <rjmcmc/forwardmodel.h>
*
#include <rjmcmc/forwardmodel_mpi.h>
*
#include <rjmcmc/part1d_forwardmodel.h>
*
#include <rjmcmc/rjmcmc_util.h>
*
#include <rjmcmc/rjmcmc_debug.h>
*
Data Structures
struct part1dfm
struct _part1d_fm_likelihood_state
Functions
resultset1dfm_t * part1d_forwardmodel (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results)
A partitioned 1d forward model.
resultset1dfm_t * part1d_forwardmodel_natural (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results)
Natural partitioned forward model.
void * part1d_forwardmodel_natural_init (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results)
int part1d_forwardmodel_natural_step (void *_s)
resultset1dfm_t * part1d_forwardmodel_natural_finish (void *_s)
resultset1dfm_t * part1d_forwardmodel_zero_cubic (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results)
Cubic partitioned 1d forward model.
resultset1dfm_t * MPI_part1d_forwardmodel (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
resultset1dfm_t * MPI_part1d_forwardmodel_natural (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
Function Documentation
[MPI_part1d_forwardmodel(int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)]resultset1dfm_t* MPI_part1d_forwardmodel (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part1d_fm_likelihood_t lp, void * user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
References _rjmcmc_engine_cb::accept, _rjmcmc_engine_cb::arg, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, MPI_resultset1dfm_assemble_results(), part1dfm::nglobalparameters, part1dfm::nlocalparameters, part1dfm::normal, part1dfm::nprocesses, PART1D_FM_ZERO, part1d_forwardmodel_create(), part1d_forwardmodel_destroy(), _rjmcmc_engine_cb::perturb_process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::random, part1dfm::results, resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
Referenced by mpi_part1d_forwardmodel_f().
[MPI_part1d_forwardmodel_natural(int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)]resultset1dfm_t* MPI_part1d_forwardmodel_natural (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part1d_fm_likelihood_t lp, void * user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
References _rjmcmc_engine_cb::accept, part1dfm::accepted, _rjmcmc_engine_cb::arg, part1dfm::birth_prob, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, part1dfm::current_like, part1dfm::death_prob, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, _part1d_fm_likelihood_state::gradients, part1dfm::index, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, _part1d_fm_likelihood_state::model, part1dfm::move_prob, MPI_resultset1dfm_assemble_results(), part1dfm::nglobalparameters, part1dfm::nlocalparameters, _part1d_fm_likelihood_state::nlocalparameters, part1dfm::normal, part1dfm::nprocesses, part1dfm::out, PART1D_FM_NATURAL, part1d_forwardmodel_clone(), part1d_forwardmodel_create(), part1d_forwardmodel_destroy(), part1d_forwardmodel_evaluate_local_parameters(), part1d_forwardmodel_global_parameters(), part1d_forwardmodel_initialize(), part1d_forwardmodel_partition_fill_list(), part1d_forwardmodel_partition_position(), part1d_forwardmodel_partitions(), part1d_forwardmodel_propose_birth(), part1d_forwardmodel_propose_death(), part1d_forwardmodel_propose_global_value(), part1d_forwardmodel_propose_local_value(), part1d_forwardmodel_propose_move(), _rjmcmc_engine_cb::perturb_process, part1dfm::process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::proposed_like, part1dfm::random, part1dfm::results, resultset1dfm_accept(), resultset1dfm_accept_local_value(), resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), resultset1dfm_propose(), resultset1dfm_propose_local_value(), resultset1dfm_sample_global_parameter(), resultset1dfm_sample_local_parameter(), resultset1dfm_sample_misfit(), resultset1dfm_sample_npartitions(), resultset1dfm_sample_partition_x(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), rjmcmc_random_choose_int(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::value_prob, _part1d_fm_likelihood_state::values, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
Referenced by mpi_part1d_forwardmodel_natural_f().
[part1d_forwardmodel(int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results)]resultset1dfm_t* part1d_forwardmodel (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part1d_fm_likelihood_t lp, void * user_arg, int results)
A partitioned 1d forward model.
This method performs a transdimensional mcmc forward model with zero order fitting within each partition. For a detailed description of this method, see [bodinThesis].
The return value calculated should be the negative log likelihood as in the single_forwardmodel method which is essentially the weighted sum of square errors.
The callback function supplied to the lp parameter is where the forward model is implemented. This function must match the signature of the part1d_fm_likelihood_t type. The parameters passed to the this callback give you opaque access to the proposed model for which the log likelihood needs to be computed.
Parameters
burnin The number of burn in iterations.
total The total number of iterations (must be greater than burnin).
minpart The minimum number of partitions, this should be 2.
maxpart The maximum number of partitions.
minx The lower bound value of the x coordinate
maxx The upper bound value of the x coordinate.
xsamples When producing mean curves etc, the number of discretization steps used for constructing the curve. A value of 100 suits most cases.
ysamples Results such as median, mode, credible intervals are computed using a histogram of values, this parameter sets the number of bins for this histogram. A value of 100 suits most cases.
credible_interval The credible interval expressed as a percentage between 0 and 1.
pd The standard deviation of the perturb partition boundary (move) step.
random User supplied uniform random number generator.
normal User supplied normal random number generator.
nglobalparameters The number of global parameters.
global_parameters An array of global parameters (their min, max and perturbation standard deviations).
nlocalparameters The number of local parameters.
local_parameters An array of local parameters (their min, max and perturbation standard deviations).
lp The hierarchical likelihood function.
user_arg A pointer to user data that will be supplied to the likelihood function.
results The results desired as a bitwise or'ing of resultset1dfm_result_t values.
For an example of using this function, see the example 1d/single/fm/partitioned/functionfit/functionfit.c
Examples:
1d/partitioned/fm/functionfit/functionfit.c, and 1d/partitioned/fm/regression/regression.c.
References _rjmcmc_engine_cb::accept, _rjmcmc_engine_cb::arg, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, part1dfm::nglobalparameters, part1dfm::nlocalparameters, part1dfm::normal, part1dfm::nprocesses, PART1D_FM_ZERO, part1d_forwardmodel_create(), part1d_forwardmodel_destroy(), _rjmcmc_engine_cb::perturb_process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::random, part1dfm::results, resultset1dfm_assemble_results(), resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
Referenced by part1d_forwardmodel_f().
[part1d_forwardmodel_natural(int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results)]resultset1dfm_t* part1d_forwardmodel_natural (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part1d_fm_likelihood_t lp, void * user_arg, int results)
Natural partitioned forward model.
This method is similar to the part1d_forwardmodel method except that instead of fitting zero order values in each partition, a continuous function is constructed using joined line segments between partition boundaries. For an example application of this method see [hopcroft2007A].
Parameters
burnin The number of burn in iterations.
total The total number of iterations (must be greater than burnin).
minpart The minimum number of partitions, this should be 2.
maxpart The maximum number of partitions.
minx The lower bound value of the x coordinate
maxx The upper bound value of the x coordinate.
xsamples When producing mean curves etc, the number of discretization steps used for constructing the curve. A value of 100 suits most cases.
ysamples Results such as median, mode, credible intervals are computed using a histogram of values, this parameter sets the number of bins for this histogram. A value of 100 suits most cases.
credible_interval The credible interval expressed as a percentage between 0 and 1.
pd The standard deviation of the perturb partition boundary (move) step.
random User supplied uniform random number generator.
normal User supplied normal random number generator.
nglobalparameters The number of global parameters.
global_parameters An array of global parameters (their min, max and perturbation standard deviations).
nlocalparameters The number of local parameters.
local_parameters An array of local parameters (their min, max and perturbation standard deviations).
lp The hierarchical likelihood function.
user_arg A pointer to user data that will be supplied to the likelihood function.
results The results desired as a bitwise or'ing of resultset1dfm_result_t values.
References _rjmcmc_engine_cb::accept, _rjmcmc_engine_cb::arg, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, part1dfm::nglobalparameters, part1dfm::nlocalparameters, part1dfm::normal, part1dfm::nprocesses, PART1D_FM_NATURAL, part1d_forwardmodel_create(), part1d_forwardmodel_destroy(), _rjmcmc_engine_cb::perturb_process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::random, part1dfm::results, resultset1dfm_assemble_results(), resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
Referenced by part1d_forwardmodel_natural_f().
resultset1dfm_t* part1d_forwardmodel_natural_finish (void * _s)
References part1dfm::current, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::nlocalparameters, part1d_forwardmodel_destroy(), part1dfm::proposed, part1dfm::results, resultset1dfm_assemble_results(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), part1dfm::x, and part1dfm::y.
[part1d_forwardmodel_natural_init(int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results)]void* part1d_forwardmodel_natural_init (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part1d_fm_likelihood_t lp, void * user_arg, int results)
References _rjmcmc_engine_cb::accept, _rjmcmc_engine_cb::arg, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, part1dfm::nglobalparameters, part1dfm::nlocalparameters, part1dfm::normal, part1dfm::nprocesses, PART1D_FM_NATURAL, part1d_forwardmodel_create(), _rjmcmc_engine_cb::perturb_process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::random, part1dfm::results, resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_engine_init(), rjmcmc_error(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, total, part1dfm::user_arg, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
int part1d_forwardmodel_natural_step (void * _s)
References part1dfm::cb, and rjmcmc_engine_step().
[part1d_forwardmodel_zero_cubic(int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results)]resultset1dfm_t* part1d_forwardmodel_zero_cubic (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part1d_fm_likelihood_t lp, void * user_arg, int results)
Cubic partitioned 1d forward model.
Experimental** code similar to part1d_forwardmodel_natural except that instead of joining partitions with straight line segments, piecewise cubic segments are used with the gradients set to zero at the partition boundary.
References _rjmcmc_engine_cb::accept, _rjmcmc_engine_cb::arg, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, part1dfm::nglobalparameters, part1dfm::nlocalparameters, part1dfm::normal, part1dfm::nprocesses, PART1D_FM_ZERO_CUBIC, part1d_forwardmodel_create(), part1d_forwardmodel_destroy(), _rjmcmc_engine_cb::perturb_process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::random, part1dfm::results, resultset1dfm_assemble_results(), resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.