forwardmodel_part2d.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <math.h>
*
#include <float.h>
*
#include <rjmcmc/engine.h>
*
#include <rjmcmc/forwardmodel.h>
*
#include <rjmcmc/forwardmodel_mpi.h>
*
#include <rjmcmc/part2d_forwardmodel.h>
*
#include <rjmcmc/rjmcmc_util.h>
*
#include <rjmcmc/rjmcmc_defines.h>
*
#include <rjmcmc/rjmcmc_debug.h>
*
Data Structures
struct part2dfm
struct _part2d_fm_likelihood_state
Macros
#define RESULTSET_CHECKPOINT_TEMPLATE `%s_%03d_%d.resultset.rjmcmc`
#define MODEL_CHECKPOINT_TEMPLATE `%s_%03d_%d.model.rjmcmc`
Enumerations
enum {
*
BIRTH = 0,
DEATH,
MOVE,
LOCALVALUE,
*
GLOBALVALUE,
NPROCESSES,
NPROCESSES_NOGLOBAL = GLOBALVALUE
 }
Functions
resultset2dfm_t * part2d_forwardmodel (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_t lp, void *user_arg, int results)
A partitioned 2d forward model.
resultset2dfm_t * part2d_forwardmodel_restartable (const char *model_file_in, const char *model_file_out, int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_t lp, void *user_arg, int results)
resultset2dfm_t * MPI_part2d_forwardmodel (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
resultset2dfm_t * MPI_part2d_forwardmodel_checkpoint (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_t lp, void *user_arg, int results, int checkpoint_interval, const char *checkpoint_prefix, int mpisize, int mpirank, int root, MPI_Comm comm)
resultset2dfm_t * MPI_part2d_forwardmodel_checkpoint_restart (rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, part2d_fm_likelihood_t lp, void *user_arg, int checkpoint, int checkpoint_interval, const char *checkpoint_prefix, int mpisize, int mpirank, int root, MPI_Comm comm, int *requested_results, int *burnin, int *total, int *thin, int *xsamples, int *ysamples, int *zsamples, int *nprocesses, int *maxpartitions, double *xmin, double *xmax, double *ymin, double *ymax, double *credibleinterval, int *nhierarchical, int *nglobal, int *nlocal, forwardmodelparameter_t **local_parameters, forwardmodelparameter_t **global_parameters)
Macro Definition Documentation
#define MODEL_CHECKPOINT_TEMPLATE `%s_%03d_%d.model.rjmcmc`
Referenced by MPI_part2d_forwardmodel_checkpoint_restart().
#define RESULTSET_CHECKPOINT_TEMPLATE `%s_%03d_%d.resultset.rjmcmc`
Referenced by MPI_part2d_forwardmodel_checkpoint_restart().
Enumeration Type Documentation
anonymous enum
Enumerator
BIRTH
DEATH
MOVE
LOCALVALUE
GLOBALVALUE
NPROCESSES
NPROCESSES_NOGLOBAL
Function Documentation
[MPI_part2d_forwardmodel(int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_t lp, void *user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)]resultset2dfm_t* MPI_part2d_forwardmodel (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part2d_fm_likelihood_t lp, void * user_arg, int results, int mpisize, int mpirank, int root, MPI_Comm comm)
References MPI_resultset2dfm_assemble_results(), part2dfm::mpirank, NPROCESSES, part2dfm::nprocesses, NPROCESSES_NOGLOBAL, part2dfm::results, rjmcmc_engine_run(), and rjmcmc_error().
Referenced by mpi_part2d_forwardmodel_f().
[MPI_part2d_forwardmodel_checkpoint(int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_t lp, void *user_arg, int results, int checkpoint_interval, const char *checkpoint_prefix, int mpisize, int mpirank, int root, MPI_Comm comm)]resultset2dfm_t* MPI_part2d_forwardmodel_checkpoint (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part2d_fm_likelihood_t lp, void * user_arg, int results, int checkpoint_interval, const char * checkpoint_prefix, int mpisize, int mpirank, int root, MPI_Comm comm)
References part2dfm::checkpoint_interval, part2dfm::checkpoint_prefix, MPI_resultset2dfm_assemble_results(), part2dfm::mpirank, NPROCESSES, part2dfm::nprocesses, NPROCESSES_NOGLOBAL, part2dfm::results, rjmcmc_engine_run(), and rjmcmc_error().
[MPI_part2d_forwardmodel_checkpoint_restart(rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, part2d_fm_likelihood_t lp, void *user_arg, int checkpoint, int checkpoint_interval, const char *checkpoint_prefix, int mpisize, int mpirank, int root, MPI_Comm comm, int *requested_results, int *burnin, int *total, int *thin, int *xsamples, int *ysamples, int *zsamples, int *nprocesses, int *maxpartitions, double *xmin, double *xmax, double *ymin, double *ymax, double *credibleinterval, int *nhierarchical, int *nglobal, int *nlocal, forwardmodelparameter_t **local_parameters, forwardmodelparameter_t **global_parameters)]resultset2dfm_t* MPI_part2d_forwardmodel_checkpoint_restart (rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, part2d_fm_likelihood_t lp, void * user_arg, int checkpoint, int checkpoint_interval, const char * checkpoint_prefix, int mpisize, int mpirank, int root, MPI_Comm comm, int * requested_results, int * burnin, int * total, int * thin, int * xsamples, int * ysamples, int * zsamples, int * nprocesses, int * maxpartitions, double * xmin, double * xmax, double * ymin, double * ymax, double * credibleinterval, int * nhierarchical, int * nglobal, int * nlocal, forwardmodelparameter_t ** local_parameters, forwardmodelparameter_t ** global_parameters)
References part2dfm::accepted, BIRTH, part2dfm::birth_prob, part2dfm::bound, part2dfm::checkpoint_interval, part2dfm::checkpoint_prefix, credible_interval, part2dfm::current, part2dfm::current_like, DEATH, part2dfm::death_prob, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part2dfm::global_parameters, part2dfm::global_value_prob, GLOBALVALUE, _part2d_fm_likelihood_state::gradients, part2dfm::initpart, part2dfm::local_parameters, LOCALVALUE, part2dfm::lp, part2dfm::maxpart, part2dfm::mf_global_parameters, part2dfm::mf_gradients, part2dfm::mf_values, part2dfm::minpart, _part2d_fm_likelihood_state::model, MODEL_CHECKPOINT_TEMPLATE, MOVE, part2dfm::move_prob, MPI_resultset2dfm_assemble_results(), part2dfm::mpirank, part2dfm::nglobalparameters, part2dfm::nlocalparameters, _part2d_fm_likelihood_state::nlocalparameters, part2dfm::normal, part2dfm::nprocesses, part2dfm::out, PART2D_FM_ZERO, part2d_forwardmodel_clone(), part2d_forwardmodel_create(), part2d_forwardmodel_destroy(), part2d_forwardmodel_evaluate_local_parameters(), part2d_forwardmodel_global_parameters(), part2d_forwardmodel_initialize(), part2d_forwardmodel_load(), part2d_forwardmodel_min_partitions(), part2d_forwardmodel_partition_centre(), part2d_forwardmodel_partitions(), part2d_forwardmodel_pdx(), part2d_forwardmodel_pdy(), part2d_forwardmodel_propose_birth(), part2d_forwardmodel_propose_death(), part2d_forwardmodel_propose_global_value(), part2d_forwardmodel_propose_local_value(), part2d_forwardmodel_propose_move(), part2d_forwardmodel_save(), part2dfm::pbound, part2dfm::process, part2dfm::proddelta_l, part2dfm::proposed, part2dfm::proposed_like, part2dfm::random, requested_results, part2dfm::results, resultset2dfm_accept(), RESULTSET2DFM_BINARY, resultset2dfm_create(), resultset2dfm_fill_xcoord_vector(), resultset2dfm_fill_ycoord_vector(), resultset2dfm_get_misfit(), resultset2dfm_load(), resultset2dfm_propose(), resultset2dfm_sample_centre(), resultset2dfm_sample_global_parameter(), resultset2dfm_sample_local_parameter(), resultset2dfm_sample_misfit(), resultset2dfm_sample_npartitions(), resultset2dfm_save(), RESULTSET_CHECKPOINT_TEMPLATE, rjmcmc_create_array_1d(), rjmcmc_create_array_3d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_3d(), rjmcmc_engine_restart(), rjmcmc_error(), RJMCMC_NULLCHECKINT, rjmcmc_random_choose_int(), total, part2dfm::user_arg, part2dfm::value_prob, _part2d_fm_likelihood_state::values, part2dfm::x, bbox2d::xmax, bbox2d::xmin, part2dfm::xsamples, part2dfm::y, bbox2d::ymax, bbox2d::ymin, part2dfm::ysamples, and part2dfm::z.
[part2d_forwardmodel(int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_t lp, void *user_arg, int results)]resultset2dfm_t* part2d_forwardmodel (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part2d_fm_likelihood_t lp, void * user_arg, int results)
A partitioned 2d forward model.
This method performs a transdimensional mcmc forward model with zero order fitting within each partition. In the 2d case, the partitions are defined as voronoi cells. For a detailed description of this method, see [bodinThesis].
The return value calculated should be the negative log likelihood as in the single_forwardmodel method which is essentially the weighted sum of square errors.
The callback function supplied to the lp parameter is where the forward model is implemented. This function must match the signature of the part2d_fm_likelihood_t type. The parameters passed to the this callback give you opaque access to the proposed model for which the log likelihood needs to be computed.
Parameters
burnin The number of burn in iterations.
total The total number of iterations (must be greater than burnin).
minpart The minimum number of partitions, this should be 2.
maxpart The maximum number of partitions.
initpart The initial number of partitions.
minx The lower bound value of the x coordinate
maxx The upper bound value of the x coordinate.
miny The lower bound value of the y coordinate
maxy The upper bound value of the y coordinate.
xsamples When producing mean curves etc, the number of discretization steps used for constructing the curve. A value of 100 suits most cases.
ysamples When producing mean curves etc, the number of discretization steps used for constructing the curve. A value of 100 suits most cases.
zsamples Results such as median, mode, credible intervals are computed using a histogram of values, this parameter sets the number of bins for this histogram. A value of 100 suits most cases.
credible_interval The credible interval expressed as a percentage between 0 and 1.
pdx The standard deviation of the perturb partition boundary (move) step in the x direction.
pdy The standard deviation of the perturb partition boundary (move) step in the y direction.
random User supplied uniform random number generator.
normal User supplied normal random number generator.
nglobalparameters The number of global parameters.
global_parameters An array of global parameters (their min, max and perturbation standard deviations).
nlocalparameters The number of local parameters.
local_parameters An array of local parameters (their min, max and perturbation standard deviations).
lp The likelihood function.
user_arg A pointer to user data that will be supplied to the likelihood function.
results The results desired as a bitwise or'ing of resultset1dfm_result_t values.
For an example of using this function, see the example 2d/partitioned/fm/regression/regression.h
Examples:
2d/partitioned/fm/regression/regression.c.
References NPROCESSES, part2dfm::nprocesses, NPROCESSES_NOGLOBAL, part2dfm::results, resultset2dfm_assemble_results(), rjmcmc_engine_run(), and rjmcmc_error().
Referenced by part2d_forwardmodel_f().
[part2d_forwardmodel_restartable(const char *model_file_in, const char *model_file_out, int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_t lp, void *user_arg, int results)]resultset2dfm_t* part2d_forwardmodel_restartable (const char * model_file_in, const char * model_file_out, int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part2d_fm_likelihood_t lp, void * user_arg, int results)
References part2dfm::bound, part2dfm::checkpoint_interval, part2dfm::checkpoint_prefix, part2dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part2dfm::global_parameters, part2dfm::initpart, part2dfm::local_parameters, part2dfm::lp, part2dfm::maxpart, part2dfm::mf_gradients, part2dfm::mf_values, part2dfm::minpart, part2dfm::mpirank, part2dfm::nglobalparameters, part2dfm::nlocalparameters, part2dfm::normal, NPROCESSES, part2dfm::nprocesses, NPROCESSES_NOGLOBAL, PART2D_FM_ZERO, part2d_forwardmodel_create(), part2d_forwardmodel_destroy(), part2d_forwardmodel_load(), part2d_forwardmodel_save(), part2dfm::proddelta_l, part2dfm::proposed, part2dfm::random, part2dfm::results, resultset2dfm_assemble_results(), resultset2dfm_create(), resultset2dfm_fill_xcoord_vector(), resultset2dfm_fill_ycoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_3d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_3d(), rjmcmc_engine_run(), rjmcmc_error(), part2dfm::user_arg, part2dfm::x, bbox2d::xmax, bbox2d::xmin, part2dfm::xsamples, part2dfm::y, bbox2d::ymax, bbox2d::ymin, part2dfm::ysamples, and part2dfm::z.