forwardmodel.h File Reference
Simple Forward Model Routines.
#include <rjmcmc/rjmcmc_config.h>
*
#include <rjmcmc/resultsetfm.h>
*
#include <rjmcmc/resultset1dfm.h>
*
#include <rjmcmc/resultset2dfm.h>
*
#include <rjmcmc/bbox2d.h>
*
#include <rjmcmc/rjmcmc_random.h>
*
Typedefs
typedef double(* single_fm_likelihood_t) (void *user_arg, int n, const double *values)
typedef double(* single_fm_likelihood_hierarchical_t) (void *user_arg, int nvalues, const double *values, int hierarchical_proposal, int nhierarchicalvalues, const double *hierarchicalvalues, double *logdetCe)
typedef struct _part1d_fm_likelihood_state part1d_fm_likelihood_state_t
typedef const double *(* part1d_fm_value_at_t) (part1d_fm_likelihood_state_t *state, double x)
typedef double(* part1d_fm_likelihood_t) (void *userarg, int npartitions, const double *partition_boundaries, int nglobalparameters, const double *global_parameters, part1d_fm_likelihood_state_t *state, part1d_fm_value_at_t value_at, part1d_fm_value_at_t gradient_at)
typedef struct _part1d_fm_hierarchical_likelihood_state part1d_fm_hierarchical_likelihood_state_t
typedef const double *(* part1d_fm_hierarchical_value_at_t) (part1d_fm_hierarchical_likelihood_state_t *state, double x)
typedef double(* part1d_fm_hierarchical_likelihood_t) (void *userarg, int npartitions, const double *partition_boundaries, int nglobalparameters, const double *global_parameters, int hierarchical, int nhierarchicalparameters, const double *heirarchical_parameters, part1d_fm_hierarchical_likelihood_state_t *state, part1d_fm_hierarchical_value_at_t value_at, part1d_fm_hierarchical_value_at_t gradient_at, double *logdetce)
typedef struct _part2d_fm_likelihood_state part2d_fm_likelihood_state_t
typedef const double *(* part2d_fm_value_at_t) (part2d_fm_likelihood_state_t *state, double x, double y)
typedef double(* part2d_fm_likelihood_t) (void *userarg, int nglobalparameters, const double *global_parameters, part2d_fm_likelihood_state_t *state, part2d_fm_value_at_t value_at, part2d_fm_value_at_t gradient_at, const bbox2d_t *bound)
typedef double(* part2d_fm_hierarchical_likelihood_t) (void *userarg, int nglobalparameters, const double *global_parameters, int hierarchical, int nhierarchicalparameters, const double *hierarchical_parameters, part2d_fm_likelihood_state_t *state, part2d_fm_value_at_t value_at, part2d_fm_value_at_t gradient_at, const bbox2d_t *bound, double *logdetce)
Functions
resultsetfm_t * single_forwardmodel (int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t *parameters, single_fm_likelihood_t lp, void *user_arg, int samples, double credible_interval, int results)
Single Partition Forward Model.
resultsetfm_t * single_forwardmodel_hierarchical (int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t *parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchicalparameters, single_fm_likelihood_hierarchical_t lp, void *user_arg, int nsamples, double credible_interval, int results)
Single Partition Forward Model with Hierarchical Noise.
resultset1dfm_t * part1d_forwardmodel (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results)
A partitioned 1d forward model.
resultset1dfm_t * part1d_forwardmodel_hierarchical (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results)
Partitioned 1d forwardmodel with hierarchical parameters.
resultset1dfm_t * part1d_forwardmodel_natural (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results)
Natural partitioned forward model.
resultset1dfm_t * part1d_forwardmodel_natural_hierarchical (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results)
Natural partitioned forward model with hierarchical parameters.
void * part1d_forwardmodel_natural_hierarchical_init (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results)
int part1d_forwardmodel_natural_hierarchical_step (void *state)
resultset1dfm_t * part1d_forwardmodel_natural_hierarchical_finish (void *state)
resultset1dfm_t * part1d_forwardmodel_zero_cubic (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results)
Cubic partitioned 1d forward model.
resultset2dfm_t * part2d_forwardmodel (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_t lp, void *user_arg, int results)
A partitioned 2d forward model.
resultset2dfm_t * part2d_forwardmodel_restartable (const char *model_file_in, const char *model_file_out, int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_t lp, void *user_arg, int results)
resultset2dfm_t * part2d_forwardmodel_hierarchical (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part2d_fm_hierarchical_likelihood_t lp, void *user_arg, int results)
A partitioned 2d forward model with hierarchical parameters.
Detailed Description
Simple Forward Model Routines.
The Forward Model routines allow the user to supply their own likelihood functions where a forward model is required to transform the data an error model other than uncorrelated gaussian noise is required.
These methods use callback functions to perform the forward model calculations. See the single_fm_likelihood_t, single_fm_likelihood_hierarchical_t, part1d_fm_likelihood_t, part1d_fm_hierarchical_likelihood_t, part2d_fm_likelihood_t and part2d_fm_hierarchical_likelihood_t types for the signatures of these functions.
The examples under the 1d/single/fm, 1d/partitioned/fm and 2d/partitioned/fm directories are instructive in the use of these methods.
Typedef Documentation
typedef struct _part1d_fm_hierarchical_likelihood_state part1d_fm_hierarchical_likelihood_state_t
typedef double(* part1d_fm_hierarchical_likelihood_t) (void *userarg, int npartitions, const double *partition_boundaries, int nglobalparameters, const double *global_parameters, int hierarchical, int nhierarchicalparameters, const double *heirarchical_parameters, part1d_fm_hierarchical_likelihood_state_t *state, part1d_fm_hierarchical_value_at_t value_at, part1d_fm_hierarchical_value_at_t gradient_at, double *logdetce)
typedef const double*(* part1d_fm_hierarchical_value_at_t) (part1d_fm_hierarchical_likelihood_state_t *state, double x)
Examples:
1d/partitioned/fm/regression/regression.c.
typedef struct _part1d_fm_likelihood_state part1d_fm_likelihood_state_t
typedef double(* part1d_fm_likelihood_t) (void *userarg, int npartitions, const double *partition_boundaries, int nglobalparameters, const double *global_parameters, part1d_fm_likelihood_state_t *state, part1d_fm_value_at_t value_at, part1d_fm_value_at_t gradient_at)
typedef const double*(* part1d_fm_value_at_t) (part1d_fm_likelihood_state_t *state, double x)
Examples:
1d/partitioned/fm/functionfit/functionfit.c, and 1d/partitioned/fm/regression/regression.c.
typedef double(* part2d_fm_hierarchical_likelihood_t) (void *userarg, int nglobalparameters, const double *global_parameters, int hierarchical, int nhierarchicalparameters, const double *hierarchical_parameters, part2d_fm_likelihood_state_t *state, part2d_fm_value_at_t value_at, part2d_fm_value_at_t gradient_at, const bbox2d_t *bound, double *logdetce)
typedef struct _part2d_fm_likelihood_state part2d_fm_likelihood_state_t
typedef double(* part2d_fm_likelihood_t) (void *userarg, int nglobalparameters, const double *global_parameters, part2d_fm_likelihood_state_t *state, part2d_fm_value_at_t value_at, part2d_fm_value_at_t gradient_at, const bbox2d_t *bound)
typedef const double*(* part2d_fm_value_at_t) (part2d_fm_likelihood_state_t *state, double x, double y)
Examples:
2d/partitioned/fm/regression/regression.c.
typedef double(* single_fm_likelihood_hierarchical_t) (void *user_arg, int nvalues, const double *values, int hierarchical_proposal, int nhierarchicalvalues, const double *hierarchicalvalues, double *logdetCe)
typedef double(* single_fm_likelihood_t) (void *user_arg, int n, const double *values)
Function Documentation
[part1d_forwardmodel(int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results)]resultset1dfm_t* part1d_forwardmodel (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part1d_fm_likelihood_t lp, void * user_arg, int results)
A partitioned 1d forward model.
This method performs a transdimensional mcmc forward model with zero order fitting within each partition. For a detailed description of this method, see [bodinThesis].
The return value calculated should be the negative log likelihood as in the single_forwardmodel method which is essentially the weighted sum of square errors.
The callback function supplied to the lp parameter is where the forward model is implemented. This function must match the signature of the part1d_fm_likelihood_t type. The parameters passed to the this callback give you opaque access to the proposed model for which the log likelihood needs to be computed.
Parameters
burnin The number of burn in iterations.
total The total number of iterations (must be greater than burnin).
minpart The minimum number of partitions, this should be 2.
maxpart The maximum number of partitions.
minx The lower bound value of the x coordinate
maxx The upper bound value of the x coordinate.
xsamples When producing mean curves etc, the number of discretization steps used for constructing the curve. A value of 100 suits most cases.
ysamples Results such as median, mode, credible intervals are computed using a histogram of values, this parameter sets the number of bins for this histogram. A value of 100 suits most cases.
credible_interval The credible interval expressed as a percentage between 0 and 1.
pd The standard deviation of the perturb partition boundary (move) step.
random User supplied uniform random number generator.
normal User supplied normal random number generator.
nglobalparameters The number of global parameters.
global_parameters An array of global parameters (their min, max and perturbation standard deviations).
nlocalparameters The number of local parameters.
local_parameters An array of local parameters (their min, max and perturbation standard deviations).
lp The hierarchical likelihood function.
user_arg A pointer to user data that will be supplied to the likelihood function.
results The results desired as a bitwise or'ing of resultset1dfm_result_t values.
For an example of using this function, see the example 1d/single/fm/partitioned/functionfit/functionfit.c
References _rjmcmc_engine_cb::accept, _rjmcmc_engine_cb::arg, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, part1dfm::nglobalparameters, part1dfm::nlocalparameters, part1dfm::normal, part1dfm::nprocesses, PART1D_FM_ZERO, part1d_forwardmodel_create(), part1d_forwardmodel_destroy(), _rjmcmc_engine_cb::perturb_process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::random, part1dfm::results, resultset1dfm_assemble_results(), resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
Referenced by part1d_forwardmodel_f().
[part1d_forwardmodel_hierarchical(int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results)]resultset1dfm_t* part1d_forwardmodel_hierarchical (int burnin, int total, int minpart, int maxpart, double minx, double maxx, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void * user_arg, int results)
Partitioned 1d forwardmodel with hierarchical parameters.
This method is the same as the part1d_forwardmodel except it also solves for hierarchical parameters that are used to construct the covariance matrix. See [bodin2012A] for an example application of hierarchical solving.
Parameters
burnin The number of burn in iterations.
total The total number of iterations (must be greater than burnin).
minpart The minimum number of partitions, this should be 2.
maxpart The maximum number of partitions.
minx The lower bound value of the x coordinate
maxx The upper bound value of the x coordinate.
xsamples When producing mean curves etc, the number of discretization steps used for constructing the curve. A value of 100 suits most cases.
ysamples Results such as median, mode, credible intervals are computed using a histogram of values, this parameter sets the number of bins for this histogram. A value of 100 suits most cases.
credible_interval The credible interval expressed as a percentage between 0 and 1.
pd The standard deviation of the perturb partition boundary (move) step.
random User supplied uniform random number generator.
normal User supplied normal random number generator.
nglobalparameters The number of global parameters.
global_parameters An array of global parameters (their min, max and perturbation standard deviations).
nlocalparameters The number of local parameters.
local_parameters An array of local parameters (their min, max and perturbation standard deviations).
nhierarchicalparameters The number of hierarchical parameters.
hierarchical_parameters An array of hierarchical parameters (their min, max and perturbation standard deviations).
lp The hierarchical likelihood function.
user_arg A pointer to user data that will be supplied to the likelihood function.
results The results desired as a bitwise or'ing of resultset1dfm_result_t values.
For an example of using this function, see the example 1d/single/fm/partitioned/regression/regression.c
References _rjmcmc_engine_cb::accept, _rjmcmc_engine_cb::arg, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, part1dfm::current_like, part1dfm::current_logdetce, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, part1dfm::hierarchical_parameters, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, part1dfm::nglobalparameters, part1dfm::nhierarchicalparameters, part1dfm::nlocalparameters, part1dfm::normal, NPROCESSES, part1dfm::nprocesses, NPROCESSES_NOGLOBAL, PART1D_FM_ZERO, part1d_forwardmodel_create(), part1d_forwardmodel_destroy(), _rjmcmc_engine_cb::perturb_process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::proposed_like, part1dfm::proposed_logdetce, part1dfm::random, part1dfm::results, resultset1dfm_assemble_results(), resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
Referenced by part1d_forwardmodel_hierarchical_f().
[part1d_forwardmodel_natural(int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results)]resultset1dfm_t* part1d_forwardmodel_natural (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part1d_fm_likelihood_t lp, void * user_arg, int results)
Natural partitioned forward model.
This method is similar to the part1d_forwardmodel method except that instead of fitting zero order values in each partition, a continuous function is constructed using joined line segments between partition boundaries. For an example application of this method see [hopcroft2007A].
Parameters
burnin The number of burn in iterations.
total The total number of iterations (must be greater than burnin).
minpart The minimum number of partitions, this should be 2.
maxpart The maximum number of partitions.
minx The lower bound value of the x coordinate
maxx The upper bound value of the x coordinate.
xsamples When producing mean curves etc, the number of discretization steps used for constructing the curve. A value of 100 suits most cases.
ysamples Results such as median, mode, credible intervals are computed using a histogram of values, this parameter sets the number of bins for this histogram. A value of 100 suits most cases.
credible_interval The credible interval expressed as a percentage between 0 and 1.
pd The standard deviation of the perturb partition boundary (move) step.
random User supplied uniform random number generator.
normal User supplied normal random number generator.
nglobalparameters The number of global parameters.
global_parameters An array of global parameters (their min, max and perturbation standard deviations).
nlocalparameters The number of local parameters.
local_parameters An array of local parameters (their min, max and perturbation standard deviations).
lp The hierarchical likelihood function.
user_arg A pointer to user data that will be supplied to the likelihood function.
results The results desired as a bitwise or'ing of resultset1dfm_result_t values.
References _rjmcmc_engine_cb::accept, _rjmcmc_engine_cb::arg, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, part1dfm::nglobalparameters, part1dfm::nlocalparameters, part1dfm::normal, part1dfm::nprocesses, PART1D_FM_NATURAL, part1d_forwardmodel_create(), part1d_forwardmodel_destroy(), _rjmcmc_engine_cb::perturb_process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::random, part1dfm::results, resultset1dfm_assemble_results(), resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
Referenced by part1d_forwardmodel_natural_f().
[part1d_forwardmodel_natural_hierarchical(int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results)]resultset1dfm_t* part1d_forwardmodel_natural_hierarchical (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void * user_arg, int results)
Natural partitioned forward model with hierarchical parameters.
This method is the same as the part1d_forwardmodel_hierarchical except it uses joined line segments between partition boundaries rather than zero order fits within each partition to fit the data.
Parameters
burnin The number of burn in iterations.
total The total number of iterations (must be greater than burnin).
minpart The minimum number of partitions, this should be 2.
maxpart The maximum number of partitions.
minx The lower bound value of the x coordinate
maxx The upper bound value of the x coordinate.
xsamples When producing mean curves etc, the number of discretization steps used for constructing the curve. A value of 100 suits most cases.
ysamples Results such as median, mode, credible intervals are computed using a histogram of values, this parameter sets the number of bins for this histogram. A value of 100 suits most cases.
credible_interval The credible interval expressed as a percentage between 0 and 1.
pd The standard deviation of the perturb partition boundary (move) step.
random User supplied uniform random number generator.
normal User supplied normal random number generator.
nglobalparameters The number of global parameters.
global_parameters An array of global parameters (their min, max and perturbation standard deviations).
nlocalparameters The number of local parameters.
local_parameters An array of local parameters (their min, max and perturbation standard deviations).
nhierarchicalparameters The number of hierarchical parameters.
hierarchical_parameters An array of hierarchical parameters (their min, max and perturbation standard deviations).
lp The hierarchical likelihood function.
user_arg A pointer to user data that will be supplied to the likelihood function.
results The results desired as a bitwise or'ing of resultset1dfm_result_t values.
References _rjmcmc_engine_cb::accept, _rjmcmc_engine_cb::arg, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, part1dfm::hierarchical_parameters, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, part1dfm::nglobalparameters, part1dfm::nhierarchicalparameters, part1dfm::nlocalparameters, part1dfm::normal, NPROCESSES, part1dfm::nprocesses, NPROCESSES_NOGLOBAL, PART1D_FM_NATURAL, part1d_forwardmodel_create(), part1d_forwardmodel_destroy(), _rjmcmc_engine_cb::perturb_process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::random, part1dfm::results, resultset1dfm_assemble_results(), resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
Referenced by part1d_forwardmodel_natural_hierarchical_f().
resultset1dfm_t* part1d_forwardmodel_natural_hierarchical_finish (void * state)
References part1dfm::current, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::nlocalparameters, part1d_forwardmodel_destroy(), part1dfm::proposed, part1dfm::results, resultset1dfm_assemble_results(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), part1dfm::x, and part1dfm::y.
Referenced by part1d_forwardmodel_natural_hierarchical_finish_f().
[part1d_forwardmodel_natural_hierarchical_init(int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void *user_arg, int results)]void* part1d_forwardmodel_natural_hierarchical_init (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part1d_fm_hierarchical_likelihood_t lp, void * user_arg, int results)
References _rjmcmc_engine_cb::accept, _rjmcmc_engine_cb::arg, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, part1dfm::hierarchical_parameters, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, part1dfm::nglobalparameters, part1dfm::nhierarchicalparameters, part1dfm::nlocalparameters, part1dfm::normal, NPROCESSES, part1dfm::nprocesses, NPROCESSES_NOGLOBAL, PART1D_FM_NATURAL, part1d_forwardmodel_create(), _rjmcmc_engine_cb::perturb_process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::random, part1dfm::results, resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_engine_init(), rjmcmc_error(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
Referenced by part1d_forwardmodel_natural_hierarchical_init_f().
int part1d_forwardmodel_natural_hierarchical_step (void * state)
References part1dfm::cb, and rjmcmc_engine_step().
Referenced by part1d_forwardmodel_natural_hierarchical_step_f().
[part1d_forwardmodel_zero_cubic(int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part1d_fm_likelihood_t lp, void *user_arg, int results)]resultset1dfm_t* part1d_forwardmodel_zero_cubic (int burnin, int total, int minpart, int maxpart, double xmin, double xmax, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part1d_fm_likelihood_t lp, void * user_arg, int results)
Cubic partitioned 1d forward model.
Experimental** code similar to part1d_forwardmodel_natural except that instead of joining partitions with straight line segments, piecewise cubic segments are used with the gradients set to zero at the partition boundary.
References _rjmcmc_engine_cb::accept, _rjmcmc_engine_cb::arg, part1dfm::cb, _rjmcmc_engine_cb::compute_misfit, part1dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part1dfm::global_parameters, _rjmcmc_engine_cb::initialize_state, part1dfm::local_parameters, part1dfm::lp, part1dfm::maxpart, part1dfm::mf_global_parameters, part1dfm::mf_gradients, part1dfm::mf_partitions, part1dfm::mf_values, part1dfm::minpart, part1dfm::nglobalparameters, part1dfm::nlocalparameters, part1dfm::normal, part1dfm::nprocesses, PART1D_FM_ZERO_CUBIC, part1d_forwardmodel_create(), part1d_forwardmodel_destroy(), _rjmcmc_engine_cb::perturb_process, part1dfm::proddelta_l, part1dfm::proposed, part1dfm::random, part1dfm::results, resultset1dfm_assemble_results(), resultset1dfm_create(), resultset1dfm_fill_xcoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), _rjmcmc_engine_cb::sample, _rjmcmc_engine_cb::select_process, part1dfm::user_arg, part1dfm::x, part1dfm::xmax, part1dfm::xmin, part1dfm::xsamples, and part1dfm::y.
[part2d_forwardmodel(int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_t lp, void *user_arg, int results)]resultset2dfm_t* part2d_forwardmodel (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part2d_fm_likelihood_t lp, void * user_arg, int results)
A partitioned 2d forward model.
This method performs a transdimensional mcmc forward model with zero order fitting within each partition. In the 2d case, the partitions are defined as voronoi cells. For a detailed description of this method, see [bodinThesis].
The return value calculated should be the negative log likelihood as in the single_forwardmodel method which is essentially the weighted sum of square errors.
The callback function supplied to the lp parameter is where the forward model is implemented. This function must match the signature of the part2d_fm_likelihood_t type. The parameters passed to the this callback give you opaque access to the proposed model for which the log likelihood needs to be computed.
Parameters
burnin The number of burn in iterations.
total The total number of iterations (must be greater than burnin).
minpart The minimum number of partitions, this should be 2.
maxpart The maximum number of partitions.
initpart The initial number of partitions.
minx The lower bound value of the x coordinate
maxx The upper bound value of the x coordinate.
miny The lower bound value of the y coordinate
maxy The upper bound value of the y coordinate.
xsamples When producing mean curves etc, the number of discretization steps used for constructing the curve. A value of 100 suits most cases.
ysamples When producing mean curves etc, the number of discretization steps used for constructing the curve. A value of 100 suits most cases.
zsamples Results such as median, mode, credible intervals are computed using a histogram of values, this parameter sets the number of bins for this histogram. A value of 100 suits most cases.
credible_interval The credible interval expressed as a percentage between 0 and 1.
pdx The standard deviation of the perturb partition boundary (move) step in the x direction.
pdy The standard deviation of the perturb partition boundary (move) step in the y direction.
random User supplied uniform random number generator.
normal User supplied normal random number generator.
nglobalparameters The number of global parameters.
global_parameters An array of global parameters (their min, max and perturbation standard deviations).
nlocalparameters The number of local parameters.
local_parameters An array of local parameters (their min, max and perturbation standard deviations).
lp The likelihood function.
user_arg A pointer to user data that will be supplied to the likelihood function.
results The results desired as a bitwise or'ing of resultset1dfm_result_t values.
For an example of using this function, see the example 2d/partitioned/fm/regression/regression.h
References NPROCESSES, part2dfm::nprocesses, NPROCESSES_NOGLOBAL, part2dfm::results, resultset2dfm_assemble_results(), rjmcmc_engine_run(), and rjmcmc_error().
Referenced by part2d_forwardmodel_f().
[part2d_forwardmodel_hierarchical(int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, part2d_fm_hierarchical_likelihood_t lp, void *user_arg, int results)]resultset2dfm_t* part2d_forwardmodel_hierarchical (int burnin, int total, int thin, int minpart, int maxpart, int initpart, double minx, double maxx, double miny, double maxy, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, part2d_fm_hierarchical_likelihood_t lp, void * user_arg, int results)
A partitioned 2d forward model with hierarchical parameters.
This method is the same as the part2d_forwardmodel method except it also solves for hierarchical parameters that are used to construct the covariance matrix.
Parameters
burnin The number of burn in iterations.
total The total number of iterations (must be greater than burnin).
thin The number of samples to skip when averaging (0 means none).
minpart The minimum number of partitions, this should be 2.
maxpart The maximum number of partitions.
initpart The initial number of partitions.
minx The lower bound value of the x coordinate
maxx The upper bound value of the x coordinate.
miny The lower bound value of the y coordinate
maxy The upper bound value of the y coordinate.
xsamples When producing mean curves etc, the number of discretization steps used for constructing the curve. A value of 100 suits most cases.
ysamples When producing mean curves etc, the number of discretization steps used for constructing the curve. A value of 100 suits most cases.
zsamples Results such as median, mode, credible intervals are computed using a histogram of values, this parameter sets the number of bins for this histogram. A value of 100 suits most cases.
credible_interval The credible interval expressed as a percentage between 0 and 1.
pdx The standard deviation of the perturb partition boundary (move) step in the x direction.
pdy The standard deviation of the perturb partition boundary (move) step in the y direction.
random User supplied uniform random number generator.
normal User supplied normal random number generator.
nglobalparameters The number of global parameters.
global_parameters An array of global parameters (their min, max and perturbation standard deviations).
nlocalparameters The number of local parameters.
local_parameters An array of local parameters (their min, max and perturbation standard deviations).
nhierarchicalparameters The number of hierarchical parameters.
hierarchical_parameters An array of hierarchical parameters (their min, max and perturbation standard deviations).
lp The likelihood function.
user_arg A pointer to user data that will be supplied to the likelihood function.
results The results desired as a bitwise or'ing of resultset1dfm_result_t values.
For an example of using this function, see the example 2d/partitioned/fm/regression/regression.h
References part2dfm::bound, part2dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part2dfm::global_parameters, part2dfm::hierarchical_parameters, part2dfm::initpart, part2dfm::local_parameters, part2dfm::lp, part2dfm::maxpart, part2dfm::mf_gradients, part2dfm::mf_values, part2dfm::minpart, part2dfm::nglobalparameters, part2dfm::nhierarchicalparameters, part2dfm::nlocalparameters, part2dfm::normal, NPROCESSES, part2dfm::nprocesses, NPROCESSES_NOGLOBAL, PART2D_FM_ZERO, part2d_forwardmodel_create(), part2d_forwardmodel_destroy(), part2dfm::proddelta_l, part2dfm::proposed, part2dfm::random, part2dfm::results, resultset2dfm_assemble_results(), resultset2dfm_create(), resultset2dfm_fill_xcoord_vector(), resultset2dfm_fill_ycoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_3d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_3d(), rjmcmc_engine_run(), rjmcmc_error(), part2dfm::user_arg, part2dfm::x, bbox2d::xmax, bbox2d::xmin, part2dfm::xsamples, part2dfm::y, bbox2d::ymax, bbox2d::ymin, part2dfm::ysamples, and part2dfm::z.
Referenced by part2d_forwardmodel_hierarchical_f().
[part2d_forwardmodel_restartable(const char *model_file_in, const char *model_file_out, int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, part2d_fm_likelihood_t lp, void *user_arg, int results)]resultset2dfm_t* part2d_forwardmodel_restartable (const char * model_file_in, const char * model_file_out, int burnin, int total, int thin, int minpart, int maxpart, int initpart, double xmin, double xmax, double ymin, double ymax, int xsamples, int ysamples, int zsamples, double credible_interval, double pdx, double pdy, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, part2d_fm_likelihood_t lp, void * user_arg, int results)
References part2dfm::bound, part2dfm::checkpoint_interval, part2dfm::checkpoint_prefix, part2dfm::current, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, part2dfm::global_parameters, part2dfm::initpart, part2dfm::local_parameters, part2dfm::lp, part2dfm::maxpart, part2dfm::mf_gradients, part2dfm::mf_values, part2dfm::minpart, part2dfm::mpirank, part2dfm::nglobalparameters, part2dfm::nlocalparameters, part2dfm::normal, NPROCESSES, part2dfm::nprocesses, NPROCESSES_NOGLOBAL, PART2D_FM_ZERO, part2d_forwardmodel_create(), part2d_forwardmodel_destroy(), part2d_forwardmodel_load(), part2d_forwardmodel_save(), part2dfm::proddelta_l, part2dfm::proposed, part2dfm::random, part2dfm::results, resultset2dfm_assemble_results(), resultset2dfm_create(), resultset2dfm_fill_xcoord_vector(), resultset2dfm_fill_ycoord_vector(), rjmcmc_create_array_1d(), rjmcmc_create_array_3d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_3d(), rjmcmc_engine_run(), rjmcmc_error(), part2dfm::user_arg, part2dfm::x, bbox2d::xmax, bbox2d::xmin, part2dfm::xsamples, part2dfm::y, bbox2d::ymax, bbox2d::ymin, part2dfm::ysamples, and part2dfm::z.
[single_forwardmodel(int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t *parameters, single_fm_likelihood_t lp, void *user_arg, int samples, double credible_interval, int results)]resultsetfm_t* single_forwardmodel (int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t * parameters, single_fm_likelihood_t lp, void * user_arg, int samples, double credible_interval, int results)
Single Partition Forward Model.
A single partition 1D forward model is essentially attempting to solve for a number of parameters. A range of these parameters is supplied via the parameters parameter.
The user supplied callback function, lp, will be passed at each iteration a set of parameters in an array. The callback should calculate negative log likelihood of the model (note that multiplicative and additive constants can be left out as these will cancel) . For an uncorrelated gaussian, this simplifies to (and removing the additive constant):
 \log({\mathrm{likelihood}}) = \sum_{i = 1}^n \frac{\left(g\left(m\right)_i - d_i\right)^2}{2 \sigma_i^2} 
From the actual likelihood:
 \Pr(d|m) = \frac{1}{\prod_{i=1}^n \sqrt{2 \pi \cdot \sigma_i^2}} \exp{\left( \sum_{i = 1}^n \frac{-\left(g\left(m\right)_i - d_i\right)^2}{2\sigma_i^2}\right)} 
Where $g(m)_i$ is the data/model generated from the parameters passed to the function, $d_i$ is the data/model to compare, and . $\sigma_i$ is the variance of the noise or uncertainty in the data. If the variance is not known and set to unity, the simulation will tend to overfit the data (unless the variance is actually near 1). In this case it is recommended that the single_forwardmodel_hierarchical function be used instead as it will also perturb an estimate of $\sigma$. Note that we don't need to calculate the scaling constant for the gaussian probability in this case since it is cancelled out in the MCMC step. This is not the case for the hierarchical version single_forwardmodel_hierarchical.
Parameters
burnin The number of burn in iterations.
total The total number of iterations (must be greater than burnin).
random User supplied uniform random number generator.
normal User supplied normal random number generator.
nparameters The number of parameters in the forward model.
parameters The array of parameter information.
lp The hierarchical likelihood function.
user_arg A pointer to user data that will be supplied to the likelihood function.
samples Results such as median, mode, credible intervals are computed using a histogram of values, this parameter sets the number of bins for this histogram. A value of 100 suits most cases.
credible_interval The credible interval expressed as a percentage between 0 and 1.
results The results desired as a bitwise or'ing of resultsetfm_result_t values.
For an example of using this function, see the example 1d/single/fm/simpleimage/simpleimage.c
References fmsingle::current, fmsingle::current_hierarchical, fmsingle::current_like, fmsingle::current_logdetce, fmsingle::hierarchicalparameters, fmsingle::lp, fmsingle::lp_hierarchical, fmsingle::nhierarchicalparameters, fmsingle::normal, fmsingle::nparameters, fmsingle::nsamples, fmsingle::out, fmsingle::parameters, fmsingle::process, fmsingle::proposed, fmsingle::proposed_hierarchical, fmsingle::proposed_like, fmsingle::proposed_logdetce, fmsingle::random, fmsingle::results, resultsetfm_assemble_results(), resultsetfm_create(), rjmcmc_create_array_1d(), rjmcmc_destroy_array_1d(), rjmcmc_engine_run(), rjmcmc_error(), samples, and fmsingle::user_arg.
Referenced by single_forwardmodel_f().
[single_forwardmodel_hierarchical(int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t *parameters, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchicalparameters, single_fm_likelihood_hierarchical_t lp, void *user_arg, int nsamples, double credible_interval, int results)]resultsetfm_t* single_forwardmodel_hierarchical (int burnin, int total, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int nparameters, const forwardmodelparameter_t * parameters, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchicalparameters, single_fm_likelihood_hierarchical_t lp, void * user_arg, int nsamples, double credible_interval, int results)
Single Partition Forward Model with Hierarchical Noise.
This forward model adds a custom number of hierarchical parameters that affect the scaling constant of the likelihood and therefore the log(likelihood) that needs to be returned from the likelihood function.
The general gaussian probability is:
 \Pr() = \frac{1}{(2 \pi)^{n/2} |C_e|} \exp{-\frac{1}{2}(g(m) - d)^T C_e^{-1} (g(m) - d)} 
Where $ C_e $ is the covariance matrix that is generated from the hierarchical parameters. In the simplest case you would have 1 hierarchical parameter with the diagonal of the covariance matrix set to this value.
The callback function now needs to calculate the entire likelihood value but only when the hierarchical parameters are perturbed. To facilitate this and to allow some efficiency gains in not having to continuously evaluate the determinant of the covariance matrix, the callback function only needs to return the positive value of the exponential term above, ie $\frac{1}{2}(g(m) - d)^T C_e^{-1} (g(m) - d)$, and the determinant of the covariance when needed. This is indicated with the hierarchical parameter to the callback function. In psuedo code, the callback function should follow the following pattern:
loglikelihood = calculate_log_likelihood();
if (hierarchical == 1) {
     logdetce = calculate_log_detCe();
} 

return loglikelihood;
Parameters
burnin The number of burn in iterations.
total The total number of iterations (must be greater than burnin).
random User supplied uniform random number generator.
normal User supplied normal random number generator.
nparameters The number of parameters in the forward model.
parameters The array of parameter information.
nhierarchicalparameters The number of hierarchical parameters to sample
hierarchicalparameters
lp The hierarchical likelihood function. Note that this has a different signature than the single_forwardmodel function parameter of the same name.
user_arg A pointer to user data that will be supplied to the likelihood function.
nsamples The number of data points used in calculating the likelihood.
credible_interval The credible interval expressed as a percentage between 0 and 1.
results The results desired as a bitwise or'ing of resultsetfm_result_t values.
For an example of using this function, see the example 1d/single/fm/simpleimage/simpleimage.c
References fmsingle::current, fmsingle::current_hierarchical, fmsingle::current_like, fmsingle::current_logdetce, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _forwardmodelparameter::fstd_value, fmsingle::hierarchicalparameters, fmsingle::lp, fmsingle::lp_hierarchical, fmsingle::nhierarchicalparameters, fmsingle::normal, fmsingle::nparameters, fmsingle::nsamples, fmsingle::out, fmsingle::parameters, fmsingle::process, fmsingle::proposed, fmsingle::proposed_hierarchical, fmsingle::proposed_like, fmsingle::proposed_logdetce, fmsingle::random, fmsingle::results, resultsetfm_accept(), resultsetfm_assemble_results(), resultsetfm_create(), resultsetfm_propose(), resultsetfm_sample(), resultsetfm_sample_hierarchical(), resultsetfm_sample_misfit(), rjmcmc_create_array_1d(), rjmcmc_destroy_array_1d(), rjmcmc_engine_run(), rjmcmc_error(), rjmcmc_random_choose_double(), rjmcmc_random_choose_int(), samples, and fmsingle::user_arg.
Referenced by single_forwardmodel_hierarchical_f().