part1d_zero.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <math.h>
*
#include <float.h>
*
#include `rjmcmc/part1d_zero.h`
*
#include `rjmcmc/position_map1d.h`
*
#include `rjmcmc/rjmcmc_util.h`
*
#include `rjmcmc/rjmcmc_defines.h`
*
Data Structures
struct _model
struct _part1d_zero
struct initialize_cb_data
Typedefs
typedef struct _model model_t
Functions
part1d_zero_t * part1d_zero_create (int min_partitions, int max_partitions, int ndatasets, double xmin, double xmax, double pd)
void part1d_zero_destroy (part1d_zero_t *p)
void part1d_zero_clone (const part1d_zero_t *src, part1d_zero_t *dst)
int part1d_zero_initialize (part1d_zero_t *p, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)
double part1d_zero_value_at (const part1d_zero_t *current, double x)
int part1d_zero_evaluate (const part1d_zero_t *current, int di, double xmin, double xmax, int nsamples, double *samples)
double part1d_zero_misfit (part1d_zero_t *p, const dataset1d_t **datasets, int ndatasets)
int part1d_zero_propose_birth (const part1d_zero_t *current, part1d_zero_t *proposed, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *birth_prob)
int part1d_zero_propose_death (const part1d_zero_t *current, part1d_zero_t *proposed, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *death_prob)
int part1d_zero_propose_value (const part1d_zero_t *current, part1d_zero_t *proposed, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *value_prob)
int part1d_zero_propose_move (const part1d_zero_t *current, part1d_zero_t *proposed, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *move_prob)
int part1d_zero_propose_lambda (const part1d_zero_t *current, part1d_zero_t *proposed, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *lambda_prob)
int part1d_zero_partitions (const part1d_zero_t *current)
double part1d_zero_lambda (const part1d_zero_t *current, int di)
double part1d_zero_partition_position (const part1d_zero_t *current, int pi)
Typedef Documentation
typedef struct _model model_t
Function Documentation
void part1d_zero_clone (const part1d_zero_t * src, part1d_zero_t * dst)
References _part1d_zero::max_partitions, _part1d_zero::models, _part1d_zero::ndatasets, _part1d_zero::npartitions, _part1d_zero::p, position_map1d_clone(), RJMCMC_CONDITIONCHECKVOID, and RJMCMC_NULLCHECKVOID.
Referenced by part1d_zero_propose_birth(), part1d_zero_propose_death(), part1d_zero_propose_lambda(), part1d_zero_propose_move(), part1d_zero_propose_value(), and part1d_zero_regression().
part1d_zero_t* part1d_zero_create (int min_partitions, int max_partitions, int ndatasets, double xmin, double xmax, double pd)
References _part1d_zero::max_partitions, _part1d_zero::min_partitions, _part1d_zero::models, _part1d_zero::ndatasets, _part1d_zero::npartitions, _part1d_zero::p, _part1d_zero::pd, position_map1d_create(), _part1d_zero::xmax, and _part1d_zero::xmin.
Referenced by part1d_zero_regression().
void part1d_zero_destroy (part1d_zero_t * p)
References _part1d_zero::max_partitions, _part1d_zero::models, _part1d_zero::ndatasets, _part1d_zero::p, and position_map1d_destroy().
Referenced by part1d_zero_regression().
int part1d_zero_evaluate (const part1d_zero_t * current, int di, double xmin, double xmax, int nsamples, double * samples)
Referenced by part1d_zero_regression().
int part1d_zero_initialize (part1d_zero_t * p, const dataset1d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)
References initialize_cb_data::datasets, _model::lambda, _part1d_zero::models, initialize_cb_data::ndatasets, normal, initialize_cb_data::normal, _part1d_zero::npartitions, _part1d_zero::p, initialize_cb_data::p, position_map1d_insert(), position_map1d_traverse_intervals(), random, initialize_cb_data::random, rjmcmc_random_choose_double(), x, _part1d_zero::xmax, and _part1d_zero::xmin.
Referenced by part1d_zero_regression().
double part1d_zero_lambda (const part1d_zero_t * current, int di)
References _model::lambda, and _part1d_zero::models.
Referenced by part1d_zero_regression().
double part1d_zero_misfit (part1d_zero_t * p, const dataset1d_t ** datasets, int ndatasets)
References _model::lambda, _dataset1d::lambdastd, _part1d_zero::models, _point1d::n, initialize_cb_data::ndatasets, _dataset1d::npoints, _dataset1d::points, _point1d::x, _point1d::y, and y.
Referenced by part1d_zero_regression().
double part1d_zero_partition_position (const part1d_zero_t * current, int pi)
References _part1d_zero::p, and position_map1d_position_of_index().
Referenced by part1d_zero_regression().
int part1d_zero_partitions (const part1d_zero_t * current)
References _part1d_zero::npartitions.
Referenced by part1d_zero_regression().
int part1d_zero_propose_birth (const part1d_zero_t * current, part1d_zero_t * proposed, const dataset1d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * birth_prob)
References _model::a, dataset1d_mean_variance(), dataset1d_range(), _part1d_zero::max_partitions, _model::mean, _part1d_zero::models, initialize_cb_data::ndatasets, normal, _part1d_zero::npartitions, _part1d_zero::p, part1d_zero_clone(), position_map1d_insert(), position_map1d_next_position(), position_map1d_position_of_index(), position_map1d_predecessor_of_index(), random, rjmcmc_error(), rjmcmc_gaussian_probability(), rjmcmc_random_choose_double(), _model::var, _part1d_zero::xmax, _part1d_zero::xmin, _dataset1d::ymax, and _dataset1d::ymin.
Referenced by part1d_zero_regression().
int part1d_zero_propose_death (const part1d_zero_t * current, part1d_zero_t * proposed, const dataset1d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * death_prob)
References _model::a, dataset1d_mean_variance(), dataset1d_range(), _part1d_zero::max_partitions, _model::mean, _part1d_zero::min_partitions, _part1d_zero::models, _part1d_zero::ndatasets, initialize_cb_data::ndatasets, normal, _part1d_zero::npartitions, _part1d_zero::p, part1d_zero_clone(), position_map1d_delete(), position_map1d_position_of_index(), position_map1d_predecessor_of_index(), position_map1d_predecessor_of_point(), position_map1d_successor_of_point(), rjmcmc_error(), rjmcmc_gaussian_probability(), rjmcmc_random_choose_double(), rjmcmc_random_choose_int(), _model::var, _dataset1d::ymax, and _dataset1d::ymin.
Referenced by part1d_zero_regression().
int part1d_zero_propose_lambda (const part1d_zero_t * current, part1d_zero_t * proposed, const dataset1d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * lambda_prob)
References _model::a, _model::lambda, _dataset1d::lambdamax, _dataset1d::lambdastd, _model::mean, _part1d_zero::models, initialize_cb_data::ndatasets, normal, _dataset1d::npoints, part1d_zero_clone(), rjmcmc_create_array_1d(), rjmcmc_destroy_array_1d(), RJMCMC_NULLCHECKVOID, rjmcmc_random_choose_int(), and _model::var.
Referenced by part1d_zero_regression().
int part1d_zero_propose_move (const part1d_zero_t * current, part1d_zero_t * proposed, const dataset1d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * move_prob)
References _model::a, dataset1d_mean_variance(), dataset1d_range(), _model::mean, _part1d_zero::models, initialize_cb_data::ndatasets, normal, _part1d_zero::npartitions, _part1d_zero::p, part1d_zero_clone(), _part1d_zero::pd, position_map1d_move(), position_map1d_position_of_index(), position_map1d_predecessor_of_index(), position_map1d_successor_of_index(), rjmcmc_error(), rjmcmc_gaussian_probability(), rjmcmc_random_choose_double(), rjmcmc_random_choose_int(), _model::var, _part1d_zero::xmax, _dataset1d::ymax, and _dataset1d::ymin.
Referenced by part1d_zero_regression().
int part1d_zero_propose_value (const part1d_zero_t * current, part1d_zero_t * proposed, const dataset1d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * value_prob)
References _model::a, _model::mean, _part1d_zero::models, normal, _part1d_zero::npartitions, part1d_zero_clone(), rjmcmc_gaussian_probability(), rjmcmc_random_choose_double(), rjmcmc_random_choose_int(), _model::var, _dataset1d::ymax, and _dataset1d::ymin.
Referenced by part1d_zero_regression().
double part1d_zero_value_at (const part1d_zero_t * current, double x)
References _model::a, _part1d_zero::models, _part1d_zero::p, position_map1d_predecessor_of_index(), position_map1d_predecessor_of_point(), rjmcmc_error(), and x.