part2d_forwardmodel.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <math.h>
*
#include `rjmcmc/part2d_forwardmodel.h`
*
#include `rjmcmc/position_map2d.h`
*
#include `rjmcmc/rjmcmc_util.h`
*
#include `rjmcmc/rjmcmc_defines.h`
*
Data Structures
struct _model
struct _part2d_forwardmodel
Typedefs
typedef struct _model model_t
Functions
part2d_forwardmodel_t * part2d_forwardmodel_create (part2d_fm_type_t type, int min_partitions, int max_partitions, double xmin, double xmax, double ymin, double ymax, double pdx, double pdy, int nglobalparameters, int nlocalparameters, int nhierarchicalparameters, int include_corners)
void part2d_forwardmodel_destroy (part2d_forwardmodel_t *p)
int part2d_forwardmodel_save (const part2d_forwardmodel_t *p, const char *filename)
part2d_forwardmodel_t * part2d_forwardmodel_load (const char *filename)
void part2d_forwardmodel_clone (const part2d_forwardmodel_t *src, part2d_forwardmodel_t *dst)
int part2d_forwardmodel_initialize (part2d_forwardmodel_t *p, const forwardmodelparameter_t *global_parameters, int nglobalparameters, const forwardmodelparameter_t *local_parameters, int nlocalparameters, const forwardmodelparameter_t *hierarchical_parameters, int nhierarchicalparameters, int initial_partitions, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)
int part2d_forwardmodel_value_at (const part2d_forwardmodel_t *current, double x, double y, int nlocalparameters, double *localparameters)
int part2d_forwardmodel_gradient_at (const part2d_forwardmodel_t *current, double x, double y, int nlocalparameters, double *localparameters)
int part2d_forwardmodel_propose_birth (const part2d_forwardmodel_t *current, part2d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, rjmcmc_uniform_rand_t uniform, rjmcmc_normal_rand_t normal, bbox2d_t *bound, double *birth_prob)
int part2d_forwardmodel_propose_death (const part2d_forwardmodel_t *current, part2d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, bbox2d_t *bound, double *death_prob)
int part2d_forwardmodel_propose_local_value (const part2d_forwardmodel_t *current, part2d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, bbox2d_t *bound, double *value_prob)
int part2d_forwardmodel_propose_global_value (const part2d_forwardmodel_t *current, part2d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *value_prob)
int part2d_forwardmodel_propose_move (const part2d_forwardmodel_t *current, part2d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, bbox2d_t *bound, double *move_prob)
int part2d_forwardmodel_propose_hierarchical (const part2d_forwardmodel_t *current, part2d_forwardmodel_t *proposed, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *hierarchical_prob)
int part2d_forwardmodel_partitions (const part2d_forwardmodel_t *current)
const double * part2d_forwardmodel_global_parameters (const part2d_forwardmodel_t *current)
const double * part2d_forwardmodel_hierarchical_parameters (const part2d_forwardmodel_t *current)
int part2d_forwardmodel_evaluate_local_parameters (const part2d_forwardmodel_t *c, int xsamples, const double *x, int ysamples, const double *y, int nlocalparameters, double ***local_parameters)
int part2d_forwardmodel_partition_centre (const part2d_forwardmodel_t *c, int pi, double *x, double *y)
part2d_fm_type_t part2d_forwardmodel_type (const part2d_forwardmodel_t *p)
int part2d_forwardmodel_min_partitions (const part2d_forwardmodel_t *p)
int part2d_forwardmodel_max_partitions (const part2d_forwardmodel_t *p)
double part2d_forwardmodel_pdx (const part2d_forwardmodel_t *p)
double part2d_forwardmodel_pdy (const part2d_forwardmodel_t *p)
int part2d_forwardmodel_addpoint (part2d_forwardmodel_t *c, double x, double y, int nlocalparameters, const double *parameters, bbox2d_t *bound)
int part2d_forwardmodel_delpoint (part2d_forwardmodel_t *c, int pi, bbox2d_t *bound)
int part2d_forwardmodel_movepoint (part2d_forwardmodel_t *c, int pi, double new_x, double new_y, bbox2d_t *bound)
Typedef Documentation
typedef struct _model model_t
Function Documentation
int part2d_forwardmodel_addpoint (part2d_forwardmodel_t * c, double x, double y, int nlocalparameters, const double * parameters, bbox2d_t * bound)
References _model::local_parameter, _part2d_forwardmodel::models, _part2d_forwardmodel::npartitions, _part2d_forwardmodel::p, position_map2d_insert(), and rjmcmc_error().
Referenced by part2d_forwardmodel_propose_birth().
void part2d_forwardmodel_clone (const part2d_forwardmodel_t * src, part2d_forwardmodel_t * dst)
References _part2d_forwardmodel::global_parameter, _part2d_forwardmodel::hierarchical_parameter, _part2d_forwardmodel::max_partitions, _part2d_forwardmodel::models, _part2d_forwardmodel::nglobalparameters, _part2d_forwardmodel::nhierarchicalparameters, _part2d_forwardmodel::nlocalparameters, _part2d_forwardmodel::npartitions, _part2d_forwardmodel::p, position_map2d_clone(), RJMCMC_CONDITIONCHECKVOID, RJMCMC_NULLCHECKVOID, and _part2d_forwardmodel::type.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), MPI_part2d_forwardmodel_hierarchical_restartable(), part2d_forwardmodel_propose_birth(), part2d_forwardmodel_propose_death(), part2d_forwardmodel_propose_global_value(), part2d_forwardmodel_propose_hierarchical(), part2d_forwardmodel_propose_local_value(), and part2d_forwardmodel_propose_move().
part2d_forwardmodel_t* part2d_forwardmodel_create (part2d_fm_type_t type, int min_partitions, int max_partitions, double xmin, double xmax, double ymin, double ymax, double pdx, double pdy, int nglobalparameters, int nlocalparameters, int nhierarchicalparameters, int include_corners)
References _part2d_forwardmodel::global_parameter, _part2d_forwardmodel::hierarchical_parameter, _part2d_forwardmodel::include_corners, _part2d_forwardmodel::max_partitions, _part2d_forwardmodel::min_partitions, _part2d_forwardmodel::model_gradients, _part2d_forwardmodel::models, _part2d_forwardmodel::nglobalparameters, _part2d_forwardmodel::nhierarchicalparameters, _part2d_forwardmodel::nlocalparameters, _part2d_forwardmodel::npartitions, _part2d_forwardmodel::p, PART2D_FM_MONOTONE_CUBIC, _part2d_forwardmodel::pdx, _part2d_forwardmodel::pdy, position_map2d_create(), rjmcmc_create_array_1d(), _part2d_forwardmodel::t_lp, _part2d_forwardmodel::type, _part2d_forwardmodel::xmax, _part2d_forwardmodel::xmin, _part2d_forwardmodel::ymax, and _part2d_forwardmodel::ymin.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), MPI_part2d_forwardmodel_hierarchical(), MPI_part2d_forwardmodel_hierarchical_restartable(), part2d_forwardmodel_hierarchical(), part2d_forwardmodel_load(), and part2d_forwardmodel_restartable().
int part2d_forwardmodel_delpoint (part2d_forwardmodel_t * c, int pi, bbox2d_t * bound)
References _part2d_forwardmodel::max_partitions, _part2d_forwardmodel::models, _part2d_forwardmodel::nlocalparameters, _part2d_forwardmodel::npartitions, _part2d_forwardmodel::p, position_map2d_delete(), and rjmcmc_error().
Referenced by part2d_forwardmodel_propose_death().
void part2d_forwardmodel_destroy (part2d_forwardmodel_t * p)
References _part2d_forwardmodel::global_parameter, _part2d_forwardmodel::hierarchical_parameter, _part2d_forwardmodel::max_partitions, _part2d_forwardmodel::model_gradients, _part2d_forwardmodel::models, _part2d_forwardmodel::nlocalparameters, _part2d_forwardmodel::p, position_map2d_destroy(), rjmcmc_destroy_array_1d(), and _part2d_forwardmodel::t_lp.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), MPI_part2d_forwardmodel_hierarchical(), MPI_part2d_forwardmodel_hierarchical_restartable(), part2d_forwardmodel_hierarchical(), and part2d_forwardmodel_restartable().
int part2d_forwardmodel_evaluate_local_parameters (const part2d_forwardmodel_t * c, int xsamples, const double * x, int ysamples, const double * y, int nlocalparameters, double *** local_parameters)
References _model::local_parameter, _part2d_forwardmodel::models, _part2d_forwardmodel::p, PART2D_FM_ZERO, position_map2d_nearest(), rjmcmc_error(), and _part2d_forwardmodel::type.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), and MPI_part2d_forwardmodel_hierarchical_restartable().
const double* part2d_forwardmodel_global_parameters (const part2d_forwardmodel_t * current)
References _part2d_forwardmodel::global_parameter.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), and MPI_part2d_forwardmodel_hierarchical_restartable().
int part2d_forwardmodel_gradient_at (const part2d_forwardmodel_t * current, double x, double y, int nlocalparameters, double * localparameters)
const double* part2d_forwardmodel_hierarchical_parameters (const part2d_forwardmodel_t * current)
References _part2d_forwardmodel::hierarchical_parameter.
Referenced by MPI_part2d_forwardmodel_hierarchical_restartable().
[part2d_forwardmodel_initialize(part2d_forwardmodel_t *p, const forwardmodelparameter_t *global_parameters, int nglobalparameters, const forwardmodelparameter_t *local_parameters, int nlocalparameters, const forwardmodelparameter_t *hierarchical_parameters, int nhierarchicalparameters, int initial_partitions, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)]int part2d_forwardmodel_initialize (part2d_forwardmodel_t * p, const forwardmodelparameter_t * global_parameters, int nglobalparameters, const forwardmodelparameter_t * local_parameters, int nlocalparameters, const forwardmodelparameter_t * hierarchical_parameters, int nhierarchicalparameters, int initial_partitions, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)
References _part2d_forwardmodel::global_parameter, _part2d_forwardmodel::hierarchical_parameter, _model::local_parameter, _part2d_forwardmodel::max_partitions, _part2d_forwardmodel::min_partitions, _part2d_forwardmodel::models, _part2d_forwardmodel::nglobalparameters, _part2d_forwardmodel::nhierarchicalparameters, _part2d_forwardmodel::nlocalparameters, _part2d_forwardmodel::npartitions, _part2d_forwardmodel::p, position_map2d_insert(), RJMCMC_CONDITIONCHECKINT, rjmcmc_random_choose_double(), x, _part2d_forwardmodel::xmax, _part2d_forwardmodel::xmin, y, _part2d_forwardmodel::ymax, and _part2d_forwardmodel::ymin.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), and MPI_part2d_forwardmodel_hierarchical_restartable().
part2d_forwardmodel_t* part2d_forwardmodel_load (const char * filename)
References _part2d_forwardmodel::global_parameter, _part2d_forwardmodel::hierarchical_parameter, _model::local_parameter, _part2d_forwardmodel::model_gradients, _part2d_forwardmodel::models, _part2d_forwardmodel::nglobalparameters, _part2d_forwardmodel::nhierarchicalparameters, _part2d_forwardmodel::nlocalparameters, _part2d_forwardmodel::npartitions, _part2d_forwardmodel::p, PART2D_FM_MONOTONE_CUBIC, part2d_forwardmodel_create(), position_map2d_insert(), RJMCMC_INTCHECKPTR, _part2d_forwardmodel::type, x, and y.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), MPI_part2d_forwardmodel_hierarchical_restartable(), and part2d_forwardmodel_restartable().
int part2d_forwardmodel_max_partitions (const part2d_forwardmodel_t * p)
References _part2d_forwardmodel::max_partitions.
int part2d_forwardmodel_min_partitions (const part2d_forwardmodel_t * p)
References _part2d_forwardmodel::min_partitions.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart().
int part2d_forwardmodel_movepoint (part2d_forwardmodel_t * c, int pi, double new_x, double new_y, bbox2d_t * bound)
References _part2d_forwardmodel::p, position_map2d_move(), and rjmcmc_error().
Referenced by part2d_forwardmodel_propose_move().
int part2d_forwardmodel_partition_centre (const part2d_forwardmodel_t * c, int pi, double * x, double * y)
References _part2d_forwardmodel::p, and position_map2d_position_of_index().
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), and MPI_part2d_forwardmodel_hierarchical_restartable().
int part2d_forwardmodel_partitions (const part2d_forwardmodel_t * current)
References _part2d_forwardmodel::npartitions.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), and MPI_part2d_forwardmodel_hierarchical_restartable().
double part2d_forwardmodel_pdx (const part2d_forwardmodel_t * p)
References _part2d_forwardmodel::pdx.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart().
double part2d_forwardmodel_pdy (const part2d_forwardmodel_t * p)
References _part2d_forwardmodel::pdy.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart().
[part2d_forwardmodel_propose_birth(const part2d_forwardmodel_t *current, part2d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, rjmcmc_uniform_rand_t uniform, rjmcmc_normal_rand_t normal, bbox2d_t *bound, double *birth_prob)]int part2d_forwardmodel_propose_birth (const part2d_forwardmodel_t * current, part2d_forwardmodel_t * proposed, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, rjmcmc_uniform_rand_t uniform, rjmcmc_normal_rand_t normal, bbox2d_t * bound, double * birth_prob)
References _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _forwardmodelparameter::fstd_bd, _model::local_parameter, _part2d_forwardmodel::max_partitions, _part2d_forwardmodel::models, _part2d_forwardmodel::nlocalparameters, normal, _part2d_forwardmodel::npartitions, _part2d_forwardmodel::p, part2d_forwardmodel_addpoint(), part2d_forwardmodel_clone(), position_map2d_nearest(), rjmcmc_error(), rjmcmc_gaussian_probability(), rjmcmc_random_choose_double(), _part2d_forwardmodel::t_lp, _part2d_forwardmodel::xmax, _part2d_forwardmodel::xmin, _part2d_forwardmodel::ymax, and _part2d_forwardmodel::ymin.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), and MPI_part2d_forwardmodel_hierarchical_restartable().
[part2d_forwardmodel_propose_death(const part2d_forwardmodel_t *current, part2d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, bbox2d_t *bound, double *death_prob)]int part2d_forwardmodel_propose_death (const part2d_forwardmodel_t * current, part2d_forwardmodel_t * proposed, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, bbox2d_t * bound, double * death_prob)
References _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _model::local_parameter, _part2d_forwardmodel::min_partitions, _part2d_forwardmodel::models, _part2d_forwardmodel::nlocalparameters, _part2d_forwardmodel::npartitions, _part2d_forwardmodel::p, part2d_forwardmodel_clone(), part2d_forwardmodel_delpoint(), position_map2d_nearest(), position_map2d_position_of_index(), rjmcmc_error(), rjmcmc_gaussian_probability(), and rjmcmc_random_choose_int().
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), and MPI_part2d_forwardmodel_hierarchical_restartable().
[part2d_forwardmodel_propose_global_value(const part2d_forwardmodel_t *current, part2d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *value_prob)]int part2d_forwardmodel_propose_global_value (const part2d_forwardmodel_t * current, part2d_forwardmodel_t * proposed, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * value_prob)
References _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _forwardmodelparameter::fstd_value, _part2d_forwardmodel::global_parameter, normal, part2d_forwardmodel_clone(), and rjmcmc_random_choose_int().
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), and MPI_part2d_forwardmodel_hierarchical_restartable().
[part2d_forwardmodel_propose_hierarchical(const part2d_forwardmodel_t *current, part2d_forwardmodel_t *proposed, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *hierarchical_prob)]int part2d_forwardmodel_propose_hierarchical (const part2d_forwardmodel_t * current, part2d_forwardmodel_t * proposed, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * hierarchical_prob)
References _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _forwardmodelparameter::fstd_value, _part2d_forwardmodel::hierarchical_parameter, _model::local_parameter, normal, part2d_forwardmodel_clone(), rjmcmc_create_array_1d(), rjmcmc_destroy_array_1d(), RJMCMC_NULLCHECKVOID, and rjmcmc_random_choose_int().
Referenced by MPI_part2d_forwardmodel_hierarchical_restartable().
[part2d_forwardmodel_propose_local_value(const part2d_forwardmodel_t *current, part2d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, bbox2d_t *bound, double *value_prob)]int part2d_forwardmodel_propose_local_value (const part2d_forwardmodel_t * current, part2d_forwardmodel_t * proposed, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, bbox2d_t * bound, double * value_prob)
References _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _forwardmodelparameter::fstd_value, _model::local_parameter, _part2d_forwardmodel::models, normal, _part2d_forwardmodel::npartitions, part2d_forwardmodel_clone(), and rjmcmc_random_choose_int().
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), and MPI_part2d_forwardmodel_hierarchical_restartable().
[part2d_forwardmodel_propose_move(const part2d_forwardmodel_t *current, part2d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, bbox2d_t *bound, double *move_prob)]int part2d_forwardmodel_propose_move (const part2d_forwardmodel_t * current, part2d_forwardmodel_t * proposed, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, bbox2d_t * bound, double * move_prob)
References normal, _part2d_forwardmodel::npartitions, _part2d_forwardmodel::p, part2d_forwardmodel_clone(), part2d_forwardmodel_movepoint(), _part2d_forwardmodel::pdx, _part2d_forwardmodel::pdy, position_map2d_position_of_index(), rjmcmc_error(), rjmcmc_random_choose_int(), _part2d_forwardmodel::xmax, and _part2d_forwardmodel::ymax.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), and MPI_part2d_forwardmodel_hierarchical_restartable().
int part2d_forwardmodel_save (const part2d_forwardmodel_t * p, const char * filename)
References _part2d_forwardmodel::global_parameter, _part2d_forwardmodel::hierarchical_parameter, _part2d_forwardmodel::include_corners, _model::local_parameter, _part2d_forwardmodel::max_partitions, _part2d_forwardmodel::min_partitions, _part2d_forwardmodel::model_gradients, _part2d_forwardmodel::models, _part2d_forwardmodel::nglobalparameters, _part2d_forwardmodel::nhierarchicalparameters, _part2d_forwardmodel::nlocalparameters, _part2d_forwardmodel::npartitions, _part2d_forwardmodel::p, PART2D_FM_MONOTONE_CUBIC, _part2d_forwardmodel::pdx, _part2d_forwardmodel::pdy, position_map2d_position_of_index(), RJMCMC_INTCHECKINT, RJMCMC_NULLCHECKINT, _part2d_forwardmodel::type, x, _part2d_forwardmodel::xmax, _part2d_forwardmodel::xmin, y, _part2d_forwardmodel::ymax, and _part2d_forwardmodel::ymin.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), MPI_part2d_forwardmodel_hierarchical_restartable(), and part2d_forwardmodel_restartable().
part2d_fm_type_t part2d_forwardmodel_type (const part2d_forwardmodel_t * p)
References _part2d_forwardmodel::type.
int part2d_forwardmodel_value_at (const part2d_forwardmodel_t * current, double x, double y, int nlocalparameters, double * localparameters)
References _model::local_parameter, _part2d_forwardmodel::models, _part2d_forwardmodel::nlocalparameters, _part2d_forwardmodel::p, position_map2d_nearest(), RJMCMC_CONDITIONCHECKINT, RJMCMC_NULLCHECKINT, _part2d_forwardmodel::xmax, _part2d_forwardmodel::xmin, _part2d_forwardmodel::ymax, and _part2d_forwardmodel::ymin.