part1d_natural_rj.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <math.h>
*
#include <float.h>
*
#include `rjmcmc/part1d_natural_rj.h`
*
#include `rjmcmc/position_map1d.h`
*
#include `rjmcmc/rjmcmc_util.h`
*
#include `rjmcmc/rjmcmc_defines.h`
*
Data Structures
struct _model
struct _part1d_natural_rj
Typedefs
typedef struct _model model_t
Functions
part1d_natural_rj_t * part1d_natural_rj_create (int min_partitions, int max_partitions, int ndatasets, double xmin, double xmax, double pv, double pd)
void part1d_natural_rj_destroy (part1d_natural_rj_t *p)
void part1d_natural_rj_clone (const part1d_natural_rj_t *src, part1d_natural_rj_t *dst)
int part1d_natural_rj_initialize (part1d_natural_rj_t *p, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)
double part1d_natural_rj_value_at (const part1d_natural_rj_t *current, double x)
int part1d_natural_rj_evaluate (const part1d_natural_rj_t *current, int di, double xmin, double xmax, int nsamples, double *samples)
int part1d_natural_rj_evaluate_gradient (const part1d_natural_rj_t *current, int di, double xmin, double xmax, int nsamples, double *samples)
double part1d_natural_rj_misfit (part1d_natural_rj_t *p, const dataset1d_t **datasets, int ndatasets)
int part1d_natural_rj_propose_birth (const part1d_natural_rj_t *current, part1d_natural_rj_t *proposed, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *birth_prob)
int part1d_natural_rj_propose_death (const part1d_natural_rj_t *current, part1d_natural_rj_t *proposed, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *death_prob)
int part1d_natural_rj_propose_value (const part1d_natural_rj_t *current, part1d_natural_rj_t *proposed, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *value_prob)
int part1d_natural_rj_propose_lambda (const part1d_natural_rj_t *current, part1d_natural_rj_t *proposed, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *lambda_prob)
int part1d_natural_rj_propose_move (const part1d_natural_rj_t *current, part1d_natural_rj_t *proposed, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *move_prob)
int part1d_natural_rj_partitions (const part1d_natural_rj_t *current)
double part1d_natural_rj_lambda (const part1d_natural_rj_t *current, int di)
double part1d_natural_rj_partition_position (const part1d_natural_rj_t *current, int pi)
Typedef Documentation
typedef struct _model model_t
Function Documentation
void part1d_natural_rj_clone (const part1d_natural_rj_t * src, part1d_natural_rj_t * dst)
References _part1d_natural_rj::max_partitions, _part1d_natural_rj::models, _part1d_natural_rj::ndatasets, _part1d_natural_rj::npartitions, _part1d_natural_rj::p, position_map1d_clone(), RJMCMC_CONDITIONCHECKVOID, and RJMCMC_NULLCHECKVOID.
Referenced by part1d_natural_regression(), part1d_natural_rj_propose_birth(), part1d_natural_rj_propose_death(), part1d_natural_rj_propose_lambda(), part1d_natural_rj_propose_move(), and part1d_natural_rj_propose_value().
part1d_natural_rj_t* part1d_natural_rj_create (int min_partitions, int max_partitions, int ndatasets, double xmin, double xmax, double pv, double pd)
References _part1d_natural_rj::max_partitions, _part1d_natural_rj::min_partitions, _part1d_natural_rj::models, _part1d_natural_rj::ndatasets, _part1d_natural_rj::npartitions, _part1d_natural_rj::p, _part1d_natural_rj::pd, position_map1d_create(), _part1d_natural_rj::pv, _part1d_natural_rj::xmax, and _part1d_natural_rj::xmin.
Referenced by part1d_natural_regression().
void part1d_natural_rj_destroy (part1d_natural_rj_t * p)
References _part1d_natural_rj::max_partitions, _part1d_natural_rj::models, _part1d_natural_rj::ndatasets, _part1d_natural_rj::p, and position_map1d_destroy().
int part1d_natural_rj_evaluate (const part1d_natural_rj_t * current, int di, double xmin, double xmax, int nsamples, double * samples)
Referenced by part1d_natural_regression().
int part1d_natural_rj_evaluate_gradient (const part1d_natural_rj_t * current, int di, double xmin, double xmax, int nsamples, double * samples)
Referenced by part1d_natural_regression().
int part1d_natural_rj_initialize (part1d_natural_rj_t * p, const dataset1d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)
References _model::a, _model::lambda, _dataset1d::lambdamax, _dataset1d::lambdamin, _part1d_natural_rj::models, _part1d_natural_rj::npartitions, _part1d_natural_rj::p, position_map1d_insert(), random, rjmcmc_random_choose_double(), x, _part1d_natural_rj::xmax, _part1d_natural_rj::xmin, _dataset1d::ymax, and _dataset1d::ymin.
Referenced by part1d_natural_regression().
double part1d_natural_rj_lambda (const part1d_natural_rj_t * current, int di)
References _model::lambda, and _part1d_natural_rj::models.
Referenced by part1d_natural_regression().
double part1d_natural_rj_misfit (part1d_natural_rj_t * p, const dataset1d_t ** datasets, int ndatasets)
References _model::lambda, _dataset1d::lambdastd, _part1d_natural_rj::models, _point1d::n, _dataset1d::npoints, _dataset1d::points, _point1d::x, _point1d::y, and y.
Referenced by part1d_natural_regression().
double part1d_natural_rj_partition_position (const part1d_natural_rj_t * current, int pi)
References _part1d_natural_rj::p, and position_map1d_position_of_index().
Referenced by part1d_natural_regression().
int part1d_natural_rj_partitions (const part1d_natural_rj_t * current)
References _part1d_natural_rj::npartitions.
Referenced by part1d_natural_regression().
int part1d_natural_rj_propose_birth (const part1d_natural_rj_t * current, part1d_natural_rj_t * proposed, const dataset1d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * birth_prob)
References _model::a, _part1d_natural_rj::max_partitions, _part1d_natural_rj::models, _part1d_natural_rj::npartitions, _part1d_natural_rj::p, part1d_natural_rj_clone(), position_map1d_insert(), position_map1d_next_position(), random, rjmcmc_error(), _part1d_natural_rj::xmax, _part1d_natural_rj::xmin, _dataset1d::ymax, and _dataset1d::ymin.
Referenced by part1d_natural_regression().
int part1d_natural_rj_propose_death (const part1d_natural_rj_t * current, part1d_natural_rj_t * proposed, const dataset1d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * death_prob)
References _part1d_natural_rj::max_partitions, _part1d_natural_rj::min_partitions, _part1d_natural_rj::models, _part1d_natural_rj::ndatasets, _part1d_natural_rj::npartitions, _part1d_natural_rj::p, part1d_natural_rj_clone(), position_map1d_delete(), position_map1d_position_of_index(), position_map1d_predecessor_of_point(), random, and rjmcmc_error().
Referenced by part1d_natural_regression().
int part1d_natural_rj_propose_lambda (const part1d_natural_rj_t * current, part1d_natural_rj_t * proposed, const dataset1d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * lambda_prob)
References _model::lambda, _dataset1d::lambdamax, _dataset1d::lambdastd, _part1d_natural_rj::models, normal, _dataset1d::npoints, part1d_natural_rj_clone(), and random.
Referenced by part1d_natural_regression().
int part1d_natural_rj_propose_move (const part1d_natural_rj_t * current, part1d_natural_rj_t * proposed, const dataset1d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * move_prob)
References _model::a, _model::lambda, normal, _part1d_natural_rj::npartitions, _part1d_natural_rj::p, part1d_natural_rj_clone(), _part1d_natural_rj::pd, position_map1d_move(), position_map1d_position_of_index(), rjmcmc_create_array_1d(), rjmcmc_destroy_array_1d(), rjmcmc_error(), RJMCMC_NULLCHECKVOID, rjmcmc_random_choose_int(), and _part1d_natural_rj::xmax.
Referenced by part1d_natural_regression().
int part1d_natural_rj_propose_value (const part1d_natural_rj_t * current, part1d_natural_rj_t * proposed, const dataset1d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * value_prob)
References _model::a, _part1d_natural_rj::models, normal, _part1d_natural_rj::npartitions, part1d_natural_rj_clone(), _part1d_natural_rj::pv, rjmcmc_random_choose_int(), _dataset1d::ymax, and _dataset1d::ymin.
Referenced by part1d_natural_regression().
double part1d_natural_rj_value_at (const part1d_natural_rj_t * current, double x)
References _model::a, _part1d_natural_rj::models, _part1d_natural_rj::p, position_map1d_next_index(), position_map1d_position_of_index(), position_map1d_predecessor_of_index(), position_map1d_predecessor_of_point(), and x.