part1d_forwardmodel.h File Reference
#include <rjmcmc/forwardmodelparameter.h>
*
#include <rjmcmc/rjmcmc_random.h>
*
Typedefs
typedef struct _part1d_forwardmodel part1d_forwardmodel_t
Enumerations
enum part1d_fm_type_t { PART1D_FM_ZERO,
PART1D_FM_NATURAL,
PART1D_FM_ZERO_CUBIC
 }
Functions
part1d_forwardmodel_t * part1d_forwardmodel_create (part1d_fm_type_t type, int min_part, int max_part, double xmin, double xmax, double pd, int nglobalparameters, int nlocalparameters, int nhierarchicalparameters)
void part1d_forwardmodel_destroy (part1d_forwardmodel_t *p)
void part1d_forwardmodel_clone (const part1d_forwardmodel_t *src, part1d_forwardmodel_t *dst)
int part1d_forwardmodel_value_at (const part1d_forwardmodel_t *current, double x, int nlocalparameters, double *localparameters)
int part1d_forwardmodel_gradient_at (const part1d_forwardmodel_t *current, double x, int nlocalparameters, double *localparameters)
int part1d_forwardmodel_initialize_fixed (part1d_forwardmodel_t *p, const double *global_parameters, const double *hierarchical_parameters, int npartitions, const double *partition_x, const double **local_parameters)
int part1d_forwardmodel_initialize (part1d_forwardmodel_t *p, const forwardmodelparameter_t *global_parameters, int nglobalparameters, const forwardmodelparameter_t *local_parameters, int nlocalparameters, const forwardmodelparameter_t *hierarchical_parameters, int nhierarchicalparameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)
int part1d_forwardmodel_propose_birth (const part1d_forwardmodel_t *current, part1d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameter, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *birth_prob)
int part1d_forwardmodel_propose_death (const part1d_forwardmodel_t *current, part1d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameter, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *death_prob)
int part1d_forwardmodel_propose_local_value (const part1d_forwardmodel_t *current, part1d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *value_prob, int *li)
int part1d_forwardmodel_propose_global_value (const part1d_forwardmodel_t *current, part1d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *value_prob)
int part1d_forwardmodel_propose_move (const part1d_forwardmodel_t *current, part1d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *move_prob)
int part1d_forwardmodel_propose_hierarchical (const part1d_forwardmodel_t *current, part1d_forwardmodel_t *proposed, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *hierarchical_prob)
int part1d_forwardmodel_partitions (const part1d_forwardmodel_t *current)
double part1d_forwardmodel_partition_position (const part1d_forwardmodel_t *current, int pi)
int part1d_forwardmodel_partition_fill_list (const part1d_forwardmodel_t *current, double *positions, int *npartitions)
const double * part1d_forwardmodel_global_parameters (const part1d_forwardmodel_t *current)
const double * part1d_forwardmodel_hierarchical_parameters (const part1d_forwardmodel_t *current)
int part1d_forwardmodel_evaluate_local_parameters (const part1d_forwardmodel_t *c, int xsamples, const double *x, double **local_parameters)
int part1d_forwardmodel_hierarchical_fill_list (const part1d_forwardmodel_t *current, double *hierarchical, int *nhierarchical)
Typedef Documentation
typedef struct _part1d_forwardmodel part1d_forwardmodel_t
Enumeration Type Documentation
enum part1d_fm_type_t
Enumerator
PART1D_FM_ZERO
PART1D_FM_NATURAL
PART1D_FM_ZERO_CUBIC
Function Documentation
void part1d_forwardmodel_clone (const part1d_forwardmodel_t * src, part1d_forwardmodel_t * dst)
References _part1d_forwardmodel::global_parameter, _part1d_forwardmodel::hierarchical_parameters, _part1d_forwardmodel::max_partitions, _part1d_forwardmodel::models, _part1d_forwardmodel::nglobalparameters, _part1d_forwardmodel::nhierarchicalparameters, _part1d_forwardmodel::nlocalparameters, _part1d_forwardmodel::npartitions, _part1d_forwardmodel::p, position_map1d_clone(), RJMCMC_CONDITIONCHECKVOID, RJMCMC_NULLCHECKVOID, and _part1d_forwardmodel::type.
Referenced by MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel_propose_birth(), part1d_forwardmodel_propose_death(), part1d_forwardmodel_propose_global_value(), part1d_forwardmodel_propose_hierarchical(), part1d_forwardmodel_propose_local_value(), and part1d_forwardmodel_propose_move().
part1d_forwardmodel_t* part1d_forwardmodel_create (part1d_fm_type_t type, int min_part, int max_part, double xmin, double xmax, double pd, int nglobalparameters, int nlocalparameters, int nhierarchicalparameters)
References _part1d_forwardmodel::global_parameter, _part1d_forwardmodel::hierarchical_parameters, _part1d_forwardmodel::local_scratch, _part1d_forwardmodel::max_partitions, _part1d_forwardmodel::min_partitions, _part1d_forwardmodel::model_gradients, _part1d_forwardmodel::models, _part1d_forwardmodel::nglobalparameters, _part1d_forwardmodel::nhierarchicalparameters, _part1d_forwardmodel::nlocalparameters, _part1d_forwardmodel::npartitions, _part1d_forwardmodel::p, PART1D_FM_ZERO_CUBIC, _part1d_forwardmodel::pd, position_map1d_create(), rjmcmc_create_array_1d(), rjmcmc_error(), _part1d_forwardmodel::type, _part1d_forwardmodel::xmax, and _part1d_forwardmodel::xmin.
Referenced by MPI_part1d_forwardmodel(), MPI_part1d_forwardmodel_hierarchical(), MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel(), part1d_forwardmodel_hierarchical(), part1d_forwardmodel_natural(), part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel_natural_hierarchical_init(), part1d_forwardmodel_natural_init(), and part1d_forwardmodel_zero_cubic().
void part1d_forwardmodel_destroy (part1d_forwardmodel_t * p)
References _part1d_forwardmodel::global_parameter, _part1d_forwardmodel::hierarchical_parameters, _part1d_forwardmodel::local_scratch, _part1d_forwardmodel::max_partitions, _part1d_forwardmodel::model_gradients, _part1d_forwardmodel::models, _part1d_forwardmodel::nlocalparameters, _part1d_forwardmodel::p, position_map1d_destroy(), and rjmcmc_destroy_array_1d().
Referenced by MPI_part1d_forwardmodel(), MPI_part1d_forwardmodel_hierarchical(), MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel(), part1d_forwardmodel_hierarchical(), part1d_forwardmodel_natural(), part1d_forwardmodel_natural_finish(), part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel_natural_hierarchical_finish(), and part1d_forwardmodel_zero_cubic().
int part1d_forwardmodel_evaluate_local_parameters (const part1d_forwardmodel_t * c, int xsamples, const double * x, double ** local_parameters)
References c, interval_data::current, interval_data::local_parameters, _part1d_forwardmodel::nlocalparameters, interval_data::nlocalparameters, _part1d_forwardmodel::p, PART1D_FM_NATURAL, PART1D_FM_ZERO, PART1D_FM_ZERO_CUBIC, position_map1d_traverse_intervals(), rjmcmc_error(), _part1d_forwardmodel::type, x, interval_data::x, interval_data::xi, and interval_data::xsamples.
Referenced by MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().
const double* part1d_forwardmodel_global_parameters (const part1d_forwardmodel_t * current)
References _part1d_forwardmodel::global_parameter.
Referenced by MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().
int part1d_forwardmodel_gradient_at (const part1d_forwardmodel_t * current, double x, int nlocalparameters, double * localparameters)
int part1d_forwardmodel_hierarchical_fill_list (const part1d_forwardmodel_t * current, double * hierarchical, int * nhierarchical)
References _part1d_forwardmodel::hierarchical_parameters, and _part1d_forwardmodel::nhierarchicalparameters.
const double* part1d_forwardmodel_hierarchical_parameters (const part1d_forwardmodel_t * current)
References _part1d_forwardmodel::hierarchical_parameters.
Referenced by MPI_part1d_forwardmodel_natural_hierarchical().
[part1d_forwardmodel_initialize(part1d_forwardmodel_t *p, const forwardmodelparameter_t *global_parameters, int nglobalparameters, const forwardmodelparameter_t *local_parameters, int nlocalparameters, const forwardmodelparameter_t *hierarchical_parameters, int nhierarchicalparameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)]int part1d_forwardmodel_initialize (part1d_forwardmodel_t * p, const forwardmodelparameter_t * global_parameters, int nglobalparameters, const forwardmodelparameter_t * local_parameters, int nlocalparameters, const forwardmodelparameter_t * hierarchical_parameters, int nhierarchicalparameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)
References _part1d_forwardmodel::global_parameter, _part1d_forwardmodel::hierarchical_parameters, _model::local_parameter, _part1d_forwardmodel::min_partitions, _part1d_forwardmodel::models, _part1d_forwardmodel::nglobalparameters, _part1d_forwardmodel::nhierarchicalparameters, _part1d_forwardmodel::nlocalparameters, _part1d_forwardmodel::npartitions, _part1d_forwardmodel::p, position_map1d_insert(), RJMCMC_CONDITIONCHECKINT, rjmcmc_random_choose_double(), x, _part1d_forwardmodel::xmax, and _part1d_forwardmodel::xmin.
Referenced by MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().
int part1d_forwardmodel_initialize_fixed (part1d_forwardmodel_t * p, const double * global_parameters, const double * hierarchical_parameters, int npartitions, const double * partition_x, const double ** local_parameters)
References _part1d_forwardmodel::global_parameter, _part1d_forwardmodel::hierarchical_parameters, _model::local_parameter, _part1d_forwardmodel::models, _part1d_forwardmodel::nglobalparameters, _part1d_forwardmodel::nhierarchicalparameters, _part1d_forwardmodel::nlocalparameters, _part1d_forwardmodel::npartitions, _part1d_forwardmodel::p, and position_map1d_insert().
int part1d_forwardmodel_partition_fill_list (const part1d_forwardmodel_t * current, double * positions, int * npartitions)
References _part1d_forwardmodel::p, and position_map1d_fill_list().
Referenced by MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().
double part1d_forwardmodel_partition_position (const part1d_forwardmodel_t * current, int pi)
References _part1d_forwardmodel::p, and position_map1d_position_of_index().
Referenced by MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().
int part1d_forwardmodel_partitions (const part1d_forwardmodel_t * current)
References _part1d_forwardmodel::npartitions.
Referenced by MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().
[part1d_forwardmodel_propose_birth(const part1d_forwardmodel_t *current, part1d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameter, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *birth_prob)]int part1d_forwardmodel_propose_birth (const part1d_forwardmodel_t * current, part1d_forwardmodel_t * proposed, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameter, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * birth_prob)
References _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _forwardmodelparameter::fstd_bd, _model::local_parameter, _part1d_forwardmodel::local_scratch, _part1d_forwardmodel::max_partitions, _part1d_forwardmodel::models, _part1d_forwardmodel::nlocalparameters, normal, _part1d_forwardmodel::npartitions, _part1d_forwardmodel::p, part1d_forwardmodel_clone(), part1d_forwardmodel_value_at(), position_map1d_insert(), rjmcmc_error(), rjmcmc_gaussian_probability(), rjmcmc_random_choose_double(), _part1d_forwardmodel::xmax, and _part1d_forwardmodel::xmin.
Referenced by MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().
[part1d_forwardmodel_propose_death(const part1d_forwardmodel_t *current, part1d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameter, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *death_prob)]int part1d_forwardmodel_propose_death (const part1d_forwardmodel_t * current, part1d_forwardmodel_t * proposed, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameter, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * death_prob)
References _part1d_forwardmodel::local_scratch, _part1d_forwardmodel::max_partitions, _part1d_forwardmodel::min_partitions, _part1d_forwardmodel::models, _part1d_forwardmodel::nlocalparameters, _part1d_forwardmodel::npartitions, _part1d_forwardmodel::p, part1d_forwardmodel_clone(), part1d_forwardmodel_value_at(), position_map1d_delete(), position_map1d_position_of_index(), rjmcmc_error(), rjmcmc_gaussian_probability(), and rjmcmc_random_choose_int().
Referenced by MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().
[part1d_forwardmodel_propose_global_value(const part1d_forwardmodel_t *current, part1d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *value_prob)]int part1d_forwardmodel_propose_global_value (const part1d_forwardmodel_t * current, part1d_forwardmodel_t * proposed, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * value_prob)
References _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _forwardmodelparameter::fstd_value, _part1d_forwardmodel::global_parameter, normal, part1d_forwardmodel_clone(), rjmcmc_error(), and rjmcmc_random_choose_int().
Referenced by MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().
[part1d_forwardmodel_propose_hierarchical(const part1d_forwardmodel_t *current, part1d_forwardmodel_t *proposed, int nhierarchicalparameters, const forwardmodelparameter_t *hierarchical_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *hierarchical_prob)]int part1d_forwardmodel_propose_hierarchical (const part1d_forwardmodel_t * current, part1d_forwardmodel_t * proposed, int nhierarchicalparameters, const forwardmodelparameter_t * hierarchical_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * hierarchical_prob)
References _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _forwardmodelparameter::fstd_value, _part1d_forwardmodel::hierarchical_parameters, _model::local_parameter, normal, part1d_forwardmodel_clone(), rjmcmc_create_array_1d(), rjmcmc_destroy_array_1d(), RJMCMC_NULLCHECKVOID, and rjmcmc_random_choose_int().
Referenced by MPI_part1d_forwardmodel_natural_hierarchical().
[part1d_forwardmodel_propose_local_value(const part1d_forwardmodel_t *current, part1d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *value_prob, int *li)]int part1d_forwardmodel_propose_local_value (const part1d_forwardmodel_t * current, part1d_forwardmodel_t * proposed, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * value_prob, int * li)
References _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _forwardmodelparameter::fstd_value, _model::local_parameter, _part1d_forwardmodel::models, normal, _part1d_forwardmodel::npartitions, PART1D_FM_ZERO, part1d_forwardmodel_clone(), rjmcmc_random_choose_int(), and _part1d_forwardmodel::type.
Referenced by MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().
[part1d_forwardmodel_propose_move(const part1d_forwardmodel_t *current, part1d_forwardmodel_t *proposed, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *move_prob)]int part1d_forwardmodel_propose_move (const part1d_forwardmodel_t * current, part1d_forwardmodel_t * proposed, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * move_prob)
References normal, _part1d_forwardmodel::npartitions, _part1d_forwardmodel::p, part1d_forwardmodel_clone(), _part1d_forwardmodel::pd, position_map1d_move(), position_map1d_position_of_index(), rjmcmc_error(), rjmcmc_random_choose_int(), and _part1d_forwardmodel::xmax.
Referenced by MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().
int part1d_forwardmodel_value_at (const part1d_forwardmodel_t * current, double x, int nlocalparameters, double * localparameters)
References _model::a, _model::local_parameter, _part1d_forwardmodel::models, _part1d_forwardmodel::nlocalparameters, _part1d_forwardmodel::p, PART1D_FM_NATURAL, PART1D_FM_ZERO, PART1D_FM_ZERO_CUBIC, position_map1d_position_of_index(), position_map1d_predecessor_of_index(), position_map1d_predecessor_of_point(), position_map1d_successor_of_point(), RJMCMC_CONDITIONCHECKINT, rjmcmc_error(), RJMCMC_NULLCHECKINT, _part1d_forwardmodel::type, and _part1d_forwardmodel::xmax.
Referenced by part1d_forwardmodel_propose_birth(), and part1d_forwardmodel_propose_death().