part1d_regression_rj.h File Reference
#include `rjmcmc/dataset1d.h`
*
#include `rjmcmc/rjmcmc_random.h`
*
Typedefs
typedef struct _part1d_regression_rj part1d_regression_rj_t
Functions
part1d_regression_rj_t * part1d_regression_rj_create (int min_part, int max_part, int max_order, int ndatasets, double xmin, double xmax, double pd)
void part1d_regression_rj_destroy (part1d_regression_rj_t *p)
void part1d_regression_rj_clone (const part1d_regression_rj_t *src, part1d_regression_rj_t *dst)
int part1d_regression_rj_evaluate (const part1d_regression_rj_t *current, int di, double xmin, double xmax, int xsamples, double *v)
double part1d_regression_rj_value_at (const part1d_regression_rj_t *current, double x)
double part1d_regression_rj_misfit (part1d_regression_rj_t *p, const dataset1d_t **datasets, int ndatasets)
int part1d_regression_rj_initialize (part1d_regression_rj_t *p, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)
int part1d_regression_rj_propose_birth (const part1d_regression_rj_t *current, part1d_regression_rj_t *proposed, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *birth_prob)
int part1d_regression_rj_propose_death (const part1d_regression_rj_t *current, part1d_regression_rj_t *proposed, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *death_prob)
int part1d_regression_rj_propose_value (const part1d_regression_rj_t *current, part1d_regression_rj_t *proposed, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *value_prob)
int part1d_regression_rj_propose_lambda (const part1d_regression_rj_t *current, part1d_regression_rj_t *proposed, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *lambda_prob)
int part1d_regression_rj_propose_move (const part1d_regression_rj_t *current, part1d_regression_rj_t *proposed, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *move_prob)
int part1d_regression_rj_propose_order (const part1d_regression_rj_t *current, part1d_regression_rj_t *proposed, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *order_prob)
int part1d_regression_rj_partitions (const part1d_regression_rj_t *current)
double part1d_regression_rj_lambda (const part1d_regression_rj_t *current, int di)
int part1d_regression_rj_order (const part1d_regression_rj_t *current, int di)
int part1d_regression_rj_order_sum (const part1d_regression_rj_t *current, int di)
double part1d_regression_rj_partition_position (const part1d_regression_rj_t *current, int pi)
Typedef Documentation
typedef struct _part1d_regression_rj part1d_regression_rj_t
Function Documentation
void part1d_regression_rj_clone (const part1d_regression_rj_t * src, part1d_regression_rj_t * dst)
References _part1d_regression_rj::max_order, _part1d_regression_rj::max_partitions, _part1d_regression_rj::models, _part1d_regression_rj::ndatasets, _part1d_regression_rj::npartitions, _part1d_regression_rj::p, position_map1d_clone(), RJMCMC_CONDITIONCHECKVOID, and RJMCMC_NULLCHECKVOID.
Referenced by part1d_regression(), part1d_regression_rj_propose_birth(), part1d_regression_rj_propose_death(), part1d_regression_rj_propose_lambda(), part1d_regression_rj_propose_move(), and part1d_regression_rj_propose_value().
part1d_regression_rj_t* part1d_regression_rj_create (int min_part, int max_part, int max_order, int ndatasets, double xmin, double xmax, double pd)
References _part1d_regression_rj::auto_z, _part1d_regression_rj::autoprior, _part1d_regression_rj::cf, curvefit_create(), _part1d_regression_rj::detCm, _part1d_regression_rj::max_order, _part1d_regression_rj::max_partitions, _part1d_regression_rj::mean, _part1d_regression_rj::mean_misfit, _part1d_regression_rj::min_partitions, _part1d_regression_rj::models, _part1d_regression_rj::ndatasets, _part1d_regression_rj::npartitions, _part1d_regression_rj::p, _part1d_regression_rj::pd, position_map1d_create(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), _part1d_regression_rj::S, _part1d_regression_rj::sigma, _part1d_regression_rj::xmax, and _part1d_regression_rj::xmin.
Referenced by part1d_regression().
void part1d_regression_rj_destroy (part1d_regression_rj_t * p)
References _part1d_regression_rj::autoprior, _part1d_regression_rj::cf, curvefit_destroy(), _part1d_regression_rj::detCm, _part1d_regression_rj::max_order, _part1d_regression_rj::max_partitions, _part1d_regression_rj::mean, _part1d_regression_rj::mean_misfit, _part1d_regression_rj::models, _part1d_regression_rj::ndatasets, _part1d_regression_rj::p, position_map1d_destroy(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), _part1d_regression_rj::S, and _part1d_regression_rj::sigma.
Referenced by part1d_regression().
int part1d_regression_rj_evaluate (const part1d_regression_rj_t * current, int di, double xmin, double xmax, int xsamples, double * v)
Referenced by part1d_regression().
int part1d_regression_rj_initialize (part1d_regression_rj_t * p, const dataset1d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)
References _model::a, dataset1d_range(), _model::lambda, _dataset1d::lambdamax, _dataset1d::lambdamin, _dataset1d::lambdastd, _part1d_regression_rj::max_order, _part1d_regression_rj::models, _part1d_regression_rj::npartitions, _model::order, _part1d_regression_rj::p, position_map1d_delete(), position_map1d_insert(), position_map1d_next_position(), position_map1d_position_of_index(), position_map1d_predecessor_of_index(), position_map1d_predecessor_of_point(), random, rjmcmc_error(), rjmcmc_polynomial_value(), rjmcmc_random_choose_double(), rjmcmc_random_choose_int(), x, _part1d_regression_rj::xmax, _part1d_regression_rj::xmin, and y.
Referenced by part1d_regression().
double part1d_regression_rj_lambda (const part1d_regression_rj_t * current, int di)
References _model::lambda, and _part1d_regression_rj::models.
Referenced by part1d_regression().
double part1d_regression_rj_misfit (part1d_regression_rj_t * p, const dataset1d_t ** datasets, int ndatasets)
References _model::lambda, _dataset1d::lambdastd, _part1d_regression_rj::models, _point1d::n, _dataset1d::npoints, _dataset1d::points, _point1d::x, _point1d::y, y, and _dataset1d::ymax.
Referenced by part1d_regression().
int part1d_regression_rj_order (const part1d_regression_rj_t * current, int di)
References _part1d_regression_rj::models, and _model::order.
Referenced by part1d_regression().
int part1d_regression_rj_order_sum (const part1d_regression_rj_t * current, int di)
References _part1d_regression_rj::models, _part1d_regression_rj::npartitions, and _model::order.
double part1d_regression_rj_partition_position (const part1d_regression_rj_t * current, int pi)
References _part1d_regression_rj::p, and position_map1d_position_of_index().
Referenced by part1d_regression().
int part1d_regression_rj_partitions (const part1d_regression_rj_t * current)
References _part1d_regression_rj::npartitions.
Referenced by part1d_regression().
int part1d_regression_rj_propose_birth (const part1d_regression_rj_t * current, part1d_regression_rj_t * proposed, const dataset1d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * birth_prob)
References dataset1d_range(), _part1d_regression_rj::max_partitions, _part1d_regression_rj::models, _part1d_regression_rj::npartitions, _part1d_regression_rj::p, part1d_regression_rj_clone(), position_map1d_insert(), position_map1d_next_position(), position_map1d_position_of_index(), position_map1d_predecessor_of_index(), _model::ppratio, random, rjmcmc_error(), _part1d_regression_rj::xmax, and _part1d_regression_rj::xmin.
Referenced by part1d_regression().
int part1d_regression_rj_propose_death (const part1d_regression_rj_t * current, part1d_regression_rj_t * proposed, const dataset1d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * death_prob)
References dataset1d_range(), _part1d_regression_rj::max_order, _part1d_regression_rj::max_partitions, _part1d_regression_rj::min_partitions, _part1d_regression_rj::models, _part1d_regression_rj::ndatasets, _part1d_regression_rj::npartitions, _model::order, _part1d_regression_rj::p, part1d_regression_rj_clone(), position_map1d_delete(), position_map1d_next_position(), position_map1d_position_of_index(), position_map1d_predecessor_of_point(), _model::ppratio, rjmcmc_error(), and rjmcmc_random_choose_int().
Referenced by part1d_regression().
[part1d_regression_rj_propose_lambda(const part1d_regression_rj_t *current, part1d_regression_rj_t *proposed, const dataset1d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *lambda_prob)]int part1d_regression_rj_propose_lambda (const part1d_regression_rj_t * current, part1d_regression_rj_t * proposed, const dataset1d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * lambda_prob)
References _model::lambda, _dataset1d::lambdamax, _dataset1d::lambdastd, _part1d_regression_rj::models, normal, _dataset1d::npoints, part1d_regression_rj_clone(), and random.
Referenced by part1d_regression().
int part1d_regression_rj_propose_move (const part1d_regression_rj_t * current, part1d_regression_rj_t * proposed, const dataset1d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * move_prob)
References _model::a, _part1d_regression_rj::auto_z, _part1d_regression_rj::autoprior, _part1d_regression_rj::cf, curvefit_compute(), curvefit_evaluate_pk(), curvefit_sample(), dataset1d_range(), _part1d_regression_rj::detCm, _model::kcdf, _model::lambda, _part1d_regression_rj::max_order, _part1d_regression_rj::mean, _part1d_regression_rj::mean_misfit, _part1d_regression_rj::models, _part1d_regression_rj::ndatasets, normal, _part1d_regression_rj::npartitions, _model::order, _part1d_regression_rj::p, part1d_regression_rj_clone(), _part1d_regression_rj::pd, _model::pk, position_map1d_move(), position_map1d_next_position(), position_map1d_position_of_index(), position_map1d_predecessor_of_index(), _model::ppratio, _model::prior_product, random, rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_create_int_array_1d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_destroy_int_array_1d(), rjmcmc_error(), RJMCMC_NULLCHECKVOID, rjmcmc_random_choose_int(), rjmcmc_random_choose_interval(), _part1d_regression_rj::S, _part1d_regression_rj::sigma, and _part1d_regression_rj::xmax.
Referenced by part1d_regression().
int part1d_regression_rj_propose_order (const part1d_regression_rj_t * current, part1d_regression_rj_t * proposed, const dataset1d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * order_prob)
int part1d_regression_rj_propose_value (const part1d_regression_rj_t * current, part1d_regression_rj_t * proposed, const dataset1d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * value_prob)
References dataset1d_range(), _part1d_regression_rj::models, _part1d_regression_rj::ndatasets, _part1d_regression_rj::npartitions, _model::order, _part1d_regression_rj::p, part1d_regression_rj_clone(), position_map1d_next_position(), position_map1d_position_of_index(), _model::ppratio, rjmcmc_error(), and rjmcmc_random_choose_int().
Referenced by part1d_regression().
double part1d_regression_rj_value_at (const part1d_regression_rj_t * current, double x)