part2d_regression_rj.h File Reference
#include `rjmcmc/dataset2d.h`
*
#include `rjmcmc/rjmcmc_random.h`
*
Typedefs
typedef struct _part2d_regression_rj part2d_regression_rj_t
Functions
part2d_regression_rj_t * part2d_regression_rj_create (int min_part, int max_part, int ndatasets, double xmin, double xmax, double ymin, double ymax, double pv, double pdx, double pdy, double pdxy)
void part2d_regression_rj_destroy (part2d_regression_rj_t *p)
void part2d_regression_rj_clone (const part2d_regression_rj_t *src, part2d_regression_rj_t *dst)
double part2d_regression_rj_misfit (part2d_regression_rj_t *p, const dataset2d_t **datasets, int ndatasets)
int part2d_regression_rj_evaluate (part2d_regression_rj_t *current, int di, double xmin, double xmax, int xsamples, double ymin, double ymax, int ysamples, double **z)
int part2d_regression_rj_initialize (part2d_regression_rj_t *p, const dataset2d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)
int part2d_regression_rj_propose_birth (const part2d_regression_rj_t *current, part2d_regression_rj_t *proposed, const dataset2d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *birth_prob)
int part2d_regression_rj_propose_death (const part2d_regression_rj_t *current, part2d_regression_rj_t *proposed, const dataset2d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *death_prob)
int part2d_regression_rj_propose_value (const part2d_regression_rj_t *current, part2d_regression_rj_t *proposed, const dataset2d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *value_prob)
int part2d_regression_rj_propose_sigma (const part2d_regression_rj_t *current, part2d_regression_rj_t *proposed, const dataset2d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *sigma_prob)
int part2d_regression_rj_propose_move (const part2d_regression_rj_t *current, part2d_regression_rj_t *proposed, const dataset2d_t **datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *move_prob)
int part2d_regression_rj_partitions (const part2d_regression_rj_t *current)
double part2d_regression_rj_lambda (const part2d_regression_rj_t *current)
double part2d_regression_rj_value_at (const part2d_regression_rj_t *current, double x, double y)
int part2d_regression_rj_partition_centre (const part2d_regression_rj_t *current, int pi, double *x, double *y)
Typedef Documentation
typedef struct _part2d_regression_rj part2d_regression_rj_t
Function Documentation
void part2d_regression_rj_clone (const part2d_regression_rj_t * src, part2d_regression_rj_t * dst)
References _part2d_regression_rj::max_partitions, _part2d_regression_rj::models, _part2d_regression_rj::ndatasets, _part2d_regression_rj::npartitions, _part2d_regression_rj::p, position_map2d_clone(), RJMCMC_CONDITIONCHECKVOID, and RJMCMC_NULLCHECKVOID.
Referenced by part2d_regression(), part2d_regression_rj_propose_birth(), part2d_regression_rj_propose_death(), part2d_regression_rj_propose_lambda(), part2d_regression_rj_propose_move(), and part2d_regression_rj_propose_value().
part2d_regression_rj_t* part2d_regression_rj_create (int min_part, int max_part, int ndatasets, double xmin, double xmax, double ymin, double ymax, double pv, double pdx, double pdy, double pdxy)
References _part2d_regression_rj::max_partitions, _part2d_regression_rj::min_partitions, _part2d_regression_rj::models, _part2d_regression_rj::ndatasets, _part2d_regression_rj::npartitions, _part2d_regression_rj::p, _part2d_regression_rj::pdx, _part2d_regression_rj::pdxy, _part2d_regression_rj::pdy, position_map2d_create(), _part2d_regression_rj::pv, _part2d_regression_rj::xmax, _part2d_regression_rj::xmin, _part2d_regression_rj::ymax, and _part2d_regression_rj::ymin.
Referenced by part2d_regression().
void part2d_regression_rj_destroy (part2d_regression_rj_t * p)
References _part2d_regression_rj::max_partitions, _part2d_regression_rj::models, _part2d_regression_rj::ndatasets, _part2d_regression_rj::p, and position_map2d_destroy().
Referenced by part2d_regression().
int part2d_regression_rj_evaluate (part2d_regression_rj_t * current, int di, double xmin, double xmax, int xsamples, double ymin, double ymax, int ysamples, double ** z)
References x, and y.
Referenced by part2d_regression().
int part2d_regression_rj_initialize (part2d_regression_rj_t * p, const dataset2d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)
References _model::a, _model::lambda, _dataset2d::lambdamax, _dataset2d::lambdamin, _dataset2d::lambdastd, _part2d_regression_rj::models, _part2d_regression_rj::npartitions, _part2d_regression_rj::p, position_map2d_insert(), rjmcmc_error(), rjmcmc_random_choose_double(), x, _part2d_regression_rj::xmax, _part2d_regression_rj::xmin, y, _part2d_regression_rj::ymax, _part2d_regression_rj::ymin, _dataset2d::zmax, and _dataset2d::zmin.
Referenced by part2d_regression().
double part2d_regression_rj_lambda (const part2d_regression_rj_t * current)
References _model::lambda, and _part2d_regression_rj::models.
Referenced by part2d_regression().
double part2d_regression_rj_misfit (part2d_regression_rj_t * p, const dataset2d_t ** datasets, int ndatasets)
References _model::lambda, _dataset2d::lambdastd, _part2d_regression_rj::models, _point2d::n, _dataset2d::npoints, _dataset2d::points, _point2d::x, _point2d::y, _point2d::z, and z.
Referenced by part2d_regression().
int part2d_regression_rj_partition_centre (const part2d_regression_rj_t * current, int pi, double * x, double * y)
References _model::a, _model::lambda, _part2d_regression_rj::models, _part2d_regression_rj::p, position_map2d_nearest(), position_map2d_position_of_index(), rjmcmc_create_array_1d(), rjmcmc_destroy_array_1d(), RJMCMC_NULLCHECKVOID, x, _part2d_regression_rj::xmax, _part2d_regression_rj::xmin, y, _part2d_regression_rj::ymax, and _part2d_regression_rj::ymin.
Referenced by part2d_regression().
int part2d_regression_rj_partitions (const part2d_regression_rj_t * current)
References _part2d_regression_rj::npartitions.
Referenced by part2d_regression().
int part2d_regression_rj_propose_birth (const part2d_regression_rj_t * current, part2d_regression_rj_t * proposed, const dataset2d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * birth_prob)
References _model::a, _part2d_regression_rj::max_partitions, _part2d_regression_rj::models, normal, _part2d_regression_rj::npartitions, _part2d_regression_rj::p, part2d_regression_rj_clone(), position_map2d_insert(), _part2d_regression_rj::pv, rjmcmc_error(), rjmcmc_gaussian_probability(), rjmcmc_random_choose_double(), x, _part2d_regression_rj::xmax, _part2d_regression_rj::xmin, y, _part2d_regression_rj::ymax, _part2d_regression_rj::ymin, _dataset2d::zmax, and _dataset2d::zmin.
Referenced by part2d_regression().
int part2d_regression_rj_propose_death (const part2d_regression_rj_t * current, part2d_regression_rj_t * proposed, const dataset2d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * death_prob)
References _part2d_regression_rj::max_partitions, _part2d_regression_rj::min_partitions, _part2d_regression_rj::models, _part2d_regression_rj::ndatasets, _part2d_regression_rj::npartitions, _part2d_regression_rj::p, part2d_regression_rj_clone(), position_map2d_delete(), position_map2d_position_of_index(), _part2d_regression_rj::pv, rjmcmc_error(), rjmcmc_gaussian_probability(), and rjmcmc_random_choose_int().
Referenced by part2d_regression().
int part2d_regression_rj_propose_move (const part2d_regression_rj_t * current, part2d_regression_rj_t * proposed, const dataset2d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * move_prob)
References normal, _part2d_regression_rj::npartitions, _part2d_regression_rj::p, part2d_regression_rj_clone(), _part2d_regression_rj::pdx, _part2d_regression_rj::pdy, position_map2d_move(), position_map2d_position_of_index(), rjmcmc_error(), rjmcmc_random_choose_int(), _part2d_regression_rj::xmax, and _part2d_regression_rj::ymax.
Referenced by part2d_regression().
int part2d_regression_rj_propose_sigma (const part2d_regression_rj_t * current, part2d_regression_rj_t * proposed, const dataset2d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * sigma_prob)
int part2d_regression_rj_propose_value (const part2d_regression_rj_t * current, part2d_regression_rj_t * proposed, const dataset2d_t ** datasets, int ndatasets, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * value_prob)
References _model::a, _part2d_regression_rj::models, normal, _part2d_regression_rj::npartitions, part2d_regression_rj_clone(), _part2d_regression_rj::pv, rjmcmc_random_choose_int(), and _dataset2d::zmax.
Referenced by part2d_regression().
double part2d_regression_rj_value_at (const part2d_regression_rj_t * current, double x, double y)
Referenced by part2d_regression().