position_map1d.h File Reference
Typedefs
typedef struct _position_map1d position_map1d_t
Functions
position_map1d_t * position_map1d_create (int max_partitions, double minx, double maxx)
void position_map1d_destroy (position_map1d_t *p)
void position_map1d_clone (const position_map1d_t *src, position_map1d_t *dst)
int position_map1d_npartitions (const position_map1d_t *p)
int position_map1d_insert (position_map1d_t *p, double x, int iy)
int position_map1d_delete (position_map1d_t *p, double x, int iy)
int position_map1d_move (position_map1d_t *p, double x, double new_x)
int position_map1d_small_move (position_map1d_t *p, double x, double new_x)
int position_map1d_nearest (position_map1d_t *p, double x, double *nx)
double position_map1d_position_of_index (position_map1d_t *p, int iy)
int position_map1d_next_index (position_map1d_t *p, double x)
double position_map1d_next_position (position_map1d_t *p, double x)
int position_map1d_predecessor_of_point (position_map1d_t *p, double x)
int position_map1d_predecessor_of_index (position_map1d_t *p, int iy)
int position_map1d_successor_of_point (position_map1d_t *p, double x)
int position_map1d_successor_of_index (position_map1d_t *p, int iy)
int position_map1d_traverse_intervals (position_map1d_t *p, int(*interval_cb)(void *user_arg, double xmin, double xmax, int iy, int riy), void *user_arg)
int position_map1d_fill_list (position_map1d_t *p, double *positions, int *npartitions)
void position_map1d_dump (position_map1d_t *p)
int position_map1d_valid (position_map1d_t *p)
Typedef Documentation
typedef struct _position_map1d position_map1d_t
Function Documentation
void position_map1d_clone (const position_map1d_t * src, position_map1d_t * dst)
References _position_map1d::ind, _position_map1d::max_partitions, _position_map1d::npartitions, _position_map1d::pos, RJMCMC_CONDITIONCHECKVOID, and RJMCMC_NULLCHECKVOID.
Referenced by part1d_forwardmodel_clone(), part1d_natural_rj_clone(), part1d_regression_rj_clone(), and part1d_zero_clone().
position_map1d_t* position_map1d_create (int max_partitions, double minx, double maxx)
References _position_map1d::ind, _position_map1d::max_partitions, _position_map1d::npartitions, _position_map1d::pos, rjmcmc_create_array_1d(), rjmcmc_create_int_array_1d(), and rjmcmc_error().
Referenced by part1d_forwardmodel_create(), part1d_natural_rj_create(), part1d_regression_rj_create(), and part1d_zero_create().
int position_map1d_delete (position_map1d_t * p, double x, int iy)
References _position_map1d::ind, _position_map1d::npartitions, _position_map1d::pos, position_map1d_valid(), RJMCMC_CONDITIONCHECKINT, rjmcmc_error(), and RJMCMC_NULLCHECKINT.
Referenced by part1d_forwardmodel_propose_death(), part1d_natural_rj_propose_death(), part1d_regression_rj_initialize(), part1d_regression_rj_propose_death(), and part1d_zero_propose_death().
void position_map1d_destroy (position_map1d_t * p)
References _position_map1d::ind, _position_map1d::pos, rjmcmc_destroy_array_1d(), and rjmcmc_destroy_int_array_1d().
Referenced by part1d_forwardmodel_destroy(), part1d_natural_rj_destroy(), part1d_regression_rj_destroy(), and part1d_zero_destroy().
void position_map1d_dump (position_map1d_t * p)
References _position_map1d::ind, _position_map1d::npartitions, and _position_map1d::pos.
int position_map1d_fill_list (position_map1d_t * p, double * positions, int * npartitions)
References _position_map1d::npartitions, _position_map1d::pos, and RJMCMC_NULLCHECKINT.
Referenced by part1d_forwardmodel_partition_fill_list().
int position_map1d_insert (position_map1d_t * p, double x, int iy)
References _position_map1d::ind, _position_map1d::max_partitions, _position_map1d::npartitions, _position_map1d::pos, RJMCMC_CONDITIONCHECKINT, rjmcmc_error(), RJMCMC_NULLCHECKINT, and x.
Referenced by part1d_forwardmodel_initialize(), part1d_forwardmodel_initialize_fixed(), part1d_forwardmodel_propose_birth(), part1d_natural_rj_initialize(), part1d_natural_rj_propose_birth(), part1d_regression_rj_initialize(), part1d_regression_rj_propose_birth(), part1d_zero_initialize(), and part1d_zero_propose_birth().
int position_map1d_move (position_map1d_t * p, double x, double new_x)
References _position_map1d::ind, _position_map1d::npartitions, _position_map1d::pos, rjmcmc_error(), and RJMCMC_NULLCHECKINT.
Referenced by part1d_forwardmodel_propose_move(), part1d_natural_rj_propose_move(), part1d_regression_rj_propose_move(), part1d_zero_propose_move(), and position_map1d_small_move().
int position_map1d_nearest (position_map1d_t * p, double x, double * nx)
References _position_map1d::ind, _position_map1d::npartitions, _position_map1d::pos, and RJMCMC_NULLCHECKINT.
int position_map1d_next_index (position_map1d_t * p, double x)
References _position_map1d::ind, _position_map1d::npartitions, _position_map1d::pos, rjmcmc_error(), and RJMCMC_NULLCHECKINT.
Referenced by part1d_natural_rj_value_at().
double position_map1d_next_position (position_map1d_t * p, double x)
References _position_map1d::npartitions, _position_map1d::pos, and rjmcmc_error().
Referenced by part1d_natural_rj_propose_birth(), part1d_regression_rj_initialize(), part1d_regression_rj_propose_birth(), part1d_regression_rj_propose_death(), part1d_regression_rj_propose_move(), part1d_regression_rj_propose_value(), and part1d_zero_propose_birth().
int position_map1d_npartitions (const position_map1d_t * p)
References _position_map1d::npartitions, and RJMCMC_NULLCHECKINT.
double position_map1d_position_of_index (position_map1d_t * p, int iy)
References _position_map1d::ind, _position_map1d::npartitions, _position_map1d::pos, and rjmcmc_error().
Referenced by part1d_forwardmodel_partition_position(), part1d_forwardmodel_propose_death(), part1d_forwardmodel_propose_move(), part1d_forwardmodel_value_at(), part1d_natural_rj_partition_position(), part1d_natural_rj_propose_death(), part1d_natural_rj_propose_move(), part1d_natural_rj_value_at(), part1d_regression_rj_initialize(), part1d_regression_rj_partition_position(), part1d_regression_rj_propose_birth(), part1d_regression_rj_propose_death(), part1d_regression_rj_propose_move(), part1d_regression_rj_propose_value(), part1d_zero_partition_position(), part1d_zero_propose_birth(), part1d_zero_propose_death(), and part1d_zero_propose_move().
int position_map1d_predecessor_of_index (position_map1d_t * p, int iy)
References _position_map1d::ind, _position_map1d::npartitions, and RJMCMC_NULLCHECKINT.
Referenced by part1d_forwardmodel_value_at(), part1d_natural_rj_value_at(), part1d_regression_rj_initialize(), part1d_regression_rj_propose_birth(), part1d_regression_rj_propose_move(), part1d_zero_propose_birth(), part1d_zero_propose_death(), part1d_zero_propose_move(), and part1d_zero_value_at().
int position_map1d_predecessor_of_point (position_map1d_t * p, double x)
References _position_map1d::ind, _position_map1d::npartitions, _position_map1d::pos, and RJMCMC_NULLCHECKINT.
Referenced by part1d_forwardmodel_value_at(), part1d_natural_rj_propose_death(), part1d_natural_rj_value_at(), part1d_regression_rj_initialize(), part1d_regression_rj_propose_death(), part1d_zero_propose_death(), and part1d_zero_value_at().
int position_map1d_small_move (position_map1d_t * p, double x, double new_x)
References position_map1d_move().
int position_map1d_successor_of_index (position_map1d_t * p, int iy)
References _position_map1d::ind, _position_map1d::npartitions, and RJMCMC_NULLCHECKINT.
Referenced by part1d_zero_propose_move().
int position_map1d_successor_of_point (position_map1d_t * p, double x)
References _position_map1d::ind, _position_map1d::npartitions, _position_map1d::pos, and RJMCMC_NULLCHECKINT.
Referenced by part1d_forwardmodel_value_at(), and part1d_zero_propose_death().
int position_map1d_traverse_intervals (position_map1d_t * p, int(*)(void *user_arg, double xmin, double xmax, int iy, int riy) interval_cb, void * user_arg)
References _position_map1d::ind, _position_map1d::npartitions, _position_map1d::pos, and RJMCMC_NULLCHECKINT.
Referenced by part1d_forwardmodel_evaluate_local_parameters(), and part1d_zero_initialize().
int position_map1d_valid (position_map1d_t * p)
References _position_map1d::ind, _position_map1d::npartitions, _position_map1d::pos, RJMCMC_CONDITIONCHECKINT, and RJMCMC_NULLCHECKINT.
Referenced by position_map1d_delete().