position_map2d.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <float.h>
*
#include <rjmcmc/position_map2d.h>
*
#include <rjmcmc/position_map2d_linear.h>
*
#include <rjmcmc/position_map2d_delaunay.h>
*
#include <rjmcmc/position_map2d_quadtree.h>
*
#include `rjmcmc/rjmcmc_util.h`
*
#include `rjmcmc/rjmcmc_defines.h`
*
Data Structures
struct position_map2d_map
Functions
void position_map2d_set_type (position_map2d_type_t t)
position_map2d_t * position_map2d_create (int max_partitions, double xmin, double xmax, double ymin, double ymax)
void position_map2d_destroy (position_map2d_t *p)
void position_map2d_clone (const position_map2d_t *src, position_map2d_t *dst)
int position_map2d_insert (position_map2d_t *p, double x, double y, bbox2d_t *bound)
int position_map2d_delete (position_map2d_t *p, int iy, bbox2d_t *bound)
int position_map2d_move (position_map2d_t *p, int iy, double new_x, double new_y, bbox2d_t *bound)
int position_map2d_nearest (position_map2d_t *p, double x, double y, double *nx, double *ny, int include_boundary_points)
int position_map2d_enclosing_triangle (position_map2d_t *p, double x, double y, int *ta, int *tb, int *tc, double *ba, double *bb, double *bc)
int position_map2d_position_of_index (position_map2d_t *p, int iy, double *x, double *y)
int position_map2d_polygon_bound (position_map2d_t *p, int iy, bbox2d_t *bound)
int position_map2d_validate (position_map2d_t *p)
Function Documentation
void position_map2d_clone (const position_map2d_t * src, position_map2d_t * dst)
Referenced by part2d_forwardmodel_clone(), and part2d_regression_rj_clone().
position_map2d_t* position_map2d_create (int max_partitions, double xmin, double xmax, double ymin, double ymax)
Referenced by part2d_forwardmodel_create(), and part2d_regression_rj_create().
int position_map2d_delete (position_map2d_t * p, int iy, bbox2d_t * bound)
Referenced by part2d_forwardmodel_delpoint(), and part2d_regression_rj_propose_death().
void position_map2d_destroy (position_map2d_t * p)
Referenced by part2d_forwardmodel_destroy(), and part2d_regression_rj_destroy().
int position_map2d_enclosing_triangle (position_map2d_t * p, double x, double y, int * ta, int * tb, int * tc, double * ba, double * bb, double * bc)
int position_map2d_insert (position_map2d_t * p, double x, double y, bbox2d_t * bound)
Referenced by part2d_forwardmodel_addpoint(), part2d_forwardmodel_initialize(), part2d_forwardmodel_load(), part2d_regression_rj_initialize(), and part2d_regression_rj_propose_birth().
int position_map2d_move (position_map2d_t * p, int iy, double new_x, double new_y, bbox2d_t * bound)
Referenced by part2d_forwardmodel_movepoint(), and part2d_regression_rj_propose_move().
int position_map2d_nearest (position_map2d_t * p, double x, double y, double * nx, double * ny, int include_boundary_points)
Referenced by part2d_forwardmodel_evaluate_local_parameters(), part2d_forwardmodel_propose_birth(), part2d_forwardmodel_propose_death(), part2d_forwardmodel_value_at(), and part2d_regression_rj_partition_centre().
int position_map2d_polygon_bound (position_map2d_t * p, int iy, bbox2d_t * bound)
int position_map2d_position_of_index (position_map2d_t * p, int iy, double * x, double * y)
Referenced by part2d_forwardmodel_partition_centre(), part2d_forwardmodel_propose_death(), part2d_forwardmodel_propose_move(), part2d_forwardmodel_save(), part2d_regression_rj_partition_centre(), part2d_regression_rj_propose_death(), and part2d_regression_rj_propose_move().
void position_map2d_set_type (position_map2d_type_t t)
Examples:
2d/partitioned/fm/regression/regression.c, and 2d/partitioned/regression/disc/disc.c.
int position_map2d_validate (position_map2d_t * p)