position_map2d_delaunay.h File Reference
#include <rjmcmc/bbox2d.h>
*
Typedefs
typedef struct _position_map2d_delaunay position_map2d_delaunay_t
Functions
position_map2d_delaunay_t * position_map2d_delaunay_create (int max_partitions, double xmin, double xmax, double ymin, double ymax)
void position_map2d_delaunay_destroy (position_map2d_delaunay_t *p)
void position_map2d_delaunay_clone (const position_map2d_delaunay_t *src, position_map2d_delaunay_t *dst)
int position_map2d_delaunay_insert (position_map2d_delaunay_t *p, double x, double y, bbox2d_t *bound)
int position_map2d_delaunay_delete (position_map2d_delaunay_t *p, int iy, bbox2d_t *bound)
int position_map2d_delaunay_move (position_map2d_delaunay_t *p, int iy, double new_x, double new_y, bbox2d_t *bound)
int position_map2d_delaunay_nearest (position_map2d_delaunay_t *p, double x, double y, double *nx, double *ny, int include_boundary_points)
int position_map2d_delaunay_enclosing_triangle (position_map2d_delaunay_t *p, double x, double y, int *ta, int *tb, int *tc, double *ba, double *bb, double *bc)
int position_map2d_delaunay_position_of_index (position_map2d_delaunay_t *p, int iy, double *x, double *y)
int position_map2d_delaunay_polygon_bound (position_map2d_delaunay_t *p, int iy, bbox2d_t *bound)
int position_map2d_delaunay_validate (position_map2d_delaunay_t *p)
int position_map2d_delaunay_save (position_map2d_delaunay_t *p, const char *filename)
Typedef Documentation
typedef struct _position_map2d_delaunay position_map2d_delaunay_t
Function Documentation
void position_map2d_delaunay_clone (const position_map2d_delaunay_t * src, position_map2d_delaunay_t * dst)
References _position_map2d_delaunay::d, delaunay2d_clone(), _position_map2d_delaunay::max_partitions, RJMCMC_CONDITIONCHECKVOID, RJMCMC_NULLCHECKVOID, and _position_map2d_delaunay::si.
position_map2d_delaunay_t* position_map2d_delaunay_create (int max_partitions, double xmin, double xmax, double ymin, double ymax)
References _position_map2d_delaunay::d, delaunay2d_create(), _position_map2d_delaunay::max_partitions, and _position_map2d_delaunay::si.
int position_map2d_delaunay_delete (position_map2d_delaunay_t * p, int iy, bbox2d_t * bound)
References _position_map2d_delaunay::d, delaunay2d_delete(), RJMCMC_NULLCHECKINT, and _position_map2d_delaunay::si.
void position_map2d_delaunay_destroy (position_map2d_delaunay_t * p)
References _position_map2d_delaunay::d, and delaunay2d_destroy().
int position_map2d_delaunay_enclosing_triangle (position_map2d_delaunay_t * p, double x, double y, int * ta, int * tb, int * tc, double * ba, double * bb, double * bc)
References _position_map2d_delaunay::d, delaunay2d_find_enclosing_triangle(), and RJMCMC_NULLCHECKINT.
int position_map2d_delaunay_insert (position_map2d_delaunay_t * p, double x, double y, bbox2d_t * bound)
References _position_map2d_delaunay::d, delaunay2d_add(), and RJMCMC_NULLCHECKINT.
int position_map2d_delaunay_move (position_map2d_delaunay_t * p, int iy, double new_x, double new_y, bbox2d_t * bound)
References bbox2d_bound_expand(), _position_map2d_delaunay::d, delaunay2d_add(), delaunay2d_delete(), delaunay2d_print_points(), delaunay2d_print_triangles(), delaunay2d_shift_replace(), position_map2d_delaunay_validate(), and RJMCMC_NULLCHECKINT.
int position_map2d_delaunay_nearest (position_map2d_delaunay_t * p, double x, double y, double * nx, double * ny, int include_boundary_points)
References _position_map2d_delaunay::d, delaunay2d_nearest_from(), delaunay2d_point_of_index(), RJMCMC_NULLCHECKINT, and _position_map2d_delaunay::si.
int position_map2d_delaunay_polygon_bound (position_map2d_delaunay_t * p, int iy, bbox2d_t * bound)
References _position_map2d_delaunay::d, delaunay2d_polygon_bound(), and RJMCMC_NULLCHECKINT.
int position_map2d_delaunay_position_of_index (position_map2d_delaunay_t * p, int iy, double * x, double * y)
References _position_map2d_delaunay::d, delaunay2d_point_of_index(), and RJMCMC_NULLCHECKINT.
int position_map2d_delaunay_save (position_map2d_delaunay_t * p, const char * filename)
References _position_map2d_delaunay::d, and delaunay2d_save().
int position_map2d_delaunay_validate (position_map2d_delaunay_t * p)
References _position_map2d_delaunay::d, delaunay2d_validate_circumcircles(), delaunay2d_validate_delaunay(), delaunay2d_validate_edges(), and delaunay2d_validate_neighbours().
Referenced by position_map2d_delaunay_move().