position_map2d_linear.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <float.h>
*
#include <rjmcmc/position_map2d.h>
*
#include <rjmcmc/position_map2d_linear.h>
*
#include <rjmcmc/rjmcmc_util.h>
*
#include <rjmcmc/rjmcmc_defines.h>
*
Data Structures
struct _position_map2d_linear
Functions
position_map2d_linear_t * position_map2d_linear_create (int max_partitions, double xmin, double xmax, double ymin, double ymax)
void position_map2d_linear_destroy (position_map2d_linear_t *p)
void position_map2d_linear_clone (const position_map2d_linear_t *src, position_map2d_linear_t *dst)
int position_map2d_linear_insert (position_map2d_linear_t *p, double x, double y, bbox2d_t *bound)
int position_map2d_linear_delete (position_map2d_linear_t *p, int iy, bbox2d_t *bound)
int position_map2d_linear_move (position_map2d_linear_t *p, int iy, double new_x, double new_y, bbox2d_t *bound)
int position_map2d_linear_nearest (position_map2d_linear_t *p, double x, double y, double *nx, double *ny, int include_boundary_points)
int position_map2d_linear_position_of_index (position_map2d_linear_t *p, int iy, double *x, double *y)
int position_map2d_linear_enclosing_triangle (position_map2d_linear_t *p, double x, double y, int *ta, int *tb, int *tc, double *ba, double *bb, double *bc)
int position_map2d_linear_polygon_bound (position_map2d_linear_t *p, int iy, bbox2d_t *bound)
int position_map2d_linear_validate (position_map2d_linear_t *p)
Function Documentation
void position_map2d_linear_clone (const position_map2d_linear_t * src, position_map2d_linear_t * dst)
References _position_map2d_linear::max_partitions, _position_map2d_linear::npartitions, RJMCMC_CONDITIONCHECKVOID, RJMCMC_NULLCHECKVOID, _position_map2d_linear::x, and _position_map2d_linear::y.
position_map2d_linear_t* position_map2d_linear_create (int max_partitions, double xmin, double xmax, double ymin, double ymax)
References _position_map2d_linear::max_partitions, _position_map2d_linear::npartitions, rjmcmc_create_array_1d(), _position_map2d_linear::x, and _position_map2d_linear::y.
int position_map2d_linear_delete (position_map2d_linear_t * p, int iy, bbox2d_t * bound)
References bbox2d_set(), _position_map2d_linear::npartitions, rjmcmc_error(), _position_map2d_linear::x, and _position_map2d_linear::y.
void position_map2d_linear_destroy (position_map2d_linear_t * p)
References rjmcmc_destroy_array_1d(), _position_map2d_linear::x, and _position_map2d_linear::y.
int position_map2d_linear_enclosing_triangle (position_map2d_linear_t * p, double x, double y, int * ta, int * tb, int * tc, double * ba, double * bb, double * bc)
References _position_map2d_linear::npartitions, _position_map2d_linear::v, and _position_map2d_linear::vdist2.
int position_map2d_linear_insert (position_map2d_linear_t * p, double x, double y, bbox2d_t * bound)
References bbox2d_set(), _position_map2d_linear::max_partitions, _position_map2d_linear::npartitions, rjmcmc_error(), _position_map2d_linear::x, and _position_map2d_linear::y.
int position_map2d_linear_move (position_map2d_linear_t * p, int iy, double new_x, double new_y, bbox2d_t * bound)
References bbox2d_set(), _position_map2d_linear::npartitions, rjmcmc_error(), _position_map2d_linear::x, and _position_map2d_linear::y.
int position_map2d_linear_nearest (position_map2d_linear_t * p, double x, double y, double * nx, double * ny, int include_boundary_points)
References _position_map2d_linear::npartitions, _position_map2d_linear::x, and _position_map2d_linear::y.
int position_map2d_linear_polygon_bound (position_map2d_linear_t * p, int iy, bbox2d_t * bound)
References RJMCMC_NULLCHECKINT, _position_map2d_linear::x, bbox2d::xmax, bbox2d::xmin, _position_map2d_linear::y, bbox2d::ymax, and bbox2d::ymin.
int position_map2d_linear_position_of_index (position_map2d_linear_t * p, int iy, double * x, double * y)
References _position_map2d_linear::npartitions, RJMCMC_NULLCHECKINT, _position_map2d_linear::x, and _position_map2d_linear::y.
int position_map2d_linear_validate (position_map2d_linear_t * p)
References _position_map2d_linear::v, _position_map2d_linear::vdist2, _position_map2d_linear::x, and _position_map2d_linear::y.