position_map2d_quadtree.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <float.h>
*
#include <rjmcmc/position_map2d_quadtree.h>
*
#include <rjmcmc/quadtree.h>
*
#include <rjmcmc/rjmcmc_util.h>
*
#include <rjmcmc/rjmcmc_defines.h>
*
Data Structures
struct _position_map2d_quadtree
Functions
position_map2d_quadtree_t * position_map2d_quadtree_create (int max_partitions, double xmin, double xmax, double ymin, double ymax)
void position_map2d_quadtree_destroy (position_map2d_quadtree_t *p)
void position_map2d_quadtree_clone (const position_map2d_quadtree_t *src, position_map2d_quadtree_t *dst)
int position_map2d_quadtree_insert (position_map2d_quadtree_t *p, double x, double y, bbox2d_t *bound)
int position_map2d_quadtree_delete (position_map2d_quadtree_t *p, int iy, bbox2d_t *bound)
int position_map2d_quadtree_move (position_map2d_quadtree_t *p, int iy, double new_x, double new_y, bbox2d_t *bound)
int position_map2d_quadtree_nearest (position_map2d_quadtree_t *p, double x, double y, double *nx, double *ny, int include_boundary_points)
int position_map2d_quadtree_enclosing_triangle (position_map2d_quadtree_t *p, double x, double y, int *ta, int *tb, int *tc, double *ba, double *bb, double *bc)
int position_map2d_quadtree_position_of_index (position_map2d_quadtree_t *p, int iy, double *x, double *y)
int position_map2d_quadtree_polygon_bound (position_map2d_quadtree_t *p, int iy, bbox2d_t *bound)
int position_map2d_quadtree_validate (position_map2d_quadtree_t *p)
Function Documentation
void position_map2d_quadtree_clone (const position_map2d_quadtree_t * src, position_map2d_quadtree_t * dst)
References _position_map2d_quadtree::d, _position_map2d_quadtree::max_partitions, quadtree_clone(), RJMCMC_CONDITIONCHECKVOID, RJMCMC_NULLCHECKVOID, and _position_map2d_quadtree::si.
position_map2d_quadtree_t* position_map2d_quadtree_create (int max_partitions, double xmin, double xmax, double ymin, double ymax)
References _position_map2d_quadtree::d, _position_map2d_quadtree::max_partitions, quadtree_create(), and _position_map2d_quadtree::si.
int position_map2d_quadtree_delete (position_map2d_quadtree_t * p, int iy, bbox2d_t * bound)
References _position_map2d_quadtree::d, quadtree_delete(), RJMCMC_NULLCHECKINT, and _position_map2d_quadtree::si.
void position_map2d_quadtree_destroy (position_map2d_quadtree_t * p)
References _position_map2d_quadtree::d, and quadtree_destroy().
int position_map2d_quadtree_enclosing_triangle (position_map2d_quadtree_t * p, double x, double y, int * ta, int * tb, int * tc, double * ba, double * bb, double * bc)
References RJMCMC_NULLCHECKINT.
int position_map2d_quadtree_insert (position_map2d_quadtree_t * p, double x, double y, bbox2d_t * bound)
References _position_map2d_quadtree::d, quadtree_add(), and RJMCMC_NULLCHECKINT.
int position_map2d_quadtree_move (position_map2d_quadtree_t * p, int iy, double new_x, double new_y, bbox2d_t * bound)
References bbox2d_bound_expand(), _position_map2d_quadtree::d, quadtree_add(), quadtree_delete(), quadtree_shift_replace(), and RJMCMC_NULLCHECKINT.
int position_map2d_quadtree_nearest (position_map2d_quadtree_t * p, double x, double y, double * nx, double * ny, int include_boundary_points)
References _position_map2d_quadtree::d, quadtree_nearest(), quadtree_point_of_index(), and RJMCMC_NULLCHECKINT.
int position_map2d_quadtree_polygon_bound (position_map2d_quadtree_t * p, int iy, bbox2d_t * bound)
References _position_map2d_quadtree::d, quadtree_polygon_bound(), and RJMCMC_NULLCHECKINT.
int position_map2d_quadtree_position_of_index (position_map2d_quadtree_t * p, int iy, double * x, double * y)
References _position_map2d_quadtree::d, quadtree_point_of_index(), and RJMCMC_NULLCHECKINT.
int position_map2d_quadtree_validate (position_map2d_quadtree_t * p)