quadtree.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <float.h>
*
#include <rjmcmc/quadtree.h>
*
#include <rjmcmc/rjmcmc_util.h>
*
Data Structures
struct _point
struct _quadtree_leaf
struct _quadtree_node
struct _quadtree
Macros
#define TEST_NEIGHBOURS
Typedefs
typedef struct _point point_t
typedef struct _quadtree_leaf quadtree_leaf_t
typedef struct _quadtree_node quadtree_node_t
Functions
quadtree_t * quadtree_create (int maxpoints, int maxlevels, double xmin, double xmax, double ymin, double ymax)
void quadtree_destroy (quadtree_t *q)
int quadtree_clone (const quadtree_t *src, quadtree_t *dst)
int quadtree_add (quadtree_t *q, double x, double y, bbox2d_t *bound)
int quadtree_delete (quadtree_t *q, int pi, bbox2d_t *bound)
int quadtree_shift_replace (quadtree_t *q, int pi)
int quadtree_nearest (quadtree_t *q, int include_corners, double px, double py)
int quadtree_point_of_index (const quadtree_t *q, int i, double *px, double *py)
int quadtree_index_of_point (const quadtree_t *q, double x, double y)
int quadtree_npoints (const quadtree_t *q)
int quadtree_polygon_bound (const quadtree_t *q, int i, bbox2d_t *bound)
Macro Definition Documentation
#define TEST_NEIGHBOURS
Typedef Documentation
typedef struct _point point_t
typedef struct _quadtree_leaf quadtree_leaf_t
typedef struct _quadtree_node quadtree_node_t
Function Documentation
int quadtree_add (quadtree_t * q, double x, double y, bbox2d_t * bound)
References _quadtree::head, _quadtree::maxpoints, _quadtree::np, _quadtree::point, _point::x, and _point::y.
Referenced by position_map2d_quadtree_insert(), and position_map2d_quadtree_move().
int quadtree_clone (const quadtree_t * src, quadtree_t * dst)
References _quadtree::head, _quadtree::np, _quadtree::point, _point::x, and _point::y.
Referenced by position_map2d_quadtree_clone().
quadtree_t* quadtree_create (int maxpoints, int maxlevels, double xmin, double xmax, double ymin, double ymax)
References _quadtree::bound, _quadtree::head, _quadtree::maxpoints, _quadtree::np, _quadtree::point, _point::x, bbox2d::xmax, bbox2d::xmin, _point::y, bbox2d::ymax, and bbox2d::ymin.
Referenced by position_map2d_quadtree_create().
int quadtree_delete (quadtree_t * q, int pi, bbox2d_t * bound)
References _quadtree::head, _quadtree::np, _quadtree::point, _point::x, and _point::y.
Referenced by position_map2d_quadtree_delete(), and position_map2d_quadtree_move().
void quadtree_destroy (quadtree_t * q)
References _quadtree::head, and _quadtree::point.
Referenced by position_map2d_quadtree_destroy().
int quadtree_index_of_point (const quadtree_t * q, double x, double y)
References _quadtree::np, _quadtree::point, _point::x, and _point::y.
int quadtree_nearest (quadtree_t * q, int include_corners, double px, double py)
References _quadtree::head.
Referenced by position_map2d_quadtree_nearest().
int quadtree_npoints (const quadtree_t * q)
References _quadtree::np.
int quadtree_point_of_index (const quadtree_t * q, int i, double * px, double * py)
References _quadtree::np, _quadtree::point, _point::x, and _point::y.
Referenced by position_map2d_quadtree_nearest(), and position_map2d_quadtree_position_of_index().
int quadtree_polygon_bound (const quadtree_t * q, int i, bbox2d_t * bound)
References _quadtree_node::bound, _quadtree::bound, _quadtree_node::child, _quadtree_node::cx, _quadtree_node::cy, _quadtree_node::data, _point::dx, _point::dy, _quadtree_node::grand_children, _quadtree_node::leaf, _quadtree_node::node, _quadtree_leaf::np, _quadtree::np, _quadtree_leaf::point, _quadtree::point, rjmcmc_create_int_array_1d(), rjmcmc_destroy_int_array_1d(), _point::x, bbox2d::xmax, bbox2d::xmin, _point::y, bbox2d::ymax, and bbox2d::ymin.
Referenced by position_map2d_quadtree_polygon_bound().
int quadtree_shift_replace (quadtree_t * q, int pi)
References _quadtree::head, _quadtree::np, _quadtree::point, _point::x, and _point::y.
Referenced by position_map2d_quadtree_move().