regression.h File Reference
Single, 1D Partitioned and 2D Partitioned Regression.
#include <rjmcmc/rjmcmc_config.h>
*
#include <rjmcmc/resultset1d.h>
*
#include <rjmcmc/dataset1d.h>
*
#include <rjmcmc/resultset2d.h>
*
#include <rjmcmc/dataset2d.h>
*
#include <rjmcmc/rjmcmc_random.h>
*
Typedefs
typedef double(* regression1d_value_at_t) (void *state, double x)
typedef void(* regression1d_cb_t) (void *state, double *boundaries, int nboundaries, regression1d_value_at_t value_at, double lambda, void *user_arg)
typedef double(* regression2d_value_at_t) (void *state, double x, double y)
typedef void(* regression2d_cb_t) (void *state, double *x, double *y, int ncells, regression2d_value_at_t value_at, double lambda, void *user_arg)
Functions
resultset1d_t * single1d_regression (const dataset1d_t *dataset, int burnin, int total, int max_order, int xsamples, int ysamples, double credible_interval, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t user_callback, void *user_arg)
Single Partition Regression.
resultset1d_t * single1d_regression_with_prior (const dataset1d_t *dataset, const double *prior, int burnin, int total, int max_order, int xsamples, int ysamples, double credible_interval, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t user_callback, void *user_arg)
Single Partition Regression with a custom prior.
resultset1d_t * single1d_direct_regression (const dataset1d_t *dataset, const double *fixed_prior, int max_order, int xsamples, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)
Single Partition Regression with direct integration.
resultset1d_t * part1d_regression (const dataset1d_t *dataset, int burnin, int total, int min_part, int max_part, int max_order, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t callback, void *user_arg)
Multiple partition arbitrary order regression.
resultset1d_t * part1d_zero_regression (const dataset1d_t *dataset, int burnin, int total, int min_part, int max_part, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t callback, void *user_arg)
Multiple partition zeroth order regression.
resultset1d_t * part1d_natural_regression (const dataset1d_t *dataset, int burnin, int total, int min_part, int max_part, int xsamples, int ysamples, double credible_interval, double pv, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t callback, void *user_arg)
Multiple partition joined line segments regression.
resultset2d_t * part2d_regression (const dataset2d_t *dataset, int burnin, int total, int min_part, int max_part, int xsamples, int ysamples, int zsamples, double credible_interval, double pv, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression2d_cb_t user_callback, void *user_arg)
Detailed Description
Single, 1D Partitioned and 2D Partitioned Regression.
The regression functions run a MCMC simulation to fit data using regression metrics. The likelihood is calculated as a gaussian probability distribution, ie:
 \Pr(d|m) = \frac{1}{\prod_{i=1}^n \sqrt{2 \pi \cdot \sigma_i^2}} \exp{\left( \sum_{i = 1}^n \frac{-\left(g\left(m\right)_i - d_i\right)^2}{2\sigma_i^2}\right)} 
Where $d$ is the data, $m$ is the proposed model and $\sigma$ is the per data point error (uncorrelated). Hierarchical regression is also supported for all of the regression methods by configuring the lambda parameters in the 1D and 2D dataset structures (by setting the lambda perturbation deviation to a non-zero value). This changes the likelihood slightly to include the $\lambda$ term as follows:
 \Pr(d|m) = \frac{1}{\prod_{i=1}^n \sqrt{2 \pi \cdot (\lambda \cdot \sigma_i)^2}} \exp{\left( \sum_{i = 1}^n \frac{-\left(g\left(m\right)_i - d_i\right)^2}{2(\lambda \cdot \sigma_i)^2}\right)} 
In each of the methods, the results returned are configurable by setting the results parameter using flags. See the resultset1d_t and resultset2d_t types. The default result is just the mean of the ensembles.
Typedef Documentation
typedef void(* regression1d_cb_t) (void *state, double *boundaries, int nboundaries, regression1d_value_at_t value_at, double lambda, void *user_arg)
typedef double(* regression1d_value_at_t) (void *state, double x)
Examples:
1d/partitioned/regression/zeromultistep/zeromultistep.c.
typedef void(* regression2d_cb_t) (void *state, double *x, double *y, int ncells, regression2d_value_at_t value_at, double lambda, void *user_arg)
typedef double(* regression2d_value_at_t) (void *state, double x, double y)
Examples:
2d/partitioned/regression/callbackex/callbackex.c.
Function Documentation
[part1d_natural_regression(const dataset1d_t *dataset, int burnin, int total, int min_part, int max_part, int xsamples, int ysamples, double credible_interval, double pv, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t callback, void *user_arg)]resultset1d_t* part1d_natural_regression (const dataset1d_t * dataset, int burnin, int total, int min_part, int max_part, int xsamples, int ysamples, double credible_interval, double pv, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t callback, void * user_arg)
Multiple partition joined line segments regression.
This method uses joined line segments between partitions so that a continuous function is formed to fit the data. This is useful for determining changes in gradient in the data.
Parameters
dataset The dataset to run the regression on. See the dataset1d_load_known, ::dataset1d_load_estimated, and dataset1d_load_fixed functions.
burnin The number of burn in iterations.
total The total number of iterations.
min_part The minimum number of partitions to allow.
max_part The maximum number of partitions to allow. to the data.
xsamples The number of samples to use for discretization of the horizontal axis.
ysamples The number of samples to use for discretization of the vertical axis when computing mode, median, and credible intervals.
credible_interval The credible interval to use for results expressed as a ratio, i.e. 0.95 for the 95% credible interval.
pv The standard deviation to use when peturbing the y value of a partition. This is needed since we can no longer use the data to determine this. A rule of thumb for selecting this value is to make it around 5 to 10 percent of the range of the data.
pd The standard deviation to use when peturbing the x-position of a partition. The new position is moved by N(0, pd).
random A function pointer to uniform random number generator to use. See the rjmcmc_uniform function.
normal A function pointer to the normal random number generator for generating normally distributed random numbers with 0 mean and a standard deviation of 1. See the rjmcmc_normal function.
results A bit mask of results to store. See resultset1d_result_t.
callback A user function to call for every sample for collecting extra statistics. Set to NULL if this is not needed.
user_arg The user argument to pass to the callback function.
References part1d::accepted, part1d::birth_prob, part1d::current, part1d::current_like, part1d::dataset, part1d::death_prob, part1d::dy, part1d::lambda_prob, _dataset1d::lambdastd, part1d::move_prob, part1d::normal, part1d::nprocesses, part1d::out, part1d_natural_rj_clone(), part1d_natural_rj_create(), part1d_natural_rj_evaluate(), part1d_natural_rj_evaluate_gradient(), part1d_natural_rj_initialize(), part1d_natural_rj_lambda(), part1d_natural_rj_misfit(), part1d_natural_rj_partition_position(), part1d_natural_rj_partitions(), part1d_natural_rj_propose_birth(), part1d_natural_rj_propose_death(), part1d_natural_rj_propose_lambda(), part1d_natural_rj_propose_move(), part1d_natural_rj_propose_value(), part1d::partitions, part1d::process, part1d::proposed, part1d::proposed_like, part1d::random, part1d::results, resultset1d_accept(), resultset1d_assemble_results(), resultset1d_create(), resultset1d_propose(), resultset1d_sample(), resultset1d_sample_gradient(), resultset1d_sample_lambda(), resultset1d_sample_misfit(), resultset1d_sample_npartitions(), resultset1d_sample_partition_x(), rjmcmc_create_array_1d(), rjmcmc_destroy_array_1d(), rjmcmc_engine_run(), rjmcmc_error(), part1d::user_arg, part1d::user_callback, part1d::v, part1d::value_prob, _dataset1d::xmax, _dataset1d::xmin, part1d::xsamples, _dataset1d::ymax, and _dataset1d::ymin.
[part1d_regression(const dataset1d_t *dataset, int burnin, int total, int min_part, int max_part, int max_order, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t callback, void *user_arg)]resultset1d_t* part1d_regression (const dataset1d_t * dataset, int burnin, int total, int min_part, int max_part, int max_order, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t callback, void * user_arg)
Multiple partition arbitrary order regression.
This method fits up to max_order polynomials into a partitioned dataset. The number of partitions and order of polynomials within each partition is determined by the data. If higher order polynomials are permitted (ie > 5) then there can be `ringing` near any discontinuities in the data as a higher order polynomial may fit a discontinuity as well as a 2 discontinuous polynomials. For this reason care should be taken with setting the max_order parameter.
Parameters
dataset The dataset to run the regression on. See the dataset1d_load_known, ::dataset1d_load_estimated, and dataset1d_load_fixed functions.
burnin The number of burn in iterations.
total The total number of iterations.
min_part The minimum number of partitions to allow.
max_part The maximum number of partitions to allow.
max_order The maximum order of the fitting polynomial. to the data.
xsamples The number of samples to use for discretization of the horizontal axis.
ysamples The number of samples to use for discretization of the vertical axis when computing mode, median, and credible intervals.
credible_interval The credible interval to use for results expressed as a ratio, i.e. 0.95 for the 95% credible interval.
pd The standard deviation to use when peturbing the x-position of a partition. The new position is moved by N(0, pd).
random A function pointer to uniform random number generator to use. See the rjmcmc_uniform function.
normal A function pointer to the normal random number generator for generating normally distributed random numbers with 0 mean and a standard deviation of 1. See the rjmcmc_normal function.
results A bit mask of results to store. See resultset1d_result_t.
callback A user function to call for every sample for collecting extra statistics. Set to NULL if this is not needed.
user_arg The user argument to pass to the callback function.
References part1d::accepted, part1d::birth_prob, part1d::current, part1d::current_like, part1d::dataset, part1d::death_prob, part1d::dk, part1d::dy, part1d::lambda_prob, _dataset1d::lambdastd, part1d::move_prob, part1d::normal, part1d::nprocesses, part1d::out, part1d_regression_rj_clone(), part1d_regression_rj_create(), part1d_regression_rj_destroy(), part1d_regression_rj_evaluate(), part1d_regression_rj_initialize(), part1d_regression_rj_lambda(), part1d_regression_rj_misfit(), part1d_regression_rj_order(), part1d_regression_rj_partition_position(), part1d_regression_rj_partitions(), part1d_regression_rj_propose_birth(), part1d_regression_rj_propose_death(), part1d_regression_rj_propose_lambda(), part1d_regression_rj_propose_move(), part1d_regression_rj_propose_value(), part1d::partitions, part1d::process, part1d::proposed, part1d::proposed_like, part1d::random, part1d::results, resultset1d_accept(), resultset1d_assemble_results(), resultset1d_create(), resultset1d_propose(), resultset1d_sample(), resultset1d_sample_lambda(), resultset1d_sample_misfit(), resultset1d_sample_npartitions(), resultset1d_sample_order(), resultset1d_sample_partition_x(), rjmcmc_create_array_1d(), rjmcmc_destroy_array_1d(), rjmcmc_engine_run(), rjmcmc_error(), rjmcmc_random_choose_int(), part1d::user_arg, part1d::user_callback, part1d::v, part1d::value_prob, _dataset1d::xmax, _dataset1d::xmin, part1d::xsamples, _dataset1d::ymax, and _dataset1d::ymin.
[part1d_zero_regression(const dataset1d_t *dataset, int burnin, int total, int min_part, int max_part, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t callback, void *user_arg)]resultset1d_t* part1d_zero_regression (const dataset1d_t * dataset, int burnin, int total, int min_part, int max_part, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t callback, void * user_arg)
Multiple partition zeroth order regression.
This method computes a regression using multiple partitions with zeroth order curves in each partition. The level of the curve is determined from the data within each partition (i.e. sampled from the mean and standard deviation). The exception is when there are too few data points within a partition, in which case the level of the curve is determined by uniformly sampling from the range of the entire dataset. For the detailed theory of this method, see the Theory section part1dzeroreg.
Parameters
dataset The dataset to run the regression on. See the dataset1d_load_known, ::dataset1d_load_estimated, and dataset1d_load_fixed functions.
burnin The number of burn in iterations.
total The total number of iterations.
min_part The minimum number of partitions to allow.
max_part The maximum number of partitions to allow. to the data.
xsamples The number of samples to use for discretization of the horizontal axis.
ysamples The number of samples to use for discretization of the vertical axis when computing mode, median, and credible intervals.
credible_interval The credible interval to use for results expressed as a ratio, i.e. 0.95 for the 95% credible interval.
pd The standard deviation to use when peturbing the x-position of a partition. The new position is moved by N(0, pd).
random A function pointer to uniform random number generator to use. See the rjmcmc_uniform function.
normal A function pointer to the normal random number generator for generating normally distributed random numbers with 0 mean and a standard deviation of 1. See the rjmcmc_normal function.
results A bit mask of results to store. See resultset1d_result_t.
callback A user function to call for every sample for collecting extra statistics. Set to NULL if this is not needed.
user_arg The user argument to pass to the callback function.
References part1d::accepted, part1d::birth_prob, part1d::current, part1d::current_like, part1d::dataset, part1d::death_prob, part1d::dy, part1d::lambda_prob, _dataset1d::lambdastd, part1d::move_prob, part1d::normal, part1d::nprocesses, part1d::out, part1d_zero_clone(), part1d_zero_create(), part1d_zero_destroy(), part1d_zero_evaluate(), part1d_zero_initialize(), part1d_zero_lambda(), part1d_zero_misfit(), part1d_zero_partition_position(), part1d_zero_partitions(), part1d_zero_propose_birth(), part1d_zero_propose_death(), part1d_zero_propose_lambda(), part1d_zero_propose_move(), part1d_zero_propose_value(), part1d::partitions, part1d::process, part1d::proposed, part1d::proposed_like, part1d::random, part1d::results, resultset1d_accept(), resultset1d_assemble_results(), resultset1d_create(), resultset1d_propose(), resultset1d_sample(), resultset1d_sample_lambda(), resultset1d_sample_misfit(), resultset1d_sample_npartitions(), resultset1d_sample_partition_x(), rjmcmc_create_array_1d(), rjmcmc_destroy_array_1d(), rjmcmc_engine_run(), rjmcmc_error(), part1d::user_arg, part1d::user_callback, part1d::v, part1d::value_prob, _dataset1d::xmax, _dataset1d::xmin, part1d::xsamples, _dataset1d::ymax, and _dataset1d::ymin.
[part2d_regression(const dataset2d_t *dataset, int burnin, int total, int min_part, int max_part, int xsamples, int ysamples, int zsamples, double credible_interval, double pv, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression2d_cb_t user_callback, void *user_arg)]resultset2d_t* part2d_regression (const dataset2d_t * dataset, int burnin, int total, int min_part, int max_part, int xsamples, int ysamples, int zsamples, double credible_interval, double pv, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression2d_cb_t user_callback, void * user_arg)
References part2d::accepted, part2d::birth_prob, part2d::current, part2d::current_like, part2d::dataset, part2d::death_prob, part2d::dpart, part2d::dz, part2d::lambda_prob, _dataset2d::lambdastd, part2d::move_prob, part2d::normal, part2d::nprocesses, part2d::out, part2d_regression_rj_clone(), part2d_regression_rj_create(), part2d_regression_rj_destroy(), part2d_regression_rj_evaluate(), part2d_regression_rj_initialize(), part2d_regression_rj_lambda(), part2d_regression_rj_misfit(), part2d_regression_rj_partition_centre(), part2d_regression_rj_partitions(), part2d_regression_rj_propose_birth(), part2d_regression_rj_propose_death(), part2d_regression_rj_propose_lambda(), part2d_regression_rj_propose_move(), part2d_regression_rj_propose_value(), part2d_regression_rj_value_at(), part2d::process, part2d::proposed, part2d::proposed_like, part2d::random, part2d::results, resultset2d_accept(), resultset2d_assemble_results(), resultset2d_create(), resultset2d_propose(), resultset2d_sample(), resultset2d_sample_centre(), resultset2d_sample_lambda(), resultset2d_sample_misfit(), resultset2d_sample_npartitions(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), rjmcmc_random_choose_int(), part2d::user_arg, part2d::user_callback, part2d::user_x_centre, part2d::user_y_centre, part2d::v, part2d::value_prob, x, _dataset2d::xmax, _dataset2d::xmin, part2d::xsamples, y, _dataset2d::ymax, _dataset2d::ymin, part2d::ysamples, _dataset2d::zmax, and _dataset2d::zmin.
resultset1d_t* single1d_direct_regression (const dataset1d_t * dataset, const double * fixed_prior, int max_order, int xsamples, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)
Single Partition Regression with direct integration.
The single1d_regression samples the fit of polynomials drawn from a distribution but it is possible to integrate these out directly and avoid the stochastic sampling process. The benefit of this is that the regression is performed quicker. The downside is that results such as credible intervals are unavailable.
References curvefit_create(), curvefit_evaluate_pk(), single1d::detCm, single1d::kcdf, single1d::max_order, single1d::mean, single1d::mean_misfit, _dataset1d::npoints, single1d::pk, single1d::results, resultset1d_create(), RESULTSET1D_MEAN, resultset1d_sample(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_error(), rjmcmc_polynomial_value(), single1d::S, single1d::sigma, x, _dataset1d::xmax, _dataset1d::xmin, _dataset1d::ymax, and _dataset1d::ymin.
[single1d_regression(const dataset1d_t *dataset, int burnin, int total, int max_order, int xsamples, int ysamples, double credible_interval, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t user_callback, void *user_arg)]resultset1d_t* single1d_regression (const dataset1d_t * dataset, int burnin, int total, int max_order, int xsamples, int ysamples, double credible_interval, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t user_callback, void * user_arg)
Single Partition Regression.
The single1d_regression function performs a regression simulation on a single partition of the given dataset. It will attempt to fit trial polynomials of order 0 to order_max and sampling acceptable polynomials at each order. The method of selecting the order of the polynomial (or the probability distribution of the order of the data) is outlined in [sambridge2006A].
The results are returned in a resultset1d_t structure that can be interrogated with various functions in ::resultset1d.h.
For example of the use of this function, see 1d/single/regression/cubic/cubic.c
Parameters
dataset The dataset to run the regression on. See the dataset1d_load_known, ::dataset1d_load_estimated, and dataset1d_load_fixed functions.
burnin The number of burn in iterations.
total The total number of iterations.
max_order The maximum order of the polynomial to allow when fitting a trial curve to the data.
xsamples The number of samples to use for discretization of the horizontal axis.
ysamples The number of samples to use for discretization of the vertical axis when computing mode, median, and credible intervals.
credible_interval The credible interval to use for results expressed as a ratio, i.e. 0.95 for the 95% credible interval.
random A function pointer to uniform random number generator to use. See the rjmcmc_uniform function.
normal A function pointer to the normal random number generator for generating normally distributed random numbers with 0 mean and a standard deviation of 1. See the rjmcmc_normal function.
results A bit mask of results to store. See resultset1d_result_t.
user_callback An optional callback function to do your own sampling of the generated curves. Set to NULL if you don't need this.
user_arg A user pointer to pass to the callback function.
[single1d_regression_with_prior(const dataset1d_t *dataset, const double *prior, int burnin, int total, int max_order, int xsamples, int ysamples, double credible_interval, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t user_callback, void *user_arg)]resultset1d_t* single1d_regression_with_prior (const dataset1d_t * dataset, const double * prior, int burnin, int total, int max_order, int xsamples, int ysamples, double credible_interval, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t user_callback, void * user_arg)
Single Partition Regression with a custom prior.
Deprecated. Used for testing.