regression.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <math.h>
*
#include <float.h>
*
#include <rjmcmc/regression.h>
*
#include <rjmcmc/engine.h>
*
#include <rjmcmc/resultset1d.h>
*
#include <rjmcmc/single1d_regression.h>
*
#include <rjmcmc/dataset1d.h>
*
#include <rjmcmc/rjmcmc_util.h>
*
#include <rjmcmc/curvefit.h>
*
Data Structures
struct single1d
struct mpi_data
Typedefs
typedef void(* resultassembler_t) (void *user, resultset1d_t *r)
Functions
resultset1d_t * single1d_regression (const dataset1d_t *dataset, int burnin, int total, int max_order, int xsamples, int ysamples, double credible_interval, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t user_callback, void *user_arg)
Single Partition Regression.
resultset1d_t * single1d_regression_with_prior (const dataset1d_t *dataset, const double *prior, int burnin, int total, int max_order, int xsamples, int ysamples, double credible_interval, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t user_callback, void *user_arg)
Single Partition Regression with a custom prior.
resultset1d_t * single1d_direct_regression (const dataset1d_t *dataset, const double *fixed_prior, int max_order, int xsamples, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)
Single Partition Regression with direct integration.
resultset1d_t * MPI_single1d_regression (const dataset1d_t *dataset, int burnin, int total, int max_order, int xsamples, int ysamples, double credible_interval, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t user_callback, void *user_arg, int mpisize, int mpirank, int root, MPI_Comm comm)
Typedef Documentation
typedef void(* resultassembler_t) (void *user, resultset1d_t *r)
Function Documentation
[MPI_single1d_regression(const dataset1d_t *dataset, int burnin, int total, int max_order, int xsamples, int ysamples, double credible_interval, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t user_callback, void *user_arg, int mpisize, int mpirank, int root, MPI_Comm comm)]resultset1d_t* MPI_single1d_regression (const dataset1d_t * dataset, int burnin, int total, int max_order, int xsamples, int ysamples, double credible_interval, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t user_callback, void * user_arg, int mpisize, int mpirank, int root, MPI_Comm comm)
References mpi_data::comm, single1d::current, single1d::current_like, single1d::dataset, single1d::lambda_prob, mpirank, mpisize, single1d::normal, single1d::nprocesses, single1d::out, single1d::process, single1d::proposed, single1d::proposed_like, single1d::random, mpi_data::rank, single1d::results, resultset1d_accept(), resultset1d_propose(), resultset1d_sample(), resultset1d_sample_lambda(), resultset1d_sample_misfit(), resultset1d_sample_order(), rjmcmc_error(), rjmcmc_random_choose_int(), root, mpi_data::root, single1d_regression_clone(), single1d_regression_evaluate(), single1d_regression_initialize(), single1d_regression_lambda(), single1d_regression_misfit(), single1d_regression_order(), single1d_regression_propose_lambda(), single1d_regression_propose_value(), mpi_data::size, single1d::v, single1d::value_prob, _dataset1d::xmax, _dataset1d::xmin, and single1d::xsamples.
resultset1d_t* single1d_direct_regression (const dataset1d_t * dataset, const double * fixed_prior, int max_order, int xsamples, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)
Single Partition Regression with direct integration.
The single1d_regression samples the fit of polynomials drawn from a distribution but it is possible to integrate these out directly and avoid the stochastic sampling process. The benefit of this is that the regression is performed quicker. The downside is that results such as credible intervals are unavailable.
References curvefit_create(), curvefit_evaluate_pk(), single1d::detCm, single1d::kcdf, single1d::max_order, single1d::mean, single1d::mean_misfit, _dataset1d::npoints, single1d::pk, single1d::results, resultset1d_create(), RESULTSET1D_MEAN, resultset1d_sample(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_error(), rjmcmc_polynomial_value(), single1d::S, single1d::sigma, x, _dataset1d::xmax, _dataset1d::xmin, _dataset1d::ymax, and _dataset1d::ymin.
[single1d_regression(const dataset1d_t *dataset, int burnin, int total, int max_order, int xsamples, int ysamples, double credible_interval, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t user_callback, void *user_arg)]resultset1d_t* single1d_regression (const dataset1d_t * dataset, int burnin, int total, int max_order, int xsamples, int ysamples, double credible_interval, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t user_callback, void * user_arg)
Single Partition Regression.
The single1d_regression function performs a regression simulation on a single partition of the given dataset. It will attempt to fit trial polynomials of order 0 to order_max and sampling acceptable polynomials at each order. The method of selecting the order of the polynomial (or the probability distribution of the order of the data) is outlined in [sambridge2006A].
The results are returned in a resultset1d_t structure that can be interrogated with various functions in ::resultset1d.h.
For example of the use of this function, see 1d/single/regression/cubic/cubic.c
Parameters
dataset The dataset to run the regression on. See the dataset1d_load_known, ::dataset1d_load_estimated, and dataset1d_load_fixed functions.
burnin The number of burn in iterations.
total The total number of iterations.
max_order The maximum order of the polynomial to allow when fitting a trial curve to the data.
xsamples The number of samples to use for discretization of the horizontal axis.
ysamples The number of samples to use for discretization of the vertical axis when computing mode, median, and credible intervals.
credible_interval The credible interval to use for results expressed as a ratio, i.e. 0.95 for the 95% credible interval.
random A function pointer to uniform random number generator to use. See the rjmcmc_uniform function.
normal A function pointer to the normal random number generator for generating normally distributed random numbers with 0 mean and a standard deviation of 1. See the rjmcmc_normal function.
results A bit mask of results to store. See resultset1d_result_t.
user_callback An optional callback function to do your own sampling of the generated curves. Set to NULL if you don't need this.
user_arg A user pointer to pass to the callback function.
Examples:
1d/single/regression/cubic/cubic.c.
[single1d_regression_with_prior(const dataset1d_t *dataset, const double *prior, int burnin, int total, int max_order, int xsamples, int ysamples, double credible_interval, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t user_callback, void *user_arg)]resultset1d_t* single1d_regression_with_prior (const dataset1d_t * dataset, const double * prior, int burnin, int total, int max_order, int xsamples, int ysamples, double credible_interval, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t user_callback, void * user_arg)
Single Partition Regression with a custom prior.
Deprecated. Used for testing.