regression_part2d.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <math.h>
*
#include <float.h>
*
#include <rjmcmc/regression.h>
*
#include <rjmcmc/engine.h>
*
#include <rjmcmc/resultset2d.h>
*
#include <rjmcmc/part2d_regression_rj.h>
*
#include <rjmcmc/dataset2d.h>
*
#include <rjmcmc/rjmcmc_util.h>
*
Data Structures
struct part2d
Functions
resultset2d_t * part2d_regression (const dataset2d_t *dataset, int burnin, int total, int min_part, int max_part, int xsamples, int ysamples, int zsamples, double credible_interval, double pv, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression2d_cb_t user_callback, void *user_arg)
Function Documentation
[part2d_regression(const dataset2d_t *dataset, int burnin, int total, int min_part, int max_part, int xsamples, int ysamples, int zsamples, double credible_interval, double pv, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression2d_cb_t user_callback, void *user_arg)]resultset2d_t* part2d_regression (const dataset2d_t * dataset, int burnin, int total, int min_part, int max_part, int xsamples, int ysamples, int zsamples, double credible_interval, double pv, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression2d_cb_t user_callback, void * user_arg)
Examples:
2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References part2d::accepted, part2d::birth_prob, part2d::current, part2d::current_like, part2d::dataset, part2d::death_prob, part2d::dpart, part2d::dz, part2d::lambda_prob, _dataset2d::lambdastd, part2d::move_prob, part2d::normal, part2d::nprocesses, part2d::out, part2d_regression_rj_clone(), part2d_regression_rj_create(), part2d_regression_rj_destroy(), part2d_regression_rj_evaluate(), part2d_regression_rj_initialize(), part2d_regression_rj_lambda(), part2d_regression_rj_misfit(), part2d_regression_rj_partition_centre(), part2d_regression_rj_partitions(), part2d_regression_rj_propose_birth(), part2d_regression_rj_propose_death(), part2d_regression_rj_propose_lambda(), part2d_regression_rj_propose_move(), part2d_regression_rj_propose_value(), part2d_regression_rj_value_at(), part2d::process, part2d::proposed, part2d::proposed_like, part2d::random, part2d::results, resultset2d_accept(), resultset2d_assemble_results(), resultset2d_create(), resultset2d_propose(), resultset2d_sample(), resultset2d_sample_centre(), resultset2d_sample_lambda(), resultset2d_sample_misfit(), resultset2d_sample_npartitions(), rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_engine_run(), rjmcmc_error(), rjmcmc_random_choose_int(), part2d::user_arg, part2d::user_callback, part2d::user_x_centre, part2d::user_y_centre, part2d::v, part2d::value_prob, x, _dataset2d::xmax, _dataset2d::xmin, part2d::xsamples, y, _dataset2d::ymax, _dataset2d::ymin, part2d::ysamples, _dataset2d::zmax, and _dataset2d::zmin.