regression_part1d.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <math.h>
*
#include <float.h>
*
#include <rjmcmc/regression.h>
*
#include <rjmcmc/engine.h>
*
#include <rjmcmc/resultset1d.h>
*
#include <rjmcmc/part1d_regression_rj.h>
*
#include <rjmcmc/dataset1d.h>
*
#include <rjmcmc/rjmcmc_util.h>
*
Data Structures
struct part1d
Functions
resultset1d_t * part1d_regression (const dataset1d_t *dataset, int burnin, int total, int min_part, int max_part, int max_order, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t callback, void *user_arg)
Multiple partition arbitrary order regression.
Function Documentation
[part1d_regression(const dataset1d_t *dataset, int burnin, int total, int min_part, int max_part, int max_order, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t callback, void *user_arg)]resultset1d_t* part1d_regression (const dataset1d_t * dataset, int burnin, int total, int min_part, int max_part, int max_order, int xsamples, int ysamples, double credible_interval, double pd, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, int results, regression1d_cb_t callback, void * user_arg)
Multiple partition arbitrary order regression.
This method fits up to max_order polynomials into a partitioned dataset. The number of partitions and order of polynomials within each partition is determined by the data. If higher order polynomials are permitted (ie > 5) then there can be `ringing` near any discontinuities in the data as a higher order polynomial may fit a discontinuity as well as a 2 discontinuous polynomials. For this reason care should be taken with setting the max_order parameter.
Parameters
dataset The dataset to run the regression on. See the dataset1d_load_known, ::dataset1d_load_estimated, and dataset1d_load_fixed functions.
burnin The number of burn in iterations.
total The total number of iterations.
min_part The minimum number of partitions to allow.
max_part The maximum number of partitions to allow.
max_order The maximum order of the fitting polynomial. to the data.
xsamples The number of samples to use for discretization of the horizontal axis.
ysamples The number of samples to use for discretization of the vertical axis when computing mode, median, and credible intervals.
credible_interval The credible interval to use for results expressed as a ratio, i.e. 0.95 for the 95% credible interval.
pd The standard deviation to use when peturbing the x-position of a partition. The new position is moved by N(0, pd).
random A function pointer to uniform random number generator to use. See the rjmcmc_uniform function.
normal A function pointer to the normal random number generator for generating normally distributed random numbers with 0 mean and a standard deviation of 1. See the rjmcmc_normal function.
results A bit mask of results to store. See resultset1d_result_t.
callback A user function to call for every sample for collecting extra statistics. Set to NULL if this is not needed.
user_arg The user argument to pass to the callback function.
Examples:
1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, and 1d/partitioned/regression/sawtooth/sawtooth.c.
References part1d::accepted, part1d::birth_prob, part1d::current, part1d::current_like, part1d::dataset, part1d::death_prob, part1d::dk, part1d::dy, part1d::lambda_prob, _dataset1d::lambdastd, part1d::move_prob, part1d::normal, part1d::nprocesses, part1d::out, part1d_regression_rj_clone(), part1d_regression_rj_create(), part1d_regression_rj_destroy(), part1d_regression_rj_evaluate(), part1d_regression_rj_initialize(), part1d_regression_rj_lambda(), part1d_regression_rj_misfit(), part1d_regression_rj_order(), part1d_regression_rj_partition_position(), part1d_regression_rj_partitions(), part1d_regression_rj_propose_birth(), part1d_regression_rj_propose_death(), part1d_regression_rj_propose_lambda(), part1d_regression_rj_propose_move(), part1d_regression_rj_propose_value(), part1d::partitions, part1d::process, part1d::proposed, part1d::proposed_like, part1d::random, part1d::results, resultset1d_accept(), resultset1d_assemble_results(), resultset1d_create(), resultset1d_propose(), resultset1d_sample(), resultset1d_sample_lambda(), resultset1d_sample_misfit(), resultset1d_sample_npartitions(), resultset1d_sample_order(), resultset1d_sample_partition_x(), rjmcmc_create_array_1d(), rjmcmc_destroy_array_1d(), rjmcmc_engine_run(), rjmcmc_error(), rjmcmc_random_choose_int(), part1d::user_arg, part1d::user_callback, part1d::v, part1d::value_prob, _dataset1d::xmax, _dataset1d::xmin, part1d::xsamples, _dataset1d::ymax, and _dataset1d::ymin.