resultset1d.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <rjmcmc/resultset1d.h>
*
#include <rjmcmc/rjmcmc_util.h>
*
#include <rjmcmc/rjmcmc_defines.h>
*
Data Structures
struct _resultset1d
Functions
resultset1d_t * resultset1d_create (int burnin, int total, int xsamples, int ysamples, int nprocesses, int maxpartitions, int maxorder, double xmin, double xmax, double ymin, double ymax, double credible_interval, int results)
void resultset1d_destroy (resultset1d_t *r)
void resultset1d_propose (resultset1d_t *r, int p)
void resultset1d_accept (resultset1d_t *r, int p)
void resultset1d_sample (resultset1d_t *r, int i, const double *v)
void resultset1d_sample_gradient (resultset1d_t *r, int i, const double *dv)
void resultset1d_sample_misfit (resultset1d_t *r, int i, double misfit)
void resultset1d_sample_order (resultset1d_t *r, int i, int order)
void resultset1d_sample_lambda (resultset1d_t *r, int i, double lambda)
void resultset1d_sample_npartitions (resultset1d_t *r, int i, int npartitions)
void resultset1d_sample_partition_x (resultset1d_t *r, int i, double x)
void resultset1d_assemble_results (resultset1d_t *r)
void MPI_resultset1d_assemble_results (resultset1d_t *r, int mpisize, int mpirank, int root, MPI_Comm comm)
const int * resultset1d_get_propose (resultset1d_t *r, int *nprocesses)
const int * resultset1d_get_accept (resultset1d_t *r, int *nprocesses)
const double * resultset1d_get_misfit (resultset1d_t *r)
const int * resultset1d_get_order (resultset1d_t *r)
const double * resultset1d_get_lambda (resultset1d_t *r)
const int * resultset1d_get_partitions (resultset1d_t *r)
const int * resultset1d_get_partition_x_histogram (resultset1d_t *r)
const double * resultset1d_get_mean (resultset1d_t *r)
const double * resultset1d_get_median (resultset1d_t *r)
const double * resultset1d_get_mode (resultset1d_t *r)
const double * resultset1d_get_credible_min (resultset1d_t *r)
const double * resultset1d_get_credible_max (resultset1d_t *r)
const int ** resultset1d_get_histogram (resultset1d_t *r)
const double * resultset1d_get_gradient (resultset1d_t *r)
const double * resultset1d_get_gradient_credible_min (resultset1d_t *r)
const double * resultset1d_get_gradient_credible_max (resultset1d_t *r)
int resultset1d_get_total (resultset1d_t *r)
int resultset1d_get_max_partitions (resultset1d_t *r)
int resultset1d_get_xsamples (resultset1d_t *r)
int resultset1d_get_ysamples (resultset1d_t *r)
int resultset1d_get_max_order (resultset1d_t *r)
void resultset1d_fill_xcoord_vector (resultset1d_t *r, double *x)
void resultset1d_fill_ycoord_vector (resultset1d_t *r, double *y)
Function Documentation
void MPI_resultset1d_assemble_results (resultset1d_t * r, int mpisize, int mpirank, int root, MPI_Comm comm)
References _resultset1d::accept, _resultset1d::burnin, _resultset1d::conf_interval, _resultset1d::conf_max, _resultset1d::conf_min, _resultset1d::gradient, _resultset1d::gradient_conf_max, _resultset1d::gradient_conf_min, _resultset1d::gradient_hist, _resultset1d::gradmax, _resultset1d::gradmin, _resultset1d::hist, _resultset1d::mean, _resultset1d::median, _resultset1d::mode, mpisize, _resultset1d::nprocesses, _resultset1d::propose, rjmcmc_create_array_1d(), rjmcmc_create_int_array_1d(), rjmcmc_error(), rjmcmc_head_from_histogram(), rjmcmc_median_from_histogram(), rjmcmc_mode_from_histogram(), rjmcmc_tail_from_histogram(), _resultset1d::total, _resultset1d::xsamples, _resultset1d::ymax, _resultset1d::ymin, and _resultset1d::ysamples.
void resultset1d_accept (resultset1d_t * r, int p)
References _resultset1d::accept, _resultset1d::nprocesses, and RJMCMC_INDEXCHECKVOID.
Referenced by MPI_single1d_regression(), part1d_natural_regression(), part1d_regression(), and part1d_zero_regression().
void resultset1d_assemble_results (resultset1d_t * r)
References _resultset1d::burnin, _resultset1d::conf_interval, _resultset1d::conf_max, _resultset1d::conf_min, _resultset1d::gradient, _resultset1d::gradient_conf_max, _resultset1d::gradient_conf_min, _resultset1d::gradient_hist, _resultset1d::gradmax, _resultset1d::gradmin, _resultset1d::hist, _resultset1d::mean, _resultset1d::median, _resultset1d::mode, rjmcmc_head_from_histogram(), rjmcmc_median_from_histogram(), rjmcmc_mode_from_histogram(), rjmcmc_tail_from_histogram(), _resultset1d::total, _resultset1d::xsamples, _resultset1d::ymax, _resultset1d::ymin, and _resultset1d::ysamples.
Referenced by part1d_natural_regression(), part1d_regression(), and part1d_zero_regression().
resultset1d_t* resultset1d_create (int burnin, int total, int xsamples, int ysamples, int nprocesses, int maxpartitions, int maxorder, double xmin, double xmax, double ymin, double ymax, double credible_interval, int results)
References _resultset1d::accept, _resultset1d::burnin, _resultset1d::conf_interval, _resultset1d::conf_max, _resultset1d::conf_min, credible_interval, _resultset1d::gradient, _resultset1d::gradient_conf_max, _resultset1d::gradient_conf_min, _resultset1d::gradient_hist, _resultset1d::gradmax, _resultset1d::gradmin, _resultset1d::hist, _resultset1d::lambda, _resultset1d::maxorder, _resultset1d::maxpartitions, _resultset1d::mean, _resultset1d::median, _resultset1d::misfit, _resultset1d::mode, _resultset1d::nprocesses, _resultset1d::order, _resultset1d::partition_x_hist, _resultset1d::partitions, _resultset1d::propose, _resultset1d::results, RESULTSET1D_CREDIBLE, RESULTSET1D_GRADIENT, RESULTSET1D_MEAN, RESULTSET1D_MEDIAN, RESULTSET1D_MODE, rjmcmc_create_array_1d(), rjmcmc_create_int_array_1d(), rjmcmc_create_int_array_2d(), _resultset1d::total, _resultset1d::xmax, _resultset1d::xmin, _resultset1d::xsamples, _resultset1d::ymax, _resultset1d::ymin, and _resultset1d::ysamples.
Referenced by part1d_natural_regression(), part1d_regression(), part1d_zero_regression(), and single1d_direct_regression().
void resultset1d_destroy (resultset1d_t * r)
Examples:
1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, 1d/partitioned/regression/sawtooth/sawtooth.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, and 1d/single/regression/cubic/cubic.c.
References _resultset1d::accept, _resultset1d::conf_max, _resultset1d::conf_min, _resultset1d::gradient, _resultset1d::gradient_conf_max, _resultset1d::gradient_conf_min, _resultset1d::gradient_hist, _resultset1d::hist, _resultset1d::lambda, _resultset1d::mean, _resultset1d::median, _resultset1d::misfit, _resultset1d::mode, _resultset1d::order, _resultset1d::partition_x_hist, _resultset1d::partitions, _resultset1d::propose, rjmcmc_destroy_array_1d(), rjmcmc_destroy_int_array_1d(), rjmcmc_destroy_int_array_2d(), and _resultset1d::xsamples.
void resultset1d_fill_xcoord_vector (resultset1d_t * r, double * x)
Examples:
1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, 1d/partitioned/regression/sawtooth/sawtooth.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, and 1d/single/regression/cubic/cubic.c.
References rjmcmc_fill_coord_vector(), _resultset1d::xmax, _resultset1d::xmin, and _resultset1d::xsamples.
void resultset1d_fill_ycoord_vector (resultset1d_t * r, double * y)
References rjmcmc_fill_coord_vector(), _resultset1d::ymax, _resultset1d::ymin, and _resultset1d::ysamples.
const int* resultset1d_get_accept (resultset1d_t * r, int * nprocesses)
Examples:
1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, 1d/partitioned/regression/sawtooth/sawtooth.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, and 1d/single/regression/cubic/cubic.c.
References _resultset1d::accept, and _resultset1d::nprocesses.
const double* resultset1d_get_credible_max (resultset1d_t * r)
Examples:
1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, 1d/partitioned/regression/sawtooth/sawtooth.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, and 1d/single/regression/cubic/cubic.c.
References _resultset1d::conf_max.
const double* resultset1d_get_credible_min (resultset1d_t * r)
Examples:
1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, 1d/partitioned/regression/sawtooth/sawtooth.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, and 1d/single/regression/cubic/cubic.c.
References _resultset1d::conf_min.
const double* resultset1d_get_gradient (resultset1d_t * r)
References _resultset1d::gradient.
const double* resultset1d_get_gradient_credible_max (resultset1d_t * r)
References _resultset1d::gradient_conf_max.
const double* resultset1d_get_gradient_credible_min (resultset1d_t * r)
References _resultset1d::gradient_conf_min.
const int** resultset1d_get_histogram (resultset1d_t * r)
References _resultset1d::hist.
const double* resultset1d_get_lambda (resultset1d_t * r)
Examples:
1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, and 1d/single/regression/cubic/cubic.c.
References _resultset1d::lambda.
int resultset1d_get_max_order (resultset1d_t * r)
References _resultset1d::maxorder.
int resultset1d_get_max_partitions (resultset1d_t * r)
References _resultset1d::total.
const double* resultset1d_get_mean (resultset1d_t * r)
Examples:
1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, 1d/partitioned/regression/sawtooth/sawtooth.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, and 1d/single/regression/cubic/cubic.c.
References _resultset1d::mean.
const double* resultset1d_get_median (resultset1d_t * r)
Examples:
1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, 1d/partitioned/regression/sawtooth/sawtooth.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, and 1d/single/regression/cubic/cubic.c.
References _resultset1d::median.
const double* resultset1d_get_misfit (resultset1d_t * r)
Examples:
1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, 1d/partitioned/regression/sawtooth/sawtooth.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, and 1d/single/regression/cubic/cubic.c.
References _resultset1d::misfit.
const double* resultset1d_get_mode (resultset1d_t * r)
Examples:
1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, 1d/partitioned/regression/sawtooth/sawtooth.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, and 1d/single/regression/cubic/cubic.c.
References _resultset1d::mode.
const int* resultset1d_get_order (resultset1d_t * r)
Examples:
1d/partitioned/regression/multiquad/multiquad.c, and 1d/single/regression/cubic/cubic.c.
References _resultset1d::order.
const int* resultset1d_get_partition_x_histogram (resultset1d_t * r)
Examples:
1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, and 1d/partitioned/regression/zeromultistep/zeromultistep.c.
References _resultset1d::partition_x_hist.
const int* resultset1d_get_partitions (resultset1d_t * r)
Examples:
1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, and 1d/partitioned/regression/zeromultistep/zeromultistep.c.
References _resultset1d::partitions.
const int* resultset1d_get_propose (resultset1d_t * r, int * nprocesses)
Examples:
1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, 1d/partitioned/regression/sawtooth/sawtooth.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, and 1d/single/regression/cubic/cubic.c.
References _resultset1d::nprocesses, and _resultset1d::propose.
int resultset1d_get_total (resultset1d_t * r)
References _resultset1d::total.
int resultset1d_get_xsamples (resultset1d_t * r)
References _resultset1d::xsamples.
int resultset1d_get_ysamples (resultset1d_t * r)
References _resultset1d::ysamples.
void resultset1d_propose (resultset1d_t * r, int p)
References _resultset1d::nprocesses, _resultset1d::propose, and RJMCMC_INDEXCHECKVOID.
Referenced by MPI_single1d_regression(), part1d_natural_regression(), part1d_regression(), and part1d_zero_regression().
void resultset1d_sample (resultset1d_t * r, int i, const double * v)
References _resultset1d::burnin, _resultset1d::hist, _resultset1d::mean, RJMCMC_INDEXCHECKVOID, rjmcmc_map_to_index(), _resultset1d::total, _resultset1d::xsamples, _resultset1d::ymax, _resultset1d::ymin, and _resultset1d::ysamples.
Referenced by MPI_single1d_regression(), part1d_natural_regression(), part1d_regression(), part1d_zero_regression(), and single1d_direct_regression().
void resultset1d_sample_gradient (resultset1d_t * r, int i, const double * dv)
References _resultset1d::burnin, _resultset1d::gradient, _resultset1d::gradient_hist, _resultset1d::gradmax, _resultset1d::gradmin, RJMCMC_INDEXCHECKVOID, rjmcmc_map_to_index(), _resultset1d::total, _resultset1d::xsamples, and _resultset1d::ysamples.
Referenced by part1d_natural_regression().
void resultset1d_sample_lambda (resultset1d_t * r, int i, double lambda)
References _resultset1d::lambda, RJMCMC_INDEXCHECKVOID, and _resultset1d::total.
Referenced by MPI_single1d_regression(), part1d_natural_regression(), part1d_regression(), and part1d_zero_regression().
void resultset1d_sample_misfit (resultset1d_t * r, int i, double misfit)
References _resultset1d::misfit, RJMCMC_INDEXCHECKVOID, and _resultset1d::total.
Referenced by MPI_single1d_regression(), part1d_natural_regression(), part1d_regression(), and part1d_zero_regression().
void resultset1d_sample_npartitions (resultset1d_t * r, int i, int npartitions)
References _resultset1d::partitions, RJMCMC_INDEXCHECKVOID, and _resultset1d::total.
Referenced by part1d_natural_regression(), part1d_regression(), and part1d_zero_regression().
void resultset1d_sample_order (resultset1d_t * r, int i, int order)
References _resultset1d::maxorder, _resultset1d::order, and RJMCMC_INDEXCHECKVOID.
Referenced by MPI_single1d_regression(), and part1d_regression().
void resultset1d_sample_partition_x (resultset1d_t * r, int i, double x)
References _resultset1d::partition_x_hist, rjmcmc_map_to_index(), _resultset1d::xmax, _resultset1d::xmin, and _resultset1d::xsamples.
Referenced by part1d_natural_regression(), part1d_regression(), and part1d_zero_regression().