resultset2d.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include `rjmcmc/resultset2d.h`
*
#include `rjmcmc/rjmcmc_util.h`
*
#include `rjmcmc/rjmcmc_defines.h`
*
Data Structures
struct _resultset2d
Functions
resultset2d_t * resultset2d_create (int burnin, int total, int xsamples, int ysamples, int zsamples, int nprocesses, int maxpartitions, double xmin, double xmax, double ymin, double ymax, double zmin, double zmax, double credible_interval, int results)
void resultset2d_destroy (resultset2d_t *r)
void resultset2d_propose (resultset2d_t *r, int p)
void resultset2d_accept (resultset2d_t *r, int p)
void resultset2d_sample (resultset2d_t *r, int i, const double **v)
void resultset2d_sample_misfit (resultset2d_t *r, int i, double misfit)
void resultset2d_sample_centre (resultset2d_t *r, double x, double y)
void resultset2d_sample_lambda (resultset2d_t *r, int i, double lambda)
void resultset2d_sample_npartitions (resultset2d_t *r, int i, int npartitions)
void resultset2d_assemble_results (resultset2d_t *r)
const int * resultset2d_get_propose (resultset2d_t *r, int *nprocesses)
const int * resultset2d_get_accept (resultset2d_t *r, int *nprocesses)
const double * resultset2d_get_misfit (resultset2d_t *r)
const double * resultset2d_get_lambda (resultset2d_t *r)
const int * resultset2d_get_partitions (resultset2d_t *r)
const double ** resultset2d_get_mean (resultset2d_t *r)
const int ** resultset2d_get_centres (resultset2d_t *r)
const double ** resultset2d_get_median (resultset2d_t *r)
const double ** resultset2d_get_mode (resultset2d_t *r)
const double ** resultset2d_get_credible_min (resultset2d_t *r)
const double ** resultset2d_get_credible_max (resultset2d_t *r)
void resultset2d_fill_xcoord_vector (resultset2d_t *r, double *x, int *l)
void resultset2d_fill_ycoord_vector (resultset2d_t *r, double *y, int *l)
void resultset2d_fill_zcoord_vector (resultset2d_t *r, double *z, int *l)
Function Documentation
void resultset2d_accept (resultset2d_t * r, int p)
References _resultset2d::accept, _resultset2d::nprocesses, and RJMCMC_INDEXCHECKVOID.
Referenced by part2d_regression().
void resultset2d_assemble_results (resultset2d_t * r)
References _resultset2d::burnin, _resultset2d::conf_interval, _resultset2d::conf_max, _resultset2d::conf_min, _resultset2d::hist, _resultset2d::mean, _resultset2d::median, _resultset2d::mode, rjmcmc_head_from_histogram(), rjmcmc_median_from_histogram(), rjmcmc_mode_from_histogram(), rjmcmc_tail_from_histogram(), _resultset2d::total, _resultset2d::xsamples, _resultset2d::ysamples, _resultset2d::zmax, _resultset2d::zmin, and _resultset2d::zsamples.
Referenced by part2d_regression().
resultset2d_t* resultset2d_create (int burnin, int total, int xsamples, int ysamples, int zsamples, int nprocesses, int maxpartitions, double xmin, double xmax, double ymin, double ymax, double zmin, double zmax, double credible_interval, int results)
References _resultset2d::accept, _resultset2d::burnin, _resultset2d::centres, _resultset2d::conf_interval, _resultset2d::conf_max, _resultset2d::conf_min, credible_interval, _resultset2d::hist, _resultset2d::lambda, _resultset2d::max_partitions, _resultset2d::mean, _resultset2d::median, _resultset2d::misfit, _resultset2d::mode, _resultset2d::nprocesses, _resultset2d::partitions, _resultset2d::propose, _resultset2d::results, RESULTSET2D_CREDIBLE, RESULTSET2D_MEAN, RESULTSET2D_MEDIAN, RESULTSET2D_MODE, rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_create_int_array_1d(), rjmcmc_create_int_array_2d(), rjmcmc_create_int_array_3d(), _resultset2d::total, _resultset2d::xmax, _resultset2d::xmin, _resultset2d::xsamples, _resultset2d::ymax, _resultset2d::ymin, _resultset2d::ysamples, _resultset2d::zmax, _resultset2d::zmin, and _resultset2d::zsamples.
Referenced by part2d_regression().
void resultset2d_destroy (resultset2d_t * r)
Examples:
2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References _resultset2d::accept, _resultset2d::centres, _resultset2d::conf_max, _resultset2d::conf_min, _resultset2d::hist, _resultset2d::lambda, _resultset2d::mean, _resultset2d::median, _resultset2d::misfit, _resultset2d::mode, _resultset2d::partitions, _resultset2d::propose, rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_destroy_int_array_1d(), rjmcmc_destroy_int_array_2d(), rjmcmc_destroy_int_array_3d(), _resultset2d::xsamples, and _resultset2d::ysamples.
void resultset2d_fill_xcoord_vector (resultset2d_t * r, double * x, int * l)
Examples:
2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References _resultset2d::xmax, _resultset2d::xmin, and _resultset2d::xsamples.
void resultset2d_fill_ycoord_vector (resultset2d_t * r, double * y, int * l)
Examples:
2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References _resultset2d::ymax, _resultset2d::ymin, and _resultset2d::ysamples.
void resultset2d_fill_zcoord_vector (resultset2d_t * r, double * z, int * l)
References _resultset2d::zmax, _resultset2d::zmin, and _resultset2d::zsamples.
const int* resultset2d_get_accept (resultset2d_t * r, int * nprocesses)
Examples:
2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References _resultset2d::accept, and _resultset2d::nprocesses.
const int** resultset2d_get_centres (resultset2d_t * r)
Examples:
2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References _resultset2d::centres.
const double** resultset2d_get_credible_max (resultset2d_t * r)
Examples:
2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References _resultset2d::conf_max.
const double** resultset2d_get_credible_min (resultset2d_t * r)
Examples:
2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References _resultset2d::conf_min.
const double* resultset2d_get_lambda (resultset2d_t * r)
Examples:
2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References _resultset2d::lambda.
const double** resultset2d_get_mean (resultset2d_t * r)
Examples:
2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References _resultset2d::mean.
const double** resultset2d_get_median (resultset2d_t * r)
Examples:
2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References _resultset2d::median.
const double* resultset2d_get_misfit (resultset2d_t * r)
Examples:
2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References _resultset2d::misfit.
const double** resultset2d_get_mode (resultset2d_t * r)
Examples:
2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References _resultset2d::mode.
const int* resultset2d_get_partitions (resultset2d_t * r)
Examples:
2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References _resultset2d::partitions.
const int* resultset2d_get_propose (resultset2d_t * r, int * nprocesses)
Examples:
2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References _resultset2d::nprocesses, and _resultset2d::propose.
void resultset2d_propose (resultset2d_t * r, int p)
References _resultset2d::nprocesses, _resultset2d::propose, and RJMCMC_INDEXCHECKVOID.
Referenced by part2d_regression().
void resultset2d_sample (resultset2d_t * r, int i, const double ** v)
References _resultset2d::burnin, _resultset2d::hist, _resultset2d::mean, RJMCMC_INDEXCHECKVOID, rjmcmc_map_to_index(), _resultset2d::total, _resultset2d::xsamples, _resultset2d::ysamples, _resultset2d::zmax, _resultset2d::zmin, and _resultset2d::zsamples.
Referenced by part2d_regression().
void resultset2d_sample_centre (resultset2d_t * r, double x, double y)
References _resultset2d::centres, rjmcmc_map_to_index(), _resultset2d::xmax, _resultset2d::xmin, _resultset2d::xsamples, _resultset2d::ymax, _resultset2d::ymin, and _resultset2d::ysamples.
Referenced by part2d_regression().
void resultset2d_sample_lambda (resultset2d_t * r, int i, double lambda)
References _resultset2d::lambda, RJMCMC_INDEXCHECKVOID, and _resultset2d::total.
Referenced by part2d_regression().
void resultset2d_sample_misfit (resultset2d_t * r, int i, double misfit)
References _resultset2d::misfit, RJMCMC_INDEXCHECKVOID, and _resultset2d::total.
Referenced by part2d_regression().
void resultset2d_sample_npartitions (resultset2d_t * r, int i, int npartitions)
References _resultset2d::partitions, RJMCMC_INDEXCHECKVOID, and _resultset2d::total.
Referenced by part2d_regression().