resultset1dfm.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <rjmcmc/resultset1dfm.h>
*
#include <rjmcmc/rjmcmc_util.h>
*
#include <rjmcmc/rjmcmc_defines.h>
*
#include <rjmcmc/rjmcmc_debug.h>
*
Data Structures
struct _resultset1dfm
Functions
resultset1dfm_t * resultset1dfm_create (int burnin, int total, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, int xsamples, int ysamples, int maxpartitions, double xmin, double xmax, int nprocesses, double credible_interval, int results)
void resultset1dfm_destroy (resultset1dfm_t *r)
void resultset1dfm_propose (resultset1dfm_t *r, int p)
void resultset1dfm_accept (resultset1dfm_t *r, int p)
void resultset1dfm_propose_local_value (resultset1dfm_t *r, int li)
void resultset1dfm_accept_local_value (resultset1dfm_t *r, int li)
void resultset1dfm_sample_global_parameter (resultset1dfm_t *r, int i, int gi, double g)
void resultset1dfm_sample_local_parameter (resultset1dfm_t *r, int i, int li, double *l)
void resultset1dfm_sample_misfit (resultset1dfm_t *r, int i, double misfit)
void resultset1dfm_sample_npartitions (resultset1dfm_t *r, int i, int npartitions)
void resultset1dfm_sample_partition_x (resultset1dfm_t *r, double x)
void resultset1dfm_sample_hierarchical (resultset1dfm_t *r, int i, int si, double hierarchical)
void resultset1dfm_assemble_results (resultset1dfm_t *r)
void MPI_resultset1dfm_assemble_results (resultset1dfm_t *r, int mpisize, int mpirank, int root, MPI_Comm comm)
int resultset1dfm_get_max_partitions (resultset1dfm_t *r)
int resultset1dfm_get_total (resultset1dfm_t *r)
int resultset1dfm_get_xsamples (resultset1dfm_t *r)
int resultset1dfm_get_nparameters (resultset1dfm_t *r)
const int * resultset1dfm_get_propose (resultset1dfm_t *r, int *nprocesses)
int resultset1dfm_get_propose_f (resultset1dfm_t *r, int maxsize, int *propose)
const int * resultset1dfm_get_accept (resultset1dfm_t *r, int *nprocesses)
int resultset1dfm_get_accept_f (resultset1dfm_t *r, int maxsize, int *accept)
const double * resultset1dfm_get_misfit (resultset1dfm_t *r)
int resultset1dfm_get_misfit_f (resultset1dfm_t *r, int maxsize, double *misfit)
const int * resultset1dfm_get_partitions (resultset1dfm_t *r)
int resultset1dfm_get_partitions_f (resultset1dfm_t *r, int maxsize, int *partitions)
const int * resultset1dfm_get_partition_x_histogram (resultset1dfm_t *r)
int resultset1dfm_get_partition_x_histogram_f (resultset1dfm_t *r, int maxsize, int *histogram)
const double * resultset1dfm_get_global_parameter (resultset1dfm_t *r, int gi)
int resultset1dfm_get_global_parameter_f (resultset1dfm_t *r, int gi, int maxsize, double *global)
const double * resultset1dfm_get_local_parameter_mean (resultset1dfm_t *r, int li)
int resultset1dfm_get_local_parameter_mean_f (resultset1dfm_t *r, int li, int maxsize, double *mean)
const double * resultset1dfm_get_local_parameter_median (resultset1dfm_t *r, int li)
int resultset1dfm_get_local_parameter_median_f (resultset1dfm_t *r, int li, int maxsize, double *median)
const double * resultset1dfm_get_local_parameter_mode (resultset1dfm_t *r, int li)
int resultset1dfm_get_local_parameter_mode_f (resultset1dfm_t *r, int li, int maxsize, double *mode)
const double * resultset1dfm_get_local_parameter_credible_min (resultset1dfm_t *r, int li)
int resultset1dfm_get_local_parameter_credible_min_f (resultset1dfm_t *r, int li, int maxsize, double *credible_min)
const double * resultset1dfm_get_local_parameter_credible_max (resultset1dfm_t *r, int li)
int resultset1dfm_get_local_parameter_credible_max_f (resultset1dfm_t *r, int li, int maxsize, double *credible_max)
const int ** resultset1dfm_get_local_parameter_histogram (resultset1dfm_t *r, int li)
int resultset1dfm_get_local_parameter_histogram_f (resultset1dfm_t *r, int li, int xsamples, int ysamples, int *histogram)
const double * resultset1dfm_get_hierarchical (resultset1dfm_t *r, int si)
int resultset1dfm_get_hierarchical_f (resultset1dfm_t *r, int hi, int maxsize, double *hierarchical)
void resultset1dfm_fill_xcoord_vector (resultset1dfm_t *r, double *x, int *l)
int resultset1dfm_get_xcoord_vector_f (resultset1dfm_t *r, int maxsize, double *x)
void resultset1dfm_fill_ycoord_vector (resultset1dfm_t *r, int li, double *y, int *l)
int resultset1dfm_get_ycoord_vector_f (resultset1dfm_t *r, int li, int maxsize, double *y)
Function Documentation
void MPI_resultset1dfm_assemble_results (resultset1dfm_t * r, int mpisize, int mpirank, int root, MPI_Comm comm)
References _resultset1dfm::accept, _resultset1dfm::burnin, _resultset1dfm::credible_interval, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _resultset1dfm::histogram, _resultset1dfm::local_cred_max, _resultset1dfm::local_cred_min, _resultset1dfm::local_mean, _resultset1dfm::local_median, _resultset1dfm::local_mode, _resultset1dfm::local_parameters, mpisize, _resultset1dfm::nlocalparameters, _resultset1dfm::nprocesses, _resultset1dfm::propose, rjmcmc_create_array_1d(), rjmcmc_create_int_array_1d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_int_array_1d(), rjmcmc_error(), rjmcmc_head_from_histogram(), rjmcmc_median_from_histogram(), rjmcmc_mode_from_histogram(), rjmcmc_tail_from_histogram(), _resultset1dfm::total, _resultset1dfm::xsamples, and _resultset1dfm::ysamples.
Referenced by MPI_part1d_forwardmodel(), MPI_part1d_forwardmodel_hierarchical(), MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().
void resultset1dfm_accept (resultset1dfm_t * r, int p)
References _resultset1dfm::accept, _resultset1dfm::nprocesses, and RJMCMC_INDEXCHECKVOID.
Referenced by MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().
void resultset1dfm_accept_local_value (resultset1dfm_t * r, int li)
References _resultset1dfm::accept_local, _resultset1dfm::nlocalparameters, and RJMCMC_INDEXCHECKVOID.
Referenced by MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().
void resultset1dfm_assemble_results (resultset1dfm_t * r)
References _resultset1dfm::burnin, _resultset1dfm::credible_interval, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _resultset1dfm::histogram, _resultset1dfm::local_cred_max, _resultset1dfm::local_cred_min, _resultset1dfm::local_mean, _resultset1dfm::local_median, _resultset1dfm::local_mode, _resultset1dfm::local_parameters, _resultset1dfm::nlocalparameters, rjmcmc_head_from_histogram(), rjmcmc_median_from_histogram(), rjmcmc_mode_from_histogram(), rjmcmc_tail_from_histogram(), _resultset1dfm::total, _resultset1dfm::xsamples, and _resultset1dfm::ysamples.
Referenced by part1d_forwardmodel(), part1d_forwardmodel_hierarchical(), part1d_forwardmodel_natural(), part1d_forwardmodel_natural_finish(), part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel_natural_hierarchical_finish(), and part1d_forwardmodel_zero_cubic().
[resultset1dfm_create(int burnin, int total, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, int xsamples, int ysamples, int maxpartitions, double xmin, double xmax, int nprocesses, double credible_interval, int results)]resultset1dfm_t* resultset1dfm_create (int burnin, int total, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, int xsamples, int ysamples, int maxpartitions, double xmin, double xmax, int nprocesses, double credible_interval, int results)
References _resultset1dfm::accept, _resultset1dfm::accept_local, _resultset1dfm::burnin, _resultset1dfm::credible_interval, _resultset1dfm::global, _resultset1dfm::global_parameters, _resultset1dfm::hierarchical, _resultset1dfm::histogram, _resultset1dfm::local_cred_max, _resultset1dfm::local_cred_min, _resultset1dfm::local_mean, _resultset1dfm::local_median, _resultset1dfm::local_mode, _resultset1dfm::local_parameters, _resultset1dfm::maxpartitions, _resultset1dfm::misfit, _resultset1dfm::nglobalparameters, _resultset1dfm::nhierarchical, _resultset1dfm::nlocalparameters, _resultset1dfm::nprocesses, _resultset1dfm::partition_x_hist, _resultset1dfm::partitions, _resultset1dfm::propose, _resultset1dfm::propose_local, _resultset1dfm::results, RESULTSET1DFM_CREDIBLE, RESULTSET1DFM_MEDIAN, RESULTSET1DFM_MODE, rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_create_int_array_1d(), rjmcmc_create_int_array_3d(), _resultset1dfm::total, _resultset1dfm::xmax, _resultset1dfm::xmin, _resultset1dfm::xsamples, and _resultset1dfm::ysamples.
Referenced by MPI_part1d_forwardmodel(), MPI_part1d_forwardmodel_hierarchical(), MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel(), part1d_forwardmodel_hierarchical(), part1d_forwardmodel_natural(), part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel_natural_hierarchical_init(), part1d_forwardmodel_natural_init(), and part1d_forwardmodel_zero_cubic().
void resultset1dfm_destroy (resultset1dfm_t * r)
Examples:
1d/partitioned/fm/functionfit/functionfit.c, and 1d/partitioned/fm/regression/regression.c.
References _resultset1dfm::accept, _resultset1dfm::accept_local, _resultset1dfm::global, _resultset1dfm::hierarchical, _resultset1dfm::histogram, _resultset1dfm::local_cred_max, _resultset1dfm::local_cred_min, _resultset1dfm::local_mean, _resultset1dfm::local_median, _resultset1dfm::local_mode, _resultset1dfm::misfit, _resultset1dfm::nglobalparameters, _resultset1dfm::nhierarchical, _resultset1dfm::nlocalparameters, _resultset1dfm::partition_x_hist, _resultset1dfm::partitions, _resultset1dfm::propose, _resultset1dfm::propose_local, rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_destroy_int_array_1d(), rjmcmc_destroy_int_array_3d(), and _resultset1dfm::xsamples.
void resultset1dfm_fill_xcoord_vector (resultset1dfm_t * r, double * x, int * l)
Examples:
1d/partitioned/fm/functionfit/functionfit.c, and 1d/partitioned/fm/regression/regression.c.
References rjmcmc_fill_coord_vector(), _resultset1dfm::xmax, _resultset1dfm::xmin, and _resultset1dfm::xsamples.
Referenced by MPI_part1d_forwardmodel(), MPI_part1d_forwardmodel_hierarchical(), MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel(), part1d_forwardmodel_hierarchical(), part1d_forwardmodel_natural(), part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel_natural_hierarchical_init(), part1d_forwardmodel_natural_init(), part1d_forwardmodel_zero_cubic(), and resultset1dfm_get_xcoord_vector_f().
void resultset1dfm_fill_ycoord_vector (resultset1dfm_t * r, int li, double * y, int * l)
References _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _resultset1dfm::local_parameters, rjmcmc_fill_coord_vector(), _resultset1dfm::xsamples, and _resultset1dfm::ysamples.
Referenced by resultset1dfm_get_ycoord_vector_f().
const int* resultset1dfm_get_accept (resultset1dfm_t * r, int * nprocesses)
Examples:
1d/partitioned/fm/functionfit/functionfit.c, and 1d/partitioned/fm/regression/regression.c.
References _resultset1dfm::accept, and _resultset1dfm::nprocesses.
int resultset1dfm_get_accept_f (resultset1dfm_t * r, int maxsize, int * accept)
References _resultset1dfm::accept, and resultset1dfm_get_nparameters().
const double* resultset1dfm_get_global_parameter (resultset1dfm_t * r, int gi)
References _resultset1dfm::global, and _resultset1dfm::nglobalparameters.
int resultset1dfm_get_global_parameter_f (resultset1dfm_t * r, int gi, int maxsize, double * global)
References _resultset1dfm::global, _resultset1dfm::nglobalparameters, and _resultset1dfm::total.
const double* resultset1dfm_get_hierarchical (resultset1dfm_t * r, int si)
References _resultset1dfm::hierarchical, and _resultset1dfm::nhierarchical.
int resultset1dfm_get_hierarchical_f (resultset1dfm_t * r, int hi, int maxsize, double * hierarchical)
References _resultset1dfm::hierarchical, _resultset1dfm::nhierarchical, and _resultset1dfm::total.
const double* resultset1dfm_get_local_parameter_credible_max (resultset1dfm_t * r, int li)
References _resultset1dfm::local_cred_max.
int resultset1dfm_get_local_parameter_credible_max_f (resultset1dfm_t * r, int li, int maxsize, double * credible_max)
References _resultset1dfm::local_cred_max, and _resultset1dfm::xsamples.
const double* resultset1dfm_get_local_parameter_credible_min (resultset1dfm_t * r, int li)
References _resultset1dfm::local_cred_min.
int resultset1dfm_get_local_parameter_credible_min_f (resultset1dfm_t * r, int li, int maxsize, double * credible_min)
References _resultset1dfm::local_cred_min, and _resultset1dfm::xsamples.
const int ** resultset1dfm_get_local_parameter_histogram (resultset1dfm_t * r, int li)
References _resultset1dfm::histogram, _resultset1dfm::nlocalparameters, RJMCMC_INDEXCHECKPTR, and RJMCMC_NULLCHECKPTR.
Referenced by resultset1dfm_get_local_parameter_histogram_f().
int resultset1dfm_get_local_parameter_histogram_f (resultset1dfm_t * r, int li, int xsamples, int ysamples, int * histogram)
References resultset1dfm_get_local_parameter_histogram(), RJMCMC_CONDITIONCHECKINT, x, _resultset1dfm::xsamples, y, and _resultset1dfm::ysamples.
const double* resultset1dfm_get_local_parameter_mean (resultset1dfm_t * r, int li)
Examples:
1d/partitioned/fm/functionfit/functionfit.c, and 1d/partitioned/fm/regression/regression.c.
References _resultset1dfm::local_mean, and _resultset1dfm::nlocalparameters.
int resultset1dfm_get_local_parameter_mean_f (resultset1dfm_t * r, int li, int maxsize, double * mean)
References _resultset1dfm::local_mean, and _resultset1dfm::xsamples.
const double* resultset1dfm_get_local_parameter_median (resultset1dfm_t * r, int li)
References _resultset1dfm::local_median.
int resultset1dfm_get_local_parameter_median_f (resultset1dfm_t * r, int li, int maxsize, double * median)
References _resultset1dfm::local_mean, _resultset1dfm::local_median, and _resultset1dfm::xsamples.
const double* resultset1dfm_get_local_parameter_mode (resultset1dfm_t * r, int li)
References _resultset1dfm::local_mode.
int resultset1dfm_get_local_parameter_mode_f (resultset1dfm_t * r, int li, int maxsize, double * mode)
References _resultset1dfm::local_mode, and _resultset1dfm::xsamples.
int resultset1dfm_get_max_partitions (resultset1dfm_t * r)
References _resultset1dfm::maxpartitions.
const double* resultset1dfm_get_misfit (resultset1dfm_t * r)
Examples:
1d/partitioned/fm/functionfit/functionfit.c, and 1d/partitioned/fm/regression/regression.c.
References _resultset1dfm::misfit.
int resultset1dfm_get_misfit_f (resultset1dfm_t * r, int maxsize, double * misfit)
References _resultset1dfm::misfit, and _resultset1dfm::total.
int resultset1dfm_get_nparameters (resultset1dfm_t * r)
References _resultset1dfm::nprocesses.
Referenced by resultset1dfm_get_accept_f(), and resultset1dfm_get_propose_f().
const int* resultset1dfm_get_partition_x_histogram (resultset1dfm_t * r)
Examples:
1d/partitioned/fm/functionfit/functionfit.c, and 1d/partitioned/fm/regression/regression.c.
References _resultset1dfm::partition_x_hist.
int resultset1dfm_get_partition_x_histogram_f (resultset1dfm_t * r, int maxsize, int * histogram)
References _resultset1dfm::partition_x_hist, and _resultset1dfm::xsamples.
const int* resultset1dfm_get_partitions (resultset1dfm_t * r)
Examples:
1d/partitioned/fm/functionfit/functionfit.c, and 1d/partitioned/fm/regression/regression.c.
References _resultset1dfm::partitions.
int resultset1dfm_get_partitions_f (resultset1dfm_t * r, int maxsize, int * partitions)
References _resultset1dfm::partitions, and _resultset1dfm::total.
const int* resultset1dfm_get_propose (resultset1dfm_t * r, int * nprocesses)
Examples:
1d/partitioned/fm/functionfit/functionfit.c, and 1d/partitioned/fm/regression/regression.c.
References _resultset1dfm::nprocesses, and _resultset1dfm::propose.
int resultset1dfm_get_propose_f (resultset1dfm_t * r, int maxsize, int * propose)
References _resultset1dfm::propose, and resultset1dfm_get_nparameters().
int resultset1dfm_get_total (resultset1dfm_t * r)
References _resultset1dfm::total.
int resultset1dfm_get_xcoord_vector_f (resultset1dfm_t * r, int maxsize, double * x)
References resultset1dfm_fill_xcoord_vector().
int resultset1dfm_get_xsamples (resultset1dfm_t * r)
References _resultset1dfm::xsamples.
int resultset1dfm_get_ycoord_vector_f (resultset1dfm_t * r, int li, int maxsize, double * y)
References resultset1dfm_fill_ycoord_vector().
void resultset1dfm_propose (resultset1dfm_t * r, int p)
References _resultset1dfm::nprocesses, _resultset1dfm::propose, and RJMCMC_INDEXCHECKVOID.
Referenced by MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().
void resultset1dfm_propose_local_value (resultset1dfm_t * r, int li)
References _resultset1dfm::nlocalparameters, _resultset1dfm::propose_local, and RJMCMC_INDEXCHECKVOID.
Referenced by MPI_part1d_forwardmodel_natural().
void resultset1dfm_sample_global_parameter (resultset1dfm_t * r, int i, int gi, double g)
References _resultset1dfm::global, _resultset1dfm::nglobalparameters, RJMCMC_INDEXCHECKVOID, and _resultset1dfm::total.
Referenced by MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().
void resultset1dfm_sample_hierarchical (resultset1dfm_t * r, int i, int si, double hierarchical)
References _resultset1dfm::hierarchical, _resultset1dfm::nhierarchical, RJMCMC_INDEXCHECKVOID, and _resultset1dfm::total.
Referenced by MPI_part1d_forwardmodel_natural_hierarchical().
void resultset1dfm_sample_local_parameter (resultset1dfm_t * r, int i, int li, double * l)
References _resultset1dfm::burnin, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _resultset1dfm::histogram, _resultset1dfm::local_mean, _resultset1dfm::local_parameters, _resultset1dfm::nlocalparameters, RJMCMC_INDEXCHECKVOID, rjmcmc_map_to_index(), _resultset1dfm::total, _resultset1dfm::xsamples, and _resultset1dfm::ysamples.
Referenced by MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().
void resultset1dfm_sample_misfit (resultset1dfm_t * r, int i, double misfit)
References _resultset1dfm::misfit, RJMCMC_INDEXCHECKVOID, and _resultset1dfm::total.
Referenced by MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().
void resultset1dfm_sample_npartitions (resultset1dfm_t * r, int i, int npartitions)
References _resultset1dfm::partitions, RJMCMC_INDEXCHECKVOID, and _resultset1dfm::total.
Referenced by MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().
void resultset1dfm_sample_partition_x (resultset1dfm_t * r, double x)
References _resultset1dfm::partition_x_hist, rjmcmc_map_to_index(), _resultset1dfm::xmax, _resultset1dfm::xmin, and _resultset1dfm::xsamples.
Referenced by MPI_part1d_forwardmodel_natural(), and MPI_part1d_forwardmodel_natural_hierarchical().