resultset2dfm.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include `rjmcmc/resultset2dfm.h`
*
#include `rjmcmc/rjmcmc_util.h`
*
#include `rjmcmc/rjmcmc_defines.h`
*
Data Structures
struct _resultset2dfm
struct writer_t
struct reader_t
Macros
#define WRITE_INT(name, var)
#define WRITE_INT_ARRAY(name, var, size)
#define WRITE_INT_ARRAY_2D(name, var, width, height)
#define WRITE_INT_ARRAY_3D(name, var, width, height, depth)
#define WRITE_INT_ARRAY_4D(name, var, width, height, depth, length)
#define WRITE_DOUBLE(name, var)
#define WRITE_DOUBLE_ARRAY(name, var, size)
#define WRITE_DOUBLE_ARRAY_2D(name, var, width, height)
#define WRITE_DOUBLE_ARRAY_3D(name, var, width, height, depth)
#define READ_INT(name, var)
#define READ_INT_ARRAY(name, var, size)
#define READ_INT_ARRAY_2D(name, var, width, height)
#define READ_INT_ARRAY_3D(name, var, width, height, depth)
#define READ_INT_ARRAY_4D(name, var, width, height, depth, length)
#define READ_DOUBLE(name, var)
#define READ_DOUBLE_ARRAY(name, var, size)
#define READ_DOUBLE_ARRAY_2D(name, var, width, height)
#define READ_DOUBLE_ARRAY_3D(name, var, width, height, depth)
Functions
resultset2dfm_t * resultset2dfm_create (int burnin, int total, int thin, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, int xsamples, int ysamples, int zsamples, int maxpartitions, double xmin, double xmax, double ymin, double ymax, int nprocesses, double credible_interval, int results)
int resultset2dfm_save (const resultset2dfm_t *r, const char *filename, int fmt)
resultset2dfm_t * resultset2dfm_load (const char *filename, int fmt, int *results, int *burnin, int *total, int *thin, int *xsamples, int *ysamples, int *zsamples, int *nprocesses, int *maxpartitions, double *xmin, double *xmax, double *ymin, double *ymax, double *credibleinterval, int *nhierarchical, int *nglobal, int *nlocal, forwardmodelparameter_t **global_parameters, forwardmodelparameter_t **local_parameters)
void resultset2dfm_destroy (resultset2dfm_t *r)
void resultset2dfm_propose (resultset2dfm_t *r, int p)
void resultset2dfm_accept (resultset2dfm_t *r, int p)
void resultset2dfm_sample_global_parameter (resultset2dfm_t *r, int i, int gi, double v)
void resultset2dfm_sample_hierarchical_parameter (resultset2dfm_t *r, int i, int hi, double v)
void resultset2dfm_sample_local_parameter (resultset2dfm_t *r, int i, int li, double **v)
void resultset2dfm_sample_misfit (resultset2dfm_t *r, int i, double misfit)
void resultset2dfm_sample_centre (resultset2dfm_t *r, double x, double y)
void resultset2dfm_sample_npartitions (resultset2dfm_t *r, int i, int npartitions)
void resultset2dfm_assemble_results (resultset2dfm_t *r)
void MPI_resultset2dfm_assemble_results (resultset2dfm_t *r, int mpisize, int mpirank, int root, MPI_Comm comm)
int resultset2dfm_get_nparameters (resultset2dfm_t *r)
int resultset2dfm_get_total (resultset2dfm_t *r)
const int * resultset2dfm_get_propose (resultset2dfm_t *r, int *nprocesses)
int resultset2dfm_get_propose_f (resultset2dfm_t *r, int maxsize, int *propose)
const int * resultset2dfm_get_accept (resultset2dfm_t *r, int *nprocesses)
int resultset2dfm_get_accept_f (resultset2dfm_t *r, int maxsize, int *accept)
const double * resultset2dfm_get_misfit (resultset2dfm_t *r)
int resultset2dfm_get_misfit_f (resultset2dfm_t *r, int maxsize, double *misfit)
const int * resultset2dfm_get_partitions (resultset2dfm_t *r)
int resultset2dfm_get_partitions_f (resultset2dfm_t *r, int maxsize, int *npartitions)
const double * resultset2dfm_get_global_parameter (resultset2dfm_t *r, int gi)
int resultset2dfm_get_global_parameter_f (resultset2dfm_t *r, int gi, int maxsize, double *global_parameter)
const double * resultset2dfm_get_hierarchical_parameter (resultset2dfm_t *r, int gi)
int resultset2dfm_get_hierarchical_parameter_f (resultset2dfm_t *r, int hi, int maxsize, double *hierarchical_parameter)
const double ** resultset2dfm_get_local_parameter_mean (resultset2dfm_t *r, int li)
int resultset2dfm_get_local_parameter_mean_f (resultset2dfm_t *r, int li, int xsamples, int ysamples, double *mean)
const double ** resultset2dfm_get_local_parameter_variance (resultset2dfm_t *r, int li)
int resultset2dfm_get_local_parameter_variance_f (resultset2dfm_t *r, int li, int xsamples, int ysamples, double *variance)
const double ** resultset2dfm_get_local_parameter_mode (resultset2dfm_t *r, int li)
int resultset2dfm_get_local_parameter_mode_f (resultset2dfm_t *r, int li, int xsamples, int ysamples, double *mode)
const double ** resultset2dfm_get_local_parameter_median (resultset2dfm_t *r, int li)
int resultset2dfm_get_local_parameter_median_f (resultset2dfm_t *r, int li, int xsamples, int ysamples, double *median)
const double ** resultset2dfm_get_local_parameter_credible_min (resultset2dfm_t *r, int li)
int resultset2dfm_get_local_parameter_credible_min_f (resultset2dfm_t *r, int li, int xsamples, int ysamples, double *credible_min)
const double ** resultset2dfm_get_local_parameter_credible_max (resultset2dfm_t *r, int li)
int resultset2dfm_get_local_parameter_credible_max_f (resultset2dfm_t *r, int li, int xsamples, int ysamples, double *credible_max)
const int ** resultset2dfm_get_centres (resultset2dfm_t *r)
int resultset2dfm_get_centres_f (resultset2dfm_t *r, int li, int xsamples, int ysamples, int *centres)
void resultset2dfm_fill_xcoord_vector (resultset2dfm_t *r, double *x, int *l)
int resultset2dfm_fill_xcoord_vector_f (resultset2dfm_t *r, int maxsize, double *x)
void resultset2dfm_fill_ycoord_vector (resultset2dfm_t *r, double *y, int *l)
int resultset2dfm_fill_ycoord_vector_f (resultset2dfm_t *r, int maxsize, double *y)
Macro Definition Documentation
#define READ_DOUBLE(name, var)
Value:
RJMCMC_INTCHECKPTR(r->read_variable_header(fp, name), \
                     "resultset2dfm_save: failed to read variable header\n"); \
  RJMCMC_INTCHECKPTR(r->read_double(fp, var), \
                     "resultset2dfm_save: failed to read int\n"); \
  RJMCMC_INTCHECKPTR(r->read_variable_footer(fp), \
                     "resultset2dfm_save: failed to read variable footer\n");
Referenced by resultset2dfm_load().
#define READ_DOUBLE_ARRAY(name, var, size)
Value:
RJMCMC_INTCHECKPTR(r->read_variable_header(fp, name), \
                     "resultset2dfm_save: failed to read variable header\n"); \
  RJMCMC_INTCHECKPTR(r->read_double_array(fp, var, size), \
                     "resultset2dfm_save: failed to read double array\n"); \
  RJMCMC_INTCHECKPTR(r->read_variable_footer(fp), \
                     "resultset2dfm_save: failed to read variable footer\n");
Referenced by resultset2dfm_load().
#define READ_DOUBLE_ARRAY_2D(name, var, width, height)
Value:
RJMCMC_INTCHECKPTR(r->read_variable_header(fp, name), \
                     "resultset2dfm_save: failed to read variable header\n"); \
  RJMCMC_INTCHECKPTR(r->read_double_array_2d(fp, var, width, height), \
                     "resultset2dfm_save: failed to read double array\n"); \
  RJMCMC_INTCHECKPTR(r->read_variable_footer(fp), \
                     "resultset2dfm_save: failed to read variable footer\n");
Referenced by resultset2dfm_load().
#define READ_DOUBLE_ARRAY_3D(name, var, width, height, depth)
Value:
RJMCMC_INTCHECKPTR(r->read_variable_header(fp, name), \
                     "resultset2dfm_save: failed to read variable header\n"); \
  RJMCMC_INTCHECKPTR(r->read_double_array_3d(fp, var, width, height, depth), \
                     "resultset2dfm_save: failed to read double array\n"); \
  RJMCMC_INTCHECKPTR(r->read_variable_footer(fp), \
                     "resultset2dfm_save: failed to read variable footer\n");
Referenced by resultset2dfm_load().
#define READ_INT(name, var)
Value:
RJMCMC_INTCHECKPTR(r->read_variable_header(fp, name), \
                     "resultset2dfm_save: failed to read variable header\n"); \
  RJMCMC_INTCHECKPTR(r->read_int(fp, var), \
                     "resultset2dfm_save: failed to read int\n"); \
  RJMCMC_INTCHECKPTR(r->read_variable_footer(fp), \
                     "resultset2dfm_save: failed to read variable footer\n");
Referenced by resultset2dfm_load().
#define READ_INT_ARRAY(name, var, size)
Value:
RJMCMC_INTCHECKPTR(r->read_variable_header(fp, name), \
                     "resultset2dfm_save: failed to read variable header\n"); \
  RJMCMC_INTCHECKPTR(r->read_int_array(fp, var, size), \
                     "resultset2dfm_save: failed to read int array\n"); \
  RJMCMC_INTCHECKPTR(r->read_variable_footer(fp), \
                     "resultset2dfm_save: failed to read variable footer\n");
Referenced by resultset2dfm_load().
#define READ_INT_ARRAY_2D(name, var, width, height)
Value:
RJMCMC_INTCHECKPTR(r->read_variable_header(fp, name), \
                     "resultset2dfm_save: failed to read variable header\n"); \
  RJMCMC_INTCHECKPTR(r->read_int_array_2d(fp, var, width, height), \
                     "resultset2dfm_save: failed to read int array\n"); \
  RJMCMC_INTCHECKPTR(r->read_variable_footer(fp), \
                     "resultset2dfm_save: failed to read variable footer\n");
Referenced by resultset2dfm_load().
#define READ_INT_ARRAY_3D(name, var, width, height, depth)
Value:
RJMCMC_INTCHECKPTR(r->read_variable_header(fp, name), \
                     "resultset2dfm_save: failed to read variable header\n"); \
  RJMCMC_INTCHECKPTR(r->read_int_array_3d(fp, var, width, height, depth), \
                     "resultset2dfm_save: failed to read int array\n"); \
  RJMCMC_INTCHECKPTR(r->read_variable_footer(fp), \
                     "resultset2dfm_save: failed to read variable footer\n");
#define READ_INT_ARRAY_4D(name, var, width, height, depth, length)
Value:
RJMCMC_INTCHECKPTR(r->read_variable_header(fp, name), \
                     "resultset2dfm_save: failed to read variable header\n"); \
  RJMCMC_INTCHECKPTR(r->read_int_array_4d(fp, var, width, height, depth, length), \
                     "resultset2dfm_save: failed to read int array\n"); \
  RJMCMC_INTCHECKPTR(r->read_variable_footer(fp), \
                     "resultset2dfm_save: failed to read variable footer\n");
Referenced by resultset2dfm_load().
#define WRITE_DOUBLE(name, var)
Value:
RJMCMC_INTCHECKINT(w->write_variable_header(fp, name), \
                     "resultset2dfm_save: failed to write variable header\n"); \
  RJMCMC_INTCHECKINT(w->write_double(fp, var), \
                     "resultset2dfm_save: failed to write int\n"); \
  RJMCMC_INTCHECKINT(w->write_variable_footer(fp), \
                     "resultset2dfm_save: failed to write variable footer\n");
Referenced by resultset2dfm_save().
#define WRITE_DOUBLE_ARRAY(name, var, size)
Value:
RJMCMC_INTCHECKINT(w->write_variable_header(fp, name), \
                     "resultset2dfm_save: failed to write variable header\n"); \
  RJMCMC_INTCHECKINT(w->write_double_array(fp, var, size), \
                     "resultset2dfm_save: failed to write double array\n"); \
  RJMCMC_INTCHECKINT(w->write_variable_footer(fp), \
                     "resultset2dfm_save: failed to write variable footer\n");
Referenced by resultset2dfm_save().
#define WRITE_DOUBLE_ARRAY_2D(name, var, width, height)
Value:
RJMCMC_INTCHECKINT(w->write_variable_header(fp, name), \
                     "resultset2dfm_save: failed to write variable header\n"); \
  RJMCMC_INTCHECKINT(w->write_double_array_2d(fp, var, width, height), \
                     "resultset2dfm_save: failed to write double array\n"); \
  RJMCMC_INTCHECKINT(w->write_variable_footer(fp), \
                     "resultset2dfm_save: failed to write variable footer\n");
Referenced by resultset2dfm_save().
#define WRITE_DOUBLE_ARRAY_3D(name, var, width, height, depth)
Value:
RJMCMC_INTCHECKINT(w->write_variable_header(fp, name), \
                     "resultset2dfm_save: failed to write variable header\n"); \
  RJMCMC_INTCHECKINT(w->write_double_array_3d(fp, var, width, height, depth), \
                     "resultset2dfm_save: failed to write double array\n"); \
  RJMCMC_INTCHECKINT(w->write_variable_footer(fp), \
                     "resultset2dfm_save: failed to write variable footer\n");
Referenced by resultset2dfm_save().
#define WRITE_INT(name, var)
Value:
RJMCMC_INTCHECKINT(w->write_variable_header(fp, name), \
                     "resultset2dfm_save: failed to write variable header\n"); \
  RJMCMC_INTCHECKINT(w->write_int(fp, var), \
                     "resultset2dfm_save: failed to write int\n"); \
  RJMCMC_INTCHECKINT(w->write_variable_footer(fp), \
                     "resultset2dfm_save: failed to write variable footer\n");
Referenced by resultset2dfm_save().
#define WRITE_INT_ARRAY(name, var, size)
Value:
RJMCMC_INTCHECKINT(w->write_variable_header(fp, name), \
                     "resultset2dfm_save: failed to write variable header\n"); \
  RJMCMC_INTCHECKINT(w->write_int_array(fp, var, size), \
                     "resultset2dfm_save: failed to write int array\n"); \
  RJMCMC_INTCHECKINT(w->write_variable_footer(fp), \
                     "resultset2dfm_save: failed to write variable footer\n");
Referenced by resultset2dfm_save().
#define WRITE_INT_ARRAY_2D(name, var, width, height)
Value:
RJMCMC_INTCHECKINT(w->write_variable_header(fp, name), \
                     "resultset2dfm_save: failed to write variable header\n"); \
  RJMCMC_INTCHECKINT(w->write_int_array_2d(fp, var, width, height), \
                     "resultset2dfm_save: failed to write int array\n"); \
  RJMCMC_INTCHECKINT(w->write_variable_footer(fp), \
                     "resultset2dfm_save: failed to write variable footer\n");
Referenced by resultset2dfm_save().
#define WRITE_INT_ARRAY_3D(name, var, width, height, depth)
Value:
RJMCMC_INTCHECKINT(w->write_variable_header(fp, name), \
                     "resultset2dfm_save: failed to write variable header\n"); \
  RJMCMC_INTCHECKINT(w->write_int_array_3d(fp, var, width, height, depth), \
                     "resultset2dfm_save: failed to write int array\n"); \
  RJMCMC_INTCHECKINT(w->write_variable_footer(fp), \
                     "resultset2dfm_save: failed to write variable footer\n");
#define WRITE_INT_ARRAY_4D(name, var, width, height, depth, length)
Value:
RJMCMC_INTCHECKINT(w->write_variable_header(fp, name), \
                     "resultset2dfm_save: failed to write variable header\n"); \
  RJMCMC_INTCHECKINT(w->write_int_array_4d(fp, var, width, height, depth, length), \
                     "resultset2dfm_save: failed to write int array\n"); \
  RJMCMC_INTCHECKINT(w->write_variable_footer(fp), \
                     "resultset2dfm_save: failed to write variable footer\n");
Referenced by resultset2dfm_save().
Function Documentation
void MPI_resultset2dfm_assemble_results (resultset2dfm_t * r, int mpisize, int mpirank, int root, MPI_Comm comm)
References _resultset2dfm::accept, _resultset2dfm::burnin, _resultset2dfm::credible_interval, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _resultset2dfm::hist, _resultset2dfm::local_cred_max, _resultset2dfm::local_cred_min, _resultset2dfm::local_mean, _resultset2dfm::local_median, _resultset2dfm::local_mode, _resultset2dfm::local_parameters, _resultset2dfm::local_samples, _resultset2dfm::local_variance, mpisize, _resultset2dfm::nlocalparameters, _resultset2dfm::nprocesses, _resultset2dfm::propose, rjmcmc_create_array_1d(), rjmcmc_create_int_array_1d(), rjmcmc_destroy_array_1d(), rjmcmc_destroy_int_array_1d(), rjmcmc_error(), rjmcmc_head_from_histogram(), rjmcmc_median_from_histogram(), rjmcmc_mode_from_histogram(), rjmcmc_tail_from_histogram(), _resultset2dfm::total, _resultset2dfm::xsamples, _resultset2dfm::ysamples, and _resultset2dfm::zsamples.
Referenced by MPI_part2d_forwardmodel(), MPI_part2d_forwardmodel_checkpoint(), MPI_part2d_forwardmodel_checkpoint_restart(), MPI_part2d_forwardmodel_hierarchical(), and MPI_part2d_forwardmodel_hierarchical_restartable().
void resultset2dfm_accept (resultset2dfm_t * r, int p)
References _resultset2dfm::accept, _resultset2dfm::nprocesses, and RJMCMC_INDEXCHECKVOID.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), and MPI_part2d_forwardmodel_hierarchical_restartable().
void resultset2dfm_assemble_results (resultset2dfm_t * r)
References _resultset2dfm::burnin, _resultset2dfm::credible_interval, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _resultset2dfm::hist, _resultset2dfm::local_cred_max, _resultset2dfm::local_cred_min, _resultset2dfm::local_mean, _resultset2dfm::local_median, _resultset2dfm::local_mode, _resultset2dfm::local_parameters, _resultset2dfm::local_samples, _resultset2dfm::local_variance, _resultset2dfm::nlocalparameters, rjmcmc_head_from_histogram(), rjmcmc_median_from_histogram(), rjmcmc_mode_from_histogram(), rjmcmc_tail_from_histogram(), _resultset2dfm::total, _resultset2dfm::xsamples, _resultset2dfm::ysamples, and _resultset2dfm::zsamples.
Referenced by part2d_forwardmodel(), part2d_forwardmodel_hierarchical(), and part2d_forwardmodel_restartable().
[resultset2dfm_create(int burnin, int total, int thin, int nglobalparameters, const forwardmodelparameter_t *global_parameters, int nlocalparameters, const forwardmodelparameter_t *local_parameters, int nhierarchicalparameters, int xsamples, int ysamples, int zsamples, int maxpartitions, double xmin, double xmax, double ymin, double ymax, int nprocesses, double credible_interval, int results)]resultset2dfm_t* resultset2dfm_create (int burnin, int total, int thin, int nglobalparameters, const forwardmodelparameter_t * global_parameters, int nlocalparameters, const forwardmodelparameter_t * local_parameters, int nhierarchicalparameters, int xsamples, int ysamples, int zsamples, int maxpartitions, double xmin, double xmax, double ymin, double ymax, int nprocesses, double credible_interval, int results)
References _resultset2dfm::accept, _resultset2dfm::burnin, _resultset2dfm::centres, _resultset2dfm::credible_interval, _resultset2dfm::global, _resultset2dfm::global_parameters, _resultset2dfm::hierarchical, _resultset2dfm::hist, _resultset2dfm::local_cred_max, _resultset2dfm::local_cred_min, _resultset2dfm::local_mean, _resultset2dfm::local_median, _resultset2dfm::local_mode, _resultset2dfm::local_parameters, _resultset2dfm::local_samples, _resultset2dfm::local_variance, _resultset2dfm::max_partitions, _resultset2dfm::misfit, _resultset2dfm::nglobalparameters, _resultset2dfm::nhierarchical, _resultset2dfm::nlocalparameters, _resultset2dfm::nprocesses, _resultset2dfm::partitions, _resultset2dfm::propose, _resultset2dfm::results, RESULTSET2DFM_CREDIBLE, RESULTSET2DFM_MEDIAN, RESULTSET2DFM_MODE, rjmcmc_create_array_1d(), rjmcmc_create_array_2d(), rjmcmc_create_array_3d(), rjmcmc_create_int_array_1d(), rjmcmc_create_int_array_2d(), rjmcmc_create_int_array_4d(), rjmcmc_fatal(), _resultset2dfm::thin, _resultset2dfm::total, _resultset2dfm::xmax, _resultset2dfm::xmin, _resultset2dfm::xsamples, _resultset2dfm::ymax, _resultset2dfm::ymin, _resultset2dfm::ysamples, and _resultset2dfm::zsamples.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), MPI_part2d_forwardmodel_hierarchical(), MPI_part2d_forwardmodel_hierarchical_restartable(), part2d_forwardmodel_hierarchical(), part2d_forwardmodel_restartable(), and resultset2dfm_load().
void resultset2dfm_destroy (resultset2dfm_t * r)
Examples:
2d/partitioned/fm/regression/regression.c.
References _resultset2dfm::accept, _resultset2dfm::centres, _resultset2dfm::global, _resultset2dfm::hierarchical, _resultset2dfm::hist, _resultset2dfm::local_cred_max, _resultset2dfm::local_cred_min, _resultset2dfm::local_mean, _resultset2dfm::local_median, _resultset2dfm::local_mode, _resultset2dfm::local_variance, _resultset2dfm::misfit, _resultset2dfm::nglobalparameters, _resultset2dfm::nhierarchical, _resultset2dfm::nlocalparameters, _resultset2dfm::partitions, _resultset2dfm::propose, rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), rjmcmc_destroy_array_3d(), rjmcmc_destroy_int_array_1d(), rjmcmc_destroy_int_array_2d(), rjmcmc_destroy_int_array_4d(), _resultset2dfm::xsamples, and _resultset2dfm::ysamples.
void resultset2dfm_fill_xcoord_vector (resultset2dfm_t * r, double * x, int * l)
Examples:
2d/partitioned/fm/regression/regression.c.
References rjmcmc_fill_coord_vector(), _resultset2dfm::xmax, _resultset2dfm::xmin, and _resultset2dfm::xsamples.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), MPI_part2d_forwardmodel_hierarchical(), MPI_part2d_forwardmodel_hierarchical_restartable(), part2d_forwardmodel_hierarchical(), part2d_forwardmodel_restartable(), and resultset2dfm_fill_xcoord_vector_f().
int resultset2dfm_fill_xcoord_vector_f (resultset2dfm_t * r, int maxsize, double * x)
References resultset2dfm_fill_xcoord_vector().
void resultset2dfm_fill_ycoord_vector (resultset2dfm_t * r, double * y, int * l)
Examples:
2d/partitioned/fm/regression/regression.c.
References rjmcmc_fill_coord_vector(), _resultset2dfm::ymax, _resultset2dfm::ymin, and _resultset2dfm::ysamples.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), MPI_part2d_forwardmodel_hierarchical(), MPI_part2d_forwardmodel_hierarchical_restartable(), part2d_forwardmodel_hierarchical(), part2d_forwardmodel_restartable(), and resultset2dfm_fill_ycoord_vector_f().
int resultset2dfm_fill_ycoord_vector_f (resultset2dfm_t * r, int maxsize, double * y)
References resultset2dfm_fill_ycoord_vector().
const int* resultset2dfm_get_accept (resultset2dfm_t * r, int * nprocesses)
Examples:
2d/partitioned/fm/regression/regression.c.
References _resultset2dfm::accept, and _resultset2dfm::nprocesses.
int resultset2dfm_get_accept_f (resultset2dfm_t * r, int maxsize, int * accept)
References _resultset2dfm::accept, and resultset2dfm_get_nparameters().
const int** resultset2dfm_get_centres (resultset2dfm_t * r)
Examples:
2d/partitioned/fm/regression/regression.c.
References _resultset2dfm::centres.
Referenced by resultset2dfm_get_centres_f().
int resultset2dfm_get_centres_f (resultset2dfm_t * r, int li, int xsamples, int ysamples, int * centres)
References resultset2dfm_get_centres(), RJMCMC_CONDITIONCHECKINT, x, _resultset2dfm::xsamples, y, and _resultset2dfm::ysamples.
const double* resultset2dfm_get_global_parameter (resultset2dfm_t * r, int gi)
References _resultset2dfm::global.
int resultset2dfm_get_global_parameter_f (resultset2dfm_t * r, int gi, int maxsize, double * global_parameter)
References _resultset2dfm::global, _resultset2dfm::nglobalparameters, and resultset2dfm_get_total().
const double* resultset2dfm_get_hierarchical_parameter (resultset2dfm_t * r, int gi)
References _resultset2dfm::hierarchical, _resultset2dfm::nhierarchical, RJMCMC_INDEXCHECKPTR, and RJMCMC_NULLCHECKPTR.
int resultset2dfm_get_hierarchical_parameter_f (resultset2dfm_t * r, int hi, int maxsize, double * hierarchical_parameter)
References _resultset2dfm::hierarchical, _resultset2dfm::nhierarchical, and resultset2dfm_get_total().
const double** resultset2dfm_get_local_parameter_credible_max (resultset2dfm_t * r, int li)
Examples:
2d/partitioned/fm/regression/regression.c.
References _resultset2dfm::local_cred_max, _resultset2dfm::nlocalparameters, RJMCMC_INDEXCHECKPTR, and RJMCMC_NULLCHECKPTR.
Referenced by resultset2dfm_get_local_parameter_credible_max_f().
int resultset2dfm_get_local_parameter_credible_max_f (resultset2dfm_t * r, int li, int xsamples, int ysamples, double * credible_max)
References resultset2dfm_get_local_parameter_credible_max(), RJMCMC_CONDITIONCHECKINT, x, _resultset2dfm::xsamples, y, and _resultset2dfm::ysamples.
const double** resultset2dfm_get_local_parameter_credible_min (resultset2dfm_t * r, int li)
Examples:
2d/partitioned/fm/regression/regression.c.
References _resultset2dfm::local_cred_min, _resultset2dfm::nlocalparameters, RJMCMC_INDEXCHECKPTR, and RJMCMC_NULLCHECKPTR.
Referenced by resultset2dfm_get_local_parameter_credible_min_f().
int resultset2dfm_get_local_parameter_credible_min_f (resultset2dfm_t * r, int li, int xsamples, int ysamples, double * credible_min)
References resultset2dfm_get_local_parameter_credible_min(), RJMCMC_CONDITIONCHECKINT, x, _resultset2dfm::xsamples, y, and _resultset2dfm::ysamples.
const double** resultset2dfm_get_local_parameter_mean (resultset2dfm_t * r, int li)
Examples:
2d/partitioned/fm/regression/regression.c.
References _resultset2dfm::local_mean, _resultset2dfm::nlocalparameters, RJMCMC_INDEXCHECKPTR, and RJMCMC_NULLCHECKPTR.
Referenced by resultset2dfm_get_local_parameter_mean_f().
int resultset2dfm_get_local_parameter_mean_f (resultset2dfm_t * r, int li, int xsamples, int ysamples, double * mean)
References resultset2dfm_get_local_parameter_mean(), RJMCMC_CONDITIONCHECKINT, x, _resultset2dfm::xsamples, y, and _resultset2dfm::ysamples.
const double** resultset2dfm_get_local_parameter_median (resultset2dfm_t * r, int li)
Examples:
2d/partitioned/fm/regression/regression.c.
References _resultset2dfm::local_median, _resultset2dfm::nlocalparameters, RJMCMC_INDEXCHECKPTR, and RJMCMC_NULLCHECKPTR.
Referenced by resultset2dfm_get_local_parameter_median_f().
int resultset2dfm_get_local_parameter_median_f (resultset2dfm_t * r, int li, int xsamples, int ysamples, double * median)
References resultset2dfm_get_local_parameter_median(), RJMCMC_CONDITIONCHECKINT, x, _resultset2dfm::xsamples, y, and _resultset2dfm::ysamples.
const double** resultset2dfm_get_local_parameter_mode (resultset2dfm_t * r, int li)
Examples:
2d/partitioned/fm/regression/regression.c.
References _resultset2dfm::local_mode, _resultset2dfm::nlocalparameters, RJMCMC_INDEXCHECKPTR, and RJMCMC_NULLCHECKPTR.
Referenced by resultset2dfm_get_local_parameter_mode_f().
int resultset2dfm_get_local_parameter_mode_f (resultset2dfm_t * r, int li, int xsamples, int ysamples, double * mode)
References resultset2dfm_get_local_parameter_mode(), RJMCMC_CONDITIONCHECKINT, x, _resultset2dfm::xsamples, y, and _resultset2dfm::ysamples.
const double** resultset2dfm_get_local_parameter_variance (resultset2dfm_t * r, int li)
References _resultset2dfm::local_variance, _resultset2dfm::nlocalparameters, RJMCMC_INDEXCHECKPTR, and RJMCMC_NULLCHECKPTR.
Referenced by resultset2dfm_get_local_parameter_variance_f().
int resultset2dfm_get_local_parameter_variance_f (resultset2dfm_t * r, int li, int xsamples, int ysamples, double * variance)
References resultset2dfm_get_local_parameter_variance(), RJMCMC_CONDITIONCHECKINT, x, _resultset2dfm::xsamples, y, and _resultset2dfm::ysamples.
const double* resultset2dfm_get_misfit (resultset2dfm_t * r)
Examples:
2d/partitioned/fm/regression/regression.c.
References _resultset2dfm::misfit.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart().
int resultset2dfm_get_misfit_f (resultset2dfm_t * r, int maxsize, double * misfit)
References _resultset2dfm::misfit, and resultset2dfm_get_total().
int resultset2dfm_get_nparameters (resultset2dfm_t * r)
References _resultset2dfm::nprocesses.
Referenced by resultset2dfm_get_accept_f(), and resultset2dfm_get_propose_f().
const int* resultset2dfm_get_partitions (resultset2dfm_t * r)
Examples:
2d/partitioned/fm/regression/regression.c.
References _resultset2dfm::partitions.
int resultset2dfm_get_partitions_f (resultset2dfm_t * r, int maxsize, int * npartitions)
References _resultset2dfm::partitions, and resultset2dfm_get_total().
const int* resultset2dfm_get_propose (resultset2dfm_t * r, int * nprocesses)
Examples:
2d/partitioned/fm/regression/regression.c.
References _resultset2dfm::nprocesses, and _resultset2dfm::propose.
int resultset2dfm_get_propose_f (resultset2dfm_t * r, int maxsize, int * propose)
References _resultset2dfm::propose, and resultset2dfm_get_nparameters().
int resultset2dfm_get_total (resultset2dfm_t * r)
References _resultset2dfm::total.
Referenced by resultset2dfm_get_global_parameter_f(), resultset2dfm_get_hierarchical_parameter_f(), resultset2dfm_get_misfit_f(), and resultset2dfm_get_partitions_f().
[resultset2dfm_load(const char *filename, int fmt, int *results, int *burnin, int *total, int *thin, int *xsamples, int *ysamples, int *zsamples, int *nprocesses, int *maxpartitions, double *xmin, double *xmax, double *ymin, double *ymax, double *credibleinterval, int *nhierarchical, int *nglobal, int *nlocal, forwardmodelparameter_t **global_parameters, forwardmodelparameter_t **local_parameters)]resultset2dfm_t* resultset2dfm_load (const char * filename, int fmt, int * results, int * burnin, int * total, int * thin, int * xsamples, int * ysamples, int * zsamples, int * nprocesses, int * maxpartitions, double * xmin, double * xmax, double * ymin, double * ymax, double * credibleinterval, int * nhierarchical, int * nglobal, int * nlocal, forwardmodelparameter_t ** global_parameters, forwardmodelparameter_t ** local_parameters)
References _resultset2dfm::accept, _resultset2dfm::centres, forwardmodelparameter_create(), _resultset2dfm::global, _resultset2dfm::hierarchical, _resultset2dfm::hist, _resultset2dfm::local_cred_max, _resultset2dfm::local_cred_min, _resultset2dfm::local_mean, _resultset2dfm::local_median, _resultset2dfm::local_mode, _resultset2dfm::local_samples, _resultset2dfm::local_variance, _resultset2dfm::misfit, _resultset2dfm::nglobalparameters, _resultset2dfm::nhierarchical, _resultset2dfm::nlocalparameters, _resultset2dfm::nprocesses, _resultset2dfm::partitions, _resultset2dfm::propose, READ_DOUBLE, READ_DOUBLE_ARRAY, READ_DOUBLE_ARRAY_2D, READ_DOUBLE_ARRAY_3D, reader_t::read_footer, reader_t::read_header, READ_INT, READ_INT_ARRAY, READ_INT_ARRAY_2D, READ_INT_ARRAY_4D, _resultset2dfm::results, RESULTSET2DFM_BINARY, resultset2dfm_create(), RESULTSET2DFM_CREDIBLE, RESULTSET2DFM_MEAN, RESULTSET2DFM_MEDIAN, RESULTSET2DFM_MODE, rjmcmc_error(), RJMCMC_INTCHECKPTR, RJMCMC_NULLCHECKPTR, _resultset2dfm::total, _resultset2dfm::xsamples, _resultset2dfm::ysamples, and _resultset2dfm::zsamples.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart().
void resultset2dfm_propose (resultset2dfm_t * r, int p)
References _resultset2dfm::nprocesses, _resultset2dfm::propose, and RJMCMC_INDEXCHECKVOID.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), and MPI_part2d_forwardmodel_hierarchical_restartable().
void resultset2dfm_sample_centre (resultset2dfm_t * r, double x, double y)
References _resultset2dfm::centres, rjmcmc_map_to_index(), _resultset2dfm::xmax, _resultset2dfm::xmin, _resultset2dfm::xsamples, _resultset2dfm::ymax, _resultset2dfm::ymin, and _resultset2dfm::ysamples.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), and MPI_part2d_forwardmodel_hierarchical_restartable().
void resultset2dfm_sample_global_parameter (resultset2dfm_t * r, int i, int gi, double v)
References _resultset2dfm::global, _resultset2dfm::nglobalparameters, RJMCMC_INDEXCHECKVOID, and _resultset2dfm::total.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), and MPI_part2d_forwardmodel_hierarchical_restartable().
void resultset2dfm_sample_hierarchical_parameter (resultset2dfm_t * r, int i, int hi, double v)
References _resultset2dfm::hierarchical, _resultset2dfm::nhierarchical, RJMCMC_INDEXCHECKVOID, and _resultset2dfm::total.
Referenced by MPI_part2d_forwardmodel_hierarchical_restartable().
void resultset2dfm_sample_local_parameter (resultset2dfm_t * r, int i, int li, double ** v)
References _resultset2dfm::burnin, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _resultset2dfm::hist, _resultset2dfm::local_mean, _resultset2dfm::local_parameters, _resultset2dfm::local_samples, _resultset2dfm::local_variance, _resultset2dfm::nlocalparameters, RJMCMC_INDEXCHECKVOID, rjmcmc_map_to_index(), _resultset2dfm::thin, _resultset2dfm::total, _resultset2dfm::xsamples, _resultset2dfm::ysamples, and _resultset2dfm::zsamples.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), and MPI_part2d_forwardmodel_hierarchical_restartable().
void resultset2dfm_sample_misfit (resultset2dfm_t * r, int i, double misfit)
References _resultset2dfm::misfit, RJMCMC_INDEXCHECKVOID, and _resultset2dfm::total.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), and MPI_part2d_forwardmodel_hierarchical_restartable().
void resultset2dfm_sample_npartitions (resultset2dfm_t * r, int i, int npartitions)
References _resultset2dfm::partitions, RJMCMC_INDEXCHECKVOID, and _resultset2dfm::total.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), and MPI_part2d_forwardmodel_hierarchical_restartable().
int resultset2dfm_save (const resultset2dfm_t * r, const char * filename, int fmt)
References _resultset2dfm::accept, _resultset2dfm::burnin, _resultset2dfm::centres, _resultset2dfm::credible_interval, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _forwardmodelparameter::fstd_bd, _forwardmodelparameter::fstd_value, _resultset2dfm::global, _resultset2dfm::global_parameters, _resultset2dfm::hierarchical, _resultset2dfm::hist, _resultset2dfm::local_cred_max, _resultset2dfm::local_cred_min, _resultset2dfm::local_mean, _resultset2dfm::local_median, _resultset2dfm::local_mode, _resultset2dfm::local_parameters, _resultset2dfm::local_samples, _resultset2dfm::local_variance, _resultset2dfm::max_partitions, _resultset2dfm::misfit, _resultset2dfm::nglobalparameters, _resultset2dfm::nhierarchical, _resultset2dfm::nlocalparameters, _resultset2dfm::nprocesses, _resultset2dfm::partitions, _resultset2dfm::propose, _resultset2dfm::results, RESULTSET2DFM_BINARY, RESULTSET2DFM_CREDIBLE, RESULTSET2DFM_MEAN, RESULTSET2DFM_MEDIAN, RESULTSET2DFM_MODE, rjmcmc_error(), RJMCMC_INTCHECKINT, RJMCMC_NULLCHECKINT, _resultset2dfm::thin, _resultset2dfm::total, WRITE_DOUBLE, WRITE_DOUBLE_ARRAY, WRITE_DOUBLE_ARRAY_2D, WRITE_DOUBLE_ARRAY_3D, writer_t::write_footer, writer_t::write_header, WRITE_INT, WRITE_INT_ARRAY, WRITE_INT_ARRAY_2D, WRITE_INT_ARRAY_4D, _resultset2dfm::xmax, _resultset2dfm::xmin, _resultset2dfm::xsamples, _resultset2dfm::ymax, _resultset2dfm::ymin, _resultset2dfm::ysamples, and _resultset2dfm::zsamples.
Referenced by MPI_part2d_forwardmodel_checkpoint_restart().