resultsetfm.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <rjmcmc/rjmcmc.h>
*
#include <rjmcmc/resultsetfm.h>
*
#include <rjmcmc/rjmcmc_util.h>
*
#include <rjmcmc/rjmcmc_debug.h>
*
#include <rjmcmc/rjmcmc_defines.h>
*
Data Structures
struct _resultsetfm
Macros
#define RESULTSETFM_2DARRAY(el, a, b)
#define RESULTSETFM_CONDITIONAL_2DARRAY(cond, el, a, b)
#define RESULTSETFM_1DARRAY(el, a)
#define RESULTSETFM_CONDITIONAL_1DARRAY(cond, el, a)
Functions
resultsetfm_t * resultsetfm_create (int burnin, int total, int nparameters, const forwardmodelparameter_t *parameters, int nhierarchical_parameters, const forwardmodelparameter_t *hierarchical_parameters, int samples, double credible_interval, int results)
void resultsetfm_destroy (resultsetfm_t *r)
void resultsetfm_propose (resultsetfm_t *r, int p)
void resultsetfm_accept (resultsetfm_t *r, int p)
void resultsetfm_sample (resultsetfm_t *r, int i, const double *v)
void resultsetfm_sample_misfit (resultsetfm_t *r, int i, double misfit)
void resultsetfm_sample_hierarchical (resultsetfm_t *r, int i, double *hierarchical)
void resultsetfm_assemble_results (resultsetfm_t *r)
void MPI_resultsetfm_assemble_results (resultsetfm_t *r, int mpisize, int mpirank, int root, MPI_Comm comm)
int resultsetfm_get_nparameters (resultsetfm_t *r)
const int * resultsetfm_get_propose (resultsetfm_t *r, int *nprocesses)
int resultsetfm_get_propose_f (resultsetfm_t *r, int maxsize, int *propose)
int resultsetfm_get_propose_n (resultsetfm_t *r, int process)
const int * resultsetfm_get_accept (resultsetfm_t *r, int *nprocesses)
int resultsetfm_get_accept_n (resultsetfm_t *r, int process)
int resultsetfm_get_accept_f (resultsetfm_t *r, int maxsize, int *accept)
const double * resultsetfm_get_misfit (resultsetfm_t *r)
int resultsetfm_get_misfit_f (resultsetfm_t *r, int maxsize, double *misfit)
const double * resultsetfm_get_parameter_history (resultsetfm_t *r, int p)
int resultsetfm_get_parameter_history_f (resultsetfm_t *r, int p, int maxsize, double *phistory)
const double * resultsetfm_get_hierarchical_parameter_history (resultsetfm_t *r, int p)
int resultsetfm_get_hierarchical_parameter_history_f (resultsetfm_t *r, int p, int maxsize, double *hphistory)
double resultsetfm_get_parameter_mean (resultsetfm_t *r, int p)
double resultsetfm_get_parameter_mode (resultsetfm_t *r, int p)
double resultsetfm_get_parameter_median (resultsetfm_t *r, int p)
double resultsetfm_get_parameter_credible_min (resultsetfm_t *r, int p)
double resultsetfm_get_parameter_credible_max (resultsetfm_t *r, int p)
Macro Definition Documentation
#define RESULTSETFM_1DARRAY(el, a)
Value:
el = rjmcmc_create_array_1d(a); \
  if (el == NULL) { \
    return NULL; \
  }
Referenced by resultsetfm_create().
#define RESULTSETFM_2DARRAY(el, a, b)
Value:
el = rjmcmc_create_array_2d(a, b); \
  if (el == NULL) { \
    return NULL; \
  }
Referenced by resultsetfm_create().
#define RESULTSETFM_CONDITIONAL_1DARRAY(cond, el, a)
Value:
el = NULL; \
  if (cond) { \
    el = rjmcmc_create_array_1d(a); \
    if (el == NULL) { \
      return NULL; \
    } \
  }
Referenced by resultsetfm_create().
#define RESULTSETFM_CONDITIONAL_2DARRAY(cond, el, a, b)
Value:
el = NULL; \
  if (cond) { \
    el = rjmcmc_create_array_2d(a, b); \
    if (el == NULL) { \
      return NULL; \
    } \
  }
Referenced by resultsetfm_create().
Function Documentation
void MPI_resultsetfm_assemble_results (resultsetfm_t * r, int mpisize, int mpirank, int root, MPI_Comm comm)
References _resultsetfm::accept, _resultsetfm::burnin, _resultsetfm::mean, _resultsetfm::nhierarchical_parameters, _resultsetfm::nparameters, _resultsetfm::parameter_hist, _resultsetfm::propose, rjmcmc_create_array_1d(), rjmcmc_create_int_array_1d(), rjmcmc_error(), rjmcmc_mean_variance(), and _resultsetfm::total.
Referenced by MPI_single_forwardmodel(), and MPI_single_forwardmodel_hierarchical().
void resultsetfm_accept (resultsetfm_t * r, int p)
References _resultsetfm::accept, _resultsetfm::nhierarchical_parameters, _resultsetfm::nparameters, RJMCMC_INDEXCHECKVOID, and RJMCMC_NULLCHECKVOID.
Referenced by single_forwardmodel_hierarchical().
void resultsetfm_assemble_results (resultsetfm_t * r)
References _resultsetfm::burnin, _resultsetfm::credible_interval, _resultsetfm::credible_max, _resultsetfm::credible_min, _forwardmodelparameter::fmax, _forwardmodelparameter::fmin, _resultsetfm::mean, _resultsetfm::median, _resultsetfm::mode, _resultsetfm::nparameters, _resultsetfm::parameter_hist, _resultsetfm::parameters, rjmcmc_create_int_array_2d(), rjmcmc_destroy_int_array_2d(), rjmcmc_error(), rjmcmc_head_from_histogram(), rjmcmc_map_to_index(), rjmcmc_mean_variance(), rjmcmc_median_from_histogram(), rjmcmc_mode_from_histogram(), rjmcmc_tail_from_histogram(), _resultsetfm::samples, and _resultsetfm::total.
Referenced by single_forwardmodel(), and single_forwardmodel_hierarchical().
resultsetfm_t* resultsetfm_create (int burnin, int total, int nparameters, const forwardmodelparameter_t * parameters, int nhierarchical_parameters, const forwardmodelparameter_t * hierarchical_parameters, int samples, double credible_interval, int results)
References _resultsetfm::accept, _resultsetfm::burnin, _resultsetfm::credible_interval, _resultsetfm::credible_max, _resultsetfm::credible_min, _resultsetfm::hierarchical_parameter_hist, _resultsetfm::hierarchical_parameters, _resultsetfm::mean, _resultsetfm::median, _resultsetfm::misfit, _resultsetfm::mode, _resultsetfm::nhierarchical_parameters, _resultsetfm::nparameters, _resultsetfm::parameter_hist, _resultsetfm::parameters, _resultsetfm::propose, RESULTSETFM_1DARRAY, RESULTSETFM_2DARRAY, RESULTSETFM_CONDITIONAL_1DARRAY, RESULTSETFM_CONDITIONAL_2DARRAY, RESULTSETFM_CREDIBLE, RESULTSETFM_MEAN, RESULTSETFM_MEDIAN, RESULTSETFM_MODE, rjmcmc_create_int_array_1d(), _resultsetfm::samples, and _resultsetfm::total.
Referenced by MPI_single_forwardmodel(), MPI_single_forwardmodel_hierarchical(), single_forwardmodel(), and single_forwardmodel_hierarchical().
void resultsetfm_destroy (resultsetfm_t * r)
Examples:
1d/single/fm/simpleimage/simpleimage.c, and 1d/single/fm/spherefit/spherefit.c.
References _resultsetfm::accept, _resultsetfm::credible_max, _resultsetfm::credible_min, _resultsetfm::hierarchical_parameter_hist, _resultsetfm::mean, _resultsetfm::median, _resultsetfm::misfit, _resultsetfm::mode, _resultsetfm::nhierarchical_parameters, _resultsetfm::nparameters, _resultsetfm::parameter_hist, _resultsetfm::propose, rjmcmc_destroy_array_1d(), rjmcmc_destroy_array_2d(), and rjmcmc_destroy_int_array_1d().
const int* resultsetfm_get_accept (resultsetfm_t * r, int * nprocesses)
Examples:
1d/single/fm/simpleimage/simpleimage.c, and 1d/single/fm/spherefit/spherefit.c.
References _resultsetfm::accept, and resultsetfm_get_nparameters().
int resultsetfm_get_accept_f (resultsetfm_t * r, int maxsize, int * accept)
References _resultsetfm::accept, and resultsetfm_get_nparameters().
int resultsetfm_get_accept_n (resultsetfm_t * r, int process)
References _resultsetfm::accept, and resultsetfm_get_nparameters().
const double* resultsetfm_get_hierarchical_parameter_history (resultsetfm_t * r, int p)
Examples:
1d/single/fm/simpleimage/simpleimage.c.
References _resultsetfm::hierarchical_parameter_hist.
int resultsetfm_get_hierarchical_parameter_history_f (resultsetfm_t * r, int p, int maxsize, double * hphistory)
References _resultsetfm::hierarchical_parameter_hist, _resultsetfm::nhierarchical_parameters, rjmcmc_error(), and _resultsetfm::total.
const double* resultsetfm_get_misfit (resultsetfm_t * r)
Examples:
1d/single/fm/simpleimage/simpleimage.c, and 1d/single/fm/spherefit/spherefit.c.
References _resultsetfm::misfit.
int resultsetfm_get_misfit_f (resultsetfm_t * r, int maxsize, double * misfit)
References _resultsetfm::misfit, and _resultsetfm::total.
int resultsetfm_get_nparameters (resultsetfm_t * r)
References _resultsetfm::nhierarchical_parameters, and _resultsetfm::nparameters.
Referenced by resultsetfm_get_accept(), resultsetfm_get_accept_f(), resultsetfm_get_accept_n(), resultsetfm_get_propose(), resultsetfm_get_propose_f(), and resultsetfm_get_propose_n().
double resultsetfm_get_parameter_credible_max (resultsetfm_t * r, int p)
References _resultsetfm::credible_max.
double resultsetfm_get_parameter_credible_min (resultsetfm_t * r, int p)
References _resultsetfm::credible_min.
const double* resultsetfm_get_parameter_history (resultsetfm_t * r, int p)
Examples:
1d/single/fm/simpleimage/simpleimage.c, and 1d/single/fm/spherefit/spherefit.c.
References _resultsetfm::nparameters, _resultsetfm::parameter_hist, and rjmcmc_error().
int resultsetfm_get_parameter_history_f (resultsetfm_t * r, int p, int maxsize, double * phistory)
References _resultsetfm::nparameters, _resultsetfm::parameter_hist, rjmcmc_error(), and _resultsetfm::total.
double resultsetfm_get_parameter_mean (resultsetfm_t * r, int p)
Examples:
1d/single/fm/spherefit/spherefit.c.
References _resultsetfm::mean.
double resultsetfm_get_parameter_median (resultsetfm_t * r, int p)
References _resultsetfm::median.
double resultsetfm_get_parameter_mode (resultsetfm_t * r, int p)
References _resultsetfm::mode.
const int* resultsetfm_get_propose (resultsetfm_t * r, int * nprocesses)
Examples:
1d/single/fm/simpleimage/simpleimage.c, and 1d/single/fm/spherefit/spherefit.c.
References _resultsetfm::propose, and resultsetfm_get_nparameters().
int resultsetfm_get_propose_f (resultsetfm_t * r, int maxsize, int * propose)
References _resultsetfm::propose, and resultsetfm_get_nparameters().
int resultsetfm_get_propose_n (resultsetfm_t * r, int process)
References _resultsetfm::propose, and resultsetfm_get_nparameters().
void resultsetfm_propose (resultsetfm_t * r, int p)
References _resultsetfm::nhierarchical_parameters, _resultsetfm::nparameters, _resultsetfm::propose, RJMCMC_INDEXCHECKVOID, and RJMCMC_NULLCHECKVOID.
Referenced by single_forwardmodel_hierarchical().
void resultsetfm_sample (resultsetfm_t * r, int i, const double * v)
References _resultsetfm::nparameters, _resultsetfm::parameter_hist, rjmcmc_error(), and _resultsetfm::total.
Referenced by single_forwardmodel_hierarchical().
void resultsetfm_sample_hierarchical (resultsetfm_t * r, int i, double * hierarchical)
References _resultsetfm::hierarchical_parameter_hist, _resultsetfm::nhierarchical_parameters, rjmcmc_error(), and _resultsetfm::total.
Referenced by single_forwardmodel_hierarchical().
void resultsetfm_sample_misfit (resultsetfm_t * r, int i, double misfit)
References _resultsetfm::misfit, rjmcmc_error(), and _resultsetfm::total.
Referenced by single_forwardmodel_hierarchical().