rjmcmc_random.c File Reference
#include <stdlib.h>
*
#include <math.h>
*
#include `rjmcmc/rjmcmc_random.h`
*
#include `rjmcmc/wellrng.h`
*
Functions
void rjmcmc_seed (int s)
double rjmcmc_uniform (void)
double rjmcmc_normal (void)
double rjmcmc_random_choose_double (double low, double high, rjmcmc_uniform_rand_t custom_rand)
int rjmcmc_random_choose_int (int low, int high, rjmcmc_uniform_rand_t custom_rand)
int rjmcmc_random_choose_interval (const double *cdf, int n, rjmcmc_uniform_rand_t custom_rand)
Function Documentation
double rjmcmc_normal (void)
Examples:
1d/partitioned/fm/functionfit/functionfit.c, 1d/partitioned/fm/regression/regression.c, 1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, 1d/partitioned/regression/sawtooth/sawtooth.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, 1d/single/fm/simpleimage/simpleimage.c, 1d/single/fm/spherefit/spherefit.c, 1d/single/regression/cubic/cubic.c, 2d/partitioned/fm/regression/regression.c, 2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References wellrng_init_simple(), and wellrng_sample().
double rjmcmc_random_choose_double (double low, double high, rjmcmc_uniform_rand_t custom_rand)
Examples:
1d/partitioned/fm/regression/regression.c, and 1d/single/fm/spherefit/spherefit.c.
Referenced by part1d_forwardmodel_initialize(), part1d_forwardmodel_propose_birth(), part1d_natural_rj_initialize(), part1d_regression_rj_initialize(), part1d_zero_initialize(), part1d_zero_propose_birth(), part1d_zero_propose_death(), part1d_zero_propose_move(), part1d_zero_propose_value(), part2d_forwardmodel_initialize(), part2d_forwardmodel_propose_birth(), part2d_regression_rj_initialize(), part2d_regression_rj_propose_birth(), single1d_regression_initialize(), and single_forwardmodel_hierarchical().
int rjmcmc_random_choose_int (int low, int high, rjmcmc_uniform_rand_t custom_rand)
Referenced by MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), MPI_part2d_forwardmodel_checkpoint_restart(), MPI_part2d_forwardmodel_hierarchical_restartable(), MPI_single1d_regression(), part1d_forwardmodel_propose_death(), part1d_forwardmodel_propose_global_value(), part1d_forwardmodel_propose_hierarchical(), part1d_forwardmodel_propose_local_value(), part1d_forwardmodel_propose_move(), part1d_natural_rj_propose_move(), part1d_natural_rj_propose_value(), part1d_regression(), part1d_regression_rj_initialize(), part1d_regression_rj_propose_death(), part1d_regression_rj_propose_move(), part1d_regression_rj_propose_value(), part1d_zero_propose_death(), part1d_zero_propose_lambda(), part1d_zero_propose_move(), part1d_zero_propose_value(), part2d_forwardmodel_propose_death(), part2d_forwardmodel_propose_global_value(), part2d_forwardmodel_propose_hierarchical(), part2d_forwardmodel_propose_local_value(), part2d_forwardmodel_propose_move(), part2d_regression(), part2d_regression_rj_propose_death(), part2d_regression_rj_propose_lambda(), part2d_regression_rj_propose_move(), part2d_regression_rj_propose_value(), single1d_regression_initialize(), and single_forwardmodel_hierarchical().
int rjmcmc_random_choose_interval (const double * cdf, int n, rjmcmc_uniform_rand_t custom_rand)
Referenced by part1d_regression_rj_propose_move(), and single1d_regression_propose_value().
void rjmcmc_seed (int s)
Examples:
1d/partitioned/regression/zeromultistep/zeromultistep.c, and 2d/partitioned/fm/regression/regression.c.
References wellrng_destroy(), and wellrng_init_simple().
double rjmcmc_uniform (void)
Examples:
1d/partitioned/fm/functionfit/functionfit.c, 1d/partitioned/fm/regression/regression.c, 1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, 1d/partitioned/regression/sawtooth/sawtooth.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, 1d/single/fm/simpleimage/simpleimage.c, 1d/single/fm/spherefit/spherefit.c, 1d/single/regression/cubic/cubic.c, 2d/partitioned/fm/regression/regression.c, 2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References wellrng_init_simple(), and wellrng_sample().