rjmcmc_util.c File Reference
#include `rjmcmc/rjmcmc_config.h`
*
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <math.h>
*
#include <limits.h>
*
#include <rjmcmc/rjmcmc_debug.h>
*
#include `rjmcmc/rjmcmc_util.h`
*
Macros
#define SQRT2PI 2.5066282746310002
Functions
double * rjmcmc_create_array_1d (int w)
double ** rjmcmc_create_array_2d (int w, int h)
double *** rjmcmc_create_array_3d (int w, int h, int d)
void rjmcmc_destroy_array_1d (double *a)
void rjmcmc_destroy_array_2d (int w, double **a)
void rjmcmc_destroy_array_3d (int w, int h, double ***a)
int * rjmcmc_create_int_array_1d (int w)
int ** rjmcmc_create_int_array_2d (int w, int h)
int *** rjmcmc_create_int_array_3d (int w, int h, int d)
int **** rjmcmc_create_int_array_4d (int w, int h, int d, int e)
void rjmcmc_destroy_int_array_1d (int *a)
void rjmcmc_destroy_int_array_2d (int w, int **a)
void rjmcmc_destroy_int_array_3d (int w, int h, int ***a)
void rjmcmc_destroy_int_array_4d (int w, int h, int d, int ****a)
int rjmcmc_map_to_index (double v, double vmin, double vmax, int n)
double rjmcmc_mean (const double *v, int n)
double rjmcmc_mean_skip (const double *v, int skip, int n)
int rjmcmc_mean_variance (const double *v, int n, double *_mean, double *_variance)
int rjmcmc_vector_to_histogram (int s, int n, const double *v, int hn, double vmin, double vmax, int *hist)
double rjmcmc_median_from_histogram (int *hist, double vmin, double vmax, int n)
double rjmcmc_head_from_histogram (int *hist, double vmin, double vmax, int n, int drop)
double rjmcmc_tail_from_histogram (int *hist, double vmin, double vmax, int n, int drop)
double rjmcmc_mode_from_histogram (int *hist, double vmin, double vmax, int n)
int rjmcmc_save_vector (const char *filename, const double *v, int n)
int rjmcmc_save_coords (const char *filename, const double *x, const double *y, int n)
int rjmcmc_save_vector_as_histogram (const char *filename, double minv, double maxv, int bins, const double *v, int n)
int rjmcmc_save_int_vector (const char *filename, const int *v, int n)
int rjmcmc_save_int_vector_as_histogram (const char *filename, int minv, int maxv, const int *v, int n)
int rjmcmc_save_int_coords (const char *filename, const double *x, const int *iy, int n)
int rjmcmc_save_matrix (const char *filename, const double **m, int c, int r)
int rjmcmc_save_int_matrix (const char *filename, const int **m, int c, int r)
double rjmcmc_gaussian_probability (double phi, double sigma)
double rjmcmc_log_gaussian_probability (double phi, double sigma)
double rjmcmc_gaussian_interval_probability (double phi, double sigma, double deltasigma)
double rjmcmc_polynomial_value (const double *coeff, int ncoeff, double x)
int rjmcmc_factorial (int n)
int rjmcmc_binomial (int _n, int _k)
int rjmcmc_fill_coord_vector (double xmin, double xmax, int xsamples, double *x)
Macro Definition Documentation
#define SQRT2PI 2.5066282746310002
Referenced by rjmcmc_gaussian_probability(), and rjmcmc_log_gaussian_probability().
Function Documentation
int rjmcmc_binomial (int _n, int _k)
double* rjmcmc_create_array_1d (int w)
Examples:
1d/partitioned/fm/functionfit/functionfit.c, 1d/partitioned/fm/regression/regression.c, 1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, 1d/partitioned/regression/sawtooth/sawtooth.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, 1d/single/fm/spherefit/spherefit.c, 1d/single/regression/cubic/cubic.c, 2d/partitioned/fm/regression/regression.c, 2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
Referenced by curvefit_create(), MPI_part1d_forwardmodel(), MPI_part1d_forwardmodel_hierarchical(), MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), MPI_part2d_forwardmodel_checkpoint_restart(), MPI_part2d_forwardmodel_hierarchical(), MPI_part2d_forwardmodel_hierarchical_restartable(), MPI_resultset1d_assemble_results(), MPI_resultset1dfm_assemble_results(), MPI_resultset2dfm_assemble_results(), MPI_resultsetfm_assemble_results(), MPI_single_forwardmodel(), MPI_single_forwardmodel_hierarchical(), part1d_forwardmodel(), part1d_forwardmodel_create(), part1d_forwardmodel_hierarchical(), part1d_forwardmodel_natural(), part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel_natural_hierarchical_init(), part1d_forwardmodel_natural_init(), part1d_forwardmodel_propose_hierarchical(), part1d_forwardmodel_zero_cubic(), part1d_natural_regression(), part1d_natural_rj_propose_move(), part1d_regression(), part1d_regression_rj_create(), part1d_regression_rj_propose_move(), part1d_zero_propose_lambda(), part1d_zero_regression(), part2d_forwardmodel_create(), part2d_forwardmodel_hierarchical(), part2d_forwardmodel_propose_hierarchical(), part2d_forwardmodel_restartable(), part2d_regression(), part2d_regression_rj_partition_centre(), position_map1d_create(), position_map2d_linear_create(), resultset1d_create(), resultset1dfm_create(), resultset2d_create(), resultset2dfm_create(), rjmcmc_create_array_2d(), rjmcmc_save_vector_as_histogram(), single1d_direct_regression(), single1d_regression_create(), single_forwardmodel(), and single_forwardmodel_hierarchical().
double** rjmcmc_create_array_2d (int w, int h)
References rjmcmc_create_array_1d().
Referenced by curvefit_create(), MPI_part1d_forwardmodel(), MPI_part1d_forwardmodel_hierarchical(), MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel(), part1d_forwardmodel_hierarchical(), part1d_forwardmodel_natural(), part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel_natural_hierarchical_init(), part1d_forwardmodel_natural_init(), part1d_forwardmodel_zero_cubic(), part1d_regression_rj_create(), part1d_regression_rj_propose_move(), part2d_regression(), resultset1dfm_create(), resultset2d_create(), resultset2dfm_create(), rjmcmc_create_array_3d(), and single1d_direct_regression().
double*** rjmcmc_create_array_3d (int w, int h, int d)
References rjmcmc_create_array_2d().
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), MPI_part2d_forwardmodel_hierarchical(), MPI_part2d_forwardmodel_hierarchical_restartable(), part2d_forwardmodel_hierarchical(), part2d_forwardmodel_restartable(), and resultset2dfm_create().
int* rjmcmc_create_int_array_1d (int w)
Referenced by MPI_resultset1d_assemble_results(), MPI_resultset1dfm_assemble_results(), MPI_resultset2dfm_assemble_results(), MPI_resultsetfm_assemble_results(), part1d_regression_rj_propose_move(), position_map1d_create(), quadtree_polygon_bound(), resultset1d_create(), resultset1dfm_create(), resultset2d_create(), resultset2dfm_create(), resultsetfm_create(), rjmcmc_create_int_array_2d(), and rjmcmc_save_int_vector_as_histogram().
int** rjmcmc_create_int_array_2d (int w, int h)
References rjmcmc_create_int_array_1d().
Referenced by resultset1d_create(), resultset2d_create(), resultset2dfm_create(), resultsetfm_assemble_results(), and rjmcmc_create_int_array_3d().
int*** rjmcmc_create_int_array_3d (int w, int h, int d)
References rjmcmc_create_int_array_2d().
Referenced by resultset1dfm_create(), resultset2d_create(), and rjmcmc_create_int_array_4d().
int**** rjmcmc_create_int_array_4d (int w, int h, int d, int e)
References rjmcmc_create_int_array_3d().
Referenced by resultset2dfm_create().
void rjmcmc_destroy_array_1d (double * a)
Examples:
1d/partitioned/fm/functionfit/functionfit.c, 1d/partitioned/fm/regression/regression.c, 1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, 1d/partitioned/regression/sawtooth/sawtooth.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, 2d/partitioned/fm/regression/regression.c, 2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
Referenced by curvefit_destroy(), MPI_part1d_forwardmodel(), MPI_part1d_forwardmodel_hierarchical(), MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), MPI_part2d_forwardmodel_checkpoint_restart(), MPI_part2d_forwardmodel_hierarchical(), MPI_part2d_forwardmodel_hierarchical_restartable(), MPI_resultset1dfm_assemble_results(), MPI_resultset2dfm_assemble_results(), MPI_single_forwardmodel(), MPI_single_forwardmodel_hierarchical(), part1d_forwardmodel(), part1d_forwardmodel_destroy(), part1d_forwardmodel_hierarchical(), part1d_forwardmodel_natural(), part1d_forwardmodel_natural_finish(), part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel_natural_hierarchical_finish(), part1d_forwardmodel_propose_hierarchical(), part1d_forwardmodel_zero_cubic(), part1d_natural_regression(), part1d_natural_rj_propose_move(), part1d_regression(), part1d_regression_rj_destroy(), part1d_regression_rj_propose_move(), part1d_zero_propose_lambda(), part1d_zero_regression(), part2d_forwardmodel_destroy(), part2d_forwardmodel_hierarchical(), part2d_forwardmodel_propose_hierarchical(), part2d_forwardmodel_restartable(), part2d_regression(), part2d_regression_rj_partition_centre(), position_map1d_destroy(), position_map2d_linear_destroy(), resultset1d_destroy(), resultset1dfm_destroy(), resultset2d_destroy(), resultset2dfm_destroy(), resultsetfm_destroy(), rjmcmc_destroy_array_2d(), rjmcmc_save_vector_as_histogram(), single1d_direct_regression(), single1d_regression_destroy(), single_forwardmodel(), and single_forwardmodel_hierarchical().
void rjmcmc_destroy_array_2d (int w, double ** a)
References rjmcmc_destroy_array_1d().
Referenced by curvefit_destroy(), MPI_part1d_forwardmodel(), MPI_part1d_forwardmodel_hierarchical(), MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel(), part1d_forwardmodel_hierarchical(), part1d_forwardmodel_natural(), part1d_forwardmodel_natural_finish(), part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel_natural_hierarchical_finish(), part1d_forwardmodel_zero_cubic(), part1d_regression_rj_destroy(), part1d_regression_rj_propose_move(), part2d_regression(), resultset1dfm_destroy(), resultset2d_destroy(), resultset2dfm_destroy(), resultsetfm_destroy(), rjmcmc_destroy_array_3d(), and single1d_direct_regression().
void rjmcmc_destroy_array_3d (int w, int h, double *** a)
References rjmcmc_destroy_array_2d().
Referenced by MPI_part2d_forwardmodel_checkpoint_restart(), MPI_part2d_forwardmodel_hierarchical(), MPI_part2d_forwardmodel_hierarchical_restartable(), part2d_forwardmodel_hierarchical(), part2d_forwardmodel_restartable(), and resultset2dfm_destroy().
void rjmcmc_destroy_int_array_1d (int * a)
Referenced by MPI_resultset1dfm_assemble_results(), MPI_resultset2dfm_assemble_results(), part1d_regression_rj_propose_move(), position_map1d_destroy(), quadtree_polygon_bound(), resultset1d_destroy(), resultset1dfm_destroy(), resultset2d_destroy(), resultset2dfm_destroy(), resultsetfm_destroy(), rjmcmc_destroy_int_array_2d(), and rjmcmc_save_int_vector_as_histogram().
void rjmcmc_destroy_int_array_2d (int w, int ** a)
References rjmcmc_destroy_int_array_1d().
Referenced by resultset1d_destroy(), resultset2d_destroy(), resultset2dfm_destroy(), resultsetfm_assemble_results(), and rjmcmc_destroy_int_array_3d().
void rjmcmc_destroy_int_array_3d (int w, int h, int *** a)
References rjmcmc_destroy_int_array_2d().
Referenced by resultset1dfm_destroy(), resultset2d_destroy(), and rjmcmc_destroy_int_array_4d().
void rjmcmc_destroy_int_array_4d (int w, int h, int d, int **** a)
References rjmcmc_destroy_int_array_3d().
Referenced by resultset2dfm_destroy().
int rjmcmc_factorial (int n)
int rjmcmc_fill_coord_vector (double xmin, double xmax, int xsamples, double * x)
Referenced by resultset1d_fill_xcoord_vector(), resultset1d_fill_ycoord_vector(), resultset1dfm_fill_xcoord_vector(), resultset1dfm_fill_ycoord_vector(), resultset2dfm_fill_xcoord_vector(), and resultset2dfm_fill_ycoord_vector().
double rjmcmc_gaussian_interval_probability (double phi, double sigma, double deltasigma)
double rjmcmc_gaussian_probability (double phi, double sigma)
References SQRT2PI.
Referenced by part1d_forwardmodel_propose_birth(), part1d_forwardmodel_propose_death(), part1d_zero_propose_birth(), part1d_zero_propose_death(), part1d_zero_propose_move(), part1d_zero_propose_value(), part2d_forwardmodel_propose_birth(), part2d_forwardmodel_propose_death(), part2d_regression_rj_propose_birth(), and part2d_regression_rj_propose_death().
double rjmcmc_head_from_histogram (int * hist, double vmin, double vmax, int n, int drop)
Referenced by MPI_resultset1d_assemble_results(), MPI_resultset1dfm_assemble_results(), MPI_resultset2dfm_assemble_results(), resultset1d_assemble_results(), resultset1dfm_assemble_results(), resultset2d_assemble_results(), resultset2dfm_assemble_results(), and resultsetfm_assemble_results().
double rjmcmc_log_gaussian_probability (double phi, double sigma)
References SQRT2PI.
int rjmcmc_map_to_index (double v, double vmin, double vmax, int n)
Referenced by resultset1d_sample(), resultset1d_sample_gradient(), resultset1d_sample_partition_x(), resultset1dfm_sample_local_parameter(), resultset1dfm_sample_partition_x(), resultset2d_sample(), resultset2d_sample_centre(), resultset2dfm_sample_centre(), resultset2dfm_sample_local_parameter(), resultsetfm_assemble_results(), and rjmcmc_vector_to_histogram().
double rjmcmc_mean (const double * v, int n)
References rjmcmc_mean_skip().
double rjmcmc_mean_skip (const double * v, int skip, int n)
Examples:
1d/single/fm/simpleimage/simpleimage.c.
Referenced by rjmcmc_mean().
int rjmcmc_mean_variance (const double * v, int n, double * _mean, double * _variance)
References _resultsetfm::mean.
Referenced by MPI_resultsetfm_assemble_results(), and resultsetfm_assemble_results().
double rjmcmc_median_from_histogram (int * hist, double vmin, double vmax, int n)
Referenced by MPI_resultset1d_assemble_results(), MPI_resultset1dfm_assemble_results(), MPI_resultset2dfm_assemble_results(), resultset1d_assemble_results(), resultset1dfm_assemble_results(), resultset2d_assemble_results(), resultset2dfm_assemble_results(), and resultsetfm_assemble_results().
double rjmcmc_mode_from_histogram (int * hist, double vmin, double vmax, int n)
Referenced by MPI_resultset1d_assemble_results(), MPI_resultset1dfm_assemble_results(), MPI_resultset2dfm_assemble_results(), resultset1d_assemble_results(), resultset1dfm_assemble_results(), resultset2d_assemble_results(), resultset2dfm_assemble_results(), and resultsetfm_assemble_results().
double rjmcmc_polynomial_value (const double * coeff, int ncoeff, double x)
References x.
Referenced by part1d_regression_rj_initialize(), and single1d_direct_regression().
int rjmcmc_save_coords (const char * filename, const double * x, const double * y, int n)
Examples:
1d/partitioned/fm/functionfit/functionfit.c, 1d/partitioned/fm/regression/regression.c, 1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, 1d/partitioned/regression/sawtooth/sawtooth.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, and 1d/single/regression/cubic/cubic.c.
References rjmcmc_error().
Referenced by rjmcmc_save_vector_as_histogram().
int rjmcmc_save_int_coords (const char * filename, const double * x, const int * iy, int n)
Examples:
1d/partitioned/fm/functionfit/functionfit.c, 1d/partitioned/fm/regression/regression.c, 1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, and 1d/partitioned/regression/zeromultistep/zeromultistep.c.
References rjmcmc_error().
int rjmcmc_save_int_matrix (const char * filename, const int ** m, int c, int r)
Examples:
2d/partitioned/fm/regression/regression.c, 2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References c, and rjmcmc_error().
int rjmcmc_save_int_vector (const char * filename, const int * v, int n)
Examples:
1d/partitioned/fm/functionfit/functionfit.c, 1d/partitioned/fm/regression/regression.c, 1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, 1d/single/regression/cubic/cubic.c, 2d/partitioned/fm/regression/regression.c, 2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References rjmcmc_error().
Referenced by rjmcmc_save_int_vector_as_histogram().
int rjmcmc_save_int_vector_as_histogram (const char * filename, int minv, int maxv, const int * v, int n)
Examples:
1d/partitioned/fm/functionfit/functionfit.c, 1d/partitioned/fm/regression/regression.c, 1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, 2d/partitioned/fm/regression/regression.c, 2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References rjmcmc_create_int_array_1d(), rjmcmc_destroy_int_array_1d(), and rjmcmc_save_int_vector().
int rjmcmc_save_matrix (const char * filename, const double ** m, int c, int r)
Examples:
2d/partitioned/fm/regression/regression.c, 2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References c, and rjmcmc_error().
int rjmcmc_save_vector (const char * filename, const double * v, int n)
Examples:
1d/partitioned/fm/functionfit/functionfit.c, 1d/partitioned/fm/regression/regression.c, 1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/multistep/multistep.c, 1d/partitioned/regression/sawtooth/sawtooth.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, 1d/single/fm/simpleimage/simpleimage.c, 1d/single/fm/spherefit/spherefit.c, 1d/single/regression/cubic/cubic.c, 2d/partitioned/fm/regression/regression.c, 2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References rjmcmc_error().
int rjmcmc_save_vector_as_histogram (const char * filename, double minv, double maxv, int bins, const double * v, int n)
Examples:
1d/partitioned/regression/multiquad/multiquad.c, 1d/partitioned/regression/zeromultistep/zeromultistep.c, 2d/partitioned/regression/callbackex/callbackex.c, 2d/partitioned/regression/disc/disc.c, and 2d/partitioned/regression/square/square.c.
References rjmcmc_create_array_1d(), rjmcmc_destroy_array_1d(), rjmcmc_save_coords(), and x.
double rjmcmc_tail_from_histogram (int * hist, double vmin, double vmax, int n, int drop)
Referenced by MPI_resultset1d_assemble_results(), MPI_resultset1dfm_assemble_results(), MPI_resultset2dfm_assemble_results(), resultset1d_assemble_results(), resultset1dfm_assemble_results(), resultset2d_assemble_results(), resultset2dfm_assemble_results(), and resultsetfm_assemble_results().
int rjmcmc_vector_to_histogram (int s, int n, const double * v, int hn, double vmin, double vmax, int * hist)
References rjmcmc_map_to_index().