rjmcmc_debug.h File Reference
#include <stdarg.h>
*
#include <rjmcmc/rjmcmc.h>
*
Typedefs
typedef void(* rjmcmc_debug_function_t) (rjmcmc_debug_level_t level, const char *fmt, va_list ap)
Enumerations
enum rjmcmc_debug_level_t { RJMCMC_FATAL = 0,
RJMCMC_ERROR,
RJMCMC_WARNING,
RJMCMC_DEBUG
 }
Functions
rjmcmc_debug_function_t rjmcmc_debug_set_output (rjmcmc_debug_function_t fn)
void rjmcmc_debug_set_default_output (void)
rjmcmc_debug_level_t rjmcmc_debug_set_level (rjmcmc_debug_level_t new_level)
void rjmcmc_fatal (const char *fmt,...)
void rjmcmc_error (const char *fmt,...)
void rjmcmc_warning (const char *fmt,...)
void rjmcmc_debug (const char *fmt,...)
Typedef Documentation
typedef void(* rjmcmc_debug_function_t) (rjmcmc_debug_level_t level, const char *fmt, va_list ap)
Enumeration Type Documentation
enum rjmcmc_debug_level_t
Enumerator
RJMCMC_FATAL
RJMCMC_ERROR
RJMCMC_WARNING
RJMCMC_DEBUG
Function Documentation
void rjmcmc_debug (const char * fmt, ...)
References RJMCMC_DEBUG, RJMCMC_ERROR, RJMCMC_FATAL, and RJMCMC_WARNING.
void rjmcmc_debug_set_default_output (void)
rjmcmc_debug_level_t rjmcmc_debug_set_level (rjmcmc_debug_level_t new_level)
rjmcmc_debug_function_t rjmcmc_debug_set_output (rjmcmc_debug_function_t fn)
void rjmcmc_error (const char * fmt, ...)
References RJMCMC_ERROR.
Referenced by curvefit_compute(), curvefit_compute_lambda(), curvefit_sample(), dataset1d_load_fixed(), dataset1d_load_known(), dataset1d_mean_variance(), dataset1d_sort(), dataset2d_load_fixed(), dataset2d_load_known(), delaunay2d_ct_value_at(), forwardmodel_misfit_sigma_power(), MPI_part1d_forwardmodel(), MPI_part1d_forwardmodel_hierarchical(), MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), MPI_part2d_forwardmodel(), MPI_part2d_forwardmodel_checkpoint(), MPI_part2d_forwardmodel_checkpoint_restart(), MPI_part2d_forwardmodel_hierarchical(), MPI_part2d_forwardmodel_hierarchical_restartable(), MPI_resultset1d_assemble_results(), MPI_resultset1dfm_assemble_results(), MPI_resultset2dfm_assemble_results(), MPI_resultsetfm_assemble_results(), MPI_single1d_regression(), MPI_single_forwardmodel(), MPI_single_forwardmodel_hierarchical(), part1d_forwardmodel(), part1d_forwardmodel_create(), part1d_forwardmodel_evaluate_local_parameters(), part1d_forwardmodel_hierarchical(), part1d_forwardmodel_natural(), part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel_natural_hierarchical_init(), part1d_forwardmodel_natural_init(), part1d_forwardmodel_propose_birth(), part1d_forwardmodel_propose_death(), part1d_forwardmodel_propose_global_value(), part1d_forwardmodel_propose_move(), part1d_forwardmodel_value_at(), part1d_forwardmodel_zero_cubic(), part1d_natural_regression(), part1d_natural_rj_propose_birth(), part1d_natural_rj_propose_death(), part1d_natural_rj_propose_move(), part1d_regression(), part1d_regression_rj_initialize(), part1d_regression_rj_propose_birth(), part1d_regression_rj_propose_death(), part1d_regression_rj_propose_move(), part1d_regression_rj_propose_value(), part1d_zero_propose_birth(), part1d_zero_propose_death(), part1d_zero_propose_move(), part1d_zero_regression(), part1d_zero_value_at(), part2d_forwardmodel(), part2d_forwardmodel_addpoint(), part2d_forwardmodel_delpoint(), part2d_forwardmodel_evaluate_local_parameters(), part2d_forwardmodel_hierarchical(), part2d_forwardmodel_movepoint(), part2d_forwardmodel_propose_birth(), part2d_forwardmodel_propose_death(), part2d_forwardmodel_propose_move(), part2d_forwardmodel_restartable(), part2d_regression(), part2d_regression_rj_initialize(), part2d_regression_rj_propose_birth(), part2d_regression_rj_propose_death(), part2d_regression_rj_propose_move(), position_map1d_create(), position_map1d_delete(), position_map1d_insert(), position_map1d_move(), position_map1d_next_index(), position_map1d_next_position(), position_map1d_position_of_index(), position_map2d_linear_delete(), position_map2d_linear_insert(), position_map2d_linear_move(), resultset2dfm_load(), resultset2dfm_save(), resultsetfm_assemble_results(), resultsetfm_get_hierarchical_parameter_history_f(), resultsetfm_get_parameter_history(), resultsetfm_get_parameter_history_f(), resultsetfm_sample(), resultsetfm_sample_hierarchical(), resultsetfm_sample_misfit(), rjmcmc_engine_init(), rjmcmc_engine_restart(), rjmcmc_engine_step(), rjmcmc_save_coords(), rjmcmc_save_int_coords(), rjmcmc_save_int_matrix(), rjmcmc_save_int_vector(), rjmcmc_save_matrix(), rjmcmc_save_vector(), single1d_direct_regression(), single1d_regression_clone(), single_forwardmodel(), and single_forwardmodel_hierarchical().
void rjmcmc_fatal (const char * fmt, ...)
References RJMCMC_FATAL.
Referenced by dataset1d_create(), and resultset2dfm_create().
void rjmcmc_warning (const char * fmt, ...)
References RJMCMC_WARNING.