rjmcmc_random.h File Reference
Typedefs
typedef double(* rjmcmc_uniform_rand_t) (void)
typedef double(* rjmcmc_normal_rand_t) (void)
Functions
void rjmcmc_seed (int s)
double rjmcmc_uniform (void)
double rjmcmc_normal (void)
double rjmcmc_random_choose_double (double low, double high, rjmcmc_uniform_rand_t rand)
int rjmcmc_random_choose_int (int low, int high, rjmcmc_uniform_rand_t rand)
int rjmcmc_random_choose_interval (const double *cdf, int n, rjmcmc_uniform_rand_t rand)
Typedef Documentation
typedef double(* rjmcmc_normal_rand_t) (void)
typedef double(* rjmcmc_uniform_rand_t) (void)
Function Documentation
double rjmcmc_normal (void)
References wellrng_init_simple(), and wellrng_sample().
double rjmcmc_random_choose_double (double low, double high, rjmcmc_uniform_rand_t rand)
Referenced by part1d_forwardmodel_initialize(), part1d_forwardmodel_propose_birth(), part1d_natural_rj_initialize(), part1d_regression_rj_initialize(), part1d_zero_initialize(), part1d_zero_propose_birth(), part1d_zero_propose_death(), part1d_zero_propose_move(), part1d_zero_propose_value(), part2d_forwardmodel_initialize(), part2d_forwardmodel_propose_birth(), part2d_regression_rj_initialize(), part2d_regression_rj_propose_birth(), single1d_regression_initialize(), and single_forwardmodel_hierarchical().
int rjmcmc_random_choose_int (int low, int high, rjmcmc_uniform_rand_t rand)
Referenced by MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), MPI_part2d_forwardmodel_checkpoint_restart(), MPI_part2d_forwardmodel_hierarchical_restartable(), MPI_single1d_regression(), part1d_forwardmodel_propose_death(), part1d_forwardmodel_propose_global_value(), part1d_forwardmodel_propose_hierarchical(), part1d_forwardmodel_propose_local_value(), part1d_forwardmodel_propose_move(), part1d_natural_rj_propose_move(), part1d_natural_rj_propose_value(), part1d_regression(), part1d_regression_rj_initialize(), part1d_regression_rj_propose_death(), part1d_regression_rj_propose_move(), part1d_regression_rj_propose_value(), part1d_zero_propose_death(), part1d_zero_propose_lambda(), part1d_zero_propose_move(), part1d_zero_propose_value(), part2d_forwardmodel_propose_death(), part2d_forwardmodel_propose_global_value(), part2d_forwardmodel_propose_hierarchical(), part2d_forwardmodel_propose_local_value(), part2d_forwardmodel_propose_move(), part2d_regression(), part2d_regression_rj_propose_death(), part2d_regression_rj_propose_lambda(), part2d_regression_rj_propose_move(), part2d_regression_rj_propose_value(), single1d_regression_initialize(), and single_forwardmodel_hierarchical().
int rjmcmc_random_choose_interval (const double * cdf, int n, rjmcmc_uniform_rand_t rand)
Referenced by part1d_regression_rj_propose_move(), and single1d_regression_propose_value().
void rjmcmc_seed (int s)
References wellrng_destroy(), and wellrng_init_simple().
double rjmcmc_uniform (void)
References wellrng_init_simple(), and wellrng_sample().