single1d_regression.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <math.h>
*
#include <rjmcmc/single1d_regression.h>
*
#include <rjmcmc/curvefit.h>
*
#include <rjmcmc/rjmcmc_util.h>
*
#include <rjmcmc/rjmcmc_random.h>
*
#include <rjmcmc/rjmcmc_debug.h>
*
Data Structures
struct _single1d_regression
Functions
single1d_regression_t * single1d_regression_create (int max_order, double xmin, double xmax, const double *kcdf)
void single1d_regression_destroy (single1d_regression_t *s)
void single1d_regression_clone (const single1d_regression_t *src, single1d_regression_t *dst)
double single1d_regression_value_at (single1d_regression_t *s, double x)
double single1d_regression_misfit (single1d_regression_t *s, const dataset1d_t *dataset)
int single1d_regression_evaluate (single1d_regression_t *s, double xmin, double xmax, int nsamples, double *samples)
int single1d_regression_initialize (single1d_regression_t *s, const dataset1d_t *data, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)
int single1d_regression_propose_value (const single1d_regression_t *current, single1d_regression_t *proposed, const dataset1d_t *dataset, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *value_prob)
int single1d_regression_propose_lambda (const single1d_regression_t *current, single1d_regression_t *proposed, const dataset1d_t *dataset, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double *lambda_prob)
int single1d_regression_order (const single1d_regression_t *current)
double single1d_regression_lambda (const single1d_regression_t *current)
int single1d_evaluate_pk (single1d_regression_t *s, const dataset1d_t *data, const double *fixedprior, double auto_z, double *mean_misfit, double *detCm, double *autoprior, double **S, double *pk, double *kcdf, double **mean, double **sigma)
Function Documentation
[single1d_evaluate_pk(single1d_regression_t *s, const dataset1d_t *data, const double *fixedprior, double auto_z, double *mean_misfit, double *detCm, double *autoprior, double **S, double *pk, double *kcdf, double **mean, double **sigma)]int single1d_evaluate_pk (single1d_regression_t * s, const dataset1d_t * data, const double * fixedprior, double auto_z, double * mean_misfit, double * detCm, double * autoprior, double ** S, double * pk, double * kcdf, double ** mean, double ** sigma)
References _single1d_regression::cf, curvefit_evaluate_pk(), _single1d_regression::max_order, and _dataset1d::npoints.
void single1d_regression_clone (const single1d_regression_t * src, single1d_regression_t * dst)
References _single1d_regression::a, _single1d_regression::lambda, _single1d_regression::max_order, _single1d_regression::order, and rjmcmc_error().
Referenced by MPI_single1d_regression(), single1d_regression_propose_lambda(), and single1d_regression_propose_value().
single1d_regression_t* single1d_regression_create (int max_order, double xmin, double xmax, const double * kcdf)
References _single1d_regression::a, _single1d_regression::cf, curvefit_create(), _single1d_regression::kcdf, _single1d_regression::max_order, rjmcmc_create_array_1d(), _single1d_regression::xmax, and _single1d_regression::xmin.
void single1d_regression_destroy (single1d_regression_t * s)
References _single1d_regression::a, _single1d_regression::cf, curvefit_destroy(), and rjmcmc_destroy_array_1d().
int single1d_regression_evaluate (single1d_regression_t * s, double xmin, double xmax, int nsamples, double * samples)
References single1d_regression_value_at().
Referenced by MPI_single1d_regression().
int single1d_regression_initialize (single1d_regression_t * s, const dataset1d_t * data, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal)
References _single1d_regression::lambda, _dataset1d::lambdamax, _dataset1d::lambdamin, _dataset1d::lambdastd, _single1d_regression::max_order, _single1d_regression::order, rjmcmc_random_choose_double(), and rjmcmc_random_choose_int().
Referenced by MPI_single1d_regression().
double single1d_regression_lambda (const single1d_regression_t * current)
References _single1d_regression::lambda.
Referenced by MPI_single1d_regression().
double single1d_regression_misfit (single1d_regression_t * s, const dataset1d_t * dataset)
References _single1d_regression::lambda, _dataset1d::lambdastd, _point1d::n, _dataset1d::npoints, _dataset1d::points, single1d_regression_value_at(), _point1d::x, _point1d::y, and y.
Referenced by MPI_single1d_regression().
int single1d_regression_order (const single1d_regression_t * current)
References _single1d_regression::order.
Referenced by MPI_single1d_regression().
int single1d_regression_propose_lambda (const single1d_regression_t * current, single1d_regression_t * proposed, const dataset1d_t * dataset, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * lambda_prob)
References _single1d_regression::a, _single1d_regression::cf, curvefit_compute(), curvefit_sample(), _single1d_regression::lambda, _dataset1d::lambdamax, _dataset1d::lambdastd, normal, _dataset1d::npoints, _single1d_regression::order, random, and single1d_regression_clone().
Referenced by MPI_single1d_regression().
int single1d_regression_propose_value (const single1d_regression_t * current, single1d_regression_t * proposed, const dataset1d_t * dataset, rjmcmc_uniform_rand_t random, rjmcmc_normal_rand_t normal, double * value_prob)
References _single1d_regression::kcdf, _single1d_regression::max_order, _single1d_regression::order, rjmcmc_random_choose_interval(), and single1d_regression_clone().
Referenced by MPI_single1d_regression().
double single1d_regression_value_at (single1d_regression_t * s, double x)
References _single1d_regression::a, _single1d_regression::order, and x.
Referenced by single1d_regression_evaluate(), and single1d_regression_misfit().