_rjmcmc_engine_cb Struct Reference
#include <engine.h>
Data Fields
int burnin
int total
int sample_rate
int i
double current_like
double(* initialize_state)(void *arg)
int(* select_process)(void *arg)
void *(* perturb_process)(void *arg, int proc)
double(* compute_misfit)(void *arg, void *state)
int(* accept)(void *arg, double current, double proposed)
int(* sample)(void *arg, int i)
void * arg
Field Documentation
int(* _rjmcmc_engine_cb::accept) (void *arg, double current, double proposed)
Referenced by MPI_part1d_forwardmodel(), MPI_part1d_forwardmodel_hierarchical(), MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel(), part1d_forwardmodel_hierarchical(), part1d_forwardmodel_natural(), part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel_natural_hierarchical_init(), part1d_forwardmodel_natural_init(), part1d_forwardmodel_zero_cubic(), and rjmcmc_engine_step().
void* _rjmcmc_engine_cb::arg
Referenced by MPI_part1d_forwardmodel(), MPI_part1d_forwardmodel_hierarchical(), MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel(), part1d_forwardmodel_hierarchical(), part1d_forwardmodel_natural(), part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel_natural_hierarchical_init(), part1d_forwardmodel_natural_init(), part1d_forwardmodel_zero_cubic(), rjmcmc_engine_init(), and rjmcmc_engine_step().
int _rjmcmc_engine_cb::burnin
Referenced by rjmcmc_engine_init(), and rjmcmc_engine_restart().
double(* _rjmcmc_engine_cb::compute_misfit) (void *arg, void *state)
Referenced by MPI_part1d_forwardmodel(), MPI_part1d_forwardmodel_hierarchical(), MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel(), part1d_forwardmodel_hierarchical(), part1d_forwardmodel_natural(), part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel_natural_hierarchical_init(), part1d_forwardmodel_natural_init(), part1d_forwardmodel_zero_cubic(), and rjmcmc_engine_step().
double _rjmcmc_engine_cb::current_like
Referenced by rjmcmc_engine_init(), rjmcmc_engine_restart(), and rjmcmc_engine_step().
int _rjmcmc_engine_cb::i
Referenced by rjmcmc_engine_init(), rjmcmc_engine_restart(), and rjmcmc_engine_step().
double(* _rjmcmc_engine_cb::initialize_state) (void *arg)
Referenced by MPI_part1d_forwardmodel(), MPI_part1d_forwardmodel_hierarchical(), MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel(), part1d_forwardmodel_hierarchical(), part1d_forwardmodel_natural(), part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel_natural_hierarchical_init(), part1d_forwardmodel_natural_init(), part1d_forwardmodel_zero_cubic(), and rjmcmc_engine_init().
void*(* _rjmcmc_engine_cb::perturb_process) (void *arg, int proc)
Referenced by MPI_part1d_forwardmodel(), MPI_part1d_forwardmodel_hierarchical(), MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel(), part1d_forwardmodel_hierarchical(), part1d_forwardmodel_natural(), part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel_natural_hierarchical_init(), part1d_forwardmodel_natural_init(), part1d_forwardmodel_zero_cubic(), and rjmcmc_engine_step().
int(* _rjmcmc_engine_cb::sample) (void *arg, int i)
Referenced by MPI_part1d_forwardmodel(), MPI_part1d_forwardmodel_hierarchical(), MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel(), part1d_forwardmodel_hierarchical(), part1d_forwardmodel_natural(), part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel_natural_hierarchical_init(), part1d_forwardmodel_natural_init(), part1d_forwardmodel_zero_cubic(), and rjmcmc_engine_step().
int _rjmcmc_engine_cb::sample_rate
Referenced by rjmcmc_engine_init(), and rjmcmc_engine_restart().
int(* _rjmcmc_engine_cb::select_process) (void *arg)
Referenced by MPI_part1d_forwardmodel(), MPI_part1d_forwardmodel_hierarchical(), MPI_part1d_forwardmodel_natural(), MPI_part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel(), part1d_forwardmodel_hierarchical(), part1d_forwardmodel_natural(), part1d_forwardmodel_natural_hierarchical(), part1d_forwardmodel_natural_hierarchical_init(), part1d_forwardmodel_natural_init(), part1d_forwardmodel_zero_cubic(), and rjmcmc_engine_step().
int _rjmcmc_engine_cb::total
Referenced by rjmcmc_engine_init(), rjmcmc_engine_restart(), and rjmcmc_engine_step().
The documentation for this struct was generated from the following file:
engine.h