wellrng.h File Reference
Typedefs
typedef struct wellrng wellrng_t
Functions
wellrng_t * wellrng_init_simple (unsigned int seed)
unsigned int wellrng_seed_size (void)
wellrng_t * wellrng_init_direct (unsigned int *seed)
double wellrng_sample (wellrng_t *w)
void wellrng_destroy (wellrng_t *w)
Typedef Documentation
typedef struct wellrng wellrng_t
Function Documentation
void wellrng_destroy (wellrng_t * w)
Referenced by rjmcmc_seed().
wellrng_t* wellrng_init_direct (unsigned int * seed)
References wellrng::i, R, wellrng::s, and wellrng::state.
wellrng_t* wellrng_init_simple (unsigned int seed)
References wellrng::i, R, wellrng::s, and wellrng::state.
Referenced by rjmcmc_normal(), rjmcmc_seed(), and rjmcmc_uniform().
double wellrng_sample (wellrng_t * w)
References FACT, wellrng::i, M1, M2, M3, MASKL, MASKU, MAT0NEG, MAT0POS, MAT1, MAT3NEG, MAT5, newV0, newV0Under, newV1, R, wellrng::s, wellrng::state, TEMPERB, TEMPERC, V0, VM1, VM1Over, VM2, VM2Over, VM3, VM3Over, Vrm1, Vrm1Under, Vrm2, Vrm2Under, and y.
Referenced by rjmcmc_normal(), and rjmcmc_uniform().
unsigned int wellrng_seed_size (void)
References R.